module.exports = {
    CITIES: [{
            "city": "Shanghai",
            "city_ascii": "Shanghai",
            "lat": 31.2165,
            "lng": 121.4365,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shanghai",
            "capital": "admin",
            "population": 14987000,
            "id": 1156073548
        },
        {
            "city": "Beijing",
            "city_ascii": "Beijing",
            "lat": 39.9289,
            "lng": 116.3883,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Beijing",
            "capital": "primary",
            "population": 11106000,
            "id": 1156228865
        },
        {
            "city": "Guangzhou",
            "city_ascii": "Guangzhou",
            "lat": 23.145,
            "lng": 113.325,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "admin",
            "population": 8829000,
            "id": 1156237133
        },
        {
            "city": "Shenzhen",
            "city_ascii": "Shenzhen",
            "lat": 22.5524,
            "lng": 114.1221,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "minor",
            "population": 7581000,
            "id": 1156158707
        },
        {
            "city": "Wuhan",
            "city_ascii": "Wuhan",
            "lat": 30.58,
            "lng": 114.27,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hubei",
            "capital": "admin",
            "population": 7243000,
            "id": 1156117184
        },
        {
            "city": "Tianjin",
            "city_ascii": "Tianjin",
            "lat": 39.13,
            "lng": 117.2,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Tianjin",
            "capital": "admin",
            "population": 7180000,
            "id": 1156174046
        },
        {
            "city": "Chongqing",
            "city_ascii": "Chongqing",
            "lat": 29.565,
            "lng": 106.595,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Chongqing",
            "capital": "admin",
            "population": 6461000,
            "id": 1156936556
        },
        {
            "city": "Shenyang",
            "city_ascii": "Shenyang",
            "lat": 41.805,
            "lng": 123.45,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "admin",
            "population": 4787000,
            "id": 1156309382
        },
        {
            "city": "Dongguan",
            "city_ascii": "Dongguan",
            "lat": 23.0489,
            "lng": 113.7447,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "minor",
            "population": 4528000,
            "id": 1156478242
        },
        {
            "city": "Chengdu",
            "city_ascii": "Chengdu",
            "lat": 30.67,
            "lng": 104.07,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "admin",
            "population": 4123000,
            "id": 1156421555
        },
        {
            "city": "Xi\u2019an",
            "city_ascii": "Xi'an",
            "lat": 34.275,
            "lng": 108.895,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shaanxi",
            "capital": "admin",
            "population": 4009000,
            "id": 1156244079
        },
        {
            "city": "Hechi",
            "city_ascii": "Hechi",
            "lat": 23.0965,
            "lng": 109.6091,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangxi",
            "capital": "",
            "population": 3830000,
            "id": 1156868701
        },
        {
            "city": "Nanjing",
            "city_ascii": "Nanjing",
            "lat": 32.05,
            "lng": 118.78,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "admin",
            "population": 3679000,
            "id": 1156644065
        },
        {
            "city": "Guiyang",
            "city_ascii": "Guiyang",
            "lat": 26.58,
            "lng": 106.72,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guizhou",
            "capital": "admin",
            "population": 3662000,
            "id": 1156932620
        },
        {
            "city": "Harbin",
            "city_ascii": "Harbin",
            "lat": 45.75,
            "lng": 126.65,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Heilongjiang",
            "capital": "admin",
            "population": 3621000,
            "id": 1156241528
        },
        {
            "city": "Zhangzhou",
            "city_ascii": "Zhangzhou",
            "lat": 24.5204,
            "lng": 117.67,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Fujian",
            "capital": "minor",
            "population": 3531147,
            "id": 1156241637
        },
        {
            "city": "Changchun",
            "city_ascii": "Changchun",
            "lat": 43.865,
            "lng": 125.34,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jilin",
            "capital": "admin",
            "population": 3183000,
            "id": 1156078103
        },
        {
            "city": "Dalian",
            "city_ascii": "Dalian",
            "lat": 38.9228,
            "lng": 121.6298,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "",
            "population": 3167000,
            "id": 1156175472
        },
        {
            "city": "Zibo",
            "city_ascii": "Zibo",
            "lat": 36.8,
            "lng": 118.05,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "",
            "population": 3061000,
            "id": 1156381094
        },
        {
            "city": "Hangzhou",
            "city_ascii": "Hangzhou",
            "lat": 30.25,
            "lng": 120.17,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Zhejiang",
            "capital": "admin",
            "population": 3007000,
            "id": 1156275243
        },
        {
            "city": "Kunming",
            "city_ascii": "Kunming",
            "lat": 25.07,
            "lng": 102.68,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Yunnan",
            "capital": "admin",
            "population": 2931000,
            "id": 1156477539
        },
        {
            "city": "Taiyuan",
            "city_ascii": "Taiyuan",
            "lat": 37.875,
            "lng": 112.5451,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shanxi",
            "capital": "admin",
            "population": 2913000,
            "id": 1156632014
        },
        {
            "city": "Qingdao",
            "city_ascii": "Qingdao",
            "lat": 36.09,
            "lng": 120.33,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "minor",
            "population": 2866000,
            "id": 1156112588
        },
        {
            "city": "Jinan",
            "city_ascii": "Jinan",
            "lat": 36.675,
            "lng": 116.995,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "admin",
            "population": 2798000,
            "id": 1156972469
        },
        {
            "city": "Zhengzhou",
            "city_ascii": "Zhengzhou",
            "lat": 34.755,
            "lng": 113.6651,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "admin",
            "population": 2636000,
            "id": 1156183137
        },
        {
            "city": "Fuzhou",
            "city_ascii": "Fuzhou",
            "lat": 26.08,
            "lng": 119.3,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Fujian",
            "capital": "admin",
            "population": 2606000,
            "id": 1156188037
        },
        {
            "city": "Changsha",
            "city_ascii": "Changsha",
            "lat": 28.2,
            "lng": 112.97,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hunan",
            "capital": "admin",
            "population": 2604000,
            "id": 1156961497
        },
        {
            "city": "Xiangtan",
            "city_ascii": "Xiangtan",
            "lat": 27.8504,
            "lng": 112.9,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hunan",
            "capital": "",
            "population": 2586948,
            "id": 1156195684
        },
        {
            "city": "Lanzhou",
            "city_ascii": "Lanzhou",
            "lat": 36.056,
            "lng": 103.792,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Gansu",
            "capital": "admin",
            "population": 2561000,
            "id": 1156280566
        },
        {
            "city": "Xiamen",
            "city_ascii": "Xiamen",
            "lat": 24.45,
            "lng": 118.08,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Fujian",
            "capital": "minor",
            "population": 2519000,
            "id": 1156212809
        },
        {
            "city": "Lianshan",
            "city_ascii": "Lianshan",
            "lat": 40.7503,
            "lng": 120.83,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "minor",
            "population": 2426000,
            "id": 1156046704
        },
        {
            "city": "Shijiazhuang",
            "city_ascii": "Shijiazhuang",
            "lat": 38.05,
            "lng": 114.48,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hebei",
            "capital": "admin",
            "population": 2417000,
            "id": 1156217541
        },
        {
            "city": "Jilin",
            "city_ascii": "Jilin",
            "lat": 43.85,
            "lng": 126.55,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jilin",
            "capital": "",
            "population": 2396000,
            "id": 1156646448
        },
        {
            "city": "Nanchang",
            "city_ascii": "Nanchang",
            "lat": 28.68,
            "lng": 115.88,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangxi",
            "capital": "admin",
            "population": 2350000,
            "id": 1156198892
        },
        {
            "city": "Wenzhou",
            "city_ascii": "Wenzhou",
            "lat": 28.02,
            "lng": 120.6501,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Zhejiang",
            "capital": "",
            "population": 2350000,
            "id": 1156188829
        },
        {
            "city": "Gaoping",
            "city_ascii": "Gaoping",
            "lat": 30.7804,
            "lng": 106.13,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "minor",
            "population": 2174000,
            "id": 1156522457
        },
        {
            "city": "Nanning",
            "city_ascii": "Nanning",
            "lat": 22.82,
            "lng": 108.32,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangxi",
            "capital": "admin",
            "population": 2167000,
            "id": 1156605439
        },
        {
            "city": "\u00dcr\u00fcmqi",
            "city_ascii": "Urumqi",
            "lat": 43.805,
            "lng": 87.575,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Xinjiang",
            "capital": "admin",
            "population": 2151000,
            "id": 1156051276
        },
        {
            "city": "Zaozhuang",
            "city_ascii": "Zaozhuang",
            "lat": 34.88,
            "lng": 117.57,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "",
            "population": 2145000,
            "id": 1156796454
        },
        {
            "city": "Yantai",
            "city_ascii": "Yantai",
            "lat": 37.5304,
            "lng": 121.4,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "",
            "population": 2116000,
            "id": 1156932948
        },
        {
            "city": "Tongshan",
            "city_ascii": "Tongshan",
            "lat": 34.28,
            "lng": 117.18,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "minor",
            "population": 2091000,
            "id": 1156241678
        },
        {
            "city": "Linyi",
            "city_ascii": "Linyi",
            "lat": 35.08,
            "lng": 118.33,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "",
            "population": 2082000,
            "id": 1156086320
        },
        {
            "city": "Haikou",
            "city_ascii": "Haikou",
            "lat": 20.05,
            "lng": 110.32,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hainan",
            "capital": "admin",
            "population": 2046189,
            "id": 1156183327
        },
        {
            "city": "Baotou",
            "city_ascii": "Baotou",
            "lat": 40.6522,
            "lng": 109.822,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Inner Mongolia",
            "capital": "",
            "population": 2036000,
            "id": 1156032751
        },
        {
            "city": "Hefei",
            "city_ascii": "Hefei",
            "lat": 31.85,
            "lng": 117.28,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "admin",
            "population": 2035000,
            "id": 1156332710
        },
        {
            "city": "Suzhou",
            "city_ascii": "Suzhou",
            "lat": 33.6361,
            "lng": 116.9789,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "",
            "population": 1964000,
            "id": 1156871297
        },
        {
            "city": "Nanyang",
            "city_ascii": "Nanyang",
            "lat": 33.0004,
            "lng": 112.53,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "",
            "population": 1944000,
            "id": 1156192287
        },
        {
            "city": "Ningbo",
            "city_ascii": "Ningbo",
            "lat": 29.88,
            "lng": 121.55,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Zhejiang",
            "capital": "minor",
            "population": 1923000,
            "id": 1156170787
        },
        {
            "city": "Tangshan",
            "city_ascii": "Tangshan",
            "lat": 39.6243,
            "lng": 118.1944,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hebei",
            "capital": "",
            "population": 1879000,
            "id": 1156904299
        },
        {
            "city": "Xiping",
            "city_ascii": "Xiping",
            "lat": 40.08,
            "lng": 113.3,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shanxi",
            "capital": "minor",
            "population": 1873000,
            "id": 1156898522
        },
        {
            "city": "Shuyangzha",
            "city_ascii": "Shuyangzha",
            "lat": 34.1299,
            "lng": 118.7734,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "",
            "population": 1770000,
            "id": 1156051957
        },
        {
            "city": "Shangqiu",
            "city_ascii": "Shangqiu",
            "lat": 34.4504,
            "lng": 115.65,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "",
            "population": 1753000,
            "id": 1156805441
        },
        {
            "city": "Wuxi",
            "city_ascii": "Wuxi",
            "lat": 31.58,
            "lng": 120.3,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "minor",
            "population": 1749000,
            "id": 1156019650
        },
        {
            "city": "Hohhot",
            "city_ascii": "Hohhot",
            "lat": 40.82,
            "lng": 111.66,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Inner Mongolia",
            "capital": "admin",
            "population": 1726000,
            "id": 1156210167
        },
        {
            "city": "Luoyang",
            "city_ascii": "Luoyang",
            "lat": 34.68,
            "lng": 112.4701,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "",
            "population": 1715000,
            "id": 1156069315
        },
        {
            "city": "Jingling",
            "city_ascii": "Jingling",
            "lat": 30.6501,
            "lng": 113.16,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hubei",
            "capital": "",
            "population": 1708000,
            "id": 1156060544
        },
        {
            "city": "Daqing",
            "city_ascii": "Daqing",
            "lat": 46.58,
            "lng": 125,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Heilongjiang",
            "capital": "",
            "population": 1693000,
            "id": 1156403962
        },
        {
            "city": "Lu\u2019an",
            "city_ascii": "Lu'an",
            "lat": 31.7503,
            "lng": 116.48,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "minor",
            "population": 1690000,
            "id": 1156499624
        },
        {
            "city": "Sanzhou",
            "city_ascii": "Sanzhou",
            "lat": 30.82,
            "lng": 108.4,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Chongqing",
            "capital": "",
            "population": 1680000,
            "id": 1156025536
        },
        {
            "city": "Suzhou",
            "city_ascii": "Suzhou",
            "lat": 31.3005,
            "lng": 120.62,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "minor",
            "population": 1650000,
            "id": 1156029196
        },
        {
            "city": "Qiqihar",
            "city_ascii": "Qiqihar",
            "lat": 47.345,
            "lng": 123.99,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Heilongjiang",
            "capital": "minor",
            "population": 1641000,
            "id": 1156775905
        },
        {
            "city": "Anshan",
            "city_ascii": "Anshan",
            "lat": 41.115,
            "lng": 122.94,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "",
            "population": 1639000,
            "id": 1156901825
        },
        {
            "city": "Handan",
            "city_ascii": "Handan",
            "lat": 36.58,
            "lng": 114.48,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hebei",
            "capital": "",
            "population": 1631000,
            "id": 1156957080
        },
        {
            "city": "Tai\u2019an",
            "city_ascii": "Tai'an",
            "lat": 36.2,
            "lng": 117.1201,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "",
            "population": 1629000,
            "id": 1156095188
        },
        {
            "city": "Shantou",
            "city_ascii": "Shantou",
            "lat": 23.37,
            "lng": 116.67,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "minor",
            "population": 1601000,
            "id": 1156457499
        },
        {
            "city": "Zhanjiang",
            "city_ascii": "Zhanjiang",
            "lat": 21.2,
            "lng": 110.38,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "minor",
            "population": 1590000,
            "id": 1156502170
        },
        {
            "city": "Xiantao",
            "city_ascii": "Xiantao",
            "lat": 30.3704,
            "lng": 113.44,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hubei",
            "capital": "",
            "population": 1556000,
            "id": 1156216927
        },
        {
            "city": "Weifang",
            "city_ascii": "Weifang",
            "lat": 36.7204,
            "lng": 119.1001,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "",
            "population": 1553000,
            "id": 1156912965
        },
        {
            "city": "Xinyang",
            "city_ascii": "Xinyang",
            "lat": 32.1304,
            "lng": 114.07,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "",
            "population": 1541000,
            "id": 1156273453
        },
        {
            "city": "Luzhou",
            "city_ascii": "Luzhou",
            "lat": 28.88,
            "lng": 105.38,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "minor",
            "population": 1537000,
            "id": 1156582079
        },
        {
            "city": "Ganzhou",
            "city_ascii": "Ganzhou",
            "lat": 25.92,
            "lng": 114.95,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangxi",
            "capital": "minor",
            "population": 1500000,
            "id": 1156832475
        },
        {
            "city": "Liuzhou",
            "city_ascii": "Liuzhou",
            "lat": 24.28,
            "lng": 109.25,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangxi",
            "capital": "minor",
            "population": 1497000,
            "id": 1156360785
        },
        {
            "city": "Fushun",
            "city_ascii": "Fushun",
            "lat": 41.8654,
            "lng": 123.87,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "",
            "population": 1470000,
            "id": 1156857743
        },
        {
            "city": "Changde",
            "city_ascii": "Changde",
            "lat": 29.03,
            "lng": 111.68,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hunan",
            "capital": "minor",
            "population": 1469000,
            "id": 1156449091
        },
        {
            "city": "Neijiang",
            "city_ascii": "Neijiang",
            "lat": 29.5804,
            "lng": 105.05,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "minor",
            "population": 1466000,
            "id": 1156516335
        },
        {
            "city": "Quanzhou",
            "city_ascii": "Quanzhou",
            "lat": 24.9,
            "lng": 118.58,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Fujian",
            "capital": "minor",
            "population": 1463000,
            "id": 1156829655
        },
        {
            "city": "Huainan",
            "city_ascii": "Huainan",
            "lat": 32.63,
            "lng": 116.98,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "",
            "population": 1451000,
            "id": 1156877299
        },
        {
            "city": "Suining",
            "city_ascii": "Suining",
            "lat": 30.5333,
            "lng": 105.5333,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "minor",
            "population": 1425000,
            "id": 1156655650
        },
        {
            "city": "Mianyang",
            "city_ascii": "Mianyang",
            "lat": 31.47,
            "lng": 104.77,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "minor",
            "population": 1396000,
            "id": 1156417758
        },
        {
            "city": "Ma\u2019anshan",
            "city_ascii": "Ma'anshan",
            "lat": 31.7304,
            "lng": 118.48,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "minor",
            "population": 1366302,
            "id": 1156847452
        },
        {
            "city": "Yiyang",
            "city_ascii": "Yiyang",
            "lat": 28.6004,
            "lng": 112.33,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hunan",
            "capital": "",
            "population": 1352000,
            "id": 1156218615
        },
        {
            "city": "Heze",
            "city_ascii": "Heze",
            "lat": 35.23,
            "lng": 115.45,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "minor",
            "population": 1338000,
            "id": 1156225008
        },
        {
            "city": "Changzhou",
            "city_ascii": "Changzhou",
            "lat": 31.78,
            "lng": 119.97,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "minor",
            "population": 1327000,
            "id": 1156185511
        },
        {
            "city": "Chifeng",
            "city_ascii": "Chifeng",
            "lat": 42.27,
            "lng": 118.95,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Inner Mongolia",
            "capital": "minor",
            "population": 1277000,
            "id": 1156277458
        },
        {
            "city": "Huaiyin",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/%E9%95%87%E6%B7%AE%E6%A5%BC.JPG/1280px-%E9%95%87%E6%B7%AE%E6%A5%BC.JPG",
            "city_ascii": "Huaiyin",
            "lat": 33.58,
            "lng": 119.03,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "",
            "population": 1264000,
            "id": 1156662372
        },
        {
            "city": "Mudanjiang",
            "city_ascii": "Mudanjiang",
            "lat": 44.575,
            "lng": 129.59,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Heilongjiang",
            "capital": "minor",
            "population": 1244000,
            "id": 1156249698
        },
        {
            "city": "Huzhou",
            "city_ascii": "Huzhou",
            "lat": 30.8704,
            "lng": 120.1,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Zhejiang",
            "capital": "minor",
            "population": 1231000,
            "id": 1156335543
        },
        {
            "city": "Beidao",
            "city_ascii": "Beidao",
            "lat": 34.6,
            "lng": 105.92,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Gansu",
            "capital": "minor",
            "population": 1225000,
            "id": 1156137209
        },
        {
            "city": "Shuangshui",
            "city_ascii": "Shuangshui",
            "lat": 26.5944,
            "lng": 104.8333,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guizhou",
            "capital": "",
            "population": 1221000,
            "id": 1156070389
        },
        {
            "city": "Gaozhou",
            "city_ascii": "Gaozhou",
            "lat": 21.9204,
            "lng": 110.87,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "",
            "population": 1217715,
            "id": 1156785303
        },
        {
            "city": "Xining",
            "city_ascii": "Xining",
            "lat": 36.62,
            "lng": 101.77,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Qinghai",
            "capital": "admin",
            "population": 1048000,
            "id": 1156081448
        },
        {
            "city": "Yinchuan",
            "city_ascii": "Yinchuan",
            "lat": 38.468,
            "lng": 106.273,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Ningxia",
            "capital": "admin",
            "population": 991000,
            "id": 1156359072
        },
        {
            "city": "Lhasa",
            "city_ascii": "Lhasa",
            "lat": 29.645,
            "lng": 91.1,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Tibet",
            "capital": "admin",
            "population": 219599,
            "id": 1156369972
        }
    ]
}