module.exports = {
  CITIES: [
    // 7 Ancient Wonders
    {
      "city": "Great Pyramid of Giza",
      "city_ascii": "",
      "lat": 29.979175,
      "lng": 31.134358,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza"
    },
    {
      "city": "Hanging Gardens of Babylon",
      "city_ascii": "",
      "lat": 32.5355,
      "lng": 44.4275,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Hanging_Gardens_of_Babylon"
    },
    {
      "city": "Temple of Artemis at Ephesus",
      "city_ascii": "",
      "lat": 37.949722,
      "lng": 27.363889,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Temple_of_Artemis"
    },
    {
      "city": "Statue of Zeus at Olympia",
      "city_ascii": "",
      "lat": 37.637861,
      "lng": 21.63,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Statue_of_Zeus_at_Olympia"
    },
    {
      "city": "Mausoleum at Halicarnassus",
      "city_ascii": "",
      "lat": 37.0379,
      "lng": 27.4241,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Mausoleum_at_Halicarnassus"
    },
    {
      "city": "Colossus of Rhodes",
      "city_ascii": "",
      "lat": 36.451111,
      "lng": 28.227778,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Colossus_of_Rhodes"
    },
    {
      "city": "Lighthouse of Alexandria",
      "city_ascii": "",
      "lat": 31.213889,
      "lng": 29.885556,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Lighthouse_of_Alexandria"
    },
    // 8th wonders
    {
      "city": "Angkor Wat (អង្គរវត្ត)",
      "city_ascii": "",
      "lat": 13.4125,
      "lng": 103.866667,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Angkor_Wat"
    },
    {
      "city": "Citadelle Laferri\u00e8re",
      "city_ascii": "Citadelle Laferriere",
      "lat": 19.573611,
      "lng": -72.243889,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Citadelle_Laferrier"
    },
    {
      "city": "The Amber Room in the Catherine Palace",
      "city_ascii": "",
      "lat": 59.9375,
      "lng": 30.308611,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Amber_Room"
    },
    {
      "city": "Borobudur Temple",
      "city_ascii": "",
      "lat": -7.608,
      "lng": 110.204,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Borobudur"
    }, 
    {
      "city": "Monasterio del Escorial",
      "city_ascii": "",
      "lat": 40.588889,
      "lng": -4.147778,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/El_Escorial"
    },
    {
      "city": "Loch Lomond",
      "city_ascii": "",
      "lat": 56.0833333,
      "lng": -4.5666667,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Loch_Lomond"
    },
    {
      "city": "Loch Ness",
      "city_ascii": "",
      "lat": 57.5,
      "lng": -4.45,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Loch_Ness"
    },
    {
      "city": "Leaning Tower of Pisa",
      "city_ascii": "",
      "lat": 43.723056,
      "lng": 10.396389,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Leaning_Tower_of_Pisa"
    },
    {
      "city": "Machu Picchu",
      "city_ascii": "",
      "lat": -13.163333,
      "lng": -72.545556,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Machu_Picchu"
    },
    {
      "city": "Moai Statues of Easter Island",
      "city_ascii": "",
      "lat": -27.116667,
      "lng": -109.366667,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/moai"
    },
    {
      "city": "Obelisk of Axum",
      "city_ascii": "",
      "lat": 14.132222,
      "lng": 38.719722,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Obelisk_of_Axum"
    },
    {
      "city": "Church of Saint George, Lalibela",
      "city_ascii": "",
      "lat": 12.03174,
      "lng": 39.04113,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Church_of_Saint_George,_Lalibela"
    },
    {
      "city": "Royal Palace of Amsterdam",
      "city_ascii": "",
      "lat": 52.373056,
      "lng": 4.891111,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Royal_Palace_of_Amsterdam"
    },
    {
      "city": "Sigiriya Fortress",
      "city_ascii": "",
      "lat": 7.956944,
      "lng": 80.759722,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Sigiriya"
    },
    {
      "city": "Statue of Liberty",
      "city_ascii": "",
      "lat": 40.689167,
      "lng": -74.044444,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Statue_of_Liberty"
    },
    {
      "city": "Stonehenge",
      "city_ascii": "",
      "lat": 51.178889,
      "lng": -1.826111,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Stonehenge"
    },
    {
      "city": "Taj Mahal",
      "city_ascii": "",
      "lat": 27.175,
      "lng": 78.041944,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Taj_Mahal"
    },
    {
      "city": "Chapel of the Rosario, Puebla",
      "city_ascii": "",
      "lat": 19.033333,
      "lng": -98.183333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Chapel_of_the_Rosario,_Puebla"
    },
    {
      "city": "Terracotta Army (兵马俑)",
      "city_ascii": "",
      "lat": 34.385,
      "lng": 109.273056,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Terracotta_Army"
    },
    {
      "city": "Empire State Building",
      "city_ascii": "",
      "lat": 40.748433,
      "lng": -73.985656,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Empire_State_Building"
    },
    {
      "city": "Golden Gate Bridge",
      "city_ascii": "",
      "lat": 37.819722,
      "lng": -122.478611,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/golden_gate_bridge"
    },
    {
      "city": "The White House",
      "city_ascii": "",
      "lat": 38.8977,
      "lng": -77.0365,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/White_House"
    },
    {
      "city": "Parliament Hill",
      "city_ascii": "",
      "lat": 45.424807,
      "lng": -75.699234,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Parliament_Hill"
    },
    {
      "city": "The Kremlin (Моско́вский Кремль)",
      "city_ascii": "",
      "lat": 55.751667,
      "lng": 37.617778,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Moscow_Kremlin"
    },
    {
      "city": "Buckingham Palace",
      "city_ascii": "",
      "lat": 51.507222,
      "lng": -0.1275,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Buckingham_Palace"
    },
    {
      "city": "Null Island",
      "city_ascii": "",
      "lat": 0,
      "lng": 0,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Null_Island"
    },
    {
      "city": "Saint Basil's Cathedral (собо́р Васи́лия Блаже́нного)",
      "city_ascii": "",
      "lat": 55.75725,
      "lng": 37.623056,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Saint_Basil%27s_Cathedral"
    },
    {
      "city": "Great Zimbabwe",
      "city_ascii": "",
      "lat": -20.266667,
      "lng": 30.933333,
      "country": "Kingdom of Zimbabwe",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Great_Zimbabwe"
    },
    {
      "city": "Burj Khalifa",
      "city_ascii": "",
      "lat": 25.197139,
      "lng": 55.274111,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Burj_Khalifa"
    },
    {
      "city": "CN Tower",
      "city_ascii": "",
      "lat": 43.6426,
      "lng": -79.3871,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/CN_Tower"
    },
    {
      "city": "Taipei 101 (臺北101/台北101)",
      "city_ascii": "",
      "lat": 25.033611,
      "lng": 121.565,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Taipei_101"
    },
    {
      "city": "Eiffel Tower",
      "city_ascii": "",
      "lat": 48.858222,
      "lng": 2.2945,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Eiffel_Tower"
    },
    {
      "city": "Louvre",
      "city_ascii": "",
      "lat": 48.858222,
      "lng": 2.2945,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Louvre"
    },
    {
      "city": "Darvaza Gas Crater",
      "city_ascii": "",
      "lat": 40.25252,
      "lng": 58.4396,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Darvaza_Gas_Crater"
    },
    {
      "city": "Fergana Valley",
      "city_ascii": "",
      "lat": 40.9008,
      "lng": 71.7578,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Fergana_Valley"
    },
    {
      "city": "Battle of Waterloo",
      "city_ascii": "",
      "lat": 50.68,
      "lng": 4.412,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Battle_of_Waterloo"
    },
    {
      "city": "Large Hadron Collider (LHC) at CERN",
      "city_ascii": "",
      "lat": 46.233324,
      "lng": 6.0499998,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Large_Hadron_Collider"
    },
    {
      "city": "Niagara Falls",
      "city_ascii": "",
      "lat": 43.0799,
      "lng": -79.0747,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Niagara_Falls"
    },
    {
      "city": "The Colosseum",
      "city_ascii": "",
      "lat": 41.883333,
      "lng": 12.5,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Colosseum"
    },
    {
      "city": "Catacombs of Kom El Shoqafa",
      "city_ascii": "",
      "lat": 31.178558,
      "lng": 29.892954,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Catacombs_of_Kom_El_Shoqafa"
    },
    {
      "city": "Hagia Sophia",
      "city_ascii": "",
      "lat": 41.0085,
      "lng": 28.9799,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Hagia_Sophia"
    },
    {
      "city": "Porcelain Tower of Nanjing (琉璃塔)",
      "city_ascii": "",
      "lat": 32.05,
      "lng": 118.766667,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Porcelain_Tower_of_Nanjing"
    },
    {
      "city": "Mount Everest",
      "city_ascii": "",
      "lat": 27.988056,
      "lng": 86.925278,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Mount_Everest"
    },
    {
      "city": "Chichen Itza",
      "city_ascii": "",
      "lat": 20.683056,
      "lng": -88.568611,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Chichen_Itza"
    },
    {
      "city": "Christ the Redeemer Statue",
      "city_ascii": "",
      "lat": -22.951944,
      "lng": -43.210556,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Christ_the_Redeemer_(statue)"
    },
    {
      "city": "Petra",
      "city_ascii": "",
      "lat": 30.328611,
      "lng": 35.441944,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Petra"
    },
    {
      "city": "Great Barrier Reef",
      "city_ascii": "",
      "lat": -18.283333,
      "lng": 147.7,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Great_Barrier_Reef"
    },
    {
      "city": "Victoria Falls",
      "city_ascii": "",
      "lat": -17.924444,
      "lng": 25.856667,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Victoria_Falls"
    },
    {
      "city": "Iguazu Falls",
      "city_ascii": "",
      "lat": -25.686667,
      "lng": -54.444722,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Iguazu_Falls"
    },
    {
      "city": "Hoover Dam",
      "city_ascii": "",
      "lat": 36.015556,
      "lng": -114.737778,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Hoover_Dam"
    },
    {
      "city": "Challenger Deep",
      "city_ascii": "",
      "lat": 11.373333,
      "lng": 142.591667,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Challenger_Deep"
    },
    {
      "city": "K2 (Mountain)",
      "city_ascii": "",
      "lat": 35.8825,
      "lng": 76.513333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/K2"
    },
    {
      "city": "Mount Kilimanjaro",
      "city_ascii": "",
      "lat": -3.075833,
      "lng": 37.353333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Mount_Kilimanjaro"
    },
    {
      "city": "Mount Aconcagua",
      "city_ascii": "",
      "lat": -32.653611,
      "lng": -70.011111,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Aconcagua"
    },
    {
      "city": "Denali (formerly Mount McKinley)",
      "city_ascii": "",
      "lat": 63.0695,
      "lng": -151.0074,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Denali"
    },
    {
      "city": "Mount Elbrus",
      "city_ascii": "",
      "lat": 43.355,
      "lng": 42.439167,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Mount_Elbrus"
    },
    {
      "city": "Mount Kosciuszko",
      "city_ascii": "",
      "lat": -36.455833,
      "lng": 148.263611,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Mount_Kosciuszko"
    },
    {
      "city": "Mont Blanc",
      "city_ascii": "",
      "lat": 45.832778,
      "lng": 6.865,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Mont_Blanc"
    },
    {
      "city": "Mount Puncak Jaya",
      "city_ascii": "",
      "lat": -4.078889,
      "lng": 137.158333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Puncak_Jaya"
    },
    {
      "city": "Tsar Bomba Nuclear Test Site",
      "city_ascii": "",
      "lat": 75.5,
      "lng": 60,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Tsar_Bomba"
    },
    {
      "city": "Trinity Nuclear Test Site",
      "city_ascii": "",
      "lat": 33.677222,
      "lng": -106.475278,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Trinity_(nuclear_test)"
    },
    {
      "city": "Area 51",
      "city_ascii": "",
      "lat": 37.233333,
      "lng": -115.808333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Area_51"
    },
    {
      "city": "Carthage",
      "city_ascii": "",
      "lat": 36.8528,
      "lng": 10.3233,
      "country": "Carthaginian Civilization",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Carthage"
    },
    {
      "city": "Nineveh",
      "city_ascii": "",
      "lat": 36.359444,
      "lng": 43.152778,
      "country": "Assyrian Empire",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Nineveh"
    },
    {
      "city": "Babylon",
      "city_ascii": "",
      "lat": 32.536389,
      "lng": 44.420833,
      "country": "Babylonian Empire",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Babylon"
    },
    {
      "city": "St. Peter's Basilica",
      "city_ascii": "",
      "lat": 41.902222,
      "lng": 12.453333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/St._Peter%27s_Basilica"
    },
    {
      "city": "Bagan",
      "city_ascii": "",
      "lat": 21.166667,
      "lng": 94.866667,
      "country": "Pagan Kingdom",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Bagan"
    },
    {
      "city": "Alexander Graham Bell makes First Phone Call",
      "city_ascii": "",
      "lat": 48.358056,
      "lng": -71.063611,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://cambridgehistory.org/innovation/First Phone Call.html"
    },
    {
      "city": "Chernobyl Nuclear Disaster",
      "city_ascii": "",
      "lat": 51.404722,
      "lng": 30.056944,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Chernobyl_Disaster"
    },
    {
      "city": "Fukushima Daiichi Nuclear Disaster (福島第一原子力発電所事故)",
      "city_ascii": "",
      "lat": 37.421389,
      "lng": 141.0325,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Fukushima_Daiichi_Nuclear_Disaster"
    },
    {
      "city": "Three Mile Island Nuclear Incident",
      "city_ascii": "",
      "lat": 40.41,
      "lng": -76.79,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Three_Mile_Island_Accident"
    },
    {
      "city": "Three Mile Island Nuclear Incident",
      "city_ascii": "",
      "lat": 40.41,
      "lng": -76.79,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Three_Mile_Island_Accident"
    },
    {
      "city": "Vela Incident",
      "city_ascii": "",
      "lat": -47,
      "lng": 40,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Vela_Incident"
    },
    {
      "city": "Lenin's Mausoleum",
      "city_ascii": "",
      "lat": 55.753611,
      "lng": 37.619722,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Lenin%27s_Mausoleum"
    },
    {
      "city": "Bodhi Tree",
      "city_ascii": "",
      "lat": 24.695102,
      "lng": 84.991275,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Bodhi_Tree"
    },
    {
      "city": "Exxon Valdez Oil Spill",
      "city_ascii": "",
      "lat": 60.8408,
      "lng": -146.8625,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Exxon_Valdez_Oil_Spill"
    },
    {
      "city": "Deepwater Horizon Oil Spill (BP Oil Spill)",
      "city_ascii": "",
      "lat": 28.738139,
      "lng": -88.365944,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Deepwater_Horizon_Oil_Spill"
    },
    {
      "city": "Sinking of the RMS Titanic",
      "city_ascii": "",
      "lat": 41.725556,
      "lng": -49.946944,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Sinking_of_the_RMS_Titanic"
    },
    {
      "city": "Hindenburg Disaster",
      "city_ascii": "",
      "lat": 40.033333,
      "lng": -74.353611,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Hindenburg_Disaster"
    },
    {
      "city": "The Great Molasses Flood",
      "city_ascii": "",
      "lat": 42.3685,
      "lng": -71.055833,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Great_Molasses_Flood"
    },
    {
      "city": "Assassination of Archduke Franz Ferdinand",
      "city_ascii": "",
      "lat": 43.857917,
      "lng": 18.42875,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Assassination_of_Archduke_Franz_Ferdinand"
    },
    {
      "city": "Assassination of Yitzhak Rabin",
      "city_ascii": "",
      "lat": 32.081889,
      "lng": 34.780944,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Assassination_of_Yitzhak_Rabin"
    },
    {
      "city": "Battle of Isandlwana",
      "city_ascii": "",
      "lat": -28.351944,
      "lng": 30.651667,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Battle_of_Isandlwana"
    },
    {
      "city": "Matterhorn Mountain",
      "city_ascii": "",
      "lat": 45.976389,
      "lng": 7.658611,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Matterhorn"
    },
    {
      "city": "Eyjafjallajökull Volcano",
      "city_ascii": ">yjafjallajokull Volcano",
      "lat": 63.62,
      "lng": -19.613333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Eyjafjallajökull"
    },
    {
      "city": "Zhangjiajie National Forest Park (湖南张家界国家森林公园)",
      "city_ascii": "",
      "lat": 29.160833,
      "lng": 110.416111,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Zhangjiajie_National_Forest_Park"
    },
    {
      "city": "Rosetta Stone Discovery Site",
      "city_ascii": "",
      "lat": 31.404444,
      "lng": 30.416389,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Rosetta_Stone"
    },
    {
      "city": "Jamestown Settlement",
      "city_ascii": "",
      "lat": 37.209167,
      "lng": -76.7775,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Jamestown,_Virginia"
    },
    {
      "city": "Vostok 1 (Yuri Gagarin) Launch Site",
      "city_ascii": "",
      "lat": 45.920278,
      "lng": 63.342222,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Vostok_1"
    },
    {
      "city": "Vostok 1 (Yuri Gagarin) Landing Site",
      "city_ascii": "",
      "lat": 51.270682,
      "lng": 45.99727,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Vostok_1"
    },
    {
      "city": "Leshan Giant Buddha (乐山大佛)",
      "city_ascii": "",
      "lat": 29.544722,
      "lng": 103.773333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Leshan_Giant_Buddha"
    },
    {
      "city": "Equestrian Statue of Genghis Khan",
      "city_ascii": "",
      "lat": 47.807928,
      "lng": 107.536897,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Equestrian_statue_of_Genghis_Khan"
    },
    {
      "city": "Fushimi Inari-taisha (伏見稲荷大社)",
      "city_ascii": "",
      "lat": 34.967222,
      "lng": 135.772778,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Fushimi_Inari-taisha"
    },
    {
      "city": "Itsukushima Shrine (厳島神社)",
      "city_ascii": "",
      "lat": 34.295833,
      "lng": 132.319722,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Itsukushima_Shrine"
    },
    {
      "city": "Sognefjord",
      "city_ascii": "",
      "lat": 61.1,
      "lng": 5.166667,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Sognefjord"
    },
    {
      "city": "Fort Knox",
      "city_ascii": "",
      "lat": 37.92,
      "lng": -85.96,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Fort_Knox"
    },
    {
      "city": "Bering Strait",
      "city_ascii": "",
      "lat": 66.5,
      "lng": -169,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Bering_Strait"
    },
    {
      "city": "Pearl Harbor",
      "city_ascii": "",
      "lat": 21.34927,
      "lng": -157.94397,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Naval_Station_Pearl_Harbor"
    },
    {
      "city": "Forbidden City (故宫)",
      "city_ascii": "",
      "lat": 39.915987,
      "lng": 116.397925,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Forbidden_City"
    },
    {
      "city": "Kinkaku-ji (金閣寺)",
      "city_ascii": "",
      "lat": 35.011667,
      "lng": 135.768333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Kinkaku-ji"
    },
    {
      "city": "Nikkō Tōshō-gū (日光東照宮)",
      "city_ascii": "",
      "lat": 36.758064,
      "lng": 139.598958,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Nikkō_Tōshō-gū"
    },
    {
      "city": "Abu Simbel Temples",
      "city_ascii": "",
      "lat": 22.336944,
      "lng": 31.625556,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Abu_Simbel_temples"
    },
    {
      "city": "Battle of Marathon",
      "city_ascii": "",
      "lat": 38.118056,
      "lng": 23.978333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Battle_of_Marathon"
    },
    {
      "city": "Grand Canyon",
      "city_ascii": "",
      "lat": 36.3,
      "lng": -112.6,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Grand_Canyon"
    },
    {
      "city": "Cave of the Crystals (Cueva de los Cristales)",
      "city_ascii": "",
      "lat": 27.850833,
      "lng": -105.496389,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Cave_of_the_Crystals"
    },
    {
      "city": "Magura Cave Prehistoric Paintings",
      "city_ascii": "",
      "lat": 43.727778,
      "lng": 22.582778,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Magura_Cave"
    },
    {
      "city": "Mount Rushmore",
      "city_ascii": "",
      "lat": 43.878889,
      "lng": -103.459722,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Mount_Rushmore"
    },
    {
      "city": "Alcatraz Island",
      "city_ascii": "",
      "lat": 37.826667,
      "lng": -122.422778,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Alcatraz_Island"
    },
    {
      "city": "Wright Flyer (First heavier-than-air powered flight) ",
      "city_ascii": "",
      "lat": 36.025556,
      "lng": -75.67,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Wright_Flyer"
    },
    {
      "city": "'I Have a Dream' Speech by Martin Luther King Jr.",
      "city_ascii": "",
      "lat": 38.889278,
      "lng": -77.050139,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/I_Have_a_Dream"
    },
    {
      "city": "Nazca Lines",
      "city_ascii": "",
      "lat": -14.716667,
      "lng": -75.133333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Nazca_Lines"
    },
    {
      "city": "Joseph Smith Discovers the Golden Plates (Book of Mormon)",
      "city_ascii": "",
      "lat": 43.28,
      "lng": -77.05,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Golden_plates"
    },
    {
      "city": "14th Dalai Lama Birthplace",
      "city_ascii": "",
      "lat": 36.378083,
      "lng": 101.865889,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/14th_Dalai_Lama"
    },
    {
      "city": "Debre Damo Monastery",
      "city_ascii": "",
      "lat": 14.373889,
      "lng": 39.290278,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Debre_Damo"
    },
    {
      "city": "Taktsang Palphug Monastery",
      "city_ascii": "",
      "lat": 27.491911,
      "lng": 89.363489,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Paro_Taktsang"
    },
    {
      "city": "Abuna Yemata Guh Church",
      "city_ascii": "",
      "lat": 13.91526,
      "lng": 39.343071,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Abuna_Yemata_Guh"
    },
    {
      "city": "Antelope Canyon",
      "city_ascii": "",
      "lat": 36.952766,
      "lng": -111.441268,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Antelope_Canyon"
    },
    {
      "city": "Newnes Glowworm Tunnel",
      "city_ascii": "",
      "lat": -33.238727,
      "lng": 150.226593,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Glowworm_Tunnel"
    },
    {
      "city": "Waitomo Glowworm Caves",
      "city_ascii": "",
      "lat": -38.26065,
      "lng": 175.103339,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Waitomo_Glowworm_Caves"
    },
    {
      "city": "That Wanaka Tree",
      "city_ascii": "",
      "lat": -45.0311,
      "lng": 168.6644,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://www.atlasobscura.com/places/lone-tree-of-lake-wanaka"
    },
    {
      "city": "Discovery of early Australopithecus, a.k.a Lucy",
      "city_ascii": "",
      "lat": 11.12,
      "lng": 40.58,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Lucy_(Australopithecus)"
    },
    {
      "city": "Discovery of Neanderthals",
      "city_ascii": "",
      "lat": 51.226129,
      "lng": 6.951058,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Neandertal_(valley)"
    },
    {
      "city": "Discovery of Denisovans",
      "city_ascii": "",
      "lat": 51.3975,
      "lng": 84.676111,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Denisovan"
    },
    {
      "city": "Valley of the Kings",
      "city_ascii": "",
      "lat": 25.740833,
      "lng": 32.602222,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Valley_of_the_Kings"
    },
    {
      "city": "Galápagos Islands",
      "city_ascii": "Galapagos Islands",
      "lat": -0.666667,
      "lng":  -90.55,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Gal%C3%A1pagos_Islands"
    },
    {
      "city": "Execution of the Romanov family",
      "city_ascii": "",
      "lat": 56.833333,
      "lng":  60.583333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Execution_of_the_Romanov_family"
    },
    {
      "city": "Auschwitz concentration camp",
      "city_ascii": "",
      "lat": 50.035833,
      "lng": 19.178333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Auschwitz_concentration_camp"
    },
    {
      "city": "Guantanamo Bay Detention Camp",
      "city_ascii": "",
      "lat": 19.902222,
      "lng": -75.098889,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Guantanamo_Bay_detention_camp"
    },
{
      "city": "Pompeii (Mount Vesuvius)",
      "city_ascii": "",
      "lat": 40.75,
      "lng": 14.5,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Pompei"
    },
    {
      "city": "Tikal",
      "city_ascii": "",
      "lat": 17.221944,
      "lng": -89.623611,
      "country": "Maya Civilization",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Tikal"
    },
    {
      "city": "Leptis Magna",
      "city_ascii": "",
      "lat": 32.639167, 
      "lng": 14.290556,
      "country": "Carthaginian Empire",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Leptis_Magna"
    },
    {
      "city": "Edward Jenner Develops the First Successful Vaccine",
      "city_ascii": "",
      "lat": 51.691, 
      "lng": -2.459,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Smallpox_vaccine#Variolation"
    },
    {
      "city": "Longmen Grottoes",
      "city_ascii": "",
      "lat": 34.555556, 
      "lng": 112.469722,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Longmen_Grottoes"
    },
    {
      "city": "Ellora Caves",
      "city_ascii": "",
      "lat": 20.0268,
      "lng": 75.1771,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Ellora_Caves"
    },
    {
      "city": "Ta Prohm Temple",
      "city_ascii": "",
      "lat": 13.435,
      "lng": 103.889167,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Ta_Prohm"
    },
    {
      "city": "Rosalind Franklin takes first diffraction photo of DNA",
      "city_ascii": "",
      "lat": 51.511944,
      "lng": -0.116111,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Photo_51"
    },
    {
      "city": "Tenochtitlan",
      "city_ascii": "",
      "lat": 19.433333,
      "lng": -99.133333,
      "country": "Aztec Empire",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Tenochtitlan"
    },
    {
      "city": "Tiwanaku",
      "city_ascii": "",
      "lat": -16.554722, 
      "lng": -68.673333,
      "country": "Tiwanaku Empire",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Tiwanaku"
    },
    {
      "city": "Uaxactun",
      "city_ascii": "",
      "lat": 17.393561,
      "lng": -89.634533,
      "country": "Mayan Civilization",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Uaxactun"
    },
    {
      "city": "Lake Titicaca",
      "city_ascii": "",
      "lat": -15.75,
      "lng": -69.416667,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Lake_Titicaca"
    },
    {
      "city": "Cusco",
      "city_ascii": "",
      "lat": -13.525,
      "lng": -71.972222,
      "country": "Incan Empire",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Cusco"
    },
    {
      "city": "Svalbard Global Seed Vault",
      "city_ascii": "",
      "lat": 78.235867,
      "lng": 15.491374,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Svalbard_Global_Seed_Vault"
    },
    {
      "city": "Petronas Towers",
      "city_ascii": "",
      "lat": 3.158,
      "lng": 101.712,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Petronas_Towers"
    },
    {
      "city": "Sinking of the RMS Lusitania",
      "city_ascii": "",
      "lat": 51.416667,
      "lng": -8.55,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Sinking_of_the_RMS_Lusitania"
    },
    {
      "city": "Ryugyong Hotel (류경려관)",
      "city_ascii": "",
      "lat": 39.036667,
      "lng": 125.730833,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Ryugyong_Hotel"
    },
    {
      "city": "Chicxulub Crater",
      "city_ascii": "",
      "lat": 21.4,
      "lng": -89.516667,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Chicxulub_crater"
    },
    {
      "city": "Vredefort Crater",
      "city_ascii": "",
      "lat": -27,
      "lng": 27.5,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Vredefort_crater"
    },
    {
      "city": "Wolfe Creek Crater",
      "city_ascii": "",
      "lat": -19.171667,
      "lng": 127.795556,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Wolfe_Creek_Crater"
    },
    {
      "city": "Meteor Crater (Canyon Diablo Crater)",
      "city_ascii": "",
      "lat": 35.027222,
      "lng": -111.0225,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Meteor_Crater"
    },
    {
      "city": "Elugelab (First H-Bomb Test Site)",
      "city_ascii": "",
      "lat": 11.666667,
      "lng": 162.186944,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Elugelab"
    },
    {
      "city": "Taal Volcano",
      "city_ascii": "",
      "lat": 14.01,
      "lng": 120.9975,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Taal_Volcano"
    },
    {
      "city": "Very Large Telescope (VLT)",
      "city_ascii": "",
      "lat": -24.62733,
      "lng": -70.40417,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Very_Large_Telescope"
    },
    {
      "city": "Extremely Large Telescope (ELT)",
      "city_ascii": "",
      "lat": -24.59328,
      "lng": -70.19717,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Extremely_Large_Telescope"
    },
    {
      "city": "Giant Magellan Telescope (GMT)",
      "city_ascii": "",
      "lat": -29.0283,
      "lng": -70.6858,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Giant_Magellan_Telescope"
    },
    {
      "city": "Christ of the Abyss",
      "city_ascii": "",
      "lat": 44.314038,
      "lng": 9.174979,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Christ_of_the_Abyss"
    },
    {
      "city": "Tian Tan Buddha (天壇大佛)",
      "city_ascii": "",
      "lat": 22.254106,
      "lng": 113.905144,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Tian_Tan_Buddha"
    },
    {
      "city": "The Little Mermaid (statue)",
      "city_ascii": "",
      "lat": 55.692861,
      "lng": 12.599278,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/The_Little_Mermaid_(statue)"
    },
    {
      "city": "Venus de Milo Statue (Αφροδίτη της Μήλου)",
      "city_ascii": "",
      "lat": 48.859958,
      "lng": 2.337269,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Venus_de_Milo"
    },
    {
      "city": "Mount Rainier",
      "city_ascii": "",
      "lat": 46.879967,
      "lng": -121.726906,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Park",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Channel Islands",
      "city_ascii": "",
      "lat": 33.998028,
      "lng": -119.772949,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Park",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Yosemite",
      "city_ascii": "",
      "lat": 37.865101,
      "lng": -119.53833,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Park",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Joshua Tree",
      "city_ascii": "",
      "lat": 33.881866,
      "lng": -115.90065,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Park",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Mojave",
      "city_ascii": "",
      "lat": 35.141689,
      "lng": -115.510399,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Preserve",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Zion",
      "city_ascii": "",
      "lat": 37.317207,
      "lng": -113.022537,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Park",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Yellowstone",
      "city_ascii": "",
      "lat": 44.429764,
      "lng": -110.584663,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Park",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Petrified Forest",
      "city_ascii": "",
      "lat": 34.909988,
      "lng": -109.806793,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Park",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Arches",
      "city_ascii": "",
      "lat": 38.733082,
      "lng": -109.592514,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Park",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Mesa Verde",
      "city_ascii": "",
      "lat": 37.230873,
      "lng": -108.461838,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Park",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Little Sandy",
      "city_ascii": "",
      "lat": 32.590797,
      "lng": -95.273666,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat'l Wildlife Refuge",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Anahuac ",
      "city_ascii": "",
      "lat": 29.6103,
      "lng": -94.449081,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat'l Wildlife Refuge",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Hot Springs",
      "city_ascii": "",
      "lat": 34.52153,
      "lng": -93.042267,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Park",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Chattahoochee",
      "city_ascii": "",
      "lat": 34.765972,
      "lng": -84.143517,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Forest",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Great Smoky Mountains",
      "city_ascii": "",
      "lat": 35.611763,
      "lng": -83.489548,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Park",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Okefenokee",
      "city_ascii": "",
      "lat": 30.77323,
      "lng": -82.292732,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Wildlife Refuge",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Acadia",
      "city_ascii": "",
      "lat": 44.338974,
      "lng": -68.27343,
      "country": "United States",
      "iso2": "US",
      "iso3": "",
      "admin_name": "Nat’l Park",
      "capital": "",
      "population": "",
      "id": ""
    },
    {
      "city": "Banff",
      "city_ascii": "",
      "lat": 51.5,
      "lng": -116,
      "country": "Canada",
      "iso2": "CA",
      "admin_name": "Nat’l Park",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Banff_National_Park"
    },
    {
      "city": "Gatineau Park",
      "city_ascii": "",
      "lat": 45.583333, 
      "lng": -76,
      "country": "Canada",
      "iso2": "CA",
      "admin_name": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Gatineau_Park"
    },
    {
      "city": "Centers for Disease Control and Prevention (CDC)",
      "city_ascii": "",
      "lat": 33.799444,
      "lng": -84.328333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Centers_for_Disease_Control_and_Prevention"
    },
    {
      "city": "de facto Capital of the European Union",
      "city_ascii": "",
      "lat": 50.84,
      "lng": 4.38,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Brussels_and_the_European_Union"
    },
    {
      "city": "Heliopolis",
      "city_ascii": "",
      "lat": 30.129333,
      "lng": 31.307528,
      "country": "Ancient Egypt",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Heliopolis_(ancient_Egypt)"
    },
    {
      "city": "Butrint",
      "city_ascii": "",
      "lat": 39.745556,
      "lng": 20.020556,
      "country": "Ancient Greece / Rome",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Butrint"
    },
    {
      "city": "Hadrian's Wall",
      "city_ascii": "",
      "lat": 55.024167,
      "lng": -2.2925,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Hadrian%27s_Wall"
    },
    {
      "city": "Antonine Wall",
      "city_ascii": "",
      "lat": 55.967,
      "lng": -4.067,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Antonine_Wall"
    },
    {
      "city": "Trajan's Column",
      "city_ascii": "",
      "lat": 41.895833,
      "lng": 12.484167,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Trajan%27s_Column"
    },
    {
      "city": "Devil's Island (penal colony of Cayenne)",
      "city_ascii": "",
      "lat": 5.293611,
      "lng": -52.583056,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Devil%27s_Island"
    },
    {
      "city": "Death place of Ferdinand Magellan",
      "city_ascii": "",
      "lat": 10.3,
      "lng": 123.966667,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Ferdinand_Magellan#Death"
    },
    {
      "city": "Elba (Napoleon Bonaparte's Island of Exile)",
      "city_ascii": "",
      "lat": 42.782711,
      "lng": 10.286335,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Napoleon#Exile_to_Elba"
    },
    {
      "city": "Large Underground Xenon Experiment (LUX)",
      "city_ascii": "",
      "lat": 44.352,
      "lng": -103.751,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Large_Underground_Xenon_experiment"
    },
    {
      "city": "Boll Weevil Monument",
      "city_ascii": "",
      "lat": 31.314444,
      "lng": -85.854028,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Boll_Weevil_Monument"
    },
    {
      "city": "Annual Nobel Prize Ceremony (excluding Peace Prize)",
      "city_ascii": "",
      "lat": 59.329444,
      "lng": 18.068611,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Nobel_Prize"
    },
    {
      "city": "Annual Nobel Peace Prize Ceremony",
      "city_ascii": "",
      "lat": 59.916667,
      "lng": 10.733333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Nobel_Prize"
    },
    {
      "city": "Kindlifresserbrunnen (The Child Eater Statue)",
      "city_ascii": "",
      "lat": 46.948519,
      "lng": 7.447447,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Kindlifresserbrunnen"
    },
    {
      "city": "Blue Mustang Statue (Blucifer)",
      "city_ascii": "",
      "lat": 39.83414,
      "lng": -104.67638,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Blue_Mustang"
    },
    {
      "city": "Smithsonian Institution",
      "city_ascii": "",
      "lat": 38.889,
      "lng": -77.026,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Smithsonian_Institution"
    },
    {
      "city": "Gereja Ayam ('Chicken Church')",
      "city_ascii": "",
      "lat": -7.605694,
      "lng": 110.1805,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Gereja_Ayam"
    },
    {
      "city": "Manneken Pis ('Little Pissing Man')",
      "city_ascii": "",
      "lat": 50.84499,
      "lng": 4.34998,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Manneken_Pis"
    },
    {
      "city": "Birth/Death Place of Johannes Gutenberg",
      "city_ascii": "",
      "lat": 50,
      "lng": 8.266667,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Johannes_Gutenberg"
    },
    {
      "city": "Ivan Pavlov's Dog Study",
      "city_ascii": "",
      "lat": 59.942,
      "lng": 30.299,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Classical_conditioning#Pavlov's_research"
    },
    {
      "city": "Eratosthenes Measures Earth's Circumference",
      "city_ascii": "",
      "lat": 31.2,
      "lng": 29.916667,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Eratosthenes#Measurement_of_the_Earth's_circumference"
    },
    {
      "city": "Michelson-Morley Experiment",
      "city_ascii": "",
      "lat": 41.504,
      "lng": -81.608,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Michelson–Morley_experiment"
    },
    {
      "city": "Marie Curie Discovers Polonium and Radium",
      "city_ascii": "",
      "lat": 48.856613,
      "lng": 2.352222,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Marie_Curie#New_elements"
    },
    {
      "city": "Robert Millikan Oil Drop Experiment",
      "city_ascii": "",
      "lat": 41.789722,
      "lng": -87.599722,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Oil_drop_experiment"
    },
    {
      "city": "Florence Nightingale Pioneers Modern Nursing",
      "city_ascii": "",
      "lat": 41.008056,
      "lng": 29.015833,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Florence_Nightingale#Statistics_and_sanitary_reform"
    },
    {
      "city": "Hell",
      "city_ascii": "",
      "lat": 63.4444,
      "lng": 10.9227,
      "country": "Norway",
      "iso2": "NO",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Hell,_Norway"
    },
    {
      "city": "Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu",
      "city_ascii": "",
      "lat": -40.346,
      "lng": 176.5402,
      "iso2": "NZ",
      "country": "New Zealand",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu"
    },
    {
      "city": "Boring",
      "city_ascii": "",
      "lat": 45.43,
      "lng": -122.373611,
      "country": "United States",
      "population": 0,
      "capital": "",
      "iso2": "US",
      "admin_name": "Oregon",
      "wiki": "https://en.wikipedia.org/wiki/Boring,_Oregon"
    },
    {
      "city": "No Name",
      "city_ascii": "",
      "lat": 39.560278,
      "lng": -107.293333,
      "country": "United States",
      "population": 0,
      "admin_name": "Colorado",
      "iso2": "US",
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/No_Name,_Colorado"
    },
    {
      "city": "Poo",
      "city_ascii": "",
      "lat": 43.30791,
      "lng": -4.83514,
      "country": "Spain",
      "iso2": "ES",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Poo_(Cabrales)"
    },
    {
      "city": "Middelfart",
      "city_ascii": "",
      "lat": 55.498611,
      "lng": 9.744444,
      "iso2": "DK",
      "country": "Denmark",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Middelfart"
    },
    {
      "city": "Batman",
      "city_ascii": "",
      "lat": 37.880556,
      "lng": 41.1275,
      "country": "Turkey",
      "iso2": "TR",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Batman,_Turkey"
    },
    {
      "city": "The Biggest Ball of Twine",
      "city_ascii": "",
      "lat": 45.096389,
      "lng": -94.410833,
      "admin_name": "Minnesota",
      "country": "United States",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Biggest_ball_of_twine#Largest_ball_of_sisal_twine_built_by_a_single_person"
    },
    {
      "city": "Hetch Hetchy Valley",
      "city_ascii": "",
      "lat": 37.9475,
      "lng": -119.7869,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Hetch_Hetchy"
    },
    {
      "city": "Everglades",
      "city_ascii": "",
      "lat": 25.3125,
      "lng": -80.6875,
      "country": "United States",
      "admin_name": "Nat’l Park",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Everglades_National_Park"
    },
    {
      "city": "Gros Morne",
      "city_ascii": "",
      "lat": 49.689444,
      "lng": -57.738056,
      "country": "Canada",
      "iso2": "CA",
      "admin_name": "Nat’l Park",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Gros_Morne_National_Park"
    },
    {
      "city": "Jasper",
      "city_ascii": "",
      "lat": 52.8,
      "lng": -117.9,
      "country": "Canada",
      "iso2": "CA",
      "admin_name": "Nat’l Park",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Jasper_National_Park"
    },
    {
      "city": "Kluane",
      "city_ascii": "",
      "lat": 60.61943,
      "lng": -138.331,
      "country": "Canada",
      "iso2": "CA",
      "admin_name": "Nat’l Park",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Kluane_National_Park_and_Reserve"
    },
    {
      "city": "Pacific Rim",
      "city_ascii": "",
      "lat": 48.636111,
      "lng": -124.769167,
      "country": "Canada",
      "iso2": "CA",
      "admin_name": "Nat’l Park",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Pacific_Rim_National_Park_Reserve"
    },
    {
      "city": "Yoho",
      "city_ascii": "",
      "lat": 51.395278,
      "lng": -116.486667,
      "country": "Canada",
      "iso2": "CA",
      "admin_name": "Nat’l Park",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Yoho_National_Park"
    },
    {
      "city": "Code of Hammurabi Discovery Site",
      "city_ascii": "",
      "lat": 32.190556,
      "lng": 48.257778,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Code_of_Hammurabi"
    },
    {
      "city": "Susa",
      "city_ascii": "",
      "lat": 32.190556,
      "lng": 48.257778,
      "country": "Parthian / Sasanian Empire",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Susa"
    },    
    {
      "city": "Istakhr",
      "city_ascii": "",
      "lat": 29.980833,
      "lng": 52.909444,
      "country": "Sasanian Empire",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Istakhr"
    },    
    {
      "city": "Karakorum",
      "city_ascii": "",
      "lat": 47.210278,
      "lng": 102.847778,
      "country": "Mongol Empire",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Karakorum"
    },    
    {
      "city": "Cirta",
      "city_ascii": "",
      "lat": 36.3675,
      "lng": 6.611944,
      "country": "Berber Kingdom of Numidia",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Cirta"
    },    
    {
      "city": "Kerma",
      "city_ascii": "",
      "lat": 19.600803,
      "lng": 30.409731,
      "country": "Kerma Kingdom of Nubia",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Kerma"
    },    
    {
      "city": "Harappa",
      "city_ascii": "",
      "lat": 30.628889,
      "lng": 72.863889,
      "country": "Indus Valley Civilization",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Harappa"
    },
    {
      "city": "Yangcheng (陽城)",
      "city_ascii": "",
      "lat": 34.455278,
      "lng": 113.025278,
      "country": "Xia Dynasty, China",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Yangcheng_(historical_city)"
    },
    {
      "city": "Chang'an (长安)",
      "city_ascii": "",
      "lat": 34.266667,
      "lng": 108.9,
      "country": "Han Dynasty, China",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Chang%27an"
    },
    {
      "city": "New Echota",
      "city_ascii": "",
      "lat": 34.539444,
      "lng": -84.908611,
      "country": "Cherokee Nation (pre-1830)",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/New_Echota"
    },
    {
      "city": "Rössing Uranium Mine",
      "city_ascii": "",
      "lat": -22.484167,
      "lng": 15.048889,
      "iso2": "NA",
      "country": "Namibia",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Rössing_uranium_mine"
    },
    {
      "city": "Spitzkoppe ('Matterhorn of Namibia')",
      "city_ascii": "",
      "lat": -21.824722,
      "lng": 15.194167,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Spitzkoppe"
    },
    {
      "city": "2013 Chelyabinsk Meteor",
      "city_ascii": "",
      "lat": 55.15,
      "lng": 61.41,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Chelyabinsk_meteor"
    },
    {
      "city": "Apollo 11 Splashdown (First Moon Landing)",
      "city_ascii": "",
      "lat": 10.6, 
      "lng": 172.4,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Apollo_11#Splashdown_and_quarantine"
    },
    {
      "city": "1969 Woodstock Music Festival",
      "city_ascii": "",
      "lat": 41.701,
      "lng": -74.88,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Woodstock"
    },
    {
      "city": "NASA Mission Control Center (MCC-H)",
      "city_ascii": "",
      "lat": 29.558056,
      "lng": -95.088333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Christopher_C._Kraft_Jr._Mission_Control_Center"
    },
    {
      "city": "Battle of Cannae",
      "city_ascii": "",
      "lat": 41.306389,
      "lng": 16.1325,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Battle_of_Cannae"
    },
    {
      "city": "Battle of the Teutoburg Forest",
      "city_ascii": "",
      "lat": 52.408056,
      "lng": 8.129444,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Battle_of_the_Teutoburg_Forest"
    },
    {
      "city": "Battle of the Trebia",
      "city_ascii": "",
      "lat": 45.05,
      "lng": 9.6,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Battle_of_the_Trebia"
    },
    {
      "city": "Battle of Lake Trasimene",
      "city_ascii": "",
      "lat": 43.139444,
      "lng": 12.1075,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Battle_of_Lake_Trasimene"
    },
    {
      "city": "Millennium Seed Bank (MSB)",
      "city_ascii": "",
      "lat": 51.068578,
      "lng": -0.090209,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Millennium_Seed_Bank_Partnership"
    },
    {
      "city": "Australian Grains Genebank (AGG)",
      "city_ascii": "",
      "lat": -36.716667,
      "lng": 142.2,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Australian_Grains_Genebank"
    },
    {
      "city": "Last Known Passenger Pigeon ('Martha') Dies in 1914",
      "city_ascii": "",
      "lat": 39.145,
      "lng": -84.508,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Passenger_pigeon"
    },
    {
      "city": "Crater Lake",
      "city_ascii": "",
      "lat": 42.95,
      "lng": -122.1,
      "country": "United States",
      "iso2": "US",
      "population": 0,
      "admin_name": "Nat’l Park",
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Crater_Lake"
    },
    {
      "city": "Dry Tortugas",
      "city_ascii": "",
      "lat": 24.628588,
      "lng": -82.873287,
      "country": "United States",
      "iso2": "US",
      "population": 0,
      "admin_name": "Nat’l Park",
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Dry_Tortugas_National_Park"
    },
    {
      "city": "Biscayne",
      "city_ascii": "",
      "lat": 25.469444,
      "lng": -80.186111,
      "country": "United States",
      "iso2": "US",
      "population": 0,
      "admin_name": "Nat’l Park",
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Biscayne_National_Park"
    },
    {
      "city": "Copernicus Creates Heliocentric Model of Solar System ('Commentariolus')",
      "city_ascii": "",
      "lat": 54.116667,
      "lng": 20.583333,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Nicolaus_Copernicus#Heliocentrism"
    },
    {
      "city": "Niccolò Machiavelli Writes 'The Prince' (Political Treatise)",
      "city_ascii": "",
      "lat": 43.682778,
      "lng": 11.197222,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Niccolò_Machiavelli#Machiavellian"
    },
    {
      "city": "Adam Smith Begins Writing 'The Wealth of Nations'",
      "city_ascii": "",
      "lat": 43.6045,
      "lng": 1.444,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Adam_Smith#The_Wealth_of_Nations"
    },
    {
      "city": "Vincent van Gogh Paints 'The Starry Night'",
      "city_ascii": "",
      "lat": 43.79,
      "lng": 4.8325,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/The_Starry_Night"
    },
    {
      "city": "Hokusai Creates The Great Wave off Kanagawa (神奈川沖浪裏)",
      "city_ascii": "",
      "lat": 35.685,
      "lng": 139.7514,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/The_Great_Wave_off_Kanagawa"
    },
    {
      "city": "Birthplace of Archimedes",
      "city_ascii": "",
      "lat": 37.069167,
      "lng": 15.2875,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Archimedes"
    },
    {
      "city": "Hacienda Nápoles (Pablo Escobar's estate)",
      "city_ascii": "",
      "lat": 5.926,
      "lng": -74.721825,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Hacienda_Nápoles"
    },
    {
      "city": "Grand Palace (พระบรมมหาราชวัง)",
      "city_ascii": "",
      "lat": 13.7501,
      "lng": 100.492,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Grand_Palace"
    },
    {
      "city": "Drottningholm Palace",
      "city_ascii": "",
      "lat": 59.321667,
      "lng": 17.886111,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Drottningholm_Palace"
    },
    {
      "city": "Kongou Falls",
      "city_ascii": "",
      "lat": 0.290739,
      "lng": 12.58905,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Kongou_Falls"
    },
    {
      "city": "Guaíra Falls",
      "city_ascii": "",
      "lat": -24.073056,
      "lng": -54.283611,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Guaíra_Falls"
    },
    {
      "city": "Khone Phapheng Falls (ນ້ຳຕົກຕາດຄອນພະເພັງ)",
      "city_ascii": "",
      "lat": 13.948056,
      "lng": 105.940556,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Khone_Phapheng_Falls"
    },
    {
      "city": "Pará Falls",
      "city_ascii": "",
      "lat": 6.311111,
      "lng": -64.523889,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Pará_Falls"
    },
    {
      "city": "Dettifoss (waterfall)",
      "city_ascii": "",
      "lat": 65.814667,
      "lng": -16.384472,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Dettifoss"
    },
    {
      "city": "Buzludhzha Monument (Бузлуджа)",
      "city_ascii": "",
      "lat": 42.7358,
      "lng": 25.3938,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Buzludzha_monument"
    },
    {
      "city": "SS Ayrfield ('The Floating Forest') in Homebush Bay",
      "city_ascii": "",
      "lat": -33.84801,
      "lng": 151.06488,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Homebush_Bay"
    },
    {
      "city": "Submerged City of Shicheng (狮城)",
      "city_ascii": "",
      "lat": 29.609167,
      "lng": 118.99,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Qiandao_Lake#Submerged_city_of_Shi_Cheng"
    },
    {
      "city": "Peñón de Vélez de la Gomera (Shortest International Border)",
      "city_ascii": "",
      "lat": 35.172581,
      "lng": -4.300803,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Peñón_de_Vélez_de_la_Gomera"
    },
    {
      "city": "Byblos (Βύβλος) / Jbeil (جبيل‎)",
      "city_ascii": "",
      "lat": 34.123611,
      "lng": 35.651111,
      "country": "Phoenicia",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Byblos"
    },
    {
      "city": "Tyre (صور‎)",
      "city_ascii": "",
      "lat": 33.270833,
      "lng": 35.196111,
      "country": "Phoenicia",
      "population": 0,
      "capital": "primary",
      "wiki": "https://en.wikipedia.org/wiki/Tyre,_Lebanon"
    },
    {
      "city": "Battle of Hastings (1066)",
      "city_ascii": "",
      "lat": 50.911944,
      "lng": 0.4875,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Battle_of_Hastings"
    },
    {
      "city": "Osun-Osogbo Sacred Grove",
      "city_ascii": "",
      "lat": 7.755556,
      "lng": 4.552222,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/Osun-Osogbo"
    },
    {
      "city": "Naqsh-e Rostam (نقش رستم‎, Tomb of Xerxes I and Darius I)",
      "city_ascii": "",
      "lat": 29.988889,
      "lng": 52.874722,
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "en.wikipedia.org/wiki/Naqsh-e_Rostam"
    },
    {
      "city": "1896 Summer Olympics (First Olympiad)",
      "city_ascii": "",
      "lat": 37.983972,
      "lng": 23.727806,
      "country": "",
      "population": 0,
      "capital": "",
      "iso2": "GR",
      "wiki": "https://en.wikipedia.org/wiki/1896_Summer_Olympics"
    },
    {
      "city": "1900 Summer Olympics (Second Olympiad)",
      "city_ascii": "",
      "lat": 48.856613,
      "lng": 2.352222,
      "country": "",
      "population": 0,
      "capital": "",
      "iso2": "FR",
      "wiki": "https://en.wikipedia.org/wiki/1900_Summer_Olympics"
    },
    {
      "city": "1904 Summer Olympics (Third Olympiad)",
      "city_ascii": "",
      "lat": 38.627222,
      "lng": -90.197778,
      "country": "",
      "population": 0,
      "iso2": "US",
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/1904_Summer_Olympics"
    },
    {
      "city": "1936 Summer Olympics (XI Olympiad)",
      "city_ascii": "",
      "lat": 52.52,
      "lng":  13.405,
      "country": "",
      "iso2": "HH",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/1936_Summer_Olympics"
    },
    {
      "city": "1968 Summer Olympics (XIX Olympiad)",
      "city_ascii": "",
      "lat": 19.433333,
      "lng": -99.133333,
      "country": "",
      "population": 0,
      "iso2": "MX",
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/1968_Summer_Olympics"
    },
    {
      "city": "1972 Summer Olympics",
      "city_ascii": "",
      "lat": 48.133333,
      "lng": 11.566667,
      "iso2": "DE",
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/1972_Summer_Olympics"
    },
    {
      "city": "2008 Summer Olympics (XXIX Olympiad)",
      "city_ascii": "",
      "lat": 39.916667,
      "lng": 116.383333,
      "country": "",
      "iso2": "CN",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/2008_Summer_Olympics"
    },
    {
      "city": "2012 Summer Olympics (XXX Olympiad)",
      "city_ascii": "",
      "lat": 51.507222,
      "lng": -0.1275,
      "country": "",
      "iso2": "GB",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/2012_Summer_Olympics"
    },
    {
      "city": "2016 Summer Olympics (XXXI Olympiad)",
      "city_ascii": "",
      "lat": -22.908333,
      "lng": -43.196389,
      "country": "",
      "population": 0,
      "iso2": "BR",
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/2016_Summer_Olympics"
    },
    {
      "city": "2010 Winter Olympics (XXI Olympiad)",
      "city_ascii": "",
      "lat": 49.25,
      "lng": -123.1,
      "country": "",
      "population": 0,
      "iso2": "CA",
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/2010_Winter_Olympics"
    },
    {
      "city": "2014 Winter Olympics (XXII Olympiad)",
      "city_ascii": "",
      "lat": 43.585278,
      "lng": 39.720278,
      "country": "",
      "population": 0,
      "iso2": "RU",
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/2014_Winter_Olympics"
    },
    {
      "city": "2018 Winter Olympics (XXIII Olympiad)",
      "city_ascii": "",
      "lat": 37.366667,
      "lng": 128.4,
      "country": "",
      "population": 0,
      "capital": "",
      "iso2": "KR",
      "wiki": "https://en.wikipedia.org/wiki/2018_Winter_Olympics"
    },
    {
      "city": "2020 Summer Olympics (XXXII Olympiad)",
      "city_ascii": "",
      "lat": 35.689722,
      "lng": 139.692222,
      "country": "",
      "iso2": "JP",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/2020_Summer_Olympics"
    },
    {
      "city": "2018 FIFA World Cup Final (FRA 4, CRO 2)",
      "city_ascii": "",
      "lat": 55.715989,
      "lng": 37.553758,
      "iso2": "RU",
      "country": "",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/2018_FIFA_World_Cup_Final"
    },
    {
      "city": "2014 FIFA World Cup Final (GER 1, ARG 0)",
      "city_ascii": "",
      "lat": -22.908333,
      "lng": -43.196389,
      "country": "",
      "iso2": "BR",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/2014_FIFA_World_Cup_Final"
    },
    {
      "city": "2010 FIFA World Cup Final (ESP 1, GUM 0)",
      "city_ascii": "",
      "lat": -26.234797,
      "lng": 27.982353,
      "country": "",
      "iso2": "ZA",
      "population": 0,
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/2010_FIFA_World_Cup_Final"
    },
    {
      "city": "1930 FIFA World Cup (First World Cup, URU 6, YUG 0)",
      "city_ascii": "",
      "lat": -34.894444,
      "lng": -56.152778,
      "country": "",
      "population": 0,
      "iso2": "UY",
      "capital": "",
      "wiki": "https://en.wikipedia.org/wiki/1930_FIFA_World_Cup"
    },
    // {
    //   "city": "",
    //   "city_ascii": "",
    //   "lat": ,
    //   "lng": ,
    //   "country": "",
    //   "population": 0,
    //   "capital": "",
    //   "wiki": ""
    // },
    // {
    //   "city": "",
    //   "city_ascii": "",
    //   "lat": ,
    //   "lng": ,
    //   "country": "",
    //   "population": 0,
    //   "capital": "",
    //   "wiki": ""
    // },
    // {
    //   "city": "",
    //   "city_ascii": "",
    //   "lat": ,
    //   "lng": ,
    //   "country": "",
    //   "population": 0,
    //   "capital": "",
    //   "wiki": ""
    // },
    // {
    //   "city": "",
    //   "city_ascii": "",
    //   "lat": ,
    //   "lng": ,
    //   "country": "",
    //   "population": 0,
    //   "capital": "",
    //   "wiki": ""
    // },
    // {
    //   "city": "",
    //   "city_ascii": "",
    //   "lat": ,
    //   "lng": ,
    //   "country": "",
    //   "population": 0,
    //   "capital": "",
    //   "wiki": ""
    // },
    // {
    //   "city": "",
    //   "city_ascii": "",
    //   "lat": ,
    //   "lng": ,
    //   "country": "",
    //   "population": 0,
    //   "capital": "",
    //   "wiki": ""
    // },
    // {
    //   "city": "",
    //   "city_ascii": "",
    //   "lat": ,
    //   "lng": ,
    //   "country": "",
    //   "population": 0,
    //   "capital": "",
    //   "wiki": ""
    // },
    // {
    //   "city": "",
    //   "city_ascii": "",
    //   "lat": ,
    //   "lng": ,
    //   "country": "",
    //   "population": 0,
    //   "capital": "",
    //   "wiki": ""
    // },
    // {
    //   "city": "",
    //   "city_ascii": "",
    //   "lat": ,
    //   "lng": ,
    //   "country": "",
    //   "population": 0,
    //   "capital": "",
    //   "wiki": ""
    // },
    // {
    //   "city": "",
    //   "city_ascii": "",
    //   "lat": ,
    //   "lng": ,
    //   "country": "",
    //   "population": 0,
    //   "capital": "",
    //   "wiki": ""
    // },
    // {
    //   "city": "",
    //   "city_ascii": "",
    //   "lat": ,
    //   "lng": ,
    //   "country": "",
    //   "population": 0,
    //   "capital": "",
    //   "wiki": ""
    // },

    
  ]
};
