module.exports = {
    CITIES: [{
            "city": "New York",
            "city_ascii": "New York",
            "lat": 40.6943,
            "lng": -73.9249,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "New York",
            "capital": "",
            "population": 19354922,
            "id": 1840034016
        },
        {
            "city": "Los Angeles",
            "city_ascii": "Los Angeles",
            "lat": 34.1139,
            "lng": -118.4068,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "California",
            "capital": "",
            "population": 12815475,
            "id": 1840020491
        },
        {
            "city": "Chicago",
            "city_ascii": "Chicago",
            "lat": 41.8373,
            "lng": -87.6862,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Illinois",
            "capital": "",
            "population": 8675982,
            "id": 1840000494
        },
        {
            "city": "Miami",
            "city_ascii": "Miami",
            "lat": 25.7839,
            "lng": -80.2102,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Florida",
            "capital": "",
            "population": 6381966,
            "id": 1840015149
        },
        {
            "city": "Dallas",
            "city_ascii": "Dallas",
            "lat": 32.7936,
            "lng": -96.7662,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Texas",
            "capital": "",
            "population": 5733259,
            "id": 1840019440
        },
        {
            "city": "Philadelphia",
            "city_ascii": "Philadelphia",
            "lat": 40.0077,
            "lng": -75.1339,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Pennsylvania",
            "capital": "",
            "population": 5637884,
            "id": 1840000673
        },
        {
            "city": "Houston",
            "city_ascii": "Houston",
            "lat": 29.7869,
            "lng": -95.3905,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Texas",
            "capital": "",
            "population": 5446468,
            "id": 1840020925
        },
        {
            "city": "Washington",
            "city_ascii": "Washington",
            "lat": 38.9047,
            "lng": -77.0163,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "District of Columbia",
            "capital": "primary",
            "population": 5289420,
            "id": 1840006060
        },
        {
            "city": "Atlanta",
            "city_ascii": "Atlanta",
            "lat": 33.7627,
            "lng": -84.4225,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Georgia",
            "capital": "admin",
            "population": 5228750,
            "id": 1840013660
        },
        {
            "city": "Boston",
            "city_ascii": "Boston",
            "lat": 42.3188,
            "lng": -71.0846,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Massachusetts",
            "capital": "admin",
            "population": 4637537,
            "id": 1840000455
        },
        {
            "city": "Phoenix",
            "city_ascii": "Phoenix",
            "lat": 33.5722,
            "lng": -112.0891,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Arizona",
            "capital": "admin",
            "population": 4081849,
            "id": 1840020568
        },
        {
            "city": "Seattle",
            "city_ascii": "Seattle",
            "lat": 47.6211,
            "lng": -122.3244,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Washington",
            "capital": "",
            "population": 3643765,
            "id": 1840021117
        },
        {
            "city": "San Francisco",
            "city_ascii": "San Francisco",
            "lat": 37.7562,
            "lng": -122.443,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "California",
            "capital": "",
            "population": 3603761,
            "id": 1840021543
        },
        {
            "city": "Detroit",
            "city_ascii": "Detroit",
            "lat": 42.3834,
            "lng": -83.1024,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Michigan",
            "capital": "",
            "population": 3522206,
            "id": 1840003971
        },
        {
            "city": "San Diego",
            "city_ascii": "San Diego",
            "lat": 32.8312,
            "lng": -117.1225,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "California",
            "capital": "",
            "population": 3210314,
            "id": 1840021990
        },
        {
            "city": "Minneapolis",
            "city_ascii": "Minneapolis",
            "lat": 44.9635,
            "lng": -93.2678,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Minnesota",
            "capital": "",
            "population": 2926757,
            "id": 1840007830
        },
        {
            "city": "Tampa",
            "city_ascii": "Tampa",
            "lat": 27.9942,
            "lng": -82.4451,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Florida",
            "capital": "",
            "population": 2804240,
            "id": 1840015982
        },
        {
            "city": "Denver",
            "city_ascii": "Denver",
            "lat": 39.7621,
            "lng": -104.8759,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Colorado",
            "capital": "admin",
            "population": 2787266,
            "id": 1840018789
        },
        {
            "city": "Brooklyn",
            "city_ascii": "Brooklyn",
            "lat": 40.6501,
            "lng": -73.9496,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "New York",
            "capital": "",
            "population": 2629150,
            "id": 1840034030
        },
        {
            "city": "Queens",
            "city_ascii": "Queens",
            "lat": 40.7498,
            "lng": -73.7976,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "New York",
            "capital": "",
            "population": 2333054,
            "id": 1840034002
        },
        {
            "city": "Baltimore",
            "city_ascii": "Baltimore",
            "lat": 39.3051,
            "lng": -76.6144,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Maryland",
            "capital": "",
            "population": 2170504,
            "id": 1840001592
        },
        {
            "city": "Riverside",
            "city_ascii": "Riverside",
            "lat": 33.9381,
            "lng": -117.3948,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "California",
            "capital": "",
            "population": 2084749,
            "id": 1840020551
        },
        {
            "city": "St. Louis",
            "city_ascii": "St. Louis",
            "lat": 38.6358,
            "lng": -90.2451,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Missouri",
            "capital": "",
            "population": 2078283,
            "id": 1840001651
        },
        {
            "city": "Las Vegas",
            "city_ascii": "Las Vegas",
            "lat": 36.2333,
            "lng": -115.2654,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Nevada",
            "capital": "",
            "population": 2073045,
            "id": 1840020364
        },
        {
            "city": "Portland",
            "city_ascii": "Portland",
            "lat": 45.5371,
            "lng": -122.65,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Oregon",
            "capital": "",
            "population": 2052796,
            "id": 1840019941
        },
        {
            "city": "San Antonio",
            "city_ascii": "San Antonio",
            "lat": 29.4658,
            "lng": -98.5254,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Texas",
            "capital": "",
            "population": 2002530,
            "id": 1840022220
        },
        {
            "city": "Sacramento",
            "city_ascii": "Sacramento",
            "lat": 38.5667,
            "lng": -121.4683,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "California",
            "capital": "admin",
            "population": 1854698,
            "id": 1840021491
        },
        {
            "city": "San Jose",
            "city_ascii": "San Jose",
            "lat": 37.3021,
            "lng": -121.8489,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "California",
            "capital": "",
            "population": 1821899,
            "id": 1840021570
        },
        {
            "city": "Orlando",
            "city_ascii": "Orlando",
            "lat": 28.4772,
            "lng": -81.3369,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Florida",
            "capital": "",
            "population": 1776841,
            "id": 1840015099
        },
        {
            "city": "Cleveland",
            "city_ascii": "Cleveland",
            "lat": 41.4767,
            "lng": -81.6805,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Ohio",
            "capital": "",
            "population": 1730363,
            "id": 1840000596
        },
        {
            "city": "Pittsburgh",
            "city_ascii": "Pittsburgh",
            "lat": 40.4396,
            "lng": -79.9763,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Pennsylvania",
            "capital": "",
            "population": 1715297,
            "id": 1840001254
        },
        {
            "city": "Cincinnati",
            "city_ascii": "Cincinnati",
            "lat": 39.1412,
            "lng": -84.506,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Ohio",
            "capital": "",
            "population": 1648254,
            "id": 1840003814
        },
        {
            "city": "Manhattan",
            "city_ascii": "Manhattan",
            "lat": 40.7834,
            "lng": -73.9662,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "New York",
            "capital": "",
            "population": 1643734,
            "id": 1840034000
        },
        {
            "city": "Austin",
            "city_ascii": "Austin",
            "lat": 30.3006,
            "lng": -97.7517,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Texas",
            "capital": "admin",
            "population": 1638716,
            "id": 1840019590
        },
        {
            "city": "Kansas City",
            "city_ascii": "Kansas City",
            "lat": 39.1239,
            "lng": -94.5541,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Missouri",
            "capital": "",
            "population": 1615621,
            "id": 1840008535
        },
        {
            "city": "Indianapolis",
            "city_ascii": "Indianapolis",
            "lat": 39.7771,
            "lng": -86.1458,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Indiana",
            "capital": "admin",
            "population": 1564699,
            "id": 1840030084
        },
        {
            "city": "Columbus",
            "city_ascii": "Columbus",
            "lat": 39.986,
            "lng": -82.9851,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Ohio",
            "capital": "admin",
            "population": 1528314,
            "id": 1840003760
        },
        {
            "city": "Virginia Beach",
            "city_ascii": "Virginia Beach",
            "lat": 36.7335,
            "lng": -76.0435,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Virginia",
            "capital": "",
            "population": 1480383,
            "id": 1840003871
        },
        {
            "city": "Charlotte",
            "city_ascii": "Charlotte",
            "lat": 35.2079,
            "lng": -80.8304,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "North Carolina",
            "capital": "",
            "population": 1467362,
            "id": 1840014557
        },
        {
            "city": "Bronx",
            "city_ascii": "Bronx",
            "lat": 40.8501,
            "lng": -73.8662,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "New York",
            "capital": "",
            "population": 1455720,
            "id": 1840033999
        },
        {
            "city": "Milwaukee",
            "city_ascii": "Milwaukee",
            "lat": 43.0642,
            "lng": -87.9673,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Wisconsin",
            "capital": "",
            "population": 1377808,
            "id": 1840003046
        },
        {
            "city": "Providence",
            "city_ascii": "Providence",
            "lat": 41.823,
            "lng": -71.4187,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Rhode Island",
            "capital": "admin",
            "population": 1206642,
            "id": 1840003289
        },
        {
            "city": "Jacksonville",
            "city_ascii": "Jacksonville",
            "lat": 30.3322,
            "lng": -81.6749,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Florida",
            "capital": "",
            "population": 1156291,
            "id": 1840015031
        },
        {
            "city": "Salt Lake City",
            "city_ascii": "Salt Lake City",
            "lat": 40.7774,
            "lng": -111.93,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Utah",
            "capital": "admin",
            "population": 1098400,
            "id": 1840021383
        },
        {
            "city": "Nashville",
            "city_ascii": "Nashville",
            "lat": 36.1715,
            "lng": -86.7843,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Tennessee",
            "capital": "admin",
            "population": 1076645,
            "id": 1840036155
        },
        {
            "city": "Memphis",
            "city_ascii": "Memphis",
            "lat": 35.1046,
            "lng": -89.9773,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Tennessee",
            "capital": "",
            "population": 1068873,
            "id": 1840015457
        },
        {
            "city": "Richmond",
            "city_ascii": "Richmond",
            "lat": 37.5295,
            "lng": -77.4756,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Virginia",
            "capital": "admin",
            "population": 1059907,
            "id": 1840001698
        },
        {
            "city": "New Orleans",
            "city_ascii": "New Orleans",
            "lat": 30.0687,
            "lng": -89.9288,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Louisiana",
            "capital": "",
            "population": 1029123,
            "id": 1840001839
        },
        {
            "city": "Raleigh",
            "city_ascii": "Raleigh",
            "lat": 35.8324,
            "lng": -78.6438,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "North Carolina",
            "capital": "admin",
            "population": 1018336,
            "id": 1840014497
        },
        {
            "city": "Louisville",
            "city_ascii": "Louisville",
            "lat": 38.1663,
            "lng": -85.6485,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Kentucky",
            "capital": "",
            "population": 1011696,
            "id": 1840030815
        },
        {
            "city": "Oklahoma City",
            "city_ascii": "Oklahoma City",
            "lat": 35.4676,
            "lng": -97.5137,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Oklahoma",
            "capital": "admin",
            "population": 955998,
            "id": 1840020428
        },
        {
            "city": "Bridgeport",
            "city_ascii": "Bridgeport",
            "lat": 41.1918,
            "lng": -73.1953,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Connecticut",
            "capital": "",
            "population": 938406,
            "id": 1840004836
        },
        {
            "city": "Buffalo",
            "city_ascii": "Buffalo",
            "lat": 42.9017,
            "lng": -78.8487,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "New York",
            "capital": "",
            "population": 926261,
            "id": 1840000386
        },
        {
            "city": "Hartford",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Hartford_Skyline_from_Great_River_Park_%28Cropped%29.jpg",
            "city_ascii": "Hartford",
            "lat": 41.7661,
            "lng": -72.6834,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Connecticut",
            "capital": "admin",
            "population": 914751,
            "id": 1840004773
        },
        {
            "city": "Fort Worth",
            "city_ascii": "Fort Worth",
            "lat": 32.7812,
            "lng": -97.3472,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Texas",
            "capital": "",
            "population": 874168,
            "id": 1840020696
        },
        {
            "city": "Tucson",
            "city_ascii": "Tucson",
            "lat": 32.1545,
            "lng": -110.8782,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Arizona",
            "capital": "",
            "population": 868391,
            "id": 1840022101
        },
        {
            "city": "El Paso",
            "city_ascii": "El Paso",
            "lat": 31.8479,
            "lng": -106.4309,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Texas",
            "capital": "",
            "population": 845674,
            "id": 1840023252
        },
        {
            "city": "Omaha",
            "city_ascii": "Omaha",
            "lat": 41.2628,
            "lng": -96.0498,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Nebraska",
            "capital": "",
            "population": 827786,
            "id": 1840009315
        },
        {
            "city": "McAllen",
            "city_ascii": "McAllen",
            "lat": 26.2273,
            "lng": -98.2471,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Texas",
            "capital": "",
            "population": 800904,
            "id": 1840021024
        },
        {
            "city": "Albany",
            "city_ascii": "Albany",
            "lat": 42.6664,
            "lng": -73.7987,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "New York",
            "capital": "admin",
            "population": 597270,
            "id": 1840000417
        },
        {
            "city": "Baton Rouge",
            "city_ascii": "Baton Rouge",
            "lat": 30.4419,
            "lng": -91.131,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Louisiana",
            "capital": "admin",
            "population": 583613,
            "id": 1840013941
        },
        {
            "city": "Columbia",
            "city_ascii": "Columbia",
            "lat": 34.0376,
            "lng": -80.9037,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "South Carolina",
            "capital": "admin",
            "population": 566166,
            "id": 1840014730
        },
        {
            "city": "Des Moines",
            "city_ascii": "Des Moines",
            "lat": 41.5725,
            "lng": -93.6105,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Iowa",
            "capital": "admin",
            "population": 481222,
            "id": 1840007069
        },
        {
            "city": "Little Rock",
            "city_ascii": "Little Rock",
            "lat": 34.7255,
            "lng": -92.358,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Arkansas",
            "capital": "admin",
            "population": 442699,
            "id": 1840015509
        },
        {
            "city": "Harrisburg",
            "city_ascii": "Harrisburg",
            "lat": 40.2752,
            "lng": -76.8843,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Pennsylvania",
            "capital": "admin",
            "population": 441580,
            "id": 1840001288
        },
        {
            "city": "Madison",
            "city_ascii": "Madison",
            "lat": 43.0827,
            "lng": -89.3923,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Wisconsin",
            "capital": "admin",
            "population": 439553,
            "id": 1840002915
        },
        {
            "city": "Augusta",
            "city_ascii": "Augusta",
            "lat": 33.3645,
            "lng": -82.0708,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Georgia",
            "capital": "admin",
            "population": 389383,
            "id": 1840029462
        },
        {
            "city": "Boise",
            "city_ascii": "Boise",
            "lat": 43.6007,
            "lng": -116.2312,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Idaho",
            "capital": "admin",
            "population": 385218,
            "id": 1840027142
        },
        {
            "city": "Jackson",
            "city_ascii": "Jackson",
            "lat": 32.3163,
            "lng": -90.2124,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Mississippi",
            "capital": "admin",
            "population": 338185,
            "id": 1840014895
        },
        {
            "city": "Lansing",
            "city_ascii": "Lansing",
            "lat": 42.7142,
            "lng": -84.5601,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Michigan",
            "capital": "admin",
            "population": 320928,
            "id": 1840003102
        },
        {
            "city": "St. Paul",
            "city_ascii": "St. Paul",
            "lat": 44.9477,
            "lng": -93.104,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Minnesota",
            "capital": "admin",
            "population": 306621,
            "id": 1840008940
        },
        {
            "city": "Trenton",
            "city_ascii": "Trenton",
            "lat": 40.2236,
            "lng": -74.7641,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "New Jersey",
            "capital": "admin",
            "population": 296869,
            "id": 1840001383
        },
        {
            "city": "Lincoln",
            "city_ascii": "Lincoln",
            "lat": 40.8088,
            "lng": -96.6796,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Nebraska",
            "capital": "admin",
            "population": 285118,
            "id": 1840009357
        },
        {
            "city": "Salem",
            "city_ascii": "Salem",
            "lat": 44.9232,
            "lng": -123.0245,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Oregon",
            "capital": "admin",
            "population": 259816,
            "id": 1840021224
        },
        {
            "city": "Montgomery",
            "city_ascii": "Montgomery",
            "lat": 32.3473,
            "lng": -86.2666,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Alabama",
            "capital": "admin",
            "population": 255908,
            "id": 1840008353
        },
        {
            "city": "Tallahassee",
            "city_ascii": "Tallahassee",
            "lat": 30.4551,
            "lng": -84.2527,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Florida",
            "capital": "admin",
            "population": 253030,
            "id": 1840015913
        },
        {
            "city": "Olympia",
            "city_ascii": "Olympia",
            "lat": 47.0417,
            "lng": -122.8959,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Washington",
            "capital": "admin",
            "population": 196078,
            "id": 1840019865
        },
        {
            "city": "Springfield",
            "city_ascii": "Springfield",
            "lat": 39.771,
            "lng": -89.6537,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Illinois",
            "capital": "admin",
            "population": 159394,
            "id": 1840009517
        },
        {
            "city": "Topeka",
            "city_ascii": "Topeka",
            "lat": 39.0346,
            "lng": -95.6955,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Kansas",
            "capital": "admin",
            "population": 148960,
            "id": 1840001621
        },
        {
            "city": "Charleston",
            "city_ascii": "Charleston",
            "lat": 38.3484,
            "lng": -81.6323,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "West Virginia",
            "capital": "admin",
            "population": 142858,
            "id": 1840006196
        },
        {
            "city": "Santa Fe",
            "city_ascii": "Santa Fe",
            "lat": 35.6619,
            "lng": -105.9819,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "New Mexico",
            "capital": "admin",
            "population": 110078,
            "id": 1840021707
        },
        {
            "city": "Bismarck",
            "city_ascii": "Bismarck",
            "lat": 46.814,
            "lng": -100.7695,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "North Dakota",
            "capital": "admin",
            "population": 97457,
            "id": 1840001926
        },
        {
            "city": "Cheyenne",
            "city_ascii": "Cheyenne",
            "lat": 41.1405,
            "lng": -104.7927,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Wyoming",
            "capital": "admin",
            "population": 78728,
            "id": 1840018713
        },
        {
            "city": "Jefferson City",
            "city_ascii": "Jefferson City",
            "lat": 38.5676,
            "lng": -92.1759,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Missouri",
            "capital": "admin",
            "population": 58279,
            "id": 1840008615
        },
        {
            "city": "Carson City",
            "city_ascii": "Carson City",
            "lat": 39.1511,
            "lng": -119.7474,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Nevada",
            "capital": "admin",
            "population": 57525,
            "id": 1840003826
        },
        {
            "city": "Helena",
            "city_ascii": "Helena",
            "lat": 46.5965,
            "lng": -112.0199,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Montana",
            "capital": "admin",
            "population": 50227,
            "id": 1840019820
        },
        {
            "city": "Concord",
            "city_ascii": "Concord",
            "lat": 43.2305,
            "lng": -71.5595,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "New Hampshire",
            "capital": "admin",
            "population": 42935,
            "id": 1840002747
        },
        {
            "city": "Annapolis",
            "city_ascii": "Annapolis",
            "lat": 38.9706,
            "lng": -76.5047,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Maryland",
            "capital": "admin",
            "population": 39321,
            "id": 1840005928
        },
        {
            "city": "Frankfort",
            "city_ascii": "Frankfort",
            "lat": 38.1924,
            "lng": -84.8643,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Kentucky",
            "capital": "admin",
            "population": 38664,
            "id": 1840013210
        },
        {
            "city": "Pierre",
            "city_ascii": "Pierre",
            "lat": 44.3748,
            "lng": -100.3205,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "South Dakota",
            "capital": "admin",
            "population": 14803,
            "id": 1840000313
        },
        {
            "city": "Montpelier",
            "city_ascii": "Montpelier",
            "lat": 44.2658,
            "lng": -72.5717,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Vermont",
            "capital": "admin",
            "population": 7484,
            "id": 1840002187
        },
        {
            "city": "Dover",
            "city_ascii": "Dover",
            "lat": 40.0033,
            "lng": -76.8484,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Pennsylvania",
            "capital": "admin",
            "population": 1991,
            "id": 1840001442
        }
    ]
}