module.exports = {
    CITIES: [{
            "city": "Algiers",
            "city_ascii": "Algiers",
            "lat": 36.7631,
            "lng": 3.0506,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Alger",
            "capital": "primary",
            "population": 3354000,
            "id": 1012973369
        },
        {
            "city": "Oran",
            "city_ascii": "Oran",
            "lat": 35.71,
            "lng": -0.62,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Oran",
            "capital": "admin",
            "population": 798000,
            "id": 1012126319
        },
        {
            "city": "Constantine",
            "city_ascii": "Constantine",
            "lat": 36.36,
            "lng": 6.5999,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Constantine",
            "capital": "admin",
            "population": 605179,
            "id": 1012275076
        },
        {
            "city": "Blida",
            "city_ascii": "Blida",
            "lat": 36.4203,
            "lng": 2.83,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Blida",
            "capital": "admin",
            "population": 511348,
            "id": 1012045589
        },
        {
            "city": "Annaba",
            "city_ascii": "Annaba",
            "lat": 36.92,
            "lng": 7.76,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Annaba",
            "capital": "admin",
            "population": 503524,
            "id": 1012600001
        },
        {
            "city": "Chlef",
            "city_ascii": "Chlef",
            "lat": 36.1704,
            "lng": 1.32,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Chlef",
            "capital": "admin",
            "population": 449167,
            "id": 1012772239
        },
        {
            "city": "Beja\u00efa",
            "city_ascii": "Bejaia",
            "lat": 36.7604,
            "lng": 5.07,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Beja\u00efa",
            "capital": "admin",
            "population": 384937,
            "id": 1012140298
        },
        {
            "city": "Batna",
            "city_ascii": "Batna",
            "lat": 35.57,
            "lng": 6.17,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Batna",
            "capital": "admin",
            "population": 280798,
            "id": 1012093229
        },
        {
            "city": "S\u00e9tif",
            "city_ascii": "Setif",
            "lat": 36.18,
            "lng": 5.4,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "S\u00e9tif",
            "capital": "admin",
            "population": 274744,
            "id": 1012981116
        },
        {
            "city": "Tlemcen",
            "city_ascii": "Tlemcen",
            "lat": 34.8904,
            "lng": -1.32,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Tlemcen",
            "capital": "admin",
            "population": 229777,
            "id": 1012978325
        },
        {
            "city": "Skikda",
            "city_ascii": "Skikda",
            "lat": 36.8804,
            "lng": 6.9,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Skikda",
            "capital": "admin",
            "population": 225181,
            "id": 1012619903
        },
        {
            "city": "Sidi Bel Abb\u00e8s",
            "city_ascii": "Sidi Bel Abbes",
            "lat": 35.1903,
            "lng": -0.64,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Sidi Bel Abb\u00e8s",
            "capital": "admin",
            "population": 208604,
            "id": 1012123414
        },
        {
            "city": "Biskra",
            "city_ascii": "Biskra",
            "lat": 34.86,
            "lng": 5.73,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Biskra",
            "capital": "admin",
            "population": 202103,
            "id": 1012947247
        },
        {
            "city": "Mostaganem",
            "city_ascii": "Mostaganem",
            "lat": 35.9404,
            "lng": 0.09,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Mostaganem",
            "capital": "admin",
            "population": 188354,
            "id": 1012061703
        },
        {
            "city": "Tiaret",
            "city_ascii": "Tiaret",
            "lat": 35.3804,
            "lng": 1.32,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Tiaret",
            "capital": "admin",
            "population": 184195,
            "id": 1012785868
        },
        {
            "city": "El Oued",
            "city_ascii": "El Oued",
            "lat": 33.3704,
            "lng": 6.86,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "El Oued",
            "capital": "admin",
            "population": 177497,
            "id": 1012148937
        },
        {
            "city": "Ouargla",
            "city_ascii": "Ouargla",
            "lat": 31.97,
            "lng": 5.34,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Ouargla",
            "capital": "admin",
            "population": 176271,
            "id": 1012425687
        },
        {
            "city": "T\u00e9bessa",
            "city_ascii": "Tebessa",
            "lat": 35.4104,
            "lng": 8.12,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "T\u00e9bessa",
            "capital": "admin",
            "population": 171742,
            "id": 1012196375
        },
        {
            "city": "Djelfa",
            "city_ascii": "Djelfa",
            "lat": 34.68,
            "lng": 3.25,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Djelfa",
            "capital": "admin",
            "population": 170901,
            "id": 1012268984
        },
        {
            "city": "M\u2019Sila",
            "city_ascii": "M'Sila",
            "lat": 35.7,
            "lng": 4.545,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "M\u2019sila",
            "capital": "admin",
            "population": 150000,
            "id": 1012857730
        },
        {
            "city": "Jijel",
            "city_ascii": "Jijel",
            "lat": 36.822,
            "lng": 5.766,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Jijel",
            "capital": "admin",
            "population": 148000,
            "id": 1012782547
        },
        {
            "city": "M\u00e9d\u00e9a",
            "city_ascii": "Medea",
            "lat": 36.2704,
            "lng": 2.77,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "M\u00e9d\u00e9a",
            "capital": "admin",
            "population": 147707,
            "id": 1012758282
        },
        {
            "city": "Tizi Ouzou",
            "city_ascii": "Tizi Ouzou",
            "lat": 36.8,
            "lng": 4.0333,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Tizi Ouzou",
            "capital": "admin",
            "population": 144000,
            "id": 1012126997
        },
        {
            "city": "B\u00e9char",
            "city_ascii": "Bechar",
            "lat": 31.6111,
            "lng": -2.23,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "B\u00e9char",
            "capital": "admin",
            "population": 143382,
            "id": 1012371820
        },
        {
            "city": "Sa\u00efda",
            "city_ascii": "Saida",
            "lat": 34.8404,
            "lng": 0.14,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Sa\u00efda",
            "capital": "admin",
            "population": 142213,
            "id": 1012285874
        },
        {
            "city": "Bordj Bou Arreridj",
            "city_ascii": "Bordj Bou Arreridj",
            "lat": 36.059,
            "lng": 4.63,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Bordj Bou Arr\u00e9ridj",
            "capital": "admin",
            "population": 140000,
            "id": 1012016677
        },
        {
            "city": "Souk Ahras",
            "city_ascii": "Souk Ahras",
            "lat": 36.2904,
            "lng": 7.95,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Souk Ahras",
            "capital": "admin",
            "population": 134947,
            "id": 1012419619
        },
        {
            "city": "Touggourt",
            "city_ascii": "Touggourt",
            "lat": 33.1,
            "lng": 6.06,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Ouargla",
            "capital": "",
            "population": 133954,
            "id": 1012546670
        },
        {
            "city": "Gharda\u00efa",
            "city_ascii": "Ghardaia",
            "lat": 32.49,
            "lng": 3.67,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Gharda\u00efa",
            "capital": "admin",
            "population": 125480,
            "id": 1012074690
        },
        {
            "city": "Guelma",
            "city_ascii": "Guelma",
            "lat": 36.466,
            "lng": 7.428,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Guelma",
            "capital": "admin",
            "population": 123590,
            "id": 1012266321
        },
        {
            "city": "Laghouat",
            "city_ascii": "Laghouat",
            "lat": 33.81,
            "lng": 2.88,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Laghouat",
            "capital": "admin",
            "population": 113872,
            "id": 1012233848
        },
        {
            "city": "Bouira",
            "city_ascii": "Bouira",
            "lat": 36.3805,
            "lng": 3.9,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Bouira",
            "capital": "admin",
            "population": 110144,
            "id": 1012006499
        },
        {
            "city": "Mascara",
            "city_ascii": "Mascara",
            "lat": 35.4004,
            "lng": 0.14,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Mascara",
            "capital": "admin",
            "population": 108230,
            "id": 1012738269
        },
        {
            "city": "Oum el Bouaghi",
            "city_ascii": "Oum el Bouaghi",
            "lat": 35.85,
            "lng": 7.15,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Oum el Bouaghi",
            "capital": "admin",
            "population": 100821,
            "id": 1012958880
        },
        {
            "city": "Tamanrasset",
            "city_ascii": "Tamanrasset",
            "lat": 22.785,
            "lng": 5.5228,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Tamanrasset",
            "capital": "admin",
            "population": 76000,
            "id": 1012765474
        },
        {
            "city": "El Bayadh",
            "city_ascii": "El Bayadh",
            "lat": 33.6904,
            "lng": 1.01,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "El Bayadh",
            "capital": "admin",
            "population": 67413,
            "id": 1012906892
        },
        {
            "city": "Adrar",
            "city_ascii": "Adrar",
            "lat": 27.87,
            "lng": -0.29,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Adrar",
            "capital": "admin",
            "population": 56910,
            "id": 1012462113
        },
        {
            "city": "Tindouf",
            "city_ascii": "Tindouf",
            "lat": 27.6742,
            "lng": -8.1478,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Tindouf",
            "capital": "admin",
            "population": 18270,
            "id": 1012450434
        },
        {
            "city": "Illizi",
            "city_ascii": "Illizi",
            "lat": 26.4834,
            "lng": 8.4666,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Illizi",
            "capital": "admin",
            "population": 7957,
            "id": 1012499058
        },
        {
            "city": "Khenchela",
            "city_ascii": "Khenchela",
            "lat": 35.4358,
            "lng": 7.1433,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Khenchela",
            "capital": "admin",
            "population": "",
            "id": 1012495148
        },
        {
            "city": "Boumerdes",
            "city_ascii": "Boumerdes",
            "lat": 36.759,
            "lng": 3.4748,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Boumerdes",
            "capital": "admin",
            "population": "",
            "id": 1012627486
        },
        {
            "city": "Relizane",
            "city_ascii": "Relizane",
            "lat": 35.7373,
            "lng": 0.556,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Relizane",
            "capital": "admin",
            "population": "",
            "id": 1012939885
        },
        {
            "city": "A\u00efn Temouchent",
            "city_ascii": "Ain Temouchent",
            "lat": 35.2975,
            "lng": -1.1404,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "A\u00efn Temouchent",
            "capital": "admin",
            "population": "",
            "id": 1012763655
        },
        {
            "city": "A\u00efn Defla",
            "city_ascii": "Ain Defla",
            "lat": 36.2641,
            "lng": 1.9679,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "A\u00efn Defla",
            "capital": "admin",
            "population": "",
            "id": 1012656497
        },
        {
            "city": "Mila",
            "city_ascii": "Mila",
            "lat": 36.4503,
            "lng": 6.2644,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Mila",
            "capital": "admin",
            "population": "",
            "id": 1012656063
        },
        {
            "city": "Tipasa",
            "city_ascii": "Tipasa",
            "lat": 36.5897,
            "lng": 2.4475,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Tipaza",
            "capital": "admin",
            "population": "",
            "id": 1012866308
        },
        {
            "city": "Tissemsilt",
            "city_ascii": "Tissemsilt",
            "lat": 35.6072,
            "lng": 1.8108,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Tissemsilt",
            "capital": "admin",
            "population": "",
            "id": 1012743339
        },
        {
            "city": "El Tarf",
            "city_ascii": "El Tarf",
            "lat": 36.7672,
            "lng": 8.3138,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "El Tarf",
            "capital": "admin",
            "population": "",
            "id": 1012205687
        },
        {
            "city": "Naama",
            "city_ascii": "Naama",
            "lat": 33.2667,
            "lng": -0.3167,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Naama",
            "capital": "admin",
            "population": "",
            "id": 1012850542
        },
        {
            "city": "A\u00efn Sefra",
            "city_ascii": "Ain Sefra",
            "lat": 32.7604,
            "lng": -0.5799,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Naama",
            "capital": "",
            "population": 63420,
            "id": 1012884513
        },
        {
            "city": "Timimoun",
            "city_ascii": "Timimoun",
            "lat": 29.2365,
            "lng": 0.27,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Adrar",
            "capital": "",
            "population": 49237,
            "id": 1012351010
        },
        {
            "city": "I-n-Salah",
            "city_ascii": "I-n-Salah",
            "lat": 27.2166,
            "lng": 2.4666,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Tamanrasset",
            "capital": "",
            "population": 49223,
            "id": 1012201146
        },
        {
            "city": "Reggane",
            "city_ascii": "Reggane",
            "lat": 26.7,
            "lng": 0.1666,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Adrar",
            "capital": "",
            "population": 32974,
            "id": 1012709576
        },
        {
            "city": "El Golea",
            "city_ascii": "El Golea",
            "lat": 30.5666,
            "lng": 2.8833,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Gharda\u00efa",
            "capital": "",
            "population": 32049,
            "id": 1012834851
        },
        {
            "city": "Hassi Messaoud",
            "city_ascii": "Hassi Messaoud",
            "lat": 31.7023,
            "lng": 6.0545,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Ouargla",
            "capital": "",
            "population": 18124,
            "id": 1012339655
        },
        {
            "city": "Abadla",
            "city_ascii": "Abadla",
            "lat": 31.0171,
            "lng": -2.7333,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "B\u00e9char",
            "capital": "",
            "population": 14364,
            "id": 1012262770
        },
        {
            "city": "Beni Ounif",
            "city_ascii": "Beni Ounif",
            "lat": 32.0493,
            "lng": -1.2514,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "B\u00e9char",
            "capital": "",
            "population": 5628,
            "id": 1012327989
        },
        {
            "city": "I-n-Amguel",
            "city_ascii": "I-n-Amguel",
            "lat": 23.6939,
            "lng": 5.1647,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Tamanrasset",
            "capital": "",
            "population": 3030,
            "id": 1012162135
        },
        {
            "city": "Djanet",
            "city_ascii": "Djanet",
            "lat": 24.5529,
            "lng": 9.4823,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Illizi",
            "capital": "",
            "population": 666,
            "id": 1012827195
        },
        {
            "city": "I-n-Amenas",
            "city_ascii": "I-n-Amenas",
            "lat": 28.0503,
            "lng": 9.55,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Illizi",
            "capital": "",
            "population": 216,
            "id": 1012221429
        }
    ]
}