module.exports = {
    CITIES: [{
            "city": "Milan",
            "city_ascii": "Milan",
            "lat": 45.47,
            "lng": 9.205,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Lombardy",
            "capital": "admin",
            "population": 2945000,
            "id": 1380724377
        },
        {
            "city": "Stuttgart",
            "city_ascii": "Stuttgart",
            "lat": 48.78,
            "lng": 9.2,
            "country": "Germany",
            "iso2": "DE",
            "iso3": "DEU",
            "admin_name": "Baden-W\u00fcrttemberg",
            "capital": "admin",
            "population": 2944700,
            "id": 1276171358
        },
        {
            "city": "Vienna",
            "city_ascii": "Vienna",
            "lat": 48.2,
            "lng": 16.3666,
            "country": "Austria",
            "iso2": "AT",
            "iso3": "AUT",
            "admin_name": "Wien",
            "capital": "primary",
            "population": 2400000,
            "id": 1040261752
        },
        {
            "city": "Turin",
            "city_ascii": "Turin",
            "lat": 45.0704,
            "lng": 7.67,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Piedmont",
            "capital": "admin",
            "population": 1652000,
            "id": 1380244627
        },
        {
            "city": "Florence",
            "city_ascii": "Florence",
            "lat": 43.78,
            "lng": 11.25,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Tuscany",
            "capital": "admin",
            "population": 1500000,
            "id": 1380726561
        },
        {
            "city": "Lyon",
            "city_ascii": "Lyon",
            "lat": 45.77,
            "lng": 4.83,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Auvergne-Rh\u00f4ne-Alpes",
            "capital": "admin",
            "population": 1423000,
            "id": 1250196189
        },
        {
            "city": "Marseille",
            "city_ascii": "Marseille",
            "lat": 43.29,
            "lng": 5.375,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Provence-Alpes-C\u00f4te d\u2019Azur",
            "capital": "admin",
            "population": 1400000,
            "id": 1250774071
        },
        {
            "city": "Munich",
            "city_ascii": "Munich",
            "lat": 48.1299,
            "lng": 11.575,
            "country": "Germany",
            "iso2": "DE",
            "iso3": "DEU",
            "admin_name": "Bavaria",
            "capital": "admin",
            "population": 1275000,
            "id": 1276692352
        },
        {
            "city": "Geneva",
            "city_ascii": "Geneva",
            "lat": 46.21,
            "lng": 6.14,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Gen\u00e8ve",
            "capital": "admin",
            "population": 1240000,
            "id": 1756810813
        },
        {
            "city": "Z\u00fcrich",
            "city_ascii": "Zurich",
            "lat": 47.38,
            "lng": 8.55,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Z\u00fcrich",
            "capital": "admin",
            "population": 1108000,
            "id": 1756539143
        },
        {
            "city": "Ljubljana",
            "city_ascii": "Ljubljana",
            "lat": 46.0553,
            "lng": 14.515,
            "country": "Slovenia",
            "iso2": "SI",
            "iso3": "SVN",
            "admin_name": "Ljubljana",
            "capital": "primary",
            "population": 314807,
            "id": 1705917455
        },
        {
            "city": "Bern",
            "city_ascii": "Bern",
            "lat": 46.9167,
            "lng": 7.467,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Bern",
            "capital": "primary",
            "population": 275329,
            "id": 1756374318
        },
        {
            "city": "Monaco",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Panorama_von_Monaco-La_Turbie.jpg/1920px-Panorama_von_Monaco-La_Turbie.jpg",
            "city_ascii": "Monaco",
            "lat": 43.7396,
            "lng": 7.4069,
            "country": "Monaco",
            "iso2": "MC",
            "iso3": "MCO",
            "admin_name": "",
            "capital": "primary",
            "population": 36371,
            "id": 1492854256
        },
        {
            "city": "Vaduz",
            "city_ascii": "Vaduz",
            "lat": 47.1337,
            "lng": 9.5167,
            "country": "Liechtenstein",
            "iso2": "LI",
            "iso3": "LIE",
            "admin_name": "Vaduz",
            "capital": "primary",
            "population": 36281,
            "id": 1438317747
        },
        {
            "city": "Nice",
            "city_ascii": "Nice",
            "lat": 43.715,
            "lng": 7.265,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Provence-Alpes-C\u00f4te d\u2019Azur",
            "capital": "minor",
            "population": 927000,
            "id": 1250774553
        },
        {
            "city": "Basel",
            "city_ascii": "Basel",
            "lat": 47.5804,
            "lng": 7.59,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Basel-Stadt",
            "capital": "admin",
            "population": 830000,
            "id": 1756731313
        },
        {
            "city": "Genoa",
            "city_ascii": "Genoa",
            "lat": 44.41,
            "lng": 8.93,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Liguria",
            "capital": "admin",
            "population": 647497,
            "id": 1380716540
        },
        {
            "city": "Bologna",
            "city_ascii": "Bologna",
            "lat": 44.5004,
            "lng": 11.34,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Emilia-Romagna",
            "capital": "admin",
            "population": 488172,
            "id": 1380202039
        },
        {
            "city": "Strasbourg",
            "city_ascii": "Strasbourg",
            "lat": 48.58,
            "lng": 7.75,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Grand Est",
            "capital": "admin",
            "population": 439972,
            "id": 1250789140
        },
        {
            "city": "Grenoble",
            "city_ascii": "Grenoble",
            "lat": 45.1804,
            "lng": 5.72,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Auvergne-Rh\u00f4ne-Alpes",
            "capital": "minor",
            "population": 388574,
            "id": 1250071647
        },
        {
            "city": "Augsburg",
            "city_ascii": "Augsburg",
            "lat": 48.35,
            "lng": 10.9,
            "country": "Germany",
            "iso2": "DE",
            "iso3": "DEU",
            "admin_name": "Bavaria",
            "capital": "minor",
            "population": 358989,
            "id": 1276314100
        },
        {
            "city": "Toulon",
            "city_ascii": "Toulon",
            "lat": 43.1342,
            "lng": 5.9188,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Provence-Alpes-C\u00f4te d\u2019Azur",
            "capital": "minor",
            "population": 357693,
            "id": 1250541629
        },
        {
            "city": "Linz",
            "city_ascii": "Linz",
            "lat": 48.3192,
            "lng": 14.2888,
            "country": "Austria",
            "iso2": "AT",
            "iso3": "AUT",
            "admin_name": "Ober\u00f6sterreich",
            "capital": "admin",
            "population": 349161,
            "id": 1040261171
        },
        {
            "city": "Verona",
            "city_ascii": "Verona",
            "lat": 45.4404,
            "lng": 10.99,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Veneto",
            "capital": "minor",
            "population": 347459,
            "id": 1380324879
        },
        {
            "city": "Montpellier",
            "city_ascii": "Montpellier",
            "lat": 43.6104,
            "lng": 3.87,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Occitanie",
            "capital": "minor",
            "population": 327254,
            "id": 1250819356
        },
        {
            "city": "Venice",
            "city_ascii": "Venice",
            "lat": 45.4387,
            "lng": 12.335,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Veneto",
            "capital": "admin",
            "population": 270816,
            "id": 1380660414
        },
        {
            "city": "Nancy",
            "city_ascii": "Nancy",
            "lat": 48.6837,
            "lng": 6.2,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Grand Est",
            "capital": "minor",
            "population": 268976,
            "id": 1250925250
        },
        {
            "city": "Lausanne",
            "city_ascii": "Lausanne",
            "lat": 46.5304,
            "lng": 6.65,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Vaud",
            "capital": "admin",
            "population": 265702,
            "id": 1756055099
        },
        {
            "city": "Saint-\u00c9tienne",
            "city_ascii": "Saint-Etienne",
            "lat": 45.4304,
            "lng": 4.38,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Auvergne-Rh\u00f4ne-Alpes",
            "capital": "minor",
            "population": 265684,
            "id": 1250000540
        },
        {
            "city": "Graz",
            "city_ascii": "Graz",
            "lat": 47.0778,
            "lng": 15.41,
            "country": "Austria",
            "iso2": "AT",
            "iso3": "AUT",
            "admin_name": "Steiermark",
            "capital": "admin",
            "population": 263234,
            "id": 1040184559
        },
        {
            "city": "Freiburg im Breisgau",
            "city_ascii": "Freiburg im Breisgau",
            "lat": 48.0004,
            "lng": 7.8699,
            "country": "Germany",
            "iso2": "DE",
            "iso3": "DEU",
            "admin_name": "Baden-W\u00fcrttemberg",
            "capital": "minor",
            "population": 254889,
            "id": 1276371228
        },
        {
            "city": "Como",
            "city_ascii": "Como",
            "lat": 45.81,
            "lng": 9.08,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Lombardy",
            "capital": "minor",
            "population": 250000,
            "id": 1380994905
        },
        {
            "city": "Lucerne",
            "city_ascii": "Lucerne",
            "lat": 47.0504,
            "lng": 8.28,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Luzern",
            "capital": "admin",
            "population": 250000,
            "id": 1756544536
        },
        {
            "city": "Trieste",
            "city_ascii": "Trieste",
            "lat": 45.6504,
            "lng": 13.8,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Friuli-Venezia Giulia",
            "capital": "admin",
            "population": 216035,
            "id": 1380102581
        },
        {
            "city": "Mulhouse",
            "city_ascii": "Mulhouse",
            "lat": 47.7504,
            "lng": 7.35,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Grand Est",
            "capital": "minor",
            "population": 215454,
            "id": 1250218452
        },
        {
            "city": "Salzburg",
            "city_ascii": "Salzburg",
            "lat": 47.8105,
            "lng": 13.04,
            "country": "Austria",
            "iso2": "AT",
            "iso3": "AUT",
            "admin_name": "Salzburg",
            "capital": "admin",
            "population": 206279,
            "id": 1040312147
        },
        {
            "city": "Pisa",
            "city_ascii": "Pisa",
            "lat": 43.7205,
            "lng": 10.4,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Tuscany",
            "capital": "minor",
            "population": 203336,
            "id": 1380310225
        },
        {
            "city": "Bergamo",
            "city_ascii": "Bergamo",
            "lat": 45.7004,
            "lng": 9.67,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Lombardy",
            "capital": "minor",
            "population": 200000,
            "id": 1380253521
        },
        {
            "city": "Treviso",
            "city_ascii": "Treviso",
            "lat": 45.67,
            "lng": 12.24,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Veneto",
            "capital": "minor",
            "population": 177309,
            "id": 1380900516
        },
        {
            "city": "Modena",
            "city_ascii": "Modena",
            "lat": 44.65,
            "lng": 10.92,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Emilia-Romagna",
            "capital": "minor",
            "population": 175502,
            "id": 1380306270
        },
        {
            "city": "Ulm",
            "city_ascii": "Ulm",
            "lat": 48.4004,
            "lng": 10,
            "country": "Germany",
            "iso2": "DE",
            "iso3": "DEU",
            "admin_name": "Baden-W\u00fcrttemberg",
            "capital": "minor",
            "population": 172955,
            "id": 1276002212
        },
        {
            "city": "Dijon",
            "city_ascii": "Dijon",
            "lat": 47.3304,
            "lng": 5.03,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Bourgogne-Franche-Comt\u00e9",
            "capital": "admin",
            "population": 169946,
            "id": 1250505606
        },
        {
            "city": "N\u00eemes",
            "city_ascii": "Nimes",
            "lat": 43.8304,
            "lng": 4.35,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Occitanie",
            "capital": "minor",
            "population": 169547,
            "id": 1250417467
        },
        {
            "city": "Parma",
            "city_ascii": "Parma",
            "lat": 44.8104,
            "lng": 10.32,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Emilia-Romagna",
            "capital": "minor",
            "population": 166011,
            "id": 1380655938
        },
        {
            "city": "Ingolstadt",
            "city_ascii": "Ingolstadt",
            "lat": 48.7704,
            "lng": 11.45,
            "country": "Germany",
            "iso2": "DE",
            "iso3": "DEU",
            "admin_name": "Bavaria",
            "capital": "minor",
            "population": 163325,
            "id": 1276803150
        },
        {
            "city": "Livorno",
            "city_ascii": "Livorno",
            "lat": 43.5511,
            "lng": 10.3023,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Tuscany",
            "capital": "minor",
            "population": 156274,
            "id": 1380159305
        },
        {
            "city": "Innsbruck",
            "city_ascii": "Innsbruck",
            "lat": 47.2804,
            "lng": 11.41,
            "country": "Austria",
            "iso2": "AT",
            "iso3": "AUT",
            "admin_name": "Tirol",
            "capital": "admin",
            "population": 155214,
            "id": 1040038924
        },
        {
            "city": "Perugia",
            "city_ascii": "Perugia",
            "lat": 43.1104,
            "lng": 12.39,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Umbria",
            "capital": "admin",
            "population": 149125,
            "id": 1380939013
        },
        {
            "city": "Aix-en-Provence",
            "city_ascii": "Aix-en-Provence",
            "lat": 43.52,
            "lng": 5.45,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Provence-Alpes-C\u00f4te d\u2019Azur",
            "capital": "minor",
            "population": 146821,
            "id": 1250001687
        },
        {
            "city": "Ravenna",
            "city_ascii": "Ravenna",
            "lat": 44.4204,
            "lng": 12.22,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Emilia-Romagna",
            "capital": "minor",
            "population": 134631,
            "id": 1380964180
        },
        {
            "city": "Ferrara",
            "city_ascii": "Ferrara",
            "lat": 44.8504,
            "lng": 11.6099,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Emilia-Romagna",
            "capital": "minor",
            "population": 130992,
            "id": 1380682411
        },
        {
            "city": "Besan\u00e7on",
            "city_ascii": "Besancon",
            "lat": 47.23,
            "lng": 6.03,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Bourgogne-Franche-Comt\u00e9",
            "capital": "minor",
            "population": 128426,
            "id": 1250182013
        },
        {
            "city": "Udine",
            "city_ascii": "Udine",
            "lat": 46.07,
            "lng": 13.24,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Friuli-Venezia Giulia",
            "capital": "minor",
            "population": 119009,
            "id": 1380396446
        },
        {
            "city": "Maribor",
            "city_ascii": "Maribor",
            "lat": 46.5405,
            "lng": 15.65,
            "country": "Slovenia",
            "iso2": "SI",
            "iso3": "SVN",
            "admin_name": "Maribor",
            "capital": "admin",
            "population": 114228,
            "id": 1705454394
        },
        {
            "city": "Trento",
            "city_ascii": "Trento",
            "lat": 46.0804,
            "lng": 11.12,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Trentino-Alto Adige",
            "capital": "admin",
            "population": 107808,
            "id": 1380953307
        },
        {
            "city": "Annecy",
            "city_ascii": "Annecy",
            "lat": 45.9,
            "lng": 6.1167,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Auvergne-Rh\u00f4ne-Alpes",
            "capital": "minor",
            "population": 105749,
            "id": 1250551848
        },
        {
            "city": "Lugano",
            "city_ascii": "Lugano",
            "lat": 46.0004,
            "lng": 8.9667,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Ticino",
            "capital": "",
            "population": 105388,
            "id": 1756503816
        },
        {
            "city": "Novara",
            "city_ascii": "Novara",
            "lat": 45.45,
            "lng": 8.62,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Piedmont",
            "capital": "minor",
            "population": 100910,
            "id": 1380911437
        },
        {
            "city": "Ancona",
            "city_ascii": "Ancona",
            "lat": 43.6004,
            "lng": 13.4999,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Marche",
            "capital": "admin",
            "population": 100507,
            "id": 1380597324
        },
        {
            "city": "Klagenfurt",
            "city_ascii": "Klagenfurt",
            "lat": 46.6203,
            "lng": 14.31,
            "country": "Austria",
            "iso2": "AT",
            "iso3": "AUT",
            "admin_name": "K\u00e4rnten",
            "capital": "admin",
            "population": 90610,
            "id": 1040149651
        },
        {
            "city": "Bolzano",
            "city_ascii": "Bolzano",
            "lat": 46.5004,
            "lng": 11.36,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Trentino-Alto Adige",
            "capital": "minor",
            "population": 95895,
            "id": 1380677819
        },
        {
            "city": "Rosenheim",
            "city_ascii": "Rosenheim",
            "lat": 47.8503,
            "lng": 12.1333,
            "country": "Germany",
            "iso2": "DE",
            "iso3": "DEU",
            "admin_name": "Bavaria",
            "capital": "minor",
            "population": 92809,
            "id": 1276301675
        },
        {
            "city": "Arezzo",
            "city_ascii": "Arezzo",
            "lat": 43.4617,
            "lng": 11.875,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Tuscany",
            "capital": "minor",
            "population": 91589,
            "id": 1380418355
        },
        {
            "city": "Wiener Neustadt",
            "city_ascii": "Wiener Neustadt",
            "lat": 47.816,
            "lng": 16.25,
            "country": "Austria",
            "iso2": "AT",
            "iso3": "AUT",
            "admin_name": "Nieder\u00f6sterreich",
            "capital": "minor",
            "population": 82762,
            "id": 1040389518
        }
    ]
}