module.exports = {
    CITIES: [{
            "city": "Lenin's Bust At Pole of Inaccessibility",
            "city_ascii": "",
            "lat": -82.1,
            "lng": 54.966667,
            "iso2": "SU",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/d/d6/Southern_Pol_of_Inaccessibility_Henry_Cookson_team_n2i.JPG",
            "wiki": "https://en.wikipedia.org/wiki/Pole_of_Inaccessibility_research_station"
        },
        {
            "city": "South Pole Flag Mast at Geographic South Pole",
            "city_ascii": "",
            "lat": -90,
            "lng": 0,
            "country": "Antarctica",
            "iso2": "AQ",
            "population": 0,
            "capital": "",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Geographic_Southpole_crop.jpg"
        },
        {
            "city": "Magnetic South Pole (as of 2020)",
            "city_ascii": "",
            "lat": -64.081,
            "lng": 135.866,
            "iso2": "AQ",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/South_magnetic_pole"
        },
        {
            "city": "Geomagnetic South Pole (as of 2020)",
            "city_ascii": "",
            "lat": -80.7,
            "lng": 107.3,
            "iso2": "AQ",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Geomagnetic_pole"
        },
        {
            "city": "Vostok Station",
            "city_ascii": "",
            "lat": -78.463889,
            "lng": 106.83757,
            "iso2": "RU",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Vostok_Station"
        },
        {
            "city": "Mount William",
            "city_ascii": "",
            "lat": -64.783333,
            "lng": -63.683333,
            "iso2": "AQ",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Mount_William_(Antarctica)"
        },
        {
            "city": "Cape Denison ('Windiest Place on Earth')",
            "city_ascii": "",
            "lat": -67,
            "lng": 142.666667,
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Blizzard_at_Cape_Denison_~_Cape_Denison%2C_Antarctica%2C_c._1912._Frank_Hurley._carbon_print_%286433918107%29.jpg",
            "iso2": "AU",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Cape_Denison"
        },
        {
            "city": "Port Lockroy 'Penguin Post Office' (Most Southerly Post Office)",
            "city_ascii": "",
            "lat": -64.825278,
            "lng": -63.494444,
            "iso2": "AQ",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Port_Lockroy"
        },
        {
            "city": "Fukushima's Rock Cairn At Showa Station",
            "city_ascii": "",
            "lat": -69,
            "lng": 39.5833,
            "iso2": "JP",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/9/9c/Fukushima%27s_Rock_Cairn.jpg",
            "wiki": "https://en.wikipedia.org/wiki/Showa_Station_(Antarctica)"
        },
        {
            "city": "Mawson's Rock Cairn At Proclamation Island",
            "city_ascii": "",
            "lat": -65.85,
            "lng": 53.6833,
            "iso2": "AQ",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/0/08/Proclamation_Island_1930.jpg",
            "wiki": "https://en.wikipedia.org/wiki/Proclamation_Island"
        },
        {
            "city": "Khmara's Stone at Mabus Point",
            "city_ascii": "",
            "lat": -66.53,
            "lng": 93,
            "iso2": "SU",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/7/72/Ivan_Khmara%27s_Stone.jpg",
            "wiki": "https://en.wikipedia.org/wiki/Mabus_Point"
        },
        {
            "city": "Soviet Expedition Cemetery at Buromskiy Island",
            "city_ascii": "",
            "lat": -66.533333,
            "lng": 93,
            "iso2": "SU",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/7/7e/Soviet_Expedition_Cemetery.jpg",
            "wiki": "https://en.wikipedia.org/wiki/Buromskiy_Island"
        },
        {
            "city": "Shackleton's Hut at Cape Royds, Ross Island",
            "city_ascii": "",
            "lat": -77.552929,
            "lng": 166.168286,
            "iso2": "UK",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/2/24/CapeRoyds.jpg",
            "wiki": "https://en.wikipedia.org/wiki/Cape_Royds"
        },
        {
            "city": "McMurdo Station ('Largest Community in Antarctica')",
            "city_ascii": "",
            "lat": -77.85,
            "lng": 166.69,
            "iso2": "US",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/b/b0/Cross_on_Observation_Hill%2C_McMurdo_Station.jpg",
            "wiki": "https://en.wikipedia.org/wiki/Observation_Hill_(McMurdo_Station)"
        },
        {
            "city": "San Martin Base",
            "city_ascii": "",
            "lat": -68.130043,
            "lng": -67.101311,
            "iso2": "AR",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/San_Mart%C3%ADn_Base"
        },
        {
            "city": "Arturo Prat's Bust at Greenwich Island",
            "city_ascii": "",
            "lat": -62.48,
            "lng": -59.66,
            "iso2": "CL",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/7/7d/Base_Arturo_Prat.JPG",
            "wiki": "https://en.wikipedia.org/wiki/Greenwich_Island"
        },
        {
            "city": "Otto Nordenskjöld's Hut at Snow Hill Island",
            "city_ascii": "",
            "lat": -64.3667,
            "lng": -56.9833,
            "iso2": "SE",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/6/67/Otto_nor_plano_233.jpg",
            "wiki": "https://en.wikipedia.org/wiki/Otto_Nordenskj%C3%B6ld"
        },
        {
            "city": "Polish Eagle Plaque",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/a/ad/Polish_Eagle_Plaque.jpg",
            "city_ascii": "",
            "lat": -62.2,
            "lng": -59.0167,
            "iso2": "PL",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Polish_Antarctic_Expedition"
        },
        {
            "city": "East Base at Stonington Island ('Oldest American Research Station in Antarctica')",
            "city_ascii": "",
            "lat": -68.183841,
            "lng": -66.998158,
            "iso2": "US",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/b/be/East_Base_-_Stonington_Island.jpg",
            "wiki": "https://en.wikipedia.org/wiki/East_Base"
        },
        {
            "city": "Whaler's Bay (South Shetland Islands)",
            "city_ascii": "",
            "lat": -62.983333,
            "lng": -60.566667,
            "iso2": "FR",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Hut A of Scott Base at Pram Point, Ross Island",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Hut_A%2C_Scott_Base.jpg",
            "city_ascii": "",
            "lat": -77.85,
            "lng": 166.7667,
            "iso2": "NZ",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Scott%27s_Hut"
        },
        {
            "city": "Monument to the Antarctic Treaty",
            "city_ascii": "",
            "lat": -62.200278,
            "lng": -58.961389,
            "iso2": "AQ",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Lame Dog Hut",
            "city_ascii": "",
            "lat": -62.641389,
            "lng": -60.364722,
            "iso2": "BG",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/9/92/Lame-Dog-Hut-Interior.jpg",
            "wiki": ""
        },
        {
            "city": "Endurance 1915 Shipwreck (Discovered in 2022)",
            "city_ascii": "",
            "img_link": "https://upload.wikimedia.org/wikipedia/en/7/7f/Endurance3.jpg",
            "lat": -69.658333,
            "lng": -52.441667,
            "iso2": "UK",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Endurance_(1912_ship)"
        },
        {
            "city": "San Telmo Shipwreck (Potentially First Ship to Discover Antarctica in 1819)",
            "city_ascii": "",
            "lat": -62.333333,
            "lng": -60.5,
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/8/88/SanTelmoAlejoBerlingueromuseonavalmadrid_%28cropped%29.jpg",
            "iso2": "ES",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/San_Telmo_(Spanish_ship)"
        },
        {
            "city": "Lake Ellsworth",
            "city_ascii": "",
            "lat": -79,
            "lng": -91,
            "iso2": "AQ",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Lake_Ellsworth_(Antarctica)"
        },
        {
            "city": "Lake Whillans",
            "city_ascii": "",
            "lat": -84.25,
            "lng": -153.5,
            "iso2": "AQ",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Lake_Whillans"
        },
        {
            "city": "Lake Vostok",
            "city_ascii": "",
            "lat": -77.5,
            "lng": 106,
            "iso2": "AQ",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Lake_Vostok"
        },
        {
            "city": "Mount Erebus (Highest Active Volcano in Antarctica)",
            "city_ascii": "",
            "lat": -77.529722,
            "lng": 167.153333,
            "iso2": "AQ",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Mount_Erebus"
        },
        {
            "city": "Mount Sidley (Highest Dormant Volcano in Antarctica)",
            "city_ascii": "",
            "lat": -77.033333,
            "lng": -126.1,
            "iso2": "AQ",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Mount_Sidley"
        },
        {
            "city": "Martel Inlet",
            "city_ascii": "",
            "lat": -62.083833,
            "lng": -58.392083,
            "iso2": "AQ",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Henryk Arctowski Polish Antarctic Station",
            "city_ascii": "",
            "lat": -62.16014,
            "lng": -58.473247,
            "iso2": "PL",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Signy Island",
            "city_ascii": "",
            "lat": -60.717,
            "lng": -45.6,
            "iso2": "UK",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Halley Research Station",
            "city_ascii": "",
            "lat": -75.568056,
            "lng": -25.508333,
            "iso2": "UK",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Palmer Station",
            "city_ascii": "",
            "lat": -64.77423,
            "lng": -64.052718,
            "iso2": "US",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Rothera Research Station",
            "city_ascii": "",
            "lat": -67.568417,
            "lng": -68.125796,
            "iso2": "UK",
            "country": "Antarctica",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
          "city": "Troll Research Station",
          "city_ascii": "",
          "lat": -72.011662,
          "lng": 2.535138,
          "iso2": "NO",
          "country": "Antarctica",
          "population": 0,
          "capital": "",
          "wiki": "https://en.wikipedia.org/wiki/Troll_(research_station)"
        },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "AQ",
        //   "country": "Antarctica",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "AQ",
        //   "country": "Antarctica",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },

    ]
};