module.exports = {
    CITIES: [{
            "city": "Reykjav\u00edk",
            "city_ascii": "Reykjavik",
            "lat": 64.15,
            "lng": -21.95,
            "country": "Iceland",
            "iso2": "IS",
            "iso3": "ISL",
            "admin_name": "H\u00f6fu\u00f0borgarsv\u00e6\u00f0i",
            "capital": "primary",
            "population": 166212,
            "id": 1352327190
        },
        {
            "city": "Arkhangel\u2019sk",
            "city_ascii": "Arkhangel'sk",
            "lat": 64.575,
            "lng": 40.545,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Arkhangel\u2019skaya Oblast\u2019",
            "capital": "admin",
            "population": 356051,
            "id": 1643797198
        },
        {
            "city": "Murmansk",
            "city_ascii": "Murmansk",
            "lat": 68.97,
            "lng": 33.1,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Murmanskaya Oblast\u2019",
            "capital": "admin",
            "population": 319263,
            "id": 1643755251
        },
        {
            "city": "Noginsk",
            "city_ascii": "Noginsk",
            "lat": 64.4833,
            "lng": 91.2333,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Krasnoyarskiy Kray",
            "capital": "",
            "population": 229731,
            "id": 1643129651
        },
        {
            "city": "Severodvinsk",
            "city_ascii": "Severodvinsk",
            "lat": 64.57,
            "lng": 39.83,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Arkhangel\u2019skaya Oblast\u2019",
            "capital": "",
            "population": 194292,
            "id": 1643427671
        },
        {
            "city": "Noril\u2019sk",
            "city_ascii": "Noril'sk",
            "lat": 69.34,
            "lng": 88.225,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Krasnoyarskiy Kray",
            "capital": "",
            "population": 165873,
            "id": 1643832764
        },
        {
            "city": "Nakhodka",
            "city_ascii": "Nakhodka",
            "lat": 67.7504,
            "lng": 77.52,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Yamalo-Nenetskiy Avtonomnyy Okrug",
            "capital": "",
            "population": 159551,
            "id": 1643884797
        },
        {
            "city": "Trondheim",
            "city_ascii": "Trondheim",
            "lat": 63.4167,
            "lng": 10.4167,
            "country": "Norway",
            "iso2": "NO",
            "iso3": "NOR",
            "admin_name": "",
            "capital": "minor",
            "population": 147139,
            "id": 1578633461
        },
        {
            "city": "Oulu",
            "city_ascii": "Oulu",
            "lat": 65,
            "lng": 25.47,
            "country": "Finland",
            "iso2": "FI",
            "iso3": "FIN",
            "admin_name": "Pohjois-Pohjanmaa",
            "capital": "admin",
            "population": 136752,
            "id": 1246093273
        },
        {
            "city": "Noyabr\u2019sk",
            "city_ascii": "Noyabr'sk",
            "lat": 63.1665,
            "lng": 75.6165,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Yamalo-Nenetskiy Avtonomnyy Okrug",
            "capital": "",
            "population": 110572,
            "id": 1643340196
        },
        {
            "city": "Kandalaksha",
            "city_ascii": "Kandalaksha",
            "lat": 67.1643,
            "lng": 32.4144,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Murmanskaya Oblast\u2019",
            "capital": "",
            "population": 106798,
            "id": 1643555433
        },
        {
            "city": "Ukhta",
            "city_ascii": "Ukhta",
            "lat": 63.56,
            "lng": 53.69,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Komi",
            "capital": "",
            "population": 102187,
            "id": 1643005165
        },
        {
            "city": "Kuopio",
            "city_ascii": "Kuopio",
            "lat": 62.8943,
            "lng": 27.6949,
            "country": "Finland",
            "iso2": "FI",
            "iso3": "FIN",
            "admin_name": "Pohjois-Savo",
            "capital": "admin",
            "population": 91900,
            "id": 1246334067
        },
        {
            "city": "Ume\u00e5",
            "city_ascii": "Umea",
            "lat": 63.83,
            "lng": 20.24,
            "country": "Sweden",
            "iso2": "SE",
            "iso3": "SWE",
            "admin_name": "V\u00e4sterbotten",
            "capital": "admin",
            "population": 78197,
            "id": 1752273881
        },
        {
            "city": "Vaasa",
            "city_ascii": "Vaasa",
            "lat": 63.1,
            "lng": 21.6,
            "country": "Finland",
            "iso2": "FI",
            "iso3": "FIN",
            "admin_name": "Pohjanmaa",
            "capital": "admin",
            "population": 57014,
            "id": 1246734710
        },
        {
            "city": "Troms\u00f8",
            "city_ascii": "Tromso",
            "lat": 69.6351,
            "lng": 18.992,
            "country": "Norway",
            "iso2": "NO",
            "iso3": "NOR",
            "admin_name": "Troms",
            "capital": "admin",
            "population": 52436,
            "id": 1578188822
        },
        {
            "city": "Lule\u00e5",
            "city_ascii": "Lulea",
            "lat": 65.5966,
            "lng": 22.1584,
            "country": "Sweden",
            "iso2": "SE",
            "iso3": "SWE",
            "admin_name": "Norrbotten",
            "capital": "admin",
            "population": 48638,
            "id": 1752765449
        },
        {
            "city": "Kokkola",
            "city_ascii": "Kokkola",
            "lat": 63.8333,
            "lng": 23.1167,
            "country": "Finland",
            "iso2": "FI",
            "iso3": "FIN",
            "admin_name": "Keski-Pohjanmaa",
            "capital": "admin",
            "population": 46714,
            "id": 1246041998
        },
        {
            "city": "\u00d6stersund",
            "city_ascii": "Ostersund",
            "lat": 63.1833,
            "lng": 14.65,
            "country": "Sweden",
            "iso2": "SE",
            "iso3": "SWE",
            "admin_name": "J\u00e4mtland",
            "capital": "admin",
            "population": 46178,
            "id": 1752026711
        },
        {
            "city": "Salekhard",
            "city_ascii": "Salekhard",
            "lat": 66.535,
            "lng": 66.61,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Yamalo-Nenetskiy Avtonomnyy Okrug",
            "capital": "admin",
            "population": 38025,
            "id": 1643083395
        },
        {
            "city": "Rovaniemi",
            "city_ascii": "Rovaniemi",
            "lat": 66.5,
            "lng": 25.7159,
            "country": "Finland",
            "iso2": "FI",
            "iso3": "FIN",
            "admin_name": "Lappi",
            "capital": "admin",
            "population": 34781,
            "id": 1246718173
        },
        {
            "city": "Bod\u00f8",
            "city_ascii": "Bodo",
            "lat": 67.2468,
            "lng": 14.399,
            "country": "Norway",
            "iso2": "NO",
            "iso3": "NOR",
            "admin_name": "Nordland",
            "capital": "admin",
            "population": 34073,
            "id": 1578023501
        },
        {
            "city": "Nar\u2019yan-Mar",
            "city_ascii": "Nar'yan-Mar",
            "lat": 67.6474,
            "lng": 53.0574,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Nenetskiy Avtonomnyy Okrug",
            "capital": "admin",
            "population": 21658,
            "id": 1643685127
        },
        {
            "city": "Molde",
            "city_ascii": "Molde",
            "lat": 62.7483,
            "lng": 7.1833,
            "country": "Norway",
            "iso2": "NO",
            "iso3": "NOR",
            "admin_name": "M\u00f8re og Romsdal",
            "capital": "admin",
            "population": 18594,
            "id": 1578540727
        },
        {
            "city": "H\u00e4rn\u00f6sand",
            "city_ascii": "Harnosand",
            "lat": 62.634,
            "lng": 17.934,
            "country": "Sweden",
            "iso2": "SE",
            "iso3": "SWE",
            "admin_name": "V\u00e4sternorrland",
            "capital": "admin",
            "population": 17016,
            "id": 1752644953
        },
        {
            "city": "Steinkjer",
            "city_ascii": "Steinkjer",
            "lat": 64.0171,
            "lng": 11.5,
            "country": "Norway",
            "iso2": "NO",
            "iso3": "NOR",
            "admin_name": "",
            "capital": "admin",
            "population": 11274,
            "id": 1578642047
        },
        {
            "city": "Anadyr\u2019",
            "city_ascii": "Anadyr'",
            "lat": 64.737,
            "lng": 177.475,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Chukotskiy Avtonomnyy Okrug",
            "capital": "admin",
            "population": 10332,
            "id": 1643453469
        },
        {
            "city": "Iqaluit",
            "city_ascii": "Iqaluit",
            "lat": 63.7505,
            "lng": -68.5002,
            "country": "Canada",
            "iso2": "CA",
            "iso3": "CAN",
            "admin_name": "Nunavut",
            "capital": "admin",
            "population": 6124,
            "id": 1124379539
        },
        {
            "city": "Vads\u00f8",
            "city_ascii": "Vadso",
            "lat": 70.0966,
            "lng": 29.7657,
            "country": "Norway",
            "iso2": "NO",
            "iso3": "NOR",
            "admin_name": "Finnmark",
            "capital": "admin",
            "population": 5139,
            "id": 1578863149
        },
        {
            "city": "Novyy Urengoy",
            "city_ascii": "Novyy Urengoy",
            "lat": 66.0833,
            "lng": 76.6332,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Yamalo-Nenetskiy Avtonomnyy Okrug",
            "capital": "",
            "population": 94212,
            "id": 1643427847
        },
        {
            "city": "Vorkuta",
            "city_ascii": "Vorkuta",
            "lat": 67.5,
            "lng": 64.01,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Komi",
            "capital": "",
            "population": 80039,
            "id": 1643002916
        },
        {
            "city": "Apatity",
            "city_ascii": "Apatity",
            "lat": 67.5731,
            "lng": 33.393,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Murmanskaya Oblast\u2019",
            "capital": "",
            "population": 66907,
            "id": 1643183303
        },
        {
            "city": "Fairbanks",
            "city_ascii": "Fairbanks",
            "lat": 64.8353,
            "lng": -147.6534,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Alaska",
            "capital": "",
            "population": 64732,
            "id": 1840023463
        },
        {
            "city": "Severomorsk",
            "city_ascii": "Severomorsk",
            "lat": 69.0731,
            "lng": 33.4231,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Murmanskaya Oblast\u2019",
            "capital": "",
            "population": 53921,
            "id": 1643295687
        },
        {
            "city": "Monchegorsk",
            "city_ascii": "Monchegorsk",
            "lat": 67.9291,
            "lng": 32.8287,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Murmanskaya Oblast\u2019",
            "capital": "",
            "population": 49868,
            "id": 1643634027
        },
        {
            "city": "Nadym",
            "city_ascii": "Nadym",
            "lat": 65.5298,
            "lng": 72.5148,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Yamalo-Nenetskiy Avtonomnyy Okrug",
            "capital": "",
            "population": 46339,
            "id": 1643709121
        },
        {
            "city": "Pechora",
            "city_ascii": "Pechora",
            "lat": 65.1587,
            "lng": 57.2087,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Komi",
            "capital": "",
            "population": 46113,
            "id": 1643523866
        },
        {
            "city": "Parma",
            "city_ascii": "Parma",
            "lat": 65.923,
            "lng": 57.403,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Komi",
            "capital": "",
            "population": 45000,
            "id": 1643982067
        },
        {
            "city": "Boyarka",
            "city_ascii": "Boyarka",
            "lat": 70.767,
            "lng": 97.5,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Krasnoyarskiy Kray",
            "capital": "",
            "population": 35968,
            "id": 1643010185
        },
        {
            "city": "Segezha",
            "city_ascii": "Segezha",
            "lat": 63.7548,
            "lng": 34.3243,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Kareliya",
            "capital": "",
            "population": 33354,
            "id": 1643971245
        },
        {
            "city": "Skellefte\u00e5",
            "city_ascii": "Skelleftea",
            "lat": 64.7721,
            "lng": 20.95,
            "country": "Sweden",
            "iso2": "SE",
            "iso3": "SWE",
            "admin_name": "V\u00e4sterbotten",
            "capital": "minor",
            "population": 31311,
            "id": 1752233025
        },
        {
            "city": "Kirovsk",
            "city_ascii": "Kirovsk",
            "lat": 67.6091,
            "lng": 33.6687,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Murmanskaya Oblast\u2019",
            "capital": "",
            "population": 29605,
            "id": 1643433043
        },
        {
            "city": "Sosnogorsk",
            "city_ascii": "Sosnogorsk",
            "lat": 63.5948,
            "lng": 53.8943,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Komi",
            "capital": "",
            "population": 29343,
            "id": 1643361228
        },
        {
            "city": "\u00d6rnsk\u00f6ldsvik",
            "city_ascii": "Ornskoldsvik",
            "lat": 63.318,
            "lng": 18.7167,
            "country": "Sweden",
            "iso2": "SE",
            "iso3": "SWE",
            "admin_name": "V\u00e4sternorrland",
            "capital": "minor",
            "population": 27749,
            "id": 1752250773
        },
        {
            "city": "Dudinka",
            "city_ascii": "Dudinka",
            "lat": 69.4182,
            "lng": 86.225,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Krasnoyarskiy Kray",
            "capital": "",
            "population": 23619,
            "id": 1643923236
        },
        {
            "city": "Inta",
            "city_ascii": "Inta",
            "lat": 66.0374,
            "lng": 60.1674,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Komi",
            "capital": "",
            "population": 22921,
            "id": 1643587482
        },
        {
            "city": "Onega",
            "city_ascii": "Onega",
            "lat": 63.9271,
            "lng": 38.0771,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Arkhangel\u2019skaya Oblast\u2019",
            "capital": "",
            "population": 22693,
            "id": 1643716527
        },
        {
            "city": "Kemi",
            "city_ascii": "Kemi",
            "lat": 65.7333,
            "lng": 24.5817,
            "country": "Finland",
            "iso2": "FI",
            "iso3": "FIN",
            "admin_name": "Lappi",
            "capital": "minor",
            "population": 22641,
            "id": 1246411843
        },
        {
            "city": "Mo i Rana",
            "city_ascii": "Mo i Rana",
            "lat": 66.3166,
            "lng": 14.1667,
            "country": "Norway",
            "iso2": "NO",
            "iso3": "NOR",
            "admin_name": "Nordland",
            "capital": "minor",
            "population": 20409,
            "id": 1578067925
        },
        {
            "city": "Narvik",
            "city_ascii": "Narvik",
            "lat": 68.3832,
            "lng": 17.29,
            "country": "Norway",
            "iso2": "NO",
            "iso3": "NOR",
            "admin_name": "Nordland",
            "capital": "minor",
            "population": 20000,
            "id": 1578744025
        },
        {
            "city": "Harstad",
            "city_ascii": "Harstad",
            "lat": 68.7879,
            "lng": 16.5156,
            "country": "Norway",
            "iso2": "NO",
            "iso3": "NOR",
            "admin_name": "Troms",
            "capital": "minor",
            "population": 19433,
            "id": 1578844884
        },
        {
            "city": "Polyarnyy",
            "city_ascii": "Polyarnyy",
            "lat": 69.2052,
            "lng": 33.4502,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Murmanskaya Oblast\u2019",
            "capital": "",
            "population": 19200,
            "id": 1643432811
        },
        {
            "city": "Badger",
            "city_ascii": "Badger",
            "lat": 64.8006,
            "lng": -147.3877,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Alaska",
            "capital": "",
            "population": 19039,
            "id": 1840023690
        },
        {
            "city": "Kiruna",
            "city_ascii": "Kiruna",
            "lat": 67.85,
            "lng": 20.2166,
            "country": "Sweden",
            "iso2": "SE",
            "iso3": "SWE",
            "admin_name": "Norrbotten",
            "capital": "minor",
            "population": 18154,
            "id": 1752001526
        },
        {
            "city": "Akureyri",
            "city_ascii": "Akureyri",
            "lat": 65.6666,
            "lng": -18.1,
            "country": "Iceland",
            "iso2": "IS",
            "iso3": "ISL",
            "admin_name": "",
            "capital": "",
            "population": 16563,
            "id": 1352098424
        },
        {
            "city": "Nikel\u2019",
            "city_ascii": "Nikel'",
            "lat": 69.4126,
            "lng": 30.2188,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Murmanskaya Oblast\u2019",
            "capital": "",
            "population": 15866,
            "id": 1643124017
        },
        {
            "city": "Udachnyy",
            "city_ascii": "Udachnyy",
            "lat": 66.4232,
            "lng": 112.3965,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Sakha (Yakutiya)",
            "capital": "",
            "population": 15266,
            "id": 1643138235
        },
        {
            "city": "College",
            "city_ascii": "College",
            "lat": 64.8694,
            "lng": -147.8217,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Alaska",
            "capital": "",
            "population": 14362,
            "id": 1840023462
        },
        {
            "city": "Kem\u2019",
            "city_ascii": "Kem'",
            "lat": 64.9536,
            "lng": 34.5684,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Kareliya",
            "capital": "",
            "population": 13829,
            "id": 1643304829
        },
        {
            "city": "Belomorsk",
            "city_ascii": "Belomorsk",
            "lat": 64.5252,
            "lng": 34.7658,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Kareliya",
            "capital": "",
            "population": 12165,
            "id": 1643588400
        },
        {
            "city": "Alta",
            "city_ascii": "Alta",
            "lat": 69.9666,
            "lng": 23.2417,
            "country": "Norway",
            "iso2": "NO",
            "iso3": "NOR",
            "admin_name": "Finnmark",
            "capital": "minor",
            "population": 12077,
            "id": 1578308187
        },
        {
            "city": "Severnyy",
            "city_ascii": "Severnyy",
            "lat": 67.6083,
            "lng": 64.1233,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Komi",
            "capital": "",
            "population": 11562,
            "id": 1643427677
        },
        {
            "city": "Hammerfest",
            "city_ascii": "Hammerfest",
            "lat": 70.6613,
            "lng": 23.688,
            "country": "Norway",
            "iso2": "NO",
            "iso3": "NOR",
            "admin_name": "Finnmark",
            "capital": "minor",
            "population": 10000,
            "id": 1578368356
        },
        {
            "city": "Namsos",
            "city_ascii": "Namsos",
            "lat": 64.4833,
            "lng": 11.5,
            "country": "Norway",
            "iso2": "NO",
            "iso3": "NOR",
            "admin_name": "",
            "capital": "minor",
            "population": 9035,
            "id": 1578576567
        },
        {
            "city": "Sodankyl\u00e4",
            "city_ascii": "Sodankyla",
            "lat": 67.4171,
            "lng": 26.6,
            "country": "Finland",
            "iso2": "FI",
            "iso3": "FIN",
            "admin_name": "Lappi",
            "capital": "minor",
            "population": 8942,
            "id": 1246413171
        },
        {
            "city": "Kemij\u00e4rvi",
            "city_ascii": "Kemijarvi",
            "lat": 66.6667,
            "lng": 27.4167,
            "country": "Finland",
            "iso2": "FI",
            "iso3": "FIN",
            "admin_name": "Lappi",
            "capital": "minor",
            "population": 8883,
            "id": 1246358285
        },
        {
            "city": "Vilyuysk",
            "city_ascii": "Vilyuysk",
            "lat": 63.7553,
            "lng": 121.6248,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Sakha (Yakutiya)",
            "capital": "",
            "population": 9948,
            "id": 1643430483
        },
        {
            "city": "Igrim",
            "city_ascii": "Igrim",
            "lat": 63.1933,
            "lng": 64.4194,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Khanty-Mansiyskiy Avtonomnyy Okrug-Yugra",
            "capital": "",
            "population": 9545,
            "id": 1643468393
        },
        {
            "city": "Ust\u2019-Nera",
            "city_ascii": "Ust'-Nera",
            "lat": 64.5666,
            "lng": 143.2,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Sakha (Yakutiya)",
            "capital": "",
            "population": 9148,
            "id": 1643124244
        },
        {
            "city": "Keflav\u00edk",
            "city_ascii": "Keflavik",
            "lat": 64.0166,
            "lng": -22.5666,
            "country": "Iceland",
            "iso2": "IS",
            "iso3": "ISL",
            "admin_name": "",
            "capital": "",
            "population": 7930,
            "id": 1352901945
        },
        {
            "city": "Steele Creek",
            "city_ascii": "Steele Creek",
            "lat": 64.9295,
            "lng": -147.3955,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Alaska",
            "capital": "",
            "population": 7571,
            "id": 1840075216
        },
        {
            "city": "Igarka",
            "city_ascii": "Igarka",
            "lat": 67.4671,
            "lng": 86.5833,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Krasnoyarskiy Kray",
            "capital": "",
            "population": 7470,
            "id": 1643125542
        },
        {
            "city": "Susuman",
            "city_ascii": "Susuman",
            "lat": 62.7833,
            "lng": 148.1668,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Magadanskaya Oblast\u2019",
            "capital": "",
            "population": 7367,
            "id": 1643731360
        },
        {
            "city": "Khandyga",
            "city_ascii": "Khandyga",
            "lat": 62.666,
            "lng": 135.6,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Sakha (Yakutiya)",
            "capital": "",
            "population": 6796,
            "id": 1643340100
        },
        {
            "city": "Verkhnevilyuysk",
            "city_ascii": "Verkhnevilyuysk",
            "lat": 63.4457,
            "lng": 120.3167,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Sakha (Yakutiya)",
            "capital": "",
            "population": 6341,
            "id": 1643968444
        },
        {
            "city": "Selfoss",
            "city_ascii": "Selfoss",
            "lat": 63.9334,
            "lng": -20.9969,
            "country": "Iceland",
            "iso2": "IS",
            "iso3": "ISL",
            "admin_name": "",
            "capital": "",
            "population": 6275,
            "id": 1352214400
        },
        {
            "city": "Chena Ridge",
            "city_ascii": "Chena Ridge",
            "lat": 64.7941,
            "lng": -148.0357,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Alaska",
            "capital": "",
            "population": 6155,
            "id": 1840075179
        },
        {
            "city": "Umba",
            "city_ascii": "Umba",
            "lat": 66.6814,
            "lng": 34.3455,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Murmanskaya Oblast\u2019",
            "capital": "",
            "population": 6128,
            "id": 1643774657
        },
        {
            "city": "Tazovskiy",
            "city_ascii": "Tazovskiy",
            "lat": 67.4667,
            "lng": 78.7,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Yamalo-Nenetskiy Avtonomnyy Okrug",
            "capital": "",
            "population": 5981,
            "id": 1643167905
        },
        {
            "city": "Bilibino",
            "city_ascii": "Bilibino",
            "lat": 68.0504,
            "lng": 166.3333,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Chukotskiy Avtonomnyy Okrug",
            "capital": "",
            "population": 5757,
            "id": 1643015766
        },
        {
            "city": "Tiksi",
            "city_ascii": "Tiksi",
            "lat": 71.6269,
            "lng": 128.835,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Sakha (Yakutiya)",
            "capital": "",
            "population": 5700,
            "id": 1643870212
        },
        {
            "city": "Tura",
            "city_ascii": "Tura",
            "lat": 64.2833,
            "lng": 100.25,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Krasnoyarskiy Kray",
            "capital": "",
            "population": 5444,
            "id": 1643809018
        },
        {
            "city": "Chernyshevskiy",
            "city_ascii": "Chernyshevskiy",
            "lat": 63.0128,
            "lng": 112.4714,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Sakha (Yakutiya)",
            "capital": "",
            "population": 5137,
            "id": 1643326299
        },
        {
            "city": "Farmers Loop",
            "city_ascii": "Farmers Loop",
            "lat": 64.9061,
            "lng": -147.6957,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Alaska",
            "capital": "",
            "population": 5092,
            "id": 1840075181
        }
    ]
}