module.exports = {
    CITIES: [{
            "city": "Sydney",
            "city_ascii": "Sydney",
            "lat": -33.92,
            "lng": 151.1852,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "admin",
            "population": 4630000,
            "id": 1036074917
        },
        {
            "city": "Melbourne",
            "city_ascii": "Melbourne",
            "lat": -37.82,
            "lng": 144.975,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Victoria",
            "capital": "admin",
            "population": 4170000,
            "id": 1036533631
        },
        {
            "city": "Brisbane",
            "city_ascii": "Brisbane",
            "lat": -27.455,
            "lng": 153.0351,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Queensland",
            "capital": "admin",
            "population": 1860000,
            "id": 1036192929
        },
        {
            "city": "Perth",
            "city_ascii": "Perth",
            "lat": -31.955,
            "lng": 115.84,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Western Australia",
            "capital": "admin",
            "population": 1532000,
            "id": 1036178956
        },
        {
            "city": "Adelaide",
            "city_ascii": "Adelaide",
            "lat": -34.935,
            "lng": 138.6,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "South Australia",
            "capital": "admin",
            "population": 1145000,
            "id": 1036538171
        },
        {
            "city": "Newcastle",
            "city_ascii": "Newcastle",
            "lat": -32.8453,
            "lng": 151.815,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 1134616,
            "id": 1036468001
        },
        {
            "city": "Canberra",
            "city_ascii": "Canberra",
            "lat": -35.283,
            "lng": 149.129,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Australian Capital Territory",
            "capital": "primary",
            "population": 327700,
            "id": 1036142029
        },
        {
            "city": "Gold Coast",
            "city_ascii": "Gold Coast",
            "lat": -28.0815,
            "lng": 153.4482,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Queensland",
            "capital": "",
            "population": 527660,
            "id": 1036153217
        },
        {
            "city": "Cranbourne",
            "city_ascii": "Cranbourne",
            "lat": -38.0996,
            "lng": 145.2834,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Victoria",
            "capital": "",
            "population": 460491,
            "id": 1036639986
        },
        {
            "city": "Wollongong",
            "city_ascii": "Wollongong",
            "lat": -34.4154,
            "lng": 150.89,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 260914,
            "id": 1036502269
        },
        {
            "city": "Geelong",
            "city_ascii": "Geelong",
            "lat": -38.1675,
            "lng": 144.3956,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Victoria",
            "capital": "",
            "population": 160991,
            "id": 1036870987
        },
        {
            "city": "Cairns",
            "city_ascii": "Cairns",
            "lat": -16.8878,
            "lng": 145.7633,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Queensland",
            "capital": "",
            "population": 154225,
            "id": 1036016939
        },
        {
            "city": "Townsville",
            "city_ascii": "Townsville",
            "lat": -19.25,
            "lng": 146.77,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Queensland",
            "capital": "",
            "population": 138954,
            "id": 1036500020
        },
        {
            "city": "Albury",
            "city_ascii": "Albury",
            "lat": -36.06,
            "lng": 146.92,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 104258,
            "id": 1036076542
        },
        {
            "city": "Darwin",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/8/84/City_landscape_of_Darwin%2C_Northern_Territory.jpg",
            "city_ascii": "Darwin",
            "lat": -12.4254,
            "lng": 130.85,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Northern Territory",
            "capital": "admin",
            "population": 93080,
            "id": 1036497565
        },
        {
            "city": "Hobart",
            "city_ascii": "Hobart",
            "lat": -42.85,
            "lng": 147.295,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Tasmania",
            "capital": "admin",
            "population": 80870,
            "id": 1036679838
        },
        {
            "city": "Caloundra",
            "city_ascii": "Caloundra",
            "lat": -26.8,
            "lng": 153.1333,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Queensland",
            "capital": "",
            "population": 38706,
            "id": 1036266942
        },
        {
            "city": "Nowra",
            "city_ascii": "Nowra",
            "lat": -34.8828,
            "lng": 150.6,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 94781,
            "id": 1036984536
        },
        {
            "city": "Toowoomba",
            "city_ascii": "Toowoomba",
            "lat": -27.5645,
            "lng": 151.9555,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Queensland",
            "capital": "",
            "population": 92800,
            "id": 1036765315
        },
        {
            "city": "Ballarat",
            "city_ascii": "Ballarat",
            "lat": -37.5596,
            "lng": 143.84,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Victoria",
            "capital": "",
            "population": 85109,
            "id": 1036567186
        },
        {
            "city": "Bendigo",
            "city_ascii": "Bendigo",
            "lat": -36.76,
            "lng": 144.28,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Victoria",
            "capital": "",
            "population": 81657,
            "id": 1036537913
        },
        {
            "city": "Mackay",
            "city_ascii": "Mackay",
            "lat": -21.1439,
            "lng": 149.15,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Queensland",
            "capital": "",
            "population": 75922,
            "id": 1036507374
        },
        {
            "city": "Mandurah",
            "city_ascii": "Mandurah",
            "lat": -32.5235,
            "lng": 115.7471,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Western Australia",
            "capital": "",
            "population": 73356,
            "id": 1036773118
        },
        {
            "city": "Launceston",
            "city_ascii": "Launceston",
            "lat": -41.4498,
            "lng": 147.1302,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Tasmania",
            "capital": "",
            "population": 72458,
            "id": 1036170383
        },
        {
            "city": "Rockhampton",
            "city_ascii": "Rockhampton",
            "lat": -23.3639,
            "lng": 150.52,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Queensland",
            "capital": "",
            "population": 65850,
            "id": 1036768986
        },
        {
            "city": "Coffs Harbour",
            "city_ascii": "Coffs Harbour",
            "lat": -30.3071,
            "lng": 153.1123,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 62978,
            "id": 1036320442
        },
        {
            "city": "Wagga Wagga",
            "city_ascii": "Wagga Wagga",
            "lat": -35.1222,
            "lng": 147.34,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 55381,
            "id": 1036273188
        },
        {
            "city": "Bundaberg",
            "city_ascii": "Bundaberg",
            "lat": -24.8791,
            "lng": 152.3509,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Queensland",
            "capital": "",
            "population": 52472,
            "id": 1036377333
        },
        {
            "city": "Port Macquarie",
            "city_ascii": "Port Macquarie",
            "lat": -31.445,
            "lng": 152.9187,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 48547,
            "id": 1036051032
        },
        {
            "city": "Mildura",
            "city_ascii": "Mildura",
            "lat": -34.185,
            "lng": 142.1514,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Victoria",
            "capital": "",
            "population": 47867,
            "id": 1036624348
        },
        {
            "city": "Taree",
            "city_ascii": "Taree",
            "lat": -31.8976,
            "lng": 152.4618,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 44182,
            "id": 1036855717
        },
        {
            "city": "Orange",
            "city_ascii": "Orange",
            "lat": -33.28,
            "lng": 149.1,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 39329,
            "id": 1036760396
        },
        {
            "city": "Tamworth",
            "city_ascii": "Tamworth",
            "lat": -31.1026,
            "lng": 150.9171,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 38551,
            "id": 1036233388
        },
        {
            "city": "Kalgoorlie",
            "city_ascii": "Kalgoorlie",
            "lat": -30.7354,
            "lng": 121.46,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Western Australia",
            "capital": "",
            "population": 36852,
            "id": 1036087904
        },
        {
            "city": "Shepparton",
            "city_ascii": "Shepparton",
            "lat": -36.3746,
            "lng": 145.3914,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Victoria",
            "capital": "",
            "population": 33550,
            "id": 1036030548
        },
        {
            "city": "Mount Isa",
            "city_ascii": "Mount Isa",
            "lat": -20.7239,
            "lng": 139.49,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Queensland",
            "capital": "",
            "population": 33200,
            "id": 1036386100
        },
        {
            "city": "Tweed Heads",
            "city_ascii": "Tweed Heads",
            "lat": -28.1826,
            "lng": 153.5466,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 33065,
            "id": 1036571941
        },
        {
            "city": "Queanbeyan",
            "city_ascii": "Queanbeyan",
            "lat": -35.3546,
            "lng": 149.2113,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 32602,
            "id": 1036846465
        },
        {
            "city": "Melton",
            "city_ascii": "Melton",
            "lat": -37.6895,
            "lng": 144.57,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Victoria",
            "capital": "",
            "population": 32368,
            "id": 1036007778
        },
        {
            "city": "Dubbo",
            "city_ascii": "Dubbo",
            "lat": -32.26,
            "lng": 148.5973,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 31574,
            "id": 1036855042
        },
        {
            "city": "Caboolture",
            "city_ascii": "Caboolture",
            "lat": -27.083,
            "lng": 152.95,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Queensland",
            "capital": "",
            "population": 31513,
            "id": 1036273434
        },
        {
            "city": "Lismore",
            "city_ascii": "Lismore",
            "lat": -28.8167,
            "lng": 153.2931,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 31430,
            "id": 1036024174
        },
        {
            "city": "Gladstone",
            "city_ascii": "Gladstone",
            "lat": -23.8533,
            "lng": 151.2467,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Queensland",
            "capital": "",
            "population": 30489,
            "id": 1036070755
        },
        {
            "city": "Warrnambool",
            "city_ascii": "Warrnambool",
            "lat": -38.38,
            "lng": 142.47,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Victoria",
            "capital": "",
            "population": 29928,
            "id": 1036291219
        },
        {
            "city": "Sunbury",
            "city_ascii": "Sunbury",
            "lat": -37.5696,
            "lng": 144.71,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Victoria",
            "capital": "",
            "population": 29925,
            "id": 1036519781
        },
        {
            "city": "Alice Springs",
            "city_ascii": "Alice Springs",
            "lat": -23.701,
            "lng": 133.88,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Northern Territory",
            "capital": "",
            "population": 27710,
            "id": 1036830397
        },
        {
            "city": "Geraldton",
            "city_ascii": "Geraldton",
            "lat": -28.7666,
            "lng": 114.6,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Western Australia",
            "capital": "",
            "population": 27258,
            "id": 1036811875
        },
        {
            "city": "Bunbury",
            "city_ascii": "Bunbury",
            "lat": -33.3443,
            "lng": 115.6502,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Western Australia",
            "capital": "",
            "population": 26998,
            "id": 1036561011
        },
        {
            "city": "Albany",
            "city_ascii": "Albany",
            "lat": -35.0169,
            "lng": 117.8916,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Western Australia",
            "capital": "",
            "population": 26445,
            "id": 1036047365
        },
        {
            "city": "Hervey Bay",
            "city_ascii": "Hervey Bay",
            "lat": -25.2887,
            "lng": 152.8409,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Queensland",
            "capital": "",
            "population": 25114,
            "id": 1036833938
        },
        {
            "city": "Mount Gambier",
            "city_ascii": "Mount Gambier",
            "lat": -37.8313,
            "lng": 140.765,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "South Australia",
            "capital": "",
            "population": 23209,
            "id": 1036932780
        },
        {
            "city": "Armidale",
            "city_ascii": "Armidale",
            "lat": -30.5123,
            "lng": 151.6675,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 22673,
            "id": 1036975829
        },
        {
            "city": "Whyalla",
            "city_ascii": "Whyalla",
            "lat": -33.025,
            "lng": 137.5614,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "South Australia",
            "capital": "",
            "population": 22559,
            "id": 1036961366
        },
        {
            "city": "Sale",
            "city_ascii": "Sale",
            "lat": -38.1096,
            "lng": 147.06,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Victoria",
            "capital": "",
            "population": 22486,
            "id": 1036960753
        },
        {
            "city": "Katoomba",
            "city_ascii": "Katoomba",
            "lat": -33.7069,
            "lng": 150.32,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 22076,
            "id": 1036674004
        },
        {
            "city": "Goulburn",
            "city_ascii": "Goulburn",
            "lat": -34.7496,
            "lng": 149.7102,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 20940,
            "id": 1036347537
        },
        {
            "city": "Maryborough",
            "city_ascii": "Maryborough",
            "lat": -25.5491,
            "lng": 152.7209,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Queensland",
            "capital": "",
            "population": 20678,
            "id": 1036205623
        },
        {
            "city": "Kwinana",
            "city_ascii": "Kwinana",
            "lat": -32.2394,
            "lng": 115.7702,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Western Australia",
            "capital": "",
            "population": 20086,
            "id": 1036753478
        },
        {
            "city": "Burnie",
            "city_ascii": "Burnie",
            "lat": -41.0666,
            "lng": 145.9167,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Tasmania",
            "capital": "",
            "population": 19972,
            "id": 1036394657
        },
        {
            "city": "Echuca",
            "city_ascii": "Echuca",
            "lat": -36.1296,
            "lng": 144.75,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Victoria",
            "capital": "",
            "population": 19457,
            "id": 1036292989
        },
        {
            "city": "Devonport",
            "city_ascii": "Devonport",
            "lat": -41.1927,
            "lng": 146.3311,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Tasmania",
            "capital": "",
            "population": 19317,
            "id": 1036033175
        },
        {
            "city": "Roebourne",
            "city_ascii": "Roebourne",
            "lat": -20.7829,
            "lng": 117.1333,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Western Australia",
            "capital": "",
            "population": 19260,
            "id": 1036752479
        },
        {
            "city": "Maitland",
            "city_ascii": "Maitland",
            "lat": -32.721,
            "lng": 151.555,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 18625,
            "id": 1036034945
        },
        {
            "city": "Traralgon",
            "city_ascii": "Traralgon",
            "lat": -38.1996,
            "lng": 146.53,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Victoria",
            "capital": "",
            "population": 18226,
            "id": 1036938861
        },
        {
            "city": "Murray Bridge",
            "city_ascii": "Murray Bridge",
            "lat": -35.1296,
            "lng": 139.26,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "South Australia",
            "capital": "",
            "population": 18194,
            "id": 1036345943
        },
        {
            "city": "Tuncurry",
            "city_ascii": "Tuncurry",
            "lat": -32.1931,
            "lng": 152.5266,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 17591,
            "id": 1036846186
        },
        {
            "city": "Broken Hill",
            "city_ascii": "Broken Hill",
            "lat": -31.95,
            "lng": 141.4331,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 17395,
            "id": 1036216956
        },
        {
            "city": "Karratha",
            "city_ascii": "Karratha",
            "lat": -20.7304,
            "lng": 116.87,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Western Australia",
            "capital": "",
            "population": 16796,
            "id": 1036951388
        },
        {
            "city": "Gawler",
            "city_ascii": "Gawler",
            "lat": -34.6074,
            "lng": 138.7264,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "South Australia",
            "capital": "",
            "population": 16362,
            "id": 1036309493
        },
        {
            "city": "Griffith",
            "city_ascii": "Griffith",
            "lat": -34.29,
            "lng": 146.04,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "New South Wales",
            "capital": "",
            "population": 15455,
            "id": 1036563313
        }
    ]
}