module.exports = {
    CITIES: [{
            "city": "Baku",
            "city_ascii": "Baku",
            "lat": 40.3953,
            "lng": 49.8622,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "Bak\u0131",
            "capital": "primary",
            "population": 2122300,
            "id": 1031946365
        },
        {
            "city": "Tabr\u012bz",
            "city_ascii": "Tabriz",
            "lat": 38.0863,
            "lng": 46.3012,
            "country": "Iran",
            "iso2": "IR",
            "iso3": "IRN",
            "admin_name": "\u0100z\u0304arb\u0101yj\u0101n-e Sharq\u012b",
            "capital": "admin",
            "population": 1413000,
            "id": 1364141756
        },
        {
            "city": "Yerevan",
            "city_ascii": "Yerevan",
            "lat": 40.1812,
            "lng": 44.5136,
            "country": "Armenia",
            "iso2": "AM",
            "iso3": "ARM",
            "admin_name": "Yerevan",
            "capital": "primary",
            "population": 1102000,
            "id": 1051074169
        },
        {
            "city": "Tbilisi",
            "city_ascii": "Tbilisi",
            "lat": 41.725,
            "lng": 44.7908,
            "country": "Georgia",
            "iso2": "GE",
            "iso3": "GEO",
            "admin_name": "Tbilisi",
            "capital": "primary",
            "population": 1100000,
            "id": 1268203191
        },
        {
            "city": "Trabzon",
            "city_ascii": "Trabzon",
            "lat": 40.98,
            "lng": 39.72,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Trabzon",
            "capital": "admin",
            "population": 764714,
            "id": 1792019202
        },
        {
            "city": "Krasnodar",
            "city_ascii": "Krasnodar",
            "lat": 45.02,
            "lng": 39,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Krasnodarskiy Kray",
            "capital": "admin",
            "population": 649851,
            "id": 1643438227
        },
        {
            "city": "Samsun",
            "city_ascii": "Samsun",
            "lat": 41.28,
            "lng": 36.3437,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Samsun",
            "capital": "admin",
            "population": 609339,
            "id": 1792169057
        },
        {
            "city": "Kayseri",
            "city_ascii": "Kayseri",
            "lat": 38.735,
            "lng": 35.49,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Kayseri",
            "capital": "admin",
            "population": 592840,
            "id": 1792945815
        },
        {
            "city": "Makhachkala",
            "city_ascii": "Makhachkala",
            "lat": 42.98,
            "lng": 47.5,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Dagestan",
            "capital": "admin",
            "population": 554981,
            "id": 1643580480
        },
        {
            "city": "Malatya",
            "city_ascii": "Malatya",
            "lat": 38.3704,
            "lng": 38.3,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Malatya",
            "capital": "admin",
            "population": 461574,
            "id": 1792485155
        },
        {
            "city": "Erzurum",
            "city_ascii": "Erzurum",
            "lat": 39.9204,
            "lng": 41.29,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Erzurum",
            "capital": "admin",
            "population": 420691,
            "id": 1792511957
        },
        {
            "city": "Ardab\u012bl",
            "city_ascii": "Ardabil",
            "lat": 38.25,
            "lng": 48.3,
            "country": "Iran",
            "iso2": "IR",
            "iso3": "IRN",
            "admin_name": "Ardab\u012bl",
            "capital": "admin",
            "population": 414603,
            "id": 1364437616
        },
        {
            "city": "Van",
            "city_ascii": "Van",
            "lat": 38.4954,
            "lng": 43.4,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Van",
            "capital": "admin",
            "population": 371713,
            "id": 1792940471
        },
        {
            "city": "Vladikavkaz",
            "city_ascii": "Vladikavkaz",
            "lat": 43.0504,
            "lng": 44.67,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "North Ossetia",
            "capital": "admin",
            "population": 364630,
            "id": 1643438348
        },
        {
            "city": "Stavropol\u2019",
            "city_ascii": "Stavropol'",
            "lat": 45.05,
            "lng": 41.98,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Stavropol\u2019skiy Kray",
            "capital": "admin",
            "population": 363064,
            "id": 1643947228
        },
        {
            "city": "Sochi",
            "city_ascii": "Sochi",
            "lat": 43.59,
            "lng": 39.73,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Krasnodarskiy Kray",
            "capital": "",
            "population": 327608,
            "id": 1643009782
        },
        {
            "city": "Nal\u2019chik",
            "city_ascii": "Nal'chik",
            "lat": 43.4981,
            "lng": 43.6179,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Kabardino-Balkariya",
            "capital": "admin",
            "population": 307866,
            "id": 1643746064
        },
        {
            "city": "G\u0259nc\u0259",
            "city_ascii": "Ganca",
            "lat": 40.685,
            "lng": 46.35,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "G\u0259nc\u0259",
            "capital": "admin",
            "population": 303268,
            "id": 1031197327
        },
        {
            "city": "Rize",
            "city_ascii": "Rize",
            "lat": 41.0208,
            "lng": 40.5219,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Rize",
            "capital": "admin",
            "population": 279450,
            "id": 1792024731
        },
        {
            "city": "Sumqay\u0131t",
            "city_ascii": "Sumqayit",
            "lat": 40.58,
            "lng": 49.63,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "Sumqay\u0131t",
            "capital": "admin",
            "population": 279159,
            "id": 1031630283
        },
        {
            "city": "Elaz\u0131\u011f",
            "city_ascii": "Elazig",
            "lat": 38.68,
            "lng": 39.23,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Elaz\u0131\u011f",
            "capital": "admin",
            "population": 271492,
            "id": 1792156766
        },
        {
            "city": "Sivas",
            "city_ascii": "Sivas",
            "lat": 39.7454,
            "lng": 37.035,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Sivas",
            "capital": "admin",
            "population": 264022,
            "id": 1792938326
        },
        {
            "city": "Novorossiysk",
            "city_ascii": "Novorossiysk",
            "lat": 44.73,
            "lng": 37.7699,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Krasnodarskiy Kray",
            "capital": "",
            "population": 241856,
            "id": 1643087180
        },
        {
            "city": "Groznyy",
            "city_ascii": "Groznyy",
            "lat": 43.3187,
            "lng": 45.6987,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Chechnya",
            "capital": "admin",
            "population": 226100,
            "id": 1643049853
        },
        {
            "city": "Khowy",
            "city_ascii": "Khowy",
            "lat": 38.5304,
            "lng": 44.97,
            "country": "Iran",
            "iso2": "IR",
            "iso3": "IRN",
            "admin_name": "\u0100z\u0304arb\u0101yj\u0101n-e Gharb\u012b",
            "capital": "minor",
            "population": 202728,
            "id": 1364186788
        },
        {
            "city": "Armavir",
            "city_ascii": "Armavir",
            "lat": 45.0004,
            "lng": 41.13,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Krasnodarskiy Kray",
            "capital": "",
            "population": 199548,
            "id": 1643809754
        },
        {
            "city": "Kutaisi",
            "city_ascii": "Kutaisi",
            "lat": 42.25,
            "lng": 42.73,
            "country": "Georgia",
            "iso2": "GE",
            "iso3": "GEO",
            "admin_name": "Imereti",
            "capital": "admin",
            "population": 183945,
            "id": 1268369835
        },
        {
            "city": "Maykop",
            "city_ascii": "Maykop",
            "lat": 44.61,
            "lng": 40.12,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Adygeya",
            "capital": "admin",
            "population": 158451,
            "id": 1643584159
        },
        {
            "city": "Rust\u2019avi",
            "city_ascii": "Rust'avi",
            "lat": 41.5704,
            "lng": 45.05,
            "country": "Georgia",
            "iso2": "GE",
            "iso3": "GEO",
            "admin_name": "",
            "capital": "",
            "population": 157063,
            "id": 1268562807
        },
        {
            "city": "Batumi",
            "city_ascii": "Batumi",
            "lat": 41.6,
            "lng": 41.63,
            "country": "Georgia",
            "iso2": "GE",
            "iso3": "GEO",
            "admin_name": "Ajaria",
            "capital": "admin",
            "population": 155542,
            "id": 1268193611
        },
        {
            "city": "Ordu",
            "city_ascii": "Ordu",
            "lat": 41.0004,
            "lng": 37.8699,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Ordu",
            "capital": "admin",
            "population": 155117,
            "id": 1792540951
        },
        {
            "city": "Gyumri",
            "city_ascii": "Gyumri",
            "lat": 40.7894,
            "lng": 43.8475,
            "country": "Armenia",
            "iso2": "AM",
            "iso3": "ARM",
            "admin_name": "Shirak",
            "capital": "admin",
            "population": 148381,
            "id": 1051341374
        },
        {
            "city": "Pyatigorsk",
            "city_ascii": "Pyatigorsk",
            "lat": 44.08,
            "lng": 43.09,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Stavropol\u2019skiy Kray",
            "capital": "",
            "population": 142865,
            "id": 1643815630
        },
        {
            "city": "Nevinnomyssk",
            "city_ascii": "Nevinnomyssk",
            "lat": 44.6201,
            "lng": 41.95,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Stavropol\u2019skiy Kray",
            "capital": "",
            "population": 134380,
            "id": 1643869152
        },
        {
            "city": "Kislovodsk",
            "city_ascii": "Kislovodsk",
            "lat": 43.91,
            "lng": 42.72,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Stavropol\u2019skiy Kray",
            "capital": "",
            "population": 132771,
            "id": 1643705192
        },
        {
            "city": "Tokat",
            "city_ascii": "Tokat",
            "lat": 40.306,
            "lng": 36.563,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Tokat",
            "capital": "admin",
            "population": 129702,
            "id": 1792534905
        },
        {
            "city": "Erzincan",
            "city_ascii": "Erzincan",
            "lat": 39.7526,
            "lng": 39.4928,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Erzincan",
            "capital": "admin",
            "population": 129407,
            "id": 1792742754
        },
        {
            "city": "Cherkessk",
            "city_ascii": "Cherkessk",
            "lat": 44.2904,
            "lng": 42.06,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Karachayevo-Cherkesiya",
            "capital": "admin",
            "population": 116224,
            "id": 1643955713
        },
        {
            "city": "Derbent",
            "city_ascii": "Derbent",
            "lat": 42.0578,
            "lng": 48.2774,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Dagestan",
            "capital": "minor",
            "population": 105965,
            "id": 1643003556
        },
        {
            "city": "Ahar",
            "city_ascii": "Ahar",
            "lat": 38.4829,
            "lng": 47.0629,
            "country": "Iran",
            "iso2": "IR",
            "iso3": "IRN",
            "admin_name": "\u0100z\u0304arb\u0101yj\u0101n-e Sharq\u012b",
            "capital": "minor",
            "population": 103639,
            "id": 1364602437
        },
        {
            "city": "Vanadzor",
            "city_ascii": "Vanadzor",
            "lat": 40.8128,
            "lng": 44.4883,
            "country": "Armenia",
            "iso2": "AM",
            "iso3": "ARM",
            "admin_name": "Lorri",
            "capital": "admin",
            "population": 101098,
            "id": 1051691929
        },
        {
            "city": "Giresun",
            "city_ascii": "Giresun",
            "lat": 40.913,
            "lng": 38.39,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Giresun",
            "capital": "admin",
            "population": 98864,
            "id": 1792486859
        },
        {
            "city": "Nax\u00e7\u0131van",
            "city_ascii": "Naxcivan",
            "lat": 39.2092,
            "lng": 45.4122,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "Nax\u00e7\u0131van",
            "capital": "admin",
            "population": 94788,
            "id": 1031943755
        },
        {
            "city": "A\u011fr\u0131",
            "city_ascii": "Agri",
            "lat": 39.7198,
            "lng": 43.0513,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "A\u011fr\u0131",
            "capital": "admin",
            "population": 87854,
            "id": 1792385654
        },
        {
            "city": "Amasya",
            "city_ascii": "Amasya",
            "lat": 40.6537,
            "lng": 35.833,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Amasya",
            "capital": "admin",
            "population": 82896,
            "id": 1792344167
        },
        {
            "city": "Mu\u015f",
            "city_ascii": "Mus",
            "lat": 38.749,
            "lng": 41.4969,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Mu\u015f",
            "capital": "admin",
            "population": 82536,
            "id": 1792530937
        },
        {
            "city": "Kaspiysk",
            "city_ascii": "Kaspiysk",
            "lat": 42.8747,
            "lng": 47.6244,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Dagestan",
            "capital": "",
            "population": 81752,
            "id": 1643020514
        },
        {
            "city": "Sokhumi",
            "city_ascii": "Sokhumi",
            "lat": 43.02,
            "lng": 41.02,
            "country": "Georgia",
            "iso2": "GE",
            "iso3": "GEO",
            "admin_name": "Abkhazia",
            "capital": "admin",
            "population": 81546,
            "id": 1268394475
        },
        {
            "city": "Bing\u00f6l",
            "city_ascii": "Bingol",
            "lat": 38.885,
            "lng": 40.498,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Bing\u00f6l",
            "capital": "admin",
            "population": 80568,
            "id": 1792920183
        },
        {
            "city": "Kars",
            "city_ascii": "Kars",
            "lat": 40.6085,
            "lng": 43.0975,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Kars",
            "capital": "admin",
            "population": 77486,
            "id": 1792000464
        },
        {
            "city": "Buynaksk",
            "city_ascii": "Buynaksk",
            "lat": 42.8335,
            "lng": 47.113,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Dagestan",
            "capital": "minor",
            "population": 75800,
            "id": 1643980922
        },
        {
            "city": "Georgiyevsk",
            "city_ascii": "Georgiyevsk",
            "lat": 44.1599,
            "lng": 43.4699,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Stavropol\u2019skiy Kray",
            "capital": "",
            "population": 72649,
            "id": 1643279802
        },
        {
            "city": "\u015eirvan",
            "city_ascii": "Sirvan",
            "lat": 39.9323,
            "lng": 48.9203,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "\u015eirvan",
            "capital": "",
            "population": 70684,
            "id": 1031478213
        },
        {
            "city": "\u015e\u0259ki",
            "city_ascii": "Saki",
            "lat": 41.1923,
            "lng": 47.1705,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "\u015e\u0259ki",
            "capital": "admin",
            "population": 64968,
            "id": 1031619846
        },
        {
            "city": "Bitlis",
            "city_ascii": "Bitlis",
            "lat": 38.394,
            "lng": 42.123,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Bitlis",
            "capital": "admin",
            "population": 62811,
            "id": 1792490436
        },
        {
            "city": "L\u0259nk\u0259ran",
            "city_ascii": "Lankaran",
            "lat": 38.754,
            "lng": 48.8511,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "L\u0259nk\u0259ran",
            "capital": "admin",
            "population": 60180,
            "id": 1031218031
        },
        {
            "city": "Yevlax",
            "city_ascii": "Yevlax",
            "lat": 40.6172,
            "lng": 47.15,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "Yevlax",
            "capital": "admin",
            "population": 53716,
            "id": 1031581655
        },
        {
            "city": "G\u00f6y\u00e7ay",
            "city_ascii": "Goycay",
            "lat": 40.6534,
            "lng": 47.7406,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "G\u00f6y\u00e7ay",
            "capital": "admin",
            "population": 35348,
            "id": 1031227222
        },
        {
            "city": "Sinop",
            "city_ascii": "Sinop",
            "lat": 42.023,
            "lng": 35.153,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Sinop",
            "capital": "admin",
            "population": 34834,
            "id": 1792497865
        },
        {
            "city": "Artvin",
            "city_ascii": "Artvin",
            "lat": 41.183,
            "lng": 41.818,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Artvin",
            "capital": "admin",
            "population": 32272,
            "id": 1792320984
        },
        {
            "city": "G\u00fcm\u00fc\u015fhane",
            "city_ascii": "Gumushane",
            "lat": 40.464,
            "lng": 39.484,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "G\u00fcm\u00fc\u015fhane",
            "capital": "admin",
            "population": 32250,
            "id": 1792559945
        },
        {
            "city": "Tunceli",
            "city_ascii": "Tunceli",
            "lat": 39.1167,
            "lng": 39.5333,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Tunceli",
            "capital": "admin",
            "population": 29062,
            "id": 1792507574
        },
        {
            "city": "Gavarr",
            "city_ascii": "Gavarr",
            "lat": 40.3589,
            "lng": 45.1267,
            "country": "Armenia",
            "iso2": "AM",
            "iso3": "ARM",
            "admin_name": "Geghark\u2019unik\u2019",
            "capital": "admin",
            "population": 21680,
            "id": 1051983153
        },
        {
            "city": "Artashat",
            "city_ascii": "Artashat",
            "lat": 39.9539,
            "lng": 44.5506,
            "country": "Armenia",
            "iso2": "AM",
            "iso3": "ARM",
            "admin_name": "Ararat",
            "capital": "admin",
            "population": 20562,
            "id": 1051969157
        },
        {
            "city": "Ashtarak",
            "city_ascii": "Ashtarak",
            "lat": 40.3017,
            "lng": 44.3592,
            "country": "Armenia",
            "iso2": "AM",
            "iso3": "ARM",
            "admin_name": "Aragatsotn",
            "capital": "admin",
            "population": 18779,
            "id": 1051714712
        },
        {
            "city": "Tovuz",
            "city_ascii": "Tovuz",
            "lat": 40.9922,
            "lng": 45.6289,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "Tovuz",
            "capital": "admin",
            "population": 12626,
            "id": 1031405942
        },
        {
            "city": "G\u0259d\u0259b\u0259y",
            "city_ascii": "Gadabay",
            "lat": 40.5656,
            "lng": 45.8161,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "G\u0259d\u0259b\u0259y",
            "capital": "admin",
            "population": 8657,
            "id": 1031444480
        },
        {
            "city": "Yeghegnadzor",
            "city_ascii": "Yeghegnadzor",
            "lat": 39.7611,
            "lng": 45.3333,
            "country": "Armenia",
            "iso2": "AM",
            "iso3": "ARM",
            "admin_name": "Vayots\u2019 Dzor",
            "capital": "admin",
            "population": 8200,
            "id": 1051234787
        },
        {
            "city": "Goranboy",
            "city_ascii": "Goranboy",
            "lat": 40.6103,
            "lng": 46.7897,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "Goranboy",
            "capital": "admin",
            "population": 7333,
            "id": 1031383465
        },
        {
            "city": "O\u011fuz",
            "city_ascii": "Oguz",
            "lat": 41.0708,
            "lng": 47.4583,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "O\u011fuz",
            "capital": "admin",
            "population": 6876,
            "id": 1031370337
        },
        {
            "city": "Tuapse",
            "city_ascii": "Tuapse",
            "lat": 44.1148,
            "lng": 39.0644,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Krasnodarskiy Kray",
            "capital": "minor",
            "population": 99145,
            "id": 1643910130
        },
        {
            "city": "Bafra",
            "city_ascii": "Bafra",
            "lat": 41.5682,
            "lng": 35.9069,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Samsun",
            "capital": "minor",
            "population": 97452,
            "id": 1792560571
        },
        {
            "city": "Nazran\u2019",
            "city_ascii": "Nazran'",
            "lat": 43.233,
            "lng": 44.783,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Ingushetiya",
            "capital": "",
            "population": 93357,
            "id": 1643123780
        },
        {
            "city": "Tatvan",
            "city_ascii": "Tatvan",
            "lat": 38.5066,
            "lng": 42.2816,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Bitlis",
            "capital": "minor",
            "population": 73222,
            "id": 1792530559
        },
        {
            "city": "Labinsk",
            "city_ascii": "Labinsk",
            "lat": 44.6348,
            "lng": 40.7443,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Krasnodarskiy Kray",
            "capital": "minor",
            "population": 61945,
            "id": 1643209545
        },
        {
            "city": "Xank\u0259ndi",
            "city_ascii": "Xankandi",
            "lat": 39.8156,
            "lng": 46.752,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "Xank\u0259ndi",
            "capital": "",
            "population": 57473,
            "id": 1031053512
        },
        {
            "city": "Gelendzhik",
            "city_ascii": "Gelendzhik",
            "lat": 44.5748,
            "lng": 38.0644,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Krasnodarskiy Kray",
            "capital": "",
            "population": 55508,
            "id": 1643756962
        },
        {
            "city": "P\u2019ot\u2019i",
            "city_ascii": "P'ot'i",
            "lat": 42.1557,
            "lng": 41.6716,
            "country": "Georgia",
            "iso2": "GE",
            "iso3": "GEO",
            "admin_name": "",
            "capital": "",
            "population": 47149,
            "id": 1268764439
        },
        {
            "city": "Apsheronsk",
            "city_ascii": "Apsheronsk",
            "lat": 44.4687,
            "lng": 39.7287,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Krasnodarskiy Kray",
            "capital": "minor",
            "population": 45876,
            "id": 1643014988
        },
        {
            "city": "Mozdok",
            "city_ascii": "Mozdok",
            "lat": 43.7543,
            "lng": 44.6544,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "North Ossetia",
            "capital": "",
            "population": 45702,
            "id": 1643138287
        },
        {
            "city": "Q\u0259zyan",
            "city_ascii": "Qazyan",
            "lat": 39.2015,
            "lng": 46.415,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "Qubadl\u0131",
            "capital": "",
            "population": 42288,
            "id": 1031867232
        },
        {
            "city": "Zelenokumsk",
            "city_ascii": "Zelenokumsk",
            "lat": 44.4091,
            "lng": 43.8787,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Stavropol\u2019skiy Kray",
            "capital": "",
            "population": 41306,
            "id": 1643031364
        },
        {
            "city": "Ts\u2019khinvali",
            "city_ascii": "Ts'khinvali",
            "lat": 42.2325,
            "lng": 43.975,
            "country": "Georgia",
            "iso2": "GE",
            "iso3": "GEO",
            "admin_name": "",
            "capital": "",
            "population": 38502,
            "id": 1268142653
        },
        {
            "city": "Ijevan",
            "city_ascii": "Ijevan",
            "lat": 40.8756,
            "lng": 45.1492,
            "country": "Armenia",
            "iso2": "AM",
            "iso3": "ARM",
            "admin_name": "Tavush",
            "capital": "",
            "population": 14737,
            "id": 1051564822
        },
        {
            "city": "Qazmalar",
            "city_ascii": "Qazmalar",
            "lat": 40.9814,
            "lng": 47.8458,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "",
            "capital": "",
            "population": 11867,
            "id": 1031242200
        }
    ]
}