module.exports = { CITIES: [
  {
    "city": "Bangui",
    "city_ascii": "Bangui",
    "lat": 4.3666,
    "lng": 18.5583,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Bangui",
    "capital": "primary",
    "population": 831925,
    "id": 1140080881
  },
  {
    "city": "Mba\u00efki",
    "city_ascii": "Mbaiki",
    "lat": 3.8704,
    "lng": 18,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Lobaye",
    "capital": "admin",
    "population": 67132,
    "id": 1140040245
  },
  {
    "city": "Bossangoa",
    "city_ascii": "Bossangoa",
    "lat": 6.4837,
    "lng": 17.45,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Ouham",
    "capital": "admin",
    "population": 63064,
    "id": 1140523604
  },
  {
    "city": "Bambari",
    "city_ascii": "Bambari",
    "lat": 5.762,
    "lng": 20.6672,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Ouaka",
    "capital": "admin",
    "population": 62098,
    "id": 1140304277
  },
  {
    "city": "Berb\u00e9rati",
    "city_ascii": "Berberati",
    "lat": 4.25,
    "lng": 15.78,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Mamb\u00e9r\u00e9-Kad\u00e9\u00ef",
    "capital": "admin",
    "population": 61815,
    "id": 1140239733
  },
  {
    "city": "Kaga Bandoro",
    "city_ascii": "Kaga Bandoro",
    "lat": 6.9804,
    "lng": 19.18,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Nana-Gr\u00e9bizi",
    "capital": "admin",
    "population": 56520,
    "id": 1140658026
  },
  {
    "city": "Bozoum",
    "city_ascii": "Bozoum",
    "lat": 6.317,
    "lng": 16.3833,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Ouham-Pend\u00e9",
    "capital": "admin",
    "population": 40201,
    "id": 1140416562
  },
  {
    "city": "Bouar",
    "city_ascii": "Bouar",
    "lat": 5.95,
    "lng": 15.6,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Nana-Mamb\u00e9r\u00e9",
    "capital": "admin",
    "population": 34372,
    "id": 1140144321
  },
  {
    "city": "Sibut",
    "city_ascii": "Sibut",
    "lat": 5.7338,
    "lng": 19.0833,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "K\u00e9mo",
    "capital": "admin",
    "population": 34267,
    "id": 1140802055
  },
  {
    "city": "Bangassou",
    "city_ascii": "Bangassou",
    "lat": 4.7338,
    "lng": 22.8166,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Mbomou",
    "capital": "admin",
    "population": 32841,
    "id": 1140539356
  },
  {
    "city": "Bria",
    "city_ascii": "Bria",
    "lat": 6.5333,
    "lng": 21.9833,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Haute-Kotto",
    "capital": "admin",
    "population": 29027,
    "id": 1140582053
  },
  {
    "city": "Nola",
    "city_ascii": "Nola",
    "lat": 3.5337,
    "lng": 16.0666,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Sangha-Mba\u00e9r\u00e9",
    "capital": "admin",
    "population": 26809,
    "id": 1140236347
  },
  {
    "city": "Mobaye",
    "city_ascii": "Mobaye",
    "lat": 4.32,
    "lng": 21.18,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Basse-Kotto",
    "capital": "admin",
    "population": 19431,
    "id": 1140935252
  },
  {
    "city": "Obo",
    "city_ascii": "Obo",
    "lat": 5.4,
    "lng": 26.5,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Haut-Mbomou",
    "capital": "admin",
    "population": 12887,
    "id": 1140533897
  },
  {
    "city": "Nd\u00e9l\u00e9",
    "city_ascii": "Ndele",
    "lat": 8.4091,
    "lng": 20.653,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Bamingui-Bangoran",
    "capital": "admin",
    "population": 11764,
    "id": 1140271951
  },
  {
    "city": "Birao",
    "city_ascii": "Birao",
    "lat": 10.2837,
    "lng": 22.7833,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Vakaga",
    "capital": "admin",
    "population": 10178,
    "id": 1140392673
  },
  {
    "city": "Bimbo",
    "city_ascii": "Bimbo",
    "lat": 4.329,
    "lng": 18.5284,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Ombella-Mpoko",
    "capital": "admin",
    "population": "",
    "id": 1140257478
  },
  {
    "city": "Carnot",
    "city_ascii": "Carnot",
    "lat": 4.9337,
    "lng": 15.8666,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "",
    "capital": "",
    "population": 38071,
    "id": 1140319605
  },
  {
    "city": "Zemio",
    "city_ascii": "Zemio",
    "lat": 5.0337,
    "lng": 25.1333,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "",
    "capital": "",
    "population": 20000,
    "id": 1140178462
  },
  {
    "city": "Bossembele",
    "city_ascii": "Bossembele",
    "lat": 5.267,
    "lng": 17.65,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Ombella-Mpoko",
    "capital": "",
    "population": 7287,
    "id": 1140955210
  },
  {
    "city": "Ouadda",
    "city_ascii": "Ouadda",
    "lat": 8.0671,
    "lng": 22.4,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "Haute-Kotto",
    "capital": "",
    "population": 5434,
    "id": 1140640564
  },
  {
    "city": "Yakossi",
    "city_ascii": "Yakossi",
    "lat": 5.617,
    "lng": 23.3167,
    "country": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "admin_name": "",
    "capital": "",
    "population": 500,
    "id": 1140246753
  }
]}