module.exports = {
    CITIES: [{
            "city": "N\u2019Djamena",
            "city_ascii": "N'Djamena",
            "lat": 12.1131,
            "lng": 15.0491,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Ville de N\u2019Djam\u00e9na",
            "capital": "primary",
            "population": 989000,
            "id": 1148708596
        },
        {
            "city": "Bongor",
            "city_ascii": "Bongor",
            "lat": 10.2859,
            "lng": 15.3872,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Mayo-K\u00e9bbi Est",
            "capital": "admin",
            "population": 193941,
            "id": 1148833900
        },
        {
            "city": "Sarh",
            "city_ascii": "Sarh",
            "lat": 9.15,
            "lng": 18.39,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Moyen-Chari",
            "capital": "admin",
            "population": 169196,
            "id": 1148442794
        },
        {
            "city": "Ab\u00e9ch\u00e9",
            "city_ascii": "Abeche",
            "lat": 13.84,
            "lng": 20.83,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Ouadda\u00ef",
            "capital": "admin",
            "population": 158317,
            "id": 1148461151
        },
        {
            "city": "Moundou",
            "city_ascii": "Moundou",
            "lat": 8.55,
            "lng": 16.09,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Logone Occidental",
            "capital": "admin",
            "population": 156705,
            "id": 1148369114
        },
        {
            "city": "Am Timan",
            "city_ascii": "Am Timan",
            "lat": 11.0333,
            "lng": 20.2833,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Salamat",
            "capital": "admin",
            "population": 30443,
            "id": 1148823427
        },
        {
            "city": "Doba",
            "city_ascii": "Doba",
            "lat": 8.6504,
            "lng": 16.85,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Logone Oriental",
            "capital": "admin",
            "population": 29597,
            "id": 1148367091
        },
        {
            "city": "Mongo",
            "city_ascii": "Mongo",
            "lat": 12.1837,
            "lng": 18.7,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Gu\u00e9ra",
            "capital": "admin",
            "population": 27763,
            "id": 1148891648
        },
        {
            "city": "Ati",
            "city_ascii": "Ati",
            "lat": 13.2171,
            "lng": 18.3333,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Batha",
            "capital": "admin",
            "population": 25373,
            "id": 1148642108
        },
        {
            "city": "La\u00ef",
            "city_ascii": "Lai",
            "lat": 9.395,
            "lng": 16.305,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Tandjil\u00e9",
            "capital": "admin",
            "population": 19382,
            "id": 1148360693
        },
        {
            "city": "Mao",
            "city_ascii": "Mao",
            "lat": 14.1194,
            "lng": 15.3133,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Kanem",
            "capital": "admin",
            "population": 18031,
            "id": 1148740154
        },
        {
            "city": "Faya",
            "city_ascii": "Faya",
            "lat": 17.9167,
            "lng": 19.1167,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Borkou",
            "capital": "admin",
            "population": 13400,
            "id": 1148095016
        },
        {
            "city": "Biltine",
            "city_ascii": "Biltine",
            "lat": 14.5333,
            "lng": 20.9167,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Wadi Fira",
            "capital": "admin",
            "population": 11000,
            "id": 1148086843
        },
        {
            "city": "Bol",
            "city_ascii": "Bol",
            "lat": 13.459,
            "lng": 14.7147,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Lac",
            "capital": "admin",
            "population": 3303,
            "id": 1148232209
        },
        {
            "city": "Fada",
            "city_ascii": "Fada",
            "lat": 17.1847,
            "lng": 21.5902,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Ennedi-Ouest",
            "capital": "admin",
            "population": 448,
            "id": 1148787282
        },
        {
            "city": "Pala",
            "city_ascii": "Pala",
            "lat": 9.3642,
            "lng": 14.9046,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Mayo-K\u00e9bbi Ouest",
            "capital": "admin",
            "population": "",
            "id": 1148687410
        },
        {
            "city": "Koumra",
            "city_ascii": "Koumra",
            "lat": 8.9126,
            "lng": 17.5539,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Mandoul",
            "capital": "admin",
            "population": "",
            "id": 1148599298
        },
        {
            "city": "Massakory",
            "city_ascii": "Massakory",
            "lat": 12.996,
            "lng": 15.7293,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Hadjer-Lamis",
            "capital": "admin",
            "population": "",
            "id": 1148908311
        },
        {
            "city": "Goz Be\u00efda",
            "city_ascii": "Goz Beida",
            "lat": 12.2248,
            "lng": 21.4103,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Sila",
            "capital": "admin",
            "population": "",
            "id": 1148101824
        },
        {
            "city": "Moussoro",
            "city_ascii": "Moussoro",
            "lat": 13.6414,
            "lng": 16.4894,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Barh el Gazel",
            "capital": "admin",
            "population": "",
            "id": 1148918270
        },
        {
            "city": "Massenya",
            "city_ascii": "Massenya",
            "lat": 11.4039,
            "lng": 16.1705,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Chari-Baguirmi",
            "capital": "admin",
            "population": "",
            "id": 1148928302
        },
        {
            "city": "Am Djarass",
            "city_ascii": "Am Djarass",
            "lat": 16.0659,
            "lng": 22.8431,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Ennedi-Est",
            "capital": "admin",
            "population": "",
            "id": 1148268495
        },
        {
            "city": "Barda\u00ef",
            "city_ascii": "Bardai",
            "lat": 21.3549,
            "lng": 17.0012,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Tibesti",
            "capital": "admin",
            "population": "",
            "id": 1148071351
        },
        {
            "city": "Kelo",
            "city_ascii": "Kelo",
            "lat": 9.3171,
            "lng": 15.8,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Tandjil\u00e9",
            "capital": "",
            "population": 96224,
            "id": 1148149571
        },
        {
            "city": "Pala Oua",
            "city_ascii": "Pala Oua",
            "lat": 9.3504,
            "lng": 14.9666,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Mayo-K\u00e9bbi Ouest",
            "capital": "",
            "population": 35466,
            "id": 1148631807
        },
        {
            "city": "Oum Hadjer",
            "city_ascii": "Oum Hadjer",
            "lat": 13.3004,
            "lng": 19.6833,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Batha",
            "capital": "",
            "population": 19271,
            "id": 1148641107
        },
        {
            "city": "Zouar",
            "city_ascii": "Zouar",
            "lat": 20.4587,
            "lng": 16.5278,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Tibesti",
            "capital": "",
            "population": 204,
            "id": 1148690803
        }
    ]
}