module.exports = {
    CITIES: [{
            "city": "Shanghai",
            "city_ascii": "Shanghai",
            "lat": 31.2165,
            "lng": 121.4365,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shanghai",
            "capital": "admin",
            "population": 14987000,
            "id": 1156073548
        },
        {
            "city": "Beijing",
            "city_ascii": "Beijing",
            "lat": 39.9289,
            "lng": 116.3883,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Beijing",
            "capital": "primary",
            "population": 11106000,
            "id": 1156228865
        },
        {
            "city": "Guangzhou",
            "city_ascii": "Guangzhou",
            "lat": 23.145,
            "lng": 113.325,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "admin",
            "population": 8829000,
            "id": 1156237133
        },
        {
            "city": "Shenzhen",
            "city_ascii": "Shenzhen",
            "lat": 22.5524,
            "lng": 114.1221,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "minor",
            "population": 7581000,
            "id": 1156158707
        },
        {
            "city": "Wuhan",
            "city_ascii": "Wuhan",
            "lat": 30.58,
            "lng": 114.27,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hubei",
            "capital": "admin",
            "population": 7243000,
            "id": 1156117184
        },
        {
            "city": "Tianjin",
            "city_ascii": "Tianjin",
            "lat": 39.13,
            "lng": 117.2,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Tianjin",
            "capital": "admin",
            "population": 7180000,
            "id": 1156174046
        },
        {
            "city": "Chongqing",
            "city_ascii": "Chongqing",
            "lat": 29.565,
            "lng": 106.595,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Chongqing",
            "capital": "admin",
            "population": 6461000,
            "id": 1156936556
        },
        {
            "city": "Shenyang",
            "city_ascii": "Shenyang",
            "lat": 41.805,
            "lng": 123.45,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "admin",
            "population": 4787000,
            "id": 1156309382
        },
        {
            "city": "Dongguan",
            "city_ascii": "Dongguan",
            "lat": 23.0489,
            "lng": 113.7447,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "minor",
            "population": 4528000,
            "id": 1156478242
        },
        {
            "city": "Chengdu",
            "city_ascii": "Chengdu",
            "lat": 30.67,
            "lng": 104.07,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "admin",
            "population": 4123000,
            "id": 1156421555
        },
        {
            "city": "Xi\u2019an",
            "city_ascii": "Xi'an",
            "lat": 34.275,
            "lng": 108.895,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shaanxi",
            "capital": "admin",
            "population": 4009000,
            "id": 1156244079
        },
        {
            "city": "Hechi",
            "city_ascii": "Hechi",
            "lat": 23.0965,
            "lng": 109.6091,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangxi",
            "capital": "",
            "population": 3830000,
            "id": 1156868701
        },
        {
            "city": "Nanjing",
            "city_ascii": "Nanjing",
            "lat": 32.05,
            "lng": 118.78,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "admin",
            "population": 3679000,
            "id": 1156644065
        },
        {
            "city": "Guiyang",
            "city_ascii": "Guiyang",
            "lat": 26.58,
            "lng": 106.72,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guizhou",
            "capital": "admin",
            "population": 3662000,
            "id": 1156932620
        },
        {
            "city": "Harbin",
            "city_ascii": "Harbin",
            "lat": 45.75,
            "lng": 126.65,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Heilongjiang",
            "capital": "admin",
            "population": 3621000,
            "id": 1156241528
        },
        {
            "city": "Zhangzhou",
            "city_ascii": "Zhangzhou",
            "lat": 24.5204,
            "lng": 117.67,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Fujian",
            "capital": "minor",
            "population": 3531147,
            "id": 1156241637
        },
        {
            "city": "Changchun",
            "city_ascii": "Changchun",
            "lat": 43.865,
            "lng": 125.34,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jilin",
            "capital": "admin",
            "population": 3183000,
            "id": 1156078103
        },
        {
            "city": "Dalian",
            "city_ascii": "Dalian",
            "lat": 38.9228,
            "lng": 121.6298,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "",
            "population": 3167000,
            "id": 1156175472
        },
        {
            "city": "Zibo",
            "city_ascii": "Zibo",
            "lat": 36.8,
            "lng": 118.05,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "",
            "population": 3061000,
            "id": 1156381094
        },
        {
            "city": "Hangzhou",
            "city_ascii": "Hangzhou",
            "lat": 30.25,
            "lng": 120.17,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Zhejiang",
            "capital": "admin",
            "population": 3007000,
            "id": 1156275243
        },
        {
            "city": "Kunming",
            "city_ascii": "Kunming",
            "lat": 25.07,
            "lng": 102.68,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Yunnan",
            "capital": "admin",
            "population": 2931000,
            "id": 1156477539
        },
        {
            "city": "Taiyuan",
            "city_ascii": "Taiyuan",
            "lat": 37.875,
            "lng": 112.5451,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shanxi",
            "capital": "admin",
            "population": 2913000,
            "id": 1156632014
        },
        {
            "city": "Qingdao",
            "city_ascii": "Qingdao",
            "lat": 36.09,
            "lng": 120.33,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "minor",
            "population": 2866000,
            "id": 1156112588
        },
        {
            "city": "Jinan",
            "city_ascii": "Jinan",
            "lat": 36.675,
            "lng": 116.995,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "admin",
            "population": 2798000,
            "id": 1156972469
        },
        {
            "city": "Zhengzhou",
            "city_ascii": "Zhengzhou",
            "lat": 34.755,
            "lng": 113.6651,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "admin",
            "population": 2636000,
            "id": 1156183137
        },
        {
            "city": "Fuzhou",
            "city_ascii": "Fuzhou",
            "lat": 26.08,
            "lng": 119.3,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Fujian",
            "capital": "admin",
            "population": 2606000,
            "id": 1156188037
        },
        {
            "city": "Changsha",
            "city_ascii": "Changsha",
            "lat": 28.2,
            "lng": 112.97,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hunan",
            "capital": "admin",
            "population": 2604000,
            "id": 1156961497
        },
        {
            "city": "Xiangtan",
            "city_ascii": "Xiangtan",
            "lat": 27.8504,
            "lng": 112.9,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hunan",
            "capital": "",
            "population": 2586948,
            "id": 1156195684
        },
        {
            "city": "Lanzhou",
            "city_ascii": "Lanzhou",
            "lat": 36.056,
            "lng": 103.792,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Gansu",
            "capital": "admin",
            "population": 2561000,
            "id": 1156280566
        },
        {
            "city": "Xiamen",
            "city_ascii": "Xiamen",
            "lat": 24.45,
            "lng": 118.08,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Fujian",
            "capital": "minor",
            "population": 2519000,
            "id": 1156212809
        },
        {
            "city": "Lianshan",
            "city_ascii": "Lianshan",
            "lat": 40.7503,
            "lng": 120.83,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "minor",
            "population": 2426000,
            "id": 1156046704
        },
        {
            "city": "Shijiazhuang",
            "city_ascii": "Shijiazhuang",
            "lat": 38.05,
            "lng": 114.48,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hebei",
            "capital": "admin",
            "population": 2417000,
            "id": 1156217541
        },
        {
            "city": "Jilin",
            "city_ascii": "Jilin",
            "lat": 43.85,
            "lng": 126.55,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jilin",
            "capital": "",
            "population": 2396000,
            "id": 1156646448
        },
        {
            "city": "Nanchang",
            "city_ascii": "Nanchang",
            "lat": 28.68,
            "lng": 115.88,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangxi",
            "capital": "admin",
            "population": 2350000,
            "id": 1156198892
        },
        {
            "city": "Wenzhou",
            "city_ascii": "Wenzhou",
            "lat": 28.02,
            "lng": 120.6501,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Zhejiang",
            "capital": "",
            "population": 2350000,
            "id": 1156188829
        },
        {
            "city": "Gaoping",
            "city_ascii": "Gaoping",
            "lat": 30.7804,
            "lng": 106.13,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "minor",
            "population": 2174000,
            "id": 1156522457
        },
        {
            "city": "Nanning",
            "city_ascii": "Nanning",
            "lat": 22.82,
            "lng": 108.32,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangxi",
            "capital": "admin",
            "population": 2167000,
            "id": 1156605439
        },
        {
            "city": "\u00dcr\u00fcmqi",
            "city_ascii": "Urumqi",
            "lat": 43.805,
            "lng": 87.575,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Xinjiang",
            "capital": "admin",
            "population": 2151000,
            "id": 1156051276
        },
        {
            "city": "Zaozhuang",
            "city_ascii": "Zaozhuang",
            "lat": 34.88,
            "lng": 117.57,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "",
            "population": 2145000,
            "id": 1156796454
        },
        {
            "city": "Yantai",
            "city_ascii": "Yantai",
            "lat": 37.5304,
            "lng": 121.4,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "",
            "population": 2116000,
            "id": 1156932948
        },
        {
            "city": "Tongshan",
            "city_ascii": "Tongshan",
            "lat": 34.28,
            "lng": 117.18,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "minor",
            "population": 2091000,
            "id": 1156241678
        },
        {
            "city": "Linyi",
            "city_ascii": "Linyi",
            "lat": 35.08,
            "lng": 118.33,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "",
            "population": 2082000,
            "id": 1156086320
        },
        {
            "city": "Haikou",
            "city_ascii": "Haikou",
            "lat": 20.05,
            "lng": 110.32,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hainan",
            "capital": "admin",
            "population": 2046189,
            "id": 1156183327
        },
        {
            "city": "Baotou",
            "city_ascii": "Baotou",
            "lat": 40.6522,
            "lng": 109.822,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Inner Mongolia",
            "capital": "",
            "population": 2036000,
            "id": 1156032751
        },
        {
            "city": "Hefei",
            "city_ascii": "Hefei",
            "lat": 31.85,
            "lng": 117.28,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "admin",
            "population": 2035000,
            "id": 1156332710
        },
        {
            "city": "Suzhou",
            "city_ascii": "Suzhou",
            "lat": 33.6361,
            "lng": 116.9789,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "",
            "population": 1964000,
            "id": 1156871297
        },
        {
            "city": "Nanyang",
            "city_ascii": "Nanyang",
            "lat": 33.0004,
            "lng": 112.53,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "",
            "population": 1944000,
            "id": 1156192287
        },
        {
            "city": "Ningbo",
            "city_ascii": "Ningbo",
            "lat": 29.88,
            "lng": 121.55,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Zhejiang",
            "capital": "minor",
            "population": 1923000,
            "id": 1156170787
        },
        {
            "city": "Tangshan",
            "city_ascii": "Tangshan",
            "lat": 39.6243,
            "lng": 118.1944,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hebei",
            "capital": "",
            "population": 1879000,
            "id": 1156904299
        },
        {
            "city": "Xiping",
            "city_ascii": "Xiping",
            "lat": 40.08,
            "lng": 113.3,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shanxi",
            "capital": "minor",
            "population": 1873000,
            "id": 1156898522
        },
        {
            "city": "Shuyangzha",
            "city_ascii": "Shuyangzha",
            "lat": 34.1299,
            "lng": 118.7734,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "",
            "population": 1770000,
            "id": 1156051957
        },
        {
            "city": "Shangqiu",
            "city_ascii": "Shangqiu",
            "lat": 34.4504,
            "lng": 115.65,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "",
            "population": 1753000,
            "id": 1156805441
        },
        {
            "city": "Wuxi",
            "city_ascii": "Wuxi",
            "lat": 31.58,
            "lng": 120.3,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "minor",
            "population": 1749000,
            "id": 1156019650
        },
        {
            "city": "Hohhot",
            "city_ascii": "Hohhot",
            "lat": 40.82,
            "lng": 111.66,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Inner Mongolia",
            "capital": "admin",
            "population": 1726000,
            "id": 1156210167
        },
        {
            "city": "Luoyang",
            "city_ascii": "Luoyang",
            "lat": 34.68,
            "lng": 112.4701,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "",
            "population": 1715000,
            "id": 1156069315
        },
        {
            "city": "Jingling",
            "city_ascii": "Jingling",
            "lat": 30.6501,
            "lng": 113.16,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hubei",
            "capital": "",
            "population": 1708000,
            "id": 1156060544
        },
        {
            "city": "Daqing",
            "city_ascii": "Daqing",
            "lat": 46.58,
            "lng": 125,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Heilongjiang",
            "capital": "",
            "population": 1693000,
            "id": 1156403962
        },
        {
            "city": "Lu\u2019an",
            "city_ascii": "Lu'an",
            "lat": 31.7503,
            "lng": 116.48,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "minor",
            "population": 1690000,
            "id": 1156499624
        },
        {
            "city": "Sanzhou",
            "city_ascii": "Sanzhou",
            "lat": 30.82,
            "lng": 108.4,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Chongqing",
            "capital": "",
            "population": 1680000,
            "id": 1156025536
        },
        {
            "city": "Suzhou",
            "city_ascii": "Suzhou",
            "lat": 31.3005,
            "lng": 120.62,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "minor",
            "population": 1650000,
            "id": 1156029196
        },
        {
            "city": "Qiqihar",
            "city_ascii": "Qiqihar",
            "lat": 47.345,
            "lng": 123.99,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Heilongjiang",
            "capital": "minor",
            "population": 1641000,
            "id": 1156775905
        },
        {
            "city": "Anshan",
            "city_ascii": "Anshan",
            "lat": 41.115,
            "lng": 122.94,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "",
            "population": 1639000,
            "id": 1156901825
        },
        {
            "city": "Handan",
            "city_ascii": "Handan",
            "lat": 36.58,
            "lng": 114.48,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hebei",
            "capital": "",
            "population": 1631000,
            "id": 1156957080
        },
        {
            "city": "Tai\u2019an",
            "city_ascii": "Tai'an",
            "lat": 36.2,
            "lng": 117.1201,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "",
            "population": 1629000,
            "id": 1156095188
        },
        {
            "city": "Shantou",
            "city_ascii": "Shantou",
            "lat": 23.37,
            "lng": 116.67,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "minor",
            "population": 1601000,
            "id": 1156457499
        },
        {
            "city": "Zhanjiang",
            "city_ascii": "Zhanjiang",
            "lat": 21.2,
            "lng": 110.38,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "minor",
            "population": 1590000,
            "id": 1156502170
        },
        {
            "city": "Xiantao",
            "city_ascii": "Xiantao",
            "lat": 30.3704,
            "lng": 113.44,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hubei",
            "capital": "",
            "population": 1556000,
            "id": 1156216927
        },
        {
            "city": "Weifang",
            "city_ascii": "Weifang",
            "lat": 36.7204,
            "lng": 119.1001,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "",
            "population": 1553000,
            "id": 1156912965
        },
        {
            "city": "Xinyang",
            "city_ascii": "Xinyang",
            "lat": 32.1304,
            "lng": 114.07,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "",
            "population": 1541000,
            "id": 1156273453
        },
        {
            "city": "Luzhou",
            "city_ascii": "Luzhou",
            "lat": 28.88,
            "lng": 105.38,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "minor",
            "population": 1537000,
            "id": 1156582079
        },
        {
            "city": "Ganzhou",
            "city_ascii": "Ganzhou",
            "lat": 25.92,
            "lng": 114.95,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangxi",
            "capital": "minor",
            "population": 1500000,
            "id": 1156832475
        },
        {
            "city": "Liuzhou",
            "city_ascii": "Liuzhou",
            "lat": 24.28,
            "lng": 109.25,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangxi",
            "capital": "minor",
            "population": 1497000,
            "id": 1156360785
        },
        {
            "city": "Fushun",
            "city_ascii": "Fushun",
            "lat": 41.8654,
            "lng": 123.87,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "",
            "population": 1470000,
            "id": 1156857743
        },
        {
            "city": "Changde",
            "city_ascii": "Changde",
            "lat": 29.03,
            "lng": 111.68,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hunan",
            "capital": "minor",
            "population": 1469000,
            "id": 1156449091
        },
        {
            "city": "Neijiang",
            "city_ascii": "Neijiang",
            "lat": 29.5804,
            "lng": 105.05,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "minor",
            "population": 1466000,
            "id": 1156516335
        },
        {
            "city": "Quanzhou",
            "city_ascii": "Quanzhou",
            "lat": 24.9,
            "lng": 118.58,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Fujian",
            "capital": "minor",
            "population": 1463000,
            "id": 1156829655
        },
        {
            "city": "Huainan",
            "city_ascii": "Huainan",
            "lat": 32.63,
            "lng": 116.98,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "",
            "population": 1451000,
            "id": 1156877299
        },
        {
            "city": "Suining",
            "city_ascii": "Suining",
            "lat": 30.5333,
            "lng": 105.5333,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "minor",
            "population": 1425000,
            "id": 1156655650
        },
        {
            "city": "Mianyang",
            "city_ascii": "Mianyang",
            "lat": 31.47,
            "lng": 104.77,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "minor",
            "population": 1396000,
            "id": 1156417758
        },
        {
            "city": "Ma\u2019anshan",
            "city_ascii": "Ma'anshan",
            "lat": 31.7304,
            "lng": 118.48,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "minor",
            "population": 1366302,
            "id": 1156847452
        },
        {
            "city": "Yiyang",
            "city_ascii": "Yiyang",
            "lat": 28.6004,
            "lng": 112.33,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hunan",
            "capital": "",
            "population": 1352000,
            "id": 1156218615
        },
        {
            "city": "Heze",
            "city_ascii": "Heze",
            "lat": 35.23,
            "lng": 115.45,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "minor",
            "population": 1338000,
            "id": 1156225008
        },
        {
            "city": "Changzhou",
            "city_ascii": "Changzhou",
            "lat": 31.78,
            "lng": 119.97,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "minor",
            "population": 1327000,
            "id": 1156185511
        },
        {
            "city": "Chifeng",
            "city_ascii": "Chifeng",
            "lat": 42.27,
            "lng": 118.95,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Inner Mongolia",
            "capital": "minor",
            "population": 1277000,
            "id": 1156277458
        },
        {
            "city": "Huaiyin",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/%E9%95%87%E6%B7%AE%E6%A5%BC.JPG/1280px-%E9%95%87%E6%B7%AE%E6%A5%BC.JPG",
            "city_ascii": "Huaiyin",
            "lat": 33.58,
            "lng": 119.03,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "",
            "population": 1264000,
            "id": 1156662372
        },
        {
            "city": "Mudanjiang",
            "city_ascii": "Mudanjiang",
            "lat": 44.575,
            "lng": 129.59,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Heilongjiang",
            "capital": "minor",
            "population": 1244000,
            "id": 1156249698
        },
        {
            "city": "Huzhou",
            "city_ascii": "Huzhou",
            "lat": 30.8704,
            "lng": 120.1,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Zhejiang",
            "capital": "minor",
            "population": 1231000,
            "id": 1156335543
        },
        {
            "city": "Beidao",
            "city_ascii": "Beidao",
            "lat": 34.6,
            "lng": 105.92,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Gansu",
            "capital": "minor",
            "population": 1225000,
            "id": 1156137209
        },
        {
            "city": "Liupanshui",
            "city_ascii": "Liupanshui",
            "lat": 26.5944,
            "lng": 104.8333,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guizhou",
            "capital": "",
            "population": 1221000,
            "id": 1156070389
        },
        {
            "city": "Gaozhou",
            "city_ascii": "Gaozhou",
            "lat": 21.9204,
            "lng": 110.87,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "",
            "population": 1217715,
            "id": 1156785303
        },
        {
            "city": "Jining",
            "city_ascii": "Jining",
            "lat": 35.4004,
            "lng": 116.55,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "",
            "population": 1186000,
            "id": 1156504601
        },
        {
            "city": "Leshan",
            "city_ascii": "Leshan",
            "lat": 29.5671,
            "lng": 103.7333,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "",
            "population": 1157000,
            "id": 1156203130
        },
        {
            "city": "Shangrao",
            "city_ascii": "Shangrao",
            "lat": 28.4704,
            "lng": 117.97,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangxi",
            "capital": "minor",
            "population": 1144577,
            "id": 1156405492
        },
        {
            "city": "Yulin",
            "city_ascii": "Yulin",
            "lat": 22.63,
            "lng": 110.15,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangxi",
            "capital": "",
            "population": 1127000,
            "id": 1156901312
        },
        {
            "city": "Xianyang",
            "city_ascii": "Xianyang",
            "lat": 34.3456,
            "lng": 108.7147,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shaanxi",
            "capital": "minor",
            "population": 1126000,
            "id": 1156120117
        },
        {
            "city": "Baoding",
            "city_ascii": "Baoding",
            "lat": 38.8704,
            "lng": 115.48,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hebei",
            "capital": "",
            "population": 1107000,
            "id": 1156256829
        },
        {
            "city": "Zigong",
            "city_ascii": "Zigong",
            "lat": 29.4,
            "lng": 104.78,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "",
            "population": 1105000,
            "id": 1156023354
        },
        {
            "city": "Ankang",
            "city_ascii": "Ankang",
            "lat": 32.68,
            "lng": 109.02,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shaanxi",
            "capital": "",
            "population": 1100000,
            "id": 1156255711
        },
        {
            "city": "Jinhua",
            "city_ascii": "Jinhua",
            "lat": 29.12,
            "lng": 119.65,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Zhejiang",
            "capital": "minor",
            "population": 1092852,
            "id": 1156547188
        },
        {
            "city": "Zhuzhou",
            "city_ascii": "Zhuzhou",
            "lat": 27.83,
            "lng": 113.15,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hunan",
            "capital": "minor",
            "population": 1080000,
            "id": 1156041962
        },
        {
            "city": "Xiangyang",
            "city_ascii": "Xiangyang",
            "lat": 32.02,
            "lng": 112.13,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hubei",
            "capital": "minor",
            "population": 1069000,
            "id": 1156107325
        },
        {
            "city": "Mizhou",
            "city_ascii": "Mizhou",
            "lat": 35.99,
            "lng": 119.3801,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "minor",
            "population": 1060000,
            "id": 1156935002
        },
        {
            "city": "Xining",
            "city_ascii": "Xining",
            "lat": 36.62,
            "lng": 101.77,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Qinghai",
            "capital": "admin",
            "population": 1048000,
            "id": 1156081448
        },
        {
            "city": "Zhangjiakou",
            "city_ascii": "Zhangjiakou",
            "lat": 40.83,
            "lng": 114.93,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hebei",
            "capital": "",
            "population": 1046000,
            "id": 1156800221
        },
        {
            "city": "Zhuhai",
            "city_ascii": "Zhuhai",
            "lat": 22.2769,
            "lng": 113.5678,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "minor",
            "population": 1023000,
            "id": 1156722242
        },
        {
            "city": "Jiamusi",
            "city_ascii": "Jiamusi",
            "lat": 46.83,
            "lng": 130.35,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Heilongjiang",
            "capital": "minor",
            "population": 1020000,
            "id": 1156350864
        },
        {
            "city": "Hengyang",
            "city_ascii": "Hengyang",
            "lat": 26.88,
            "lng": 112.59,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hunan",
            "capital": "",
            "population": 1016000,
            "id": 1156696884
        },
        {
            "city": "Benxi",
            "city_ascii": "Benxi",
            "lat": 41.3304,
            "lng": 123.75,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "",
            "population": 1012000,
            "id": 1156097909
        },
        {
            "city": "Qinhuangdao",
            "city_ascii": "Qinhuangdao",
            "lat": 39.9304,
            "lng": 119.62,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hebei",
            "capital": "",
            "population": 1003000,
            "id": 1156091093
        },
        {
            "city": "Yongzhou",
            "city_ascii": "Yongzhou",
            "lat": 26.2304,
            "lng": 111.62,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hunan",
            "capital": "",
            "population": 1000000,
            "id": 1156694479
        },
        {
            "city": "Baoshan",
            "city_ascii": "Baoshan",
            "lat": 25.12,
            "lng": 99.15,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Yunnan",
            "capital": "",
            "population": 1000000,
            "id": 1156546994
        },
        {
            "city": "Yinchuan",
            "city_ascii": "Yinchuan",
            "lat": 38.468,
            "lng": 106.273,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Ningxia",
            "capital": "admin",
            "population": 991000,
            "id": 1156359072
        },
        {
            "city": "Jiaxing",
            "city_ascii": "Jiaxing",
            "lat": 30.7704,
            "lng": 120.75,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Zhejiang",
            "capital": "minor",
            "population": 988000,
            "id": 1156491661
        },
        {
            "city": "Guilin",
            "city_ascii": "Guilin",
            "lat": 25.28,
            "lng": 110.28,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangxi",
            "capital": "minor",
            "population": 987000,
            "id": 1156235364
        },
        {
            "city": "Yichun",
            "city_ascii": "Yichun",
            "lat": 27.8333,
            "lng": 114.4,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangxi",
            "capital": "minor",
            "population": 982000,
            "id": 1156229590
        },
        {
            "city": "Yangquan",
            "city_ascii": "Yangquan",
            "lat": 37.87,
            "lng": 113.57,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shanxi",
            "capital": "minor",
            "population": 981448,
            "id": 1156157844
        },
        {
            "city": "Jixi",
            "city_ascii": "Jixi",
            "lat": 45.3,
            "lng": 130.97,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Heilongjiang",
            "capital": "minor",
            "population": 965000,
            "id": 1156393765
        },
        {
            "city": "Xin\u2019an",
            "city_ascii": "Xin'an",
            "lat": 34.38,
            "lng": 118.35,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "",
            "population": 962656,
            "id": 1156236053
        },
        {
            "city": "Pingxiang",
            "city_ascii": "Pingxiang",
            "lat": 27.62,
            "lng": 113.85,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangxi",
            "capital": "minor",
            "population": 961000,
            "id": 1156066465
        },
        {
            "city": "Jinzhou",
            "city_ascii": "Jinzhou",
            "lat": 41.1204,
            "lng": 121.1,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "",
            "population": 956000,
            "id": 1156157151
        },
        {
            "city": "Nantong",
            "city_ascii": "Nantong",
            "lat": 32.0304,
            "lng": 120.825,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "minor",
            "population": 947000,
            "id": 1156045365
        },
        {
            "city": "Foshan",
            "city_ascii": "Foshan",
            "lat": 23.0301,
            "lng": 113.12,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "minor",
            "population": 943000,
            "id": 1156738403
        },
        {
            "city": "Huaibei",
            "city_ascii": "Huaibei",
            "lat": 33.9504,
            "lng": 116.75,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "",
            "population": 913000,
            "id": 1156142626
        },
        {
            "city": "Xinyu",
            "city_ascii": "Xinyu",
            "lat": 27.8,
            "lng": 114.93,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangxi",
            "capital": "minor",
            "population": 913000,
            "id": 1156138735
        },
        {
            "city": "Nangandao",
            "city_ascii": "Nangandao",
            "lat": 35.3204,
            "lng": 113.87,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "minor",
            "population": 903000,
            "id": 1156127660
        },
        {
            "city": "Yibin",
            "city_ascii": "Yibin",
            "lat": 28.77,
            "lng": 104.57,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Sichuan",
            "capital": "minor",
            "population": 902000,
            "id": 1156107603
        },
        {
            "city": "Bengbu",
            "city_ascii": "Bengbu",
            "lat": 32.95,
            "lng": 117.33,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "",
            "population": 894000,
            "id": 1156440668
        },
        {
            "city": "Dengtalu",
            "city_ascii": "Dengtalu",
            "lat": 36.08,
            "lng": 114.35,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "minor",
            "population": 887000,
            "id": 1156202014
        },
        {
            "city": "Tongliao",
            "city_ascii": "Tongliao",
            "lat": 43.62,
            "lng": 122.27,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Inner Mongolia",
            "capital": "minor",
            "population": 884000,
            "id": 1156358686
        },
        {
            "city": "Xiaoxita",
            "city_ascii": "Xiaoxita",
            "lat": 30.7,
            "lng": 111.28,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hubei",
            "capital": "minor",
            "population": 875000,
            "id": 1156764447
        },
        {
            "city": "Yangjiang",
            "city_ascii": "Yangjiang",
            "lat": 21.8504,
            "lng": 111.97,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "minor",
            "population": 872363,
            "id": 1156123172
        },
        {
            "city": "Kaifeng Chengguanzhen",
            "city_ascii": "Kaifeng Chengguanzhen",
            "lat": 34.85,
            "lng": 114.35,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "minor",
            "population": 872000,
            "id": 1156686574
        },
        {
            "city": "Dandong",
            "city_ascii": "Dandong",
            "lat": 40.1436,
            "lng": 124.3936,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "",
            "population": 870000,
            "id": 1156178316
        },
        {
            "city": "Xuanzhou",
            "city_ascii": "Xuanzhou",
            "lat": 30.9525,
            "lng": 118.7553,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "",
            "population": 866000,
            "id": 1156424311
        },
        {
            "city": "Rizhao",
            "city_ascii": "Rizhao",
            "lat": 35.4304,
            "lng": 119.45,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "minor",
            "population": 865000,
            "id": 1156032841
        },
        {
            "city": "Jiaozuo",
            "city_ascii": "Jiaozuo",
            "lat": 35.25,
            "lng": 113.22,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "",
            "population": 857000,
            "id": 1156157854
        },
        {
            "city": "Zhenjiang",
            "city_ascii": "Zhenjiang",
            "lat": 32.22,
            "lng": 119.43,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "minor",
            "population": 854000,
            "id": 1156934125
        },
        {
            "city": "Pingdingshan",
            "city_ascii": "Pingdingshan",
            "lat": 33.7304,
            "lng": 113.3,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "",
            "population": 849000,
            "id": 1156735124
        },
        {
            "city": "Zunyi",
            "city_ascii": "Zunyi",
            "lat": 27.7,
            "lng": 106.92,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guizhou",
            "capital": "",
            "population": 849000,
            "id": 1156539782
        },
        {
            "city": "Anshun",
            "city_ascii": "Anshun",
            "lat": 26.2504,
            "lng": 105.93,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guizhou",
            "capital": "",
            "population": 849000,
            "id": 1156415948
        },
        {
            "city": "Yuci",
            "city_ascii": "Yuci",
            "lat": 37.6804,
            "lng": 112.73,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shanxi",
            "capital": "",
            "population": 840000,
            "id": 1156177817
        },
        {
            "city": "Yancheng",
            "city_ascii": "Yancheng",
            "lat": 33.3856,
            "lng": 120.1253,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "minor",
            "population": 839000,
            "id": 1156995410
        },
        {
            "city": "Linfen",
            "city_ascii": "Linfen",
            "lat": 36.0803,
            "lng": 111.52,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shanxi",
            "capital": "",
            "population": 834000,
            "id": 1156416074
        },
        {
            "city": "Rongjiawan",
            "city_ascii": "Rongjiawan",
            "lat": 29.3801,
            "lng": 113.1,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hunan",
            "capital": "minor",
            "population": 826000,
            "id": 1156795164
        },
        {
            "city": "Xingyi",
            "city_ascii": "Xingyi",
            "lat": 25.0904,
            "lng": 104.89,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guizhou",
            "capital": "",
            "population": 816000,
            "id": 1156255316
        },
        {
            "city": "Wuhu",
            "city_ascii": "Wuhu",
            "lat": 31.3504,
            "lng": 118.37,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "minor",
            "population": 810000,
            "id": 1156315512
        },
        {
            "city": "Langfang",
            "city_ascii": "Langfang",
            "lat": 39.5204,
            "lng": 116.68,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hebei",
            "capital": "",
            "population": 810000,
            "id": 1156109017
        },
        {
            "city": "Zhaotong",
            "city_ascii": "Zhaotong",
            "lat": 27.3204,
            "lng": 103.72,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Yunnan",
            "capital": "",
            "population": 809000,
            "id": 1156924687
        },
        {
            "city": "Lingyuan",
            "city_ascii": "Lingyuan",
            "lat": 41.24,
            "lng": 119.4011,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "",
            "population": 806000,
            "id": 1156184681
        },
        {
            "city": "Baojishi",
            "city_ascii": "Baojishi",
            "lat": 34.38,
            "lng": 107.15,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shaanxi",
            "capital": "",
            "population": 800000,
            "id": 1156101096
        },
        {
            "city": "Yingkou",
            "city_ascii": "Yingkou",
            "lat": 40.6703,
            "lng": 122.28,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "minor",
            "population": 795000,
            "id": 1156257074
        },
        {
            "city": "Liaoyang",
            "city_ascii": "Liaoyang",
            "lat": 41.28,
            "lng": 123.18,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "",
            "population": 794000,
            "id": 1156202749
        },
        {
            "city": "Shaoxing",
            "city_ascii": "Shaoxing",
            "lat": 30.0004,
            "lng": 120.57,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Zhejiang",
            "capital": "minor",
            "population": 777000,
            "id": 1156893449
        },
        {
            "city": "Yichun",
            "city_ascii": "Yichun",
            "lat": 47.6999,
            "lng": 128.9,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Heilongjiang",
            "capital": "minor",
            "population": 777000,
            "id": 1156757274
        },
        {
            "city": "Fuyang",
            "city_ascii": "Fuyang",
            "lat": 30.0533,
            "lng": 119.9519,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Zhejiang",
            "capital": "minor",
            "population": 771000,
            "id": 1156340393
        },
        {
            "city": "Fuxin",
            "city_ascii": "Fuxin",
            "lat": 42.0105,
            "lng": 121.66,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Liaoning",
            "capital": "",
            "population": 770000,
            "id": 1156141954
        },
        {
            "city": "Shiyan",
            "city_ascii": "Shiyan",
            "lat": 32.57,
            "lng": 110.78,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hubei",
            "capital": "minor",
            "population": 770000,
            "id": 1156383921
        },
        {
            "city": "Jincheng",
            "city_ascii": "Jincheng",
            "lat": 35.5004,
            "lng": 112.83,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shanxi",
            "capital": "minor",
            "population": 760000,
            "id": 1156163376
        },
        {
            "city": "Hegang",
            "city_ascii": "Hegang",
            "lat": 47.4,
            "lng": 130.37,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Heilongjiang",
            "capital": "minor",
            "population": 743307,
            "id": 1156541759
        },
        {
            "city": "Beihai",
            "city_ascii": "Beihai",
            "lat": 21.4804,
            "lng": 109.1,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangxi",
            "capital": "",
            "population": 728978,
            "id": 1156421449
        },
        {
            "city": "Shaoguan",
            "city_ascii": "Shaoguan",
            "lat": 24.8,
            "lng": 113.58,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "minor",
            "population": 720266,
            "id": 1156617066
        },
        {
            "city": "Xinpu",
            "city_ascii": "Xinpu",
            "lat": 34.6004,
            "lng": 119.17,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "minor",
            "population": 715600,
            "id": 1156035381
        },
        {
            "city": "Qingyuan",
            "city_ascii": "Qingyuan",
            "lat": 23.7004,
            "lng": 113.0301,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "minor",
            "population": 706717,
            "id": 1156135890
        },
        {
            "city": "Changzhi",
            "city_ascii": "Changzhi",
            "lat": 36.1839,
            "lng": 113.1053,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shanxi",
            "capital": "minor",
            "population": 706000,
            "id": 1156057944
        },
        {
            "city": "Huangshi",
            "city_ascii": "Huangshi",
            "lat": 30.22,
            "lng": 115.1,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hubei",
            "capital": "minor",
            "population": 688090,
            "id": 1156234290
        },
        {
            "city": "Puyang Chengguanzhen",
            "city_ascii": "Puyang Chengguanzhen",
            "lat": 35.7004,
            "lng": 114.98,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Henan",
            "capital": "minor",
            "population": 666322,
            "id": 1156103317
        },
        {
            "city": "Xiping",
            "city_ascii": "Xiping",
            "lat": 25.6005,
            "lng": 103.8166,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Yunnan",
            "capital": "minor",
            "population": 652604,
            "id": 1156207794
        },
        {
            "city": "Zhuozhou",
            "city_ascii": "Zhuozhou",
            "lat": 39.5401,
            "lng": 115.79,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hebei",
            "capital": "",
            "population": 628000,
            "id": 1156045160
        },
        {
            "city": "Changping",
            "city_ascii": "Changping",
            "lat": 40.2248,
            "lng": 116.1944,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Beijing",
            "capital": "",
            "population": 614821,
            "id": 1156166828
        },
        {
            "city": "Taizhou",
            "city_ascii": "Taizhou",
            "lat": 32.4904,
            "lng": 119.9,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "minor",
            "population": 612356,
            "id": 1156119229
        },
        {
            "city": "Xingtai",
            "city_ascii": "Xingtai",
            "lat": 37.05,
            "lng": 114.5,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hebei",
            "capital": "",
            "population": 611739,
            "id": 1156294952
        },
        {
            "city": "Anqing",
            "city_ascii": "Anqing",
            "lat": 30.5,
            "lng": 117.05,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "minor",
            "population": 580497,
            "id": 1156238875
        },
        {
            "city": "Shihezi",
            "city_ascii": "Shihezi",
            "lat": 44.3,
            "lng": 86.0299,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Xinjiang",
            "capital": "minor",
            "population": 573182,
            "id": 1156232270
        },
        {
            "city": "Shuozhou",
            "city_ascii": "Shuozhou",
            "lat": 39.3004,
            "lng": 112.42,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shanxi",
            "capital": "minor",
            "population": 570000,
            "id": 1156227167
        },
        {
            "city": "Wusong",
            "city_ascii": "Wusong",
            "lat": 30.9504,
            "lng": 117.78,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Anhui",
            "capital": "minor",
            "population": 562832,
            "id": 1156264408
        },
        {
            "city": "Weihai",
            "city_ascii": "Weihai",
            "lat": 37.5,
            "lng": 122.1,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Shandong",
            "capital": "minor",
            "population": 560255,
            "id": 1156473300
        },
        {
            "city": "Siping",
            "city_ascii": "Siping",
            "lat": 43.17,
            "lng": 124.33,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jilin",
            "capital": "",
            "population": 555609,
            "id": 1156063295
        },
        {
            "city": "Jiujiang",
            "city_ascii": "Jiujiang",
            "lat": 29.73,
            "lng": 115.98,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangxi",
            "capital": "minor",
            "population": 545616,
            "id": 1156206041
        },
        {
            "city": "Kashgar",
            "city_ascii": "Kashgar",
            "lat": 39.4763,
            "lng": 75.9699,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Xinjiang",
            "capital": "minor",
            "population": 543914,
            "id": 1156113193
        },
        {
            "city": "Yangzhou",
            "city_ascii": "Yangzhou",
            "lat": 32.4,
            "lng": 119.43,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangsu",
            "capital": "",
            "population": 539715,
            "id": 1156818601
        },
        {
            "city": "Linxia Chengguanzhen",
            "city_ascii": "Linxia Chengguanzhen",
            "lat": 35.6,
            "lng": 103.2,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Gansu",
            "capital": "minor",
            "population": 534555,
            "id": 1156043522
        },
        {
            "city": "Jiangmen",
            "city_ascii": "Jiangmen",
            "lat": 22.5804,
            "lng": 113.08,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Guangdong",
            "capital": "minor",
            "population": 532419,
            "id": 1156105613
        },
        {
            "city": "Cangzhou",
            "city_ascii": "Cangzhou",
            "lat": 38.3204,
            "lng": 116.87,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hebei",
            "capital": "",
            "population": 527681,
            "id": 1156698069
        },
        {
            "city": "Ji\u2019an",
            "city_ascii": "Ji'an",
            "lat": 27.1304,
            "lng": 115,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jiangxi",
            "capital": "minor",
            "population": 520248,
            "id": 1156278215
        },
        {
            "city": "Shashi",
            "city_ascii": "Shashi",
            "lat": 30.32,
            "lng": 112.23,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Hubei",
            "capital": "",
            "population": 520000,
            "id": 1156254380
        },
        {
            "city": "Liaoyuan",
            "city_ascii": "Liaoyuan",
            "lat": 42.9,
            "lng": 125.13,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Jilin",
            "capital": "",
            "population": 506548,
            "id": 1156249772
        },
        {
            "city": "Shuangyashan",
            "city_ascii": "Shuangyashan",
            "lat": 46.6704,
            "lng": 131.35,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Heilongjiang",
            "capital": "",
            "population": 500000,
            "id": 1156245904
        },
        {
            "city": "Lhasa",
            "city_ascii": "Lhasa",
            "lat": 29.645,
            "lng": 91.1,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Tibet",
            "capital": "admin",
            "population": 219599,
            "id": 1156369972
        }
    ]
}