module.exports = {
    CITIES: [{
            "city": "Kinshasa",
            "city_ascii": "Kinshasa",
            "lat": -4.3297,
            "lng": 15.315,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kinshasa",
            "capital": "primary",
            "population": 7843000,
            "id": 1180000363
        },
        {
            "city": "Lubumbashi",
            "city_ascii": "Lubumbashi",
            "lat": -11.68,
            "lng": 27.48,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Haut-Katanga",
            "capital": "admin",
            "population": 1352000,
            "id": 1180506234
        },
        {
            "city": "Mbuji-Mayi",
            "city_ascii": "Mbuji-Mayi",
            "lat": -6.15,
            "lng": 23.6,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kasa\u00ef Oriental",
            "capital": "admin",
            "population": 1295000,
            "id": 1180399586
        },
        {
            "city": "Kananga",
            "city_ascii": "Kananga",
            "lat": -5.89,
            "lng": 22.4,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kasa\u00ef Central",
            "capital": "admin",
            "population": 765000,
            "id": 1180172460
        },
        {
            "city": "Kikwit",
            "city_ascii": "Kikwit",
            "lat": -5.03,
            "lng": 18.85,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kwilu",
            "capital": "admin",
            "population": 637736,
            "id": 1180518247
        },
        {
            "city": "Kisangani",
            "city_ascii": "Kisangani",
            "lat": 0.52,
            "lng": 25.22,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Tshopo",
            "capital": "admin",
            "population": 578470,
            "id": 1180478201
        },
        {
            "city": "Bukavu",
            "city_ascii": "Bukavu",
            "lat": -2.51,
            "lng": 28.84,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Sud-Kivu",
            "capital": "admin",
            "population": 436779,
            "id": 1180475821
        },
        {
            "city": "Likasi",
            "city_ascii": "Likasi",
            "lat": -10.97,
            "lng": 26.78,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Haut-Katanga",
            "capital": "",
            "population": 434408,
            "id": 1180978192
        },
        {
            "city": "Kolwezi",
            "city_ascii": "Kolwezi",
            "lat": -10.7167,
            "lng": 25.4724,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Lualaba",
            "capital": "admin",
            "population": 418000,
            "id": 1180380965
        },
        {
            "city": "Beni",
            "city_ascii": "Beni",
            "lat": 0.4904,
            "lng": 29.45,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Nord-Kivu",
            "capital": "",
            "population": 332903,
            "id": 1180325051
        },
        {
            "city": "Butembo",
            "city_ascii": "Butembo",
            "lat": 0.13,
            "lng": 29.28,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Nord-Kivu",
            "capital": "",
            "population": 286403,
            "id": 1180446432
        },
        {
            "city": "Mbandaka",
            "city_ascii": "Mbandaka",
            "lat": 0.04,
            "lng": 18.26,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "\u00c9quateur",
            "capital": "admin",
            "population": 274996,
            "id": 1180720887
        },
        {
            "city": "Tshikapa",
            "city_ascii": "Tshikapa",
            "lat": -6.41,
            "lng": 20.77,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kasa\u00ef",
            "capital": "",
            "population": 267462,
            "id": 1180581239
        },
        {
            "city": "Kindu",
            "city_ascii": "Kindu",
            "lat": -2.9639,
            "lng": 25.91,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Maniema",
            "capital": "admin",
            "population": 262914,
            "id": 1180106925
        },
        {
            "city": "Matadi",
            "city_ascii": "Matadi",
            "lat": -5.8166,
            "lng": 13.45,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kongo Central",
            "capital": "admin",
            "population": 245862,
            "id": 1180529604
        },
        {
            "city": "Kalemie",
            "city_ascii": "Kalemie",
            "lat": -5.9333,
            "lng": 29.2,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Tanganyika",
            "capital": "admin",
            "population": 206257,
            "id": 1180574233
        },
        {
            "city": "Gemena",
            "city_ascii": "Gemena",
            "lat": 3.26,
            "lng": 19.77,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Sud-Ubangi",
            "capital": "admin",
            "population": 198056,
            "id": 1180000163
        },
        {
            "city": "Mbanza-Ngungu",
            "city_ascii": "Mbanza-Ngungu",
            "lat": -5.2496,
            "lng": 14.86,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kongo Central",
            "capital": "",
            "population": 197545,
            "id": 1180474388
        },
        {
            "city": "Mwene-Ditu",
            "city_ascii": "Mwene-Ditu",
            "lat": -7,
            "lng": 23.44,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Lomami",
            "capital": "",
            "population": 189177,
            "id": 1180134137
        },
        {
            "city": "Boma",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/1/10/Boma_city_centre.jpg",
            "city_ascii": "Boma",
            "lat": -5.83,
            "lng": 13.05,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kongo Central",
            "capital": "",
            "population": 178638,
            "id": 1180611452
        },
        {
            "city": "Uvira",
            "city_ascii": "Uvira",
            "lat": -3.37,
            "lng": 29.14,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Sud-Kivu",
            "capital": "",
            "population": 170391,
            "id": 1180205443
        },
        {
            "city": "Bumba",
            "city_ascii": "Bumba",
            "lat": 2.19,
            "lng": 22.46,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Mongala",
            "capital": "",
            "population": 160539,
            "id": 1180549980
        },
        {
            "city": "Isiro",
            "city_ascii": "Isiro",
            "lat": 2.76,
            "lng": 27.62,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Haut-U\u00e9l\u00e9",
            "capital": "admin",
            "population": 157196,
            "id": 1180183850
        },
        {
            "city": "Gandajika",
            "city_ascii": "Gandajika",
            "lat": -6.7396,
            "lng": 23.96,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Lomami",
            "capital": "",
            "population": 154425,
            "id": 1180466776
        },
        {
            "city": "Moanda",
            "city_ascii": "Moanda",
            "lat": -5.9229,
            "lng": 12.355,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kongo Central",
            "capital": "",
            "population": 153915,
            "id": 1180108441
        },
        {
            "city": "Wamba",
            "city_ascii": "Wamba",
            "lat": 2.1404,
            "lng": 27.99,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Haut-U\u00e9l\u00e9",
            "capital": "",
            "population": 146871,
            "id": 1180866253
        },
        {
            "city": "Goma",
            "city_ascii": "Goma",
            "lat": -1.6788,
            "lng": 29.2218,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Nord-Kivu",
            "capital": "admin",
            "population": 144124,
            "id": 1180805022
        },
        {
            "city": "Kamina",
            "city_ascii": "Kamina",
            "lat": -8.73,
            "lng": 25.01,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Haut-Lomami",
            "capital": "admin",
            "population": 128803,
            "id": 1180363197
        },
        {
            "city": "Bandundu",
            "city_ascii": "Bandundu",
            "lat": -3.31,
            "lng": 17.38,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kwilu",
            "capital": "",
            "population": 118211,
            "id": 1180219776
        },
        {
            "city": "Kipushi",
            "city_ascii": "Kipushi",
            "lat": -11.7596,
            "lng": 27.25,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Haut-Katanga",
            "capital": "",
            "population": 113347,
            "id": 1180810333
        },
        {
            "city": "Ilebo",
            "city_ascii": "Ilebo",
            "lat": -4.3196,
            "lng": 20.61,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kasa\u00ef",
            "capital": "",
            "population": 107093,
            "id": 1180788280
        },
        {
            "city": "Kongolo",
            "city_ascii": "Kongolo",
            "lat": -5.3795,
            "lng": 26.98,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Tanganyika",
            "capital": "",
            "population": 105202,
            "id": 1180814807
        },
        {
            "city": "Bunia",
            "city_ascii": "Bunia",
            "lat": 1.5604,
            "lng": 30.24,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Ituri",
            "capital": "admin",
            "population": 96764,
            "id": 1180006418
        },
        {
            "city": "Lisala",
            "city_ascii": "Lisala",
            "lat": 2.14,
            "lng": 21.51,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Mongala",
            "capital": "admin",
            "population": 70087,
            "id": 1180477995
        },
        {
            "city": "Kabinda",
            "city_ascii": "Kabinda",
            "lat": -6.1296,
            "lng": 24.48,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Lomami",
            "capital": "admin",
            "population": 59004,
            "id": 1180751831
        },
        {
            "city": "Gbadolite",
            "city_ascii": "Gbadolite",
            "lat": 4.2904,
            "lng": 21.0199,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Nord-Ubangi",
            "capital": "admin",
            "population": 50493,
            "id": 1180674224
        },
        {
            "city": "Buta",
            "city_ascii": "Buta",
            "lat": 2.82,
            "lng": 24.74,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Bas-U\u00e9l\u00e9",
            "capital": "admin",
            "population": 45677,
            "id": 1180712204
        },
        {
            "city": "Lusambo",
            "city_ascii": "Lusambo",
            "lat": -4.9696,
            "lng": 23.43,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Sankuru",
            "capital": "admin",
            "population": 41416,
            "id": 1180127290
        },
        {
            "city": "Inongo",
            "city_ascii": "Inongo",
            "lat": -1.94,
            "lng": 18.28,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Mai-Ndombe",
            "capital": "admin",
            "population": 40113,
            "id": 1180194164
        },
        {
            "city": "Luebo",
            "city_ascii": "Luebo",
            "lat": -5.3495,
            "lng": 21.41,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kasa\u00ef",
            "capital": "admin",
            "population": 35183,
            "id": 1180012250
        },
        {
            "city": "Boende",
            "city_ascii": "Boende",
            "lat": -0.2196,
            "lng": 20.86,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Tshuapa",
            "capital": "admin",
            "population": 32091,
            "id": 1180688906
        },
        {
            "city": "Kenge",
            "city_ascii": "Kenge",
            "lat": -4.8296,
            "lng": 16.8999,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kwango",
            "capital": "admin",
            "population": 241,
            "id": 1180158365
        },
        {
            "city": "Lodja",
            "city_ascii": "Lodja",
            "lat": -3.4896,
            "lng": 23.42,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Sankuru",
            "capital": "",
            "population": 68244,
            "id": 1180001261
        },
        {
            "city": "Binga",
            "city_ascii": "Binga",
            "lat": 2.3834,
            "lng": 20.42,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Mongala",
            "capital": "",
            "population": 64639,
            "id": 1180236070
        },
        {
            "city": "Kasongo",
            "city_ascii": "Kasongo",
            "lat": -4.45,
            "lng": 26.66,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Maniema",
            "capital": "",
            "population": 63000,
            "id": 1180000473
        },
        {
            "city": "Aketi",
            "city_ascii": "Aketi",
            "lat": 2.7405,
            "lng": 23.78,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Bas-U\u00e9l\u00e9",
            "capital": "",
            "population": 58601,
            "id": 1180273302
        },
        {
            "city": "Basankusu",
            "city_ascii": "Basankusu",
            "lat": 1.2337,
            "lng": 19.8,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "\u00c9quateur",
            "capital": "",
            "population": 52216,
            "id": 1180515335
        },
        {
            "city": "Mweka",
            "city_ascii": "Mweka",
            "lat": -4.8396,
            "lng": 21.57,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kasa\u00ef",
            "capital": "",
            "population": 50675,
            "id": 1180140663
        },
        {
            "city": "Kahemba",
            "city_ascii": "Kahemba",
            "lat": -7.2829,
            "lng": 19,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kwango",
            "capital": "",
            "population": 50000,
            "id": 1180689417
        },
        {
            "city": "Bulungu",
            "city_ascii": "Bulungu",
            "lat": -4.5496,
            "lng": 18.6,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kwilu",
            "capital": "",
            "population": 48344,
            "id": 1180342743
        },
        {
            "city": "Manono",
            "city_ascii": "Manono",
            "lat": -7.3,
            "lng": 27.45,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Tanganyika",
            "capital": "",
            "population": 46111,
            "id": 1180968800
        },
        {
            "city": "Basoko",
            "city_ascii": "Basoko",
            "lat": 1.2404,
            "lng": 23.59,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Tshopo",
            "capital": "",
            "population": 43709,
            "id": 1180509801
        },
        {
            "city": "Lubao",
            "city_ascii": "Lubao",
            "lat": -5.3896,
            "lng": 25.75,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Lomami",
            "capital": "",
            "population": 43068,
            "id": 1180891619
        },
        {
            "city": "Tshela",
            "city_ascii": "Tshela",
            "lat": -4.9696,
            "lng": 12.93,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kongo Central",
            "capital": "",
            "population": 38845,
            "id": 1180377922
        },
        {
            "city": "Bukama",
            "city_ascii": "Bukama",
            "lat": -9.2096,
            "lng": 25.84,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Haut-Lomami",
            "capital": "",
            "population": 38770,
            "id": 1180047354
        },
        {
            "city": "Mangai",
            "city_ascii": "Mangai",
            "lat": -4.0396,
            "lng": 19.53,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kwilu",
            "capital": "",
            "population": 37188,
            "id": 1180224936
        },
        {
            "city": "Kampene",
            "city_ascii": "Kampene",
            "lat": -3.5995,
            "lng": 26.67,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Maniema",
            "capital": "",
            "population": 37034,
            "id": 1180064621
        },
        {
            "city": "Kambove",
            "city_ascii": "Kambove",
            "lat": -10.8696,
            "lng": 26.6,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Haut-Katanga",
            "capital": "",
            "population": 36702,
            "id": 1180986023
        },
        {
            "city": "Kaniama",
            "city_ascii": "Kaniama",
            "lat": -7.5696,
            "lng": 24.17,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Haut-Lomami",
            "capital": "",
            "population": 36481,
            "id": 1180770775
        },
        {
            "city": "Yangambi",
            "city_ascii": "Yangambi",
            "lat": 0.7704,
            "lng": 24.43,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Tshopo",
            "capital": "",
            "population": 35531,
            "id": 1180077706
        },
        {
            "city": "Businga",
            "city_ascii": "Businga",
            "lat": 3.3404,
            "lng": 20.87,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Nord-Ubangi",
            "capital": "",
            "population": 34247,
            "id": 1180719970
        },
        {
            "city": "Mushie",
            "city_ascii": "Mushie",
            "lat": -3.0196,
            "lng": 16.92,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Mai-Ndombe",
            "capital": "",
            "population": 33062,
            "id": 1180240809
        },
        {
            "city": "Kabalo",
            "city_ascii": "Kabalo",
            "lat": -6.0496,
            "lng": 26.91,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Tanganyika",
            "capital": "",
            "population": 29833,
            "id": 1180905835
        },
        {
            "city": "Kasangulu",
            "city_ascii": "Kasangulu",
            "lat": -4.5796,
            "lng": 15.18,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kongo Central",
            "capital": "",
            "population": 27961,
            "id": 1180582533
        },
        {
            "city": "Bolobo",
            "city_ascii": "Bolobo",
            "lat": -2.1595,
            "lng": 16.24,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Mai-Ndombe",
            "capital": "",
            "population": 27862,
            "id": 1180723089
        },
        {
            "city": "Libenge",
            "city_ascii": "Libenge",
            "lat": 3.6604,
            "lng": 18.62,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Sud-Ubangi",
            "capital": "",
            "population": 27053,
            "id": 1180325896
        },
        {
            "city": "Watsa",
            "city_ascii": "Watsa",
            "lat": 3.04,
            "lng": 29.53,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Haut-U\u00e9l\u00e9",
            "capital": "",
            "population": 24516,
            "id": 1180367451
        },
        {
            "city": "Bondo",
            "city_ascii": "Bondo",
            "lat": 3.81,
            "lng": 23.67,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Bas-U\u00e9l\u00e9",
            "capital": "",
            "population": 23517,
            "id": 1180786691
        },
        {
            "city": "Demba",
            "city_ascii": "Demba",
            "lat": -5.5096,
            "lng": 22.26,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kasa\u00ef Central",
            "capital": "",
            "population": 22263,
            "id": 1180021198
        },
        {
            "city": "Kasongo-Lunda",
            "city_ascii": "Kasongo-Lunda",
            "lat": -6.4796,
            "lng": 16.83,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kwango",
            "capital": "",
            "population": 20060,
            "id": 1180706751
        },
        {
            "city": "Zongo",
            "city_ascii": "Zongo",
            "lat": 4.3303,
            "lng": 18.615,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Sud-Ubangi",
            "capital": "",
            "population": 17667,
            "id": 1180165321
        },
        {
            "city": "Nyunzu",
            "city_ascii": "Nyunzu",
            "lat": -5.9496,
            "lng": 28.0167,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Tanganyika",
            "capital": "",
            "population": 15397,
            "id": 1180921995
        },
        {
            "city": "Bosobolo",
            "city_ascii": "Bosobolo",
            "lat": 4.1904,
            "lng": 19.88,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Nord-Ubangi",
            "capital": "",
            "population": 14553,
            "id": 1180318544
        },
        {
            "city": "Kasaji",
            "city_ascii": "Kasaji",
            "lat": -10.3662,
            "lng": 23.45,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Lualaba",
            "capital": "",
            "population": 11969,
            "id": 1180795640
        },
        {
            "city": "Kimpese",
            "city_ascii": "Kimpese",
            "lat": -5.5496,
            "lng": 14.4333,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kongo Central",
            "capital": "",
            "population": 10578,
            "id": 1180273961
        },
        {
            "city": "Moba",
            "city_ascii": "Moba",
            "lat": -7.0596,
            "lng": 29.72,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Tanganyika",
            "capital": "",
            "population": 10006,
            "id": 1180776583
        },
        {
            "city": "Mangbwalu",
            "city_ascii": "Mangbwalu",
            "lat": 1.9504,
            "lng": 30.0333,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Ituri",
            "capital": "",
            "population": 2819,
            "id": 1180299514
        },
        {
            "city": "Dilolo",
            "city_ascii": "Dilolo",
            "lat": -10.6996,
            "lng": 22.3333,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Lualaba",
            "capital": "",
            "population": 7854,
            "id": 1180154207
        },
        {
            "city": "Bongandanga",
            "city_ascii": "Bongandanga",
            "lat": 1.5104,
            "lng": 21.05,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Mongala",
            "capital": "",
            "population": 4105,
            "id": 1180746434
        },
        {
            "city": "Mwenga",
            "city_ascii": "Mwenga",
            "lat": -3.0382,
            "lng": 28.4325,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Sud-Kivu",
            "capital": "",
            "population": 2216,
            "id": 1180606289
        },
        {
            "city": "Lubutu",
            "city_ascii": "Lubutu",
            "lat": -0.7329,
            "lng": 26.5833,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Maniema",
            "capital": "",
            "population": 1313,
            "id": 1180330836
        },
        {
            "city": "Buluko",
            "city_ascii": "Buluko",
            "lat": -0.757,
            "lng": 28.528,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Nord-Kivu",
            "capital": "",
            "population": 1192,
            "id": 1180000569
        },
        {
            "city": "Luanza",
            "city_ascii": "Luanza",
            "lat": -8.6996,
            "lng": 28.7,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Haut-Katanga",
            "capital": "",
            "population": 861,
            "id": 1180293709
        },
        {
            "city": "Dibaya",
            "city_ascii": "Dibaya",
            "lat": -6.5095,
            "lng": 22.87,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kasa\u00ef Central",
            "capital": "",
            "population": 603,
            "id": 1180985189
        },
        {
            "city": "Ikela",
            "city_ascii": "Ikela",
            "lat": -1.1829,
            "lng": 23.2666,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Tshuapa",
            "capital": "",
            "population": 291,
            "id": 1180365335
        },
        {
            "city": "Kalima",
            "city_ascii": "Kalima",
            "lat": -2.5096,
            "lng": 26.43,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Maniema",
            "capital": "",
            "population": 194,
            "id": 1180335450
        },
        {
            "city": "Lusanga",
            "city_ascii": "Lusanga",
            "lat": -5.5829,
            "lng": 16.5167,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kwango",
            "capital": "",
            "population": 177,
            "id": 1180423801
        },
        {
            "city": "Bafwasende",
            "city_ascii": "Bafwasende",
            "lat": 1.0838,
            "lng": 27.2666,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Tshopo",
            "capital": "",
            "population": 149,
            "id": 1180841746
        }
    ]
}