module.exports = {
    CITIES: [{
            "city": "Tallinn",
            "city_ascii": "Tallinn",
            "lat": 59.4339,
            "lng": 24.728,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "Harjumaa",
            "capital": "primary",
            "population": 394024,
            "id": 1233260021
        },
        {
            "city": "Tartu",
            "city_ascii": "Tartu",
            "lat": 58.3839,
            "lng": 26.7099,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "Tartumaa",
            "capital": "admin",
            "population": 101092,
            "id": 1233809410
        },
        {
            "city": "P\u00e4rnu",
            "city_ascii": "Parnu",
            "lat": 58.3747,
            "lng": 24.5136,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "P\u00e4rnumaa",
            "capital": "admin",
            "population": 44192,
            "id": 1233955054
        },
        {
            "city": "Viljandi",
            "city_ascii": "Viljandi",
            "lat": 58.3639,
            "lng": 25.59,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "Viljandimaa",
            "capital": "admin",
            "population": 20309,
            "id": 1233067368
        },
        {
            "city": "Haapsalu",
            "city_ascii": "Haapsalu",
            "lat": 58.9431,
            "lng": 23.5414,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "L\u00e4\u00e4nemaa",
            "capital": "admin",
            "population": 11805,
            "id": 1233967642
        },
        {
            "city": "Rapla",
            "city_ascii": "Rapla",
            "lat": 59.0072,
            "lng": 24.7928,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "Raplamaa",
            "capital": "admin",
            "population": "",
            "id": 1233013333
        },
        {
            "city": "Rakvere",
            "city_ascii": "Rakvere",
            "lat": 59.3464,
            "lng": 26.3558,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "L\u00e4\u00e4ne-Virumaa",
            "capital": "admin",
            "population": "",
            "id": 1233049348
        },
        {
            "city": "J\u00f5geva",
            "city_ascii": "Jogeva",
            "lat": 58.7467,
            "lng": 26.3939,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "J\u00f5gevamaa",
            "capital": "admin",
            "population": "",
            "id": 1233192849
        },
        {
            "city": "Kuressaare",
            "city_ascii": "Kuressaare",
            "lat": 58.2481,
            "lng": 22.5039,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "Saaremaa",
            "capital": "admin",
            "population": "",
            "id": 1233341219
        },
        {
            "city": "V\u00f5ru",
            "city_ascii": "Voru",
            "lat": 57.8339,
            "lng": 27.0194,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "V\u00f5rumaa",
            "capital": "admin",
            "population": "",
            "id": 1233754374
        },
        {
            "city": "P\u00f5lva",
            "city_ascii": "Polva",
            "lat": 58.0603,
            "lng": 27.0694,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "P\u00f5lvamaa",
            "capital": "admin",
            "population": "",
            "id": 1233866730
        },
        {
            "city": "Paide",
            "city_ascii": "Paide",
            "lat": 58.8856,
            "lng": 25.5572,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "J\u00e4rvamaa",
            "capital": "admin",
            "population": "",
            "id": 1233393684
        },
        {
            "city": "K\u00e4rdla",
            "city_ascii": "Kardla",
            "lat": 58.9978,
            "lng": 22.7492,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "Hiiumaa",
            "capital": "admin",
            "population": "",
            "id": 1233977488
        },
        {
            "city": "Valga",
            "city_ascii": "Valga",
            "lat": 57.7744,
            "lng": 26.0453,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "Valgamaa",
            "capital": "admin",
            "population": "",
            "id": 1233406308
        },
        {
            "city": "J\u00f5hvi",
            "city_ascii": "Johvi",
            "lat": 59.3592,
            "lng": 27.4211,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "Ida-Virumaa",
            "capital": "admin",
            "population": "",
            "id": 1233731045
        },
        {
            "city": "Narva",
            "city_ascii": "Narva",
            "lat": 59.3776,
            "lng": 28.1603,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "Ida-Virumaa",
            "capital": "minor",
            "population": 66980,
            "id": 1233751159
        },
        {
            "city": "Kohtla-J\u00e4rve",
            "city_ascii": "Kohtla-Jarve",
            "lat": 59.4,
            "lng": 27.2833,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "Ida-Virumaa",
            "capital": "minor",
            "population": 46060,
            "id": 1233016348
        },
        {
            "city": "P\u00fcssi",
            "city_ascii": "Pussi",
            "lat": 59.366667,
            "lng": 27.05,
            "country": "Estonia",
            "iso2": "EE",
            "admin_name": "Ida-Virumaa",
            "capital": "",
            "population": 0,
            "id": 10000000002
        },
        {
            "city": "Tapa",
            "city_ascii": "Tapa",
            "lat": 59.266667,
            "lng": 25.95,
            "country": "Estonia",
            "iso2": "EE",
            "admin_name": "L\u00e4\u00e4ne-Virumaa",
            "capital": "",
            "population": 0,
            "id": 10000000003
        },
        {
            "city": "Kivi\u00f5li",
            "city_ascii": "Kivioli",
            "lat": 59.35,
            "lng": 26.966667,
            "country": "Estonia",
            "iso2": "EE",
            "admin_name": "Ida-Virumaa",
            "capital": "",
            "population": 0,
            "id": 10000000004
        },
        {
            "city": "T\u00fcri",
            "city_ascii": "Turi",
            "lat": 58.809444,
            "lng": 25.429167,
            "country": "Estonia",
            "iso2": "EE",
            "admin_name": "J\u00e4rvamaa",
            "capital": "",
            "population": 0,
            "id": 10000000005
        },
        {
            "city": "P\u00f5ltsamaa",
            "city_ascii": "P\u00f5ltsamaa",
            "lat": 58.655278,
            "lng": 25.976944,
            "country": "Estonia",
            "iso2": "EE",
            "admin_name": "J\u00f5gevamaa",
            "capital": "",
            "population": 0,
            "id": 10000000006
        },
        {
            "city": "Sindi",
            "city_ascii": "Sindi",
            "lat": 58.400556,
            "lng": 24.6675,
            "country": "Estonia",
            "iso2": "EE",
            "admin_name": "P\u00e4rnumaa",
            "capital": "",
            "population": 0,
            "id": 10000000007
        }
    ]
}