module.exports = {
    CITIES: [{
            "city": "Paris",
            "city_ascii": "Paris",
            "lat": 48.8667,
            "lng": 2.3333,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "\u00cele-de-France",
            "capital": "primary",
            "population": 9904000,
            "id": 1250015082
        },
        {
            "city": "Lyon",
            "city_ascii": "Lyon",
            "lat": 45.77,
            "lng": 4.83,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Auvergne-Rh\u00f4ne-Alpes",
            "capital": "admin",
            "population": 1423000,
            "id": 1250196189
        },
        {
            "city": "Marseille",
            "city_ascii": "Marseille",
            "lat": 43.29,
            "lng": 5.375,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Provence-Alpes-C\u00f4te d\u2019Azur",
            "capital": "admin",
            "population": 1400000,
            "id": 1250774071
        },
        {
            "city": "Lille",
            "city_ascii": "Lille",
            "lat": 50.65,
            "lng": 3.08,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Hauts-de-France",
            "capital": "admin",
            "population": 1044000,
            "id": 1250071961
        },
        {
            "city": "Nice",
            "city_ascii": "Nice",
            "lat": 43.715,
            "lng": 7.265,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Provence-Alpes-C\u00f4te d\u2019Azur",
            "capital": "minor",
            "population": 927000,
            "id": 1250774553
        },
        {
            "city": "Toulouse",
            "city_ascii": "Toulouse",
            "lat": 43.62,
            "lng": 1.4499,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Occitanie",
            "capital": "admin",
            "population": 847000,
            "id": 1250258110
        },
        {
            "city": "Bordeaux",
            "city_ascii": "Bordeaux",
            "lat": 44.85,
            "lng": -0.595,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Nouvelle-Aquitaine",
            "capital": "admin",
            "population": 803000,
            "id": 1250449238
        },
        {
            "city": "Rouen",
            "city_ascii": "Rouen",
            "lat": 49.4304,
            "lng": 1.08,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Normandie",
            "capital": "admin",
            "population": 532559,
            "id": 1250372069
        },
        {
            "city": "Strasbourg",
            "city_ascii": "Strasbourg",
            "lat": 48.58,
            "lng": 7.75,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Grand Est",
            "capital": "admin",
            "population": 439972,
            "id": 1250789140
        },
        {
            "city": "Nantes",
            "city_ascii": "Nantes",
            "lat": 47.2104,
            "lng": -1.59,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Pays de la Loire",
            "capital": "admin",
            "population": 438537,
            "id": 1250091495
        },
        {
            "city": "Metz",
            "city_ascii": "Metz",
            "lat": 49.1203,
            "lng": 6.18,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Grand Est",
            "capital": "minor",
            "population": 409186,
            "id": 1250778717
        },
        {
            "city": "Grenoble",
            "city_ascii": "Grenoble",
            "lat": 45.1804,
            "lng": 5.72,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Auvergne-Rh\u00f4ne-Alpes",
            "capital": "minor",
            "population": 388574,
            "id": 1250071647
        },
        {
            "city": "Toulon",
            "city_ascii": "Toulon",
            "lat": 43.1342,
            "lng": 5.9188,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Provence-Alpes-C\u00f4te d\u2019Azur",
            "capital": "minor",
            "population": 357693,
            "id": 1250541629
        },
        {
            "city": "Montpellier",
            "city_ascii": "Montpellier",
            "lat": 43.6104,
            "lng": 3.87,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Occitanie",
            "capital": "minor",
            "population": 327254,
            "id": 1250819356
        },
        {
            "city": "Nancy",
            "city_ascii": "Nancy",
            "lat": 48.6837,
            "lng": 6.2,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Grand Est",
            "capital": "minor",
            "population": 268976,
            "id": 1250925250
        },
        {
            "city": "Saint-\u00c9tienne",
            "city_ascii": "Saint-Etienne",
            "lat": 45.4304,
            "lng": 4.38,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Auvergne-Rh\u00f4ne-Alpes",
            "capital": "minor",
            "population": 265684,
            "id": 1250000540
        },
        {
            "city": "Melun",
            "city_ascii": "Melun",
            "lat": 48.5333,
            "lng": 2.6666,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "\u00cele-de-France",
            "capital": "minor",
            "population": 249432,
            "id": 1250913458
        },
        {
            "city": "Le Havre",
            "city_ascii": "Le Havre",
            "lat": 49.505,
            "lng": 0.105,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Normandie",
            "capital": "minor",
            "population": 242124,
            "id": 1250775297
        },
        {
            "city": "Tours",
            "city_ascii": "Tours",
            "lat": 47.3804,
            "lng": 0.6999,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Centre-Val de Loire",
            "capital": "minor",
            "population": 236096,
            "id": 1250635972
        },
        {
            "city": "Clermont-Ferrand",
            "city_ascii": "Clermont-Ferrand",
            "lat": 45.78,
            "lng": 3.08,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Auvergne-Rh\u00f4ne-Alpes",
            "capital": "minor",
            "population": 233050,
            "id": 1250135509
        },
        {
            "city": "Orl\u00e9ans",
            "city_ascii": "Orleans",
            "lat": 47.9004,
            "lng": 1.9,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Centre-Val de Loire",
            "capital": "admin",
            "population": 217301,
            "id": 1250441405
        },
        {
            "city": "Mulhouse",
            "city_ascii": "Mulhouse",
            "lat": 47.7504,
            "lng": 7.35,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Grand Est",
            "capital": "minor",
            "population": 215454,
            "id": 1250218452
        },
        {
            "city": "Rennes",
            "city_ascii": "Rennes",
            "lat": 48.1,
            "lng": -1.67,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Bretagne",
            "capital": "admin",
            "population": 209375,
            "id": 1250363682
        },
        {
            "city": "Reims",
            "city_ascii": "Reims",
            "lat": 49.2504,
            "lng": 4.03,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Grand Est",
            "capital": "minor",
            "population": 196565,
            "id": 1250608730
        },
        {
            "city": "Caen",
            "city_ascii": "Caen",
            "lat": 49.1838,
            "lng": -0.35,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Normandie",
            "capital": "minor",
            "population": 190099,
            "id": 1250001272
        },
        {
            "city": "Angers",
            "city_ascii": "Angers",
            "lat": 47.48,
            "lng": -0.53,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Pays de la Loire",
            "capital": "minor",
            "population": 188380,
            "id": 1250962174
        },
        {
            "city": "Dijon",
            "city_ascii": "Dijon",
            "lat": 47.3304,
            "lng": 5.03,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Bourgogne-Franche-Comt\u00e9",
            "capital": "admin",
            "population": 169946,
            "id": 1250505606
        },
        {
            "city": "N\u00eemes",
            "city_ascii": "Nimes",
            "lat": 43.8304,
            "lng": 4.35,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Occitanie",
            "capital": "minor",
            "population": 169547,
            "id": 1250417467
        },
        {
            "city": "Limoges",
            "city_ascii": "Limoges",
            "lat": 45.83,
            "lng": 1.25,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Nouvelle-Aquitaine",
            "capital": "minor",
            "population": 152199,
            "id": 1250736774
        },
        {
            "city": "Aix-en-Provence",
            "city_ascii": "Aix-en-Provence",
            "lat": 43.52,
            "lng": 5.45,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Provence-Alpes-C\u00f4te d\u2019Azur",
            "capital": "minor",
            "population": 146821,
            "id": 1250001687
        },
        {
            "city": "Perpignan",
            "city_ascii": "Perpignan",
            "lat": 42.7,
            "lng": 2.9,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Occitanie",
            "capital": "minor",
            "population": 146620,
            "id": 1250102680
        },
        {
            "city": "Biarritz",
            "city_ascii": "Biarritz",
            "lat": 43.4733,
            "lng": -1.5616,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Nouvelle-Aquitaine",
            "capital": "",
            "population": 145348,
            "id": 1250324713
        },
        {
            "city": "Brest",
            "city_ascii": "Brest",
            "lat": 48.3904,
            "lng": -4.495,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Bretagne",
            "capital": "minor",
            "population": 144899,
            "id": 1250882453
        },
        {
            "city": "Le Mans",
            "city_ascii": "Le Mans",
            "lat": 48.0004,
            "lng": 0.1,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Pays de la Loire",
            "capital": "minor",
            "population": 144515,
            "id": 1250829671
        },
        {
            "city": "Amiens",
            "city_ascii": "Amiens",
            "lat": 49.9004,
            "lng": 2.3,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Hauts-de-France",
            "capital": "minor",
            "population": 143086,
            "id": 1250794759
        },
        {
            "city": "Besan\u00e7on",
            "city_ascii": "Besancon",
            "lat": 47.23,
            "lng": 6.03,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Bourgogne-Franche-Comt\u00e9",
            "capital": "minor",
            "population": 128426,
            "id": 1250182013
        },
        {
            "city": "Annecy",
            "city_ascii": "Annecy",
            "lat": 45.9,
            "lng": 6.1167,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Auvergne-Rh\u00f4ne-Alpes",
            "capital": "minor",
            "population": 105749,
            "id": 1250551848
        },
        {
            "city": "Calais",
            "city_ascii": "Calais",
            "lat": 50.9504,
            "lng": 1.8333,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Hauts-de-France",
            "capital": "minor",
            "population": 92201,
            "id": 1250081128
        },
        {
            "city": "Poitiers",
            "city_ascii": "Poitiers",
            "lat": 46.5833,
            "lng": 0.3333,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Nouvelle-Aquitaine",
            "capital": "minor",
            "population": 85960,
            "id": 1250812174
        },
        {
            "city": "Versailles",
            "city_ascii": "Versailles",
            "lat": 48.8005,
            "lng": 2.1333,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "\u00cele-de-France",
            "capital": "minor",
            "population": 85416,
            "id": 1250143827
        },
        {
            "city": "Lorient",
            "city_ascii": "Lorient",
            "lat": 47.7504,
            "lng": -3.3666,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Bretagne",
            "capital": "minor",
            "population": 84952,
            "id": 1250615711
        },
        {
            "city": "La Rochelle",
            "city_ascii": "La Rochelle",
            "lat": 46.1667,
            "lng": -1.15,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Nouvelle-Aquitaine",
            "capital": "minor",
            "population": 76997,
            "id": 1250623782
        },
        {
            "city": "Roanne",
            "city_ascii": "Roanne",
            "lat": 46.0333,
            "lng": 4.0667,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Auvergne-Rh\u00f4ne-Alpes",
            "capital": "minor",
            "population": 73315,
            "id": 1250674978
        },
        {
            "city": "Arras",
            "city_ascii": "Arras",
            "lat": 50.2833,
            "lng": 2.7833,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Hauts-de-France",
            "capital": "minor",
            "population": 64165,
            "id": 1250447540
        },
        {
            "city": "Troyes",
            "city_ascii": "Troyes",
            "lat": 48.3404,
            "lng": 4.0834,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Grand Est",
            "capital": "minor",
            "population": 61703,
            "id": 1250800856
        },
        {
            "city": "Cherbourg",
            "city_ascii": "Cherbourg",
            "lat": 49.6504,
            "lng": -1.65,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Normandie",
            "capital": "minor",
            "population": 60991,
            "id": 1250026751
        },
        {
            "city": "Agen",
            "city_ascii": "Agen",
            "lat": 44.2004,
            "lng": 0.6333,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Nouvelle-Aquitaine",
            "capital": "minor",
            "population": 58223,
            "id": 1250059626
        },
        {
            "city": "Tarbes",
            "city_ascii": "Tarbes",
            "lat": 43.2333,
            "lng": 0.0833,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Occitanie",
            "capital": "minor",
            "population": 54854,
            "id": 1250001722
        },
        {
            "city": "Ajaccio",
            "city_ascii": "Ajaccio",
            "lat": 41.9271,
            "lng": 8.7283,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Corsica",
            "capital": "admin",
            "population": 54364,
            "id": 1250622666
        },
        {
            "city": "Saint-Brieuc",
            "city_ascii": "Saint-Brieuc",
            "lat": 48.5167,
            "lng": -2.7833,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Bretagne",
            "capital": "minor",
            "population": 53223,
            "id": 1250574796
        },
        {
            "city": "Nevers",
            "city_ascii": "Nevers",
            "lat": 46.9837,
            "lng": 3.1667,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Bourgogne-Franche-Comt\u00e9",
            "capital": "minor",
            "population": 45929,
            "id": 1250147982
        },
        {
            "city": "Vichy",
            "city_ascii": "Vichy",
            "lat": 46.1171,
            "lng": 3.4167,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Auvergne-Rh\u00f4ne-Alpes",
            "capital": "minor",
            "population": 43158,
            "id": 1250084403
        },
        {
            "city": "Dieppe",
            "city_ascii": "Dieppe",
            "lat": 49.9337,
            "lng": 1.0833,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Normandie",
            "capital": "minor",
            "population": 42461,
            "id": 1250006284
        },
        {
            "city": "Bastia",
            "city_ascii": "Bastia",
            "lat": 42.7032,
            "lng": 9.45,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Corsica",
            "capital": "",
            "population": 41001,
            "id": 1250664815
        },
        {
            "city": "B\u00e9ziers",
            "city_ascii": "Beziers",
            "lat": 43.3505,
            "lng": 3.21,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Occitanie",
            "capital": "minor",
            "population": 81438,
            "id": 1250666824
        },
        {
            "city": "Bourges",
            "city_ascii": "Bourges",
            "lat": 47.0837,
            "lng": 2.4,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Centre-Val de Loire",
            "capital": "minor",
            "population": 72340,
            "id": 1250043242
        },
        {
            "city": "Brive-la-Gaillarde",
            "city_ascii": "Brive-la-Gaillarde",
            "lat": 45.1504,
            "lng": 1.5333,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Nouvelle-Aquitaine",
            "capital": "minor",
            "population": 55448,
            "id": 1250549859
        },
        {
            "city": "Auxerre",
            "city_ascii": "Auxerre",
            "lat": 47.8004,
            "lng": 3.5666,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "Bourgogne-Franche-Comt\u00e9",
            "capital": "minor",
            "population": 41516,
            "id": 1250482884
        }
    ]
}