module.exports = {
    CITIES: [{
            "city": "Havana",
            "city_ascii": "Havana",
            "lat": 23.132,
            "lng": -82.3642,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "La Habana",
            "capital": "primary",
            "population": 2174000,
            "id": 1192752771
        },
        {
            "city": "Santo Domingo",
            "city_ascii": "Santo Domingo",
            "lat": 18.4701,
            "lng": -69.9001,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Ozama",
            "capital": "primary",
            "population": 2154000,
            "id": 1214636202
        },
        {
            "city": "Port-au-Prince",
            "city_ascii": "Port-au-Prince",
            "lat": 18.541,
            "lng": -72.336,
            "country": "Haiti",
            "iso2": "HT",
            "iso3": "HTI",
            "admin_name": "Ouest",
            "capital": "primary",
            "population": 1998000,
            "id": 1332401940
        },
        {
            "city": "Santiago",
            "city_ascii": "Santiago",
            "lat": 19.5,
            "lng": -70.67,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Cibao Norte",
            "capital": "admin",
            "population": 1550753,
            "id": 1214985348
        },
        {
            "city": "Kingston",
            "city_ascii": "Kingston",
            "lat": 17.9771,
            "lng": -76.7674,
            "country": "Jamaica",
            "iso2": "JM",
            "iso3": "JAM",
            "admin_name": "Kingston",
            "capital": "primary",
            "population": 937700,
            "id": 1388709177
        },
        {
            "city": "Santiago de Cuba",
            "city_ascii": "Santiago de Cuba",
            "lat": 20.025,
            "lng": -75.8213,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Santiago de Cuba",
            "capital": "admin",
            "population": 555865,
            "id": 1192766111
        },
        {
            "city": "Spanish Town",
            "city_ascii": "Spanish Town",
            "lat": 17.9833,
            "lng": -76.95,
            "country": "Jamaica",
            "iso2": "JM",
            "iso3": "JAM",
            "admin_name": "Saint Catherine",
            "capital": "admin",
            "population": 432704,
            "id": 1388689196
        },
        {
            "city": "Camag\u00fcey",
            "city_ascii": "Camaguey",
            "lat": 21.3808,
            "lng": -77.9169,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Camag\u00fcey",
            "capital": "admin",
            "population": 347562,
            "id": 1192667983
        },
        {
            "city": "San Juan",
            "city_ascii": "San Juan",
            "lat": 18.4037,
            "lng": -66.0636,
            "country": "Puerto Rico",
            "iso2": "PR",
            "iso3": "PRI",
            "admin_name": "Puerto Rico",
            "capital": "",
            "population": 341657,
            "id": 1630035577
        },
        {
            "city": "Holgu\u00edn",
            "city_ascii": "Holguin",
            "lat": 20.8872,
            "lng": -76.2631,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Holgu\u00edn",
            "capital": "admin",
            "population": 319102,
            "id": 1192920574
        },
        {
            "city": "Cap-Ha\u00eftien",
            "city_ascii": "Cap-Haitien",
            "lat": 19.7592,
            "lng": -72.2125,
            "country": "Haiti",
            "iso2": "HT",
            "iso3": "HTI",
            "admin_name": "Nord",
            "capital": "admin",
            "population": 281487,
            "id": 1332333795
        },
        {
            "city": "Guant\u00e1namo",
            "city_ascii": "Guantanamo",
            "lat": 20.1453,
            "lng": -75.2061,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Guant\u00e1namo",
            "capital": "admin",
            "population": 272801,
            "id": 1192866062
        },
        {
            "city": "Santa Clara",
            "city_ascii": "Santa Clara",
            "lat": 22.4,
            "lng": -79.9667,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Villa Clara",
            "capital": "admin",
            "population": 250512,
            "id": 1192329773
        },
        {
            "city": "San Pedro de Macor\u00eds",
            "city_ascii": "San Pedro de Macoris",
            "lat": 18.4504,
            "lng": -69.3,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Higuamo",
            "capital": "admin",
            "population": 217899,
            "id": 1214233006
        },
        {
            "city": "La Romana",
            "city_ascii": "La Romana",
            "lat": 18.417,
            "lng": -68.9666,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Yuma",
            "capital": "admin",
            "population": 208437,
            "id": 1214760518
        },
        {
            "city": "Las Tunas",
            "city_ascii": "Las Tunas",
            "lat": 20.9601,
            "lng": -76.9544,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Las Tunas",
            "capital": "admin",
            "population": 203684,
            "id": 1192626319
        },
        {
            "city": "Bayamo",
            "city_ascii": "Bayamo",
            "lat": 20.3795,
            "lng": -76.6433,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Granma",
            "capital": "admin",
            "population": 192632,
            "id": 1192297857
        },
        {
            "city": "Pinar del R\u00edo",
            "city_ascii": "Pinar del Rio",
            "lat": 22.4175,
            "lng": -83.6981,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Pinar del R\u00edo",
            "capital": "admin",
            "population": 186990,
            "id": 1192216820
        },
        {
            "city": "Cienfuegos",
            "city_ascii": "Cienfuegos",
            "lat": 22.1444,
            "lng": -80.4403,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Cienfuegos",
            "capital": "admin",
            "population": 186644,
            "id": 1192020054
        },
        {
            "city": "Les Cayes",
            "city_ascii": "Les Cayes",
            "lat": 18.2004,
            "lng": -73.75,
            "country": "Haiti",
            "iso2": "HT",
            "iso3": "HTI",
            "admin_name": "Sud",
            "capital": "admin",
            "population": 175457,
            "id": 1332587854
        },
        {
            "city": "Bayam\u00f3n",
            "city_ascii": "Bayamon",
            "lat": 18.3793,
            "lng": -66.1635,
            "country": "Puerto Rico",
            "iso2": "PR",
            "iso3": "PRI",
            "admin_name": "Puerto Rico",
            "capital": "",
            "population": 170245,
            "id": 1630035622
        },
        {
            "city": "Gona\u00efves",
            "city_ascii": "Gonaives",
            "lat": 19.4504,
            "lng": -72.6832,
            "country": "Haiti",
            "iso2": "HT",
            "iso3": "HTI",
            "admin_name": "Artibonite",
            "capital": "admin",
            "population": 166678,
            "id": 1332384588
        },
        {
            "city": "La Vega",
            "city_ascii": "La Vega",
            "lat": 19.2166,
            "lng": -70.5166,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Cibao Sur",
            "capital": "admin",
            "population": 163197,
            "id": 1214691060
        },
        {
            "city": "San Crist\u00f3bal",
            "city_ascii": "San Cristobal",
            "lat": 18.416,
            "lng": -70.109,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Valdesia",
            "capital": "admin",
            "population": 154040,
            "id": 1214335207
        },
        {
            "city": "San Francisco de Macor\u00eds",
            "city_ascii": "San Francisco de Macoris",
            "lat": 19.3,
            "lng": -70.25,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Cibao Nordeste",
            "capital": "admin",
            "population": 152538,
            "id": 1214710545
        },
        {
            "city": "Matanzas",
            "city_ascii": "Matanzas",
            "lat": 23.0415,
            "lng": -81.5775,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Matanzas",
            "capital": "admin",
            "population": 146733,
            "id": 1192888416
        },
        {
            "city": "Carolina",
            "city_ascii": "Carolina",
            "lat": 18.4054,
            "lng": -65.9792,
            "country": "Puerto Rico",
            "iso2": "PR",
            "iso3": "PRI",
            "admin_name": "Puerto Rico",
            "capital": "",
            "population": 144192,
            "id": 1630035637
        },
        {
            "city": "Ciego de \u00c1vila",
            "city_ascii": "Ciego de Avila",
            "lat": 21.84,
            "lng": -78.7619,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Ciego de \u00c1vila",
            "capital": "admin",
            "population": 142027,
            "id": 1192302618
        },
        {
            "city": "May Pen",
            "city_ascii": "May Pen",
            "lat": 17.9666,
            "lng": -77.2333,
            "country": "Jamaica",
            "iso2": "JM",
            "iso3": "JAM",
            "admin_name": "Clarendon",
            "capital": "admin",
            "population": 135142,
            "id": 1388671677
        },
        {
            "city": "Manzanillo",
            "city_ascii": "Manzanillo",
            "lat": 20.3438,
            "lng": -77.1166,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Granma",
            "capital": "minor",
            "population": 128188,
            "id": 1192805452
        },
        {
            "city": "Sancti Sp\u00edritus",
            "city_ascii": "Sancti Spiritus",
            "lat": 21.9301,
            "lng": -79.4425,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Sancti Sp\u00edritus",
            "capital": "admin",
            "population": 127069,
            "id": 1192600260
        },
        {
            "city": "Montego Bay",
            "city_ascii": "Montego Bay",
            "lat": 18.4667,
            "lng": -77.9167,
            "country": "Jamaica",
            "iso2": "JM",
            "iso3": "JAM",
            "admin_name": "Saint James",
            "capital": "admin",
            "population": 126008,
            "id": 1388955058
        },
        {
            "city": "Hig\u00fcey",
            "city_ascii": "Higuey",
            "lat": 18.616,
            "lng": -68.708,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Yuma",
            "capital": "minor",
            "population": 123787,
            "id": 1214313712
        },
        {
            "city": "Ponce",
            "city_ascii": "Ponce",
            "lat": 18.012,
            "lng": -66.6198,
            "country": "Puerto Rico",
            "iso2": "PR",
            "iso3": "PRI",
            "admin_name": "Puerto Rico",
            "capital": "",
            "population": 120295,
            "id": 1630023669
        },
        {
            "city": "Puerto Plata",
            "city_ascii": "Puerto Plata",
            "lat": 19.7902,
            "lng": -70.6902,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Cibao Norte",
            "capital": "minor",
            "population": 119897,
            "id": 1214279422
        },
        {
            "city": "Palma Soriano",
            "city_ascii": "Palma Soriano",
            "lat": 20.2172,
            "lng": -75.9988,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Santiago de Cuba",
            "capital": "minor",
            "population": 102826,
            "id": 1192323011
        },
        {
            "city": "Half Way Tree",
            "city_ascii": "Half Way Tree",
            "lat": 18.0333,
            "lng": -76.8,
            "country": "Jamaica",
            "iso2": "JM",
            "iso3": "JAM",
            "admin_name": "Saint Andrew",
            "capital": "admin",
            "population": 96494,
            "id": 1388715163
        },
        {
            "city": "Barahona",
            "city_ascii": "Barahona",
            "lat": 18.2004,
            "lng": -71.1,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Enriquillo",
            "capital": "admin",
            "population": 90128,
            "id": 1214900129
        },
        {
            "city": "Caguas",
            "city_ascii": "Caguas",
            "lat": 18.2319,
            "lng": -66.0388,
            "country": "Puerto Rico",
            "iso2": "PR",
            "iso3": "PRI",
            "admin_name": "Puerto Rico",
            "capital": "",
            "population": 77064,
            "id": 1630023540
        },
        {
            "city": "San Juan",
            "city_ascii": "San Juan",
            "lat": 18.807,
            "lng": -71.229,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "El Valle",
            "capital": "admin",
            "population": 72950,
            "id": 1214608846
        },
        {
            "city": "Guaynabo",
            "city_ascii": "Guaynabo",
            "lat": 18.3839,
            "lng": -66.1134,
            "country": "Puerto Rico",
            "iso2": "PR",
            "iso3": "PRI",
            "admin_name": "Puerto Rico",
            "capital": "",
            "population": 70797,
            "id": 1630023575
        },
        {
            "city": "Artemisa",
            "city_ascii": "Artemisa",
            "lat": 22.8134,
            "lng": -82.7619,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Artemisa",
            "capital": "admin",
            "population": 68073,
            "id": 1192325408
        },
        {
            "city": "Azua",
            "city_ascii": "Azua",
            "lat": 18.454,
            "lng": -70.729,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Valdesia",
            "capital": "minor",
            "population": 59139,
            "id": 1214004418
        },
        {
            "city": "Mao",
            "city_ascii": "Mao",
            "lat": 19.552,
            "lng": -71.075,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Cibao Noroeste",
            "capital": "admin",
            "population": 48297,
            "id": 1214217168
        },
        {
            "city": "Mandeville",
            "city_ascii": "Mandeville",
            "lat": 18.033,
            "lng": -77.5,
            "country": "Jamaica",
            "iso2": "JM",
            "iso3": "JAM",
            "admin_name": "Manchester",
            "capital": "admin",
            "population": 47115,
            "id": 1388493847
        },
        {
            "city": "Trujillo Alto",
            "city_ascii": "Trujillo Alto",
            "lat": 18.3601,
            "lng": -66.0103,
            "country": "Puerto Rico",
            "iso2": "PR",
            "iso3": "PRI",
            "admin_name": "Puerto Rico",
            "capital": "",
            "population": 45936,
            "id": 1630023656
        },
        {
            "city": "Port-de-Paix",
            "city_ascii": "Port-de-Paix",
            "lat": 19.9318,
            "lng": -72.8295,
            "country": "Haiti",
            "iso2": "HT",
            "iso3": "HTI",
            "admin_name": "Nord-Ouest",
            "capital": "admin",
            "population": 34657,
            "id": 1332536650
        },
        {
            "city": "Jacmel",
            "city_ascii": "Jacmel",
            "lat": 18.235,
            "lng": -72.537,
            "country": "Haiti",
            "iso2": "HT",
            "iso3": "HTI",
            "admin_name": "Sud-Est",
            "capital": "admin",
            "population": 33563,
            "id": 1332314393
        },
        {
            "city": "J\u00e9r\u00e9mie",
            "city_ascii": "Jeremie",
            "lat": 18.6339,
            "lng": -74.1184,
            "country": "Haiti",
            "iso2": "HT",
            "iso3": "HTI",
            "admin_name": "Grand\u2019Anse",
            "capital": "admin",
            "population": 30917,
            "id": 1332612037
        },
        {
            "city": "Savanna-la-Mar",
            "city_ascii": "Savanna-la-Mar",
            "lat": 18.164,
            "lng": -77.948,
            "country": "Jamaica",
            "iso2": "JM",
            "iso3": "JAM",
            "admin_name": "Westmoreland",
            "capital": "admin",
            "population": 30000,
            "id": 1388690384
        },
        {
            "city": "Bonao",
            "city_ascii": "Bonao",
            "lat": 18.942,
            "lng": -70.409,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Cibao Sur",
            "capital": "minor",
            "population": 73269,
            "id": 1214793175
        },
        {
            "city": "G\u00fcines",
            "city_ascii": "Guines",
            "lat": 22.8361,
            "lng": -82.028,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Mayabeque",
            "capital": "minor",
            "population": 68935,
            "id": 1192190364
        },
        {
            "city": "Ban\u00ed",
            "city_ascii": "Bani",
            "lat": 18.28,
            "lng": -70.331,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Valdesia",
            "capital": "minor",
            "population": 66709,
            "id": 1214720035
        },
        {
            "city": "Mor\u00f3n",
            "city_ascii": "Moron",
            "lat": 22.1099,
            "lng": -78.6275,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Ciego de \u00c1vila",
            "capital": "minor",
            "population": 66060,
            "id": 1192161102
        },
        {
            "city": "Mayag\u00fcez",
            "city_ascii": "Mayaguez",
            "lat": 18.2003,
            "lng": -67.1397,
            "country": "Puerto Rico",
            "iso2": "PR",
            "iso3": "PRI",
            "admin_name": "Puerto Rico",
            "capital": "",
            "population": 64624,
            "id": 1630035520
        },
        {
            "city": "Col\u00f3n",
            "city_ascii": "Colon",
            "lat": 22.7196,
            "lng": -80.9058,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Matanzas",
            "capital": "minor",
            "population": 63882,
            "id": 1192866771
        },
        {
            "city": "Sagua la Grande",
            "city_ascii": "Sagua la Grande",
            "lat": 22.809,
            "lng": -80.0711,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Villa Clara",
            "capital": "minor",
            "population": 62073,
            "id": 1192446410
        },
        {
            "city": "Moca",
            "city_ascii": "Moca",
            "lat": 19.397,
            "lng": -70.523,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Cibao Norte",
            "capital": "minor",
            "population": 61834,
            "id": 1214863528
        },
        {
            "city": "Placetas",
            "city_ascii": "Placetas",
            "lat": 22.3158,
            "lng": -79.6555,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Villa Clara",
            "capital": "minor",
            "population": 55408,
            "id": 1192546991
        },
        {
            "city": "Nuevitas",
            "city_ascii": "Nuevitas",
            "lat": 21.5456,
            "lng": -77.2644,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Camag\u00fcey",
            "capital": "",
            "population": 54022,
            "id": 1192448182
        },
        {
            "city": "Banes",
            "city_ascii": "Banes",
            "lat": 20.9629,
            "lng": -75.7186,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Holgu\u00edn",
            "capital": "minor",
            "population": 53104,
            "id": 1192981466
        },
        {
            "city": "Salcedo",
            "city_ascii": "Salcedo",
            "lat": 19.383,
            "lng": -70.4167,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Cibao Nordeste",
            "capital": "minor",
            "population": 45299,
            "id": 1214901060
        },
        {
            "city": "Comendador",
            "city_ascii": "Comendador",
            "lat": 18.876,
            "lng": -71.707,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "El Valle",
            "capital": "minor",
            "population": 43894,
            "id": 1214626724
        },
        {
            "city": "San Antonio de los Ba\u00f1os",
            "city_ascii": "San Antonio de los Banos",
            "lat": 22.8911,
            "lng": -82.4991,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Artemisa",
            "capital": "minor",
            "population": 42724,
            "id": 1192374010
        },
        {
            "city": "Cotu\u00ed",
            "city_ascii": "Cotui",
            "lat": 19.059,
            "lng": -70.152,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Cibao Sur",
            "capital": "minor",
            "population": 41641,
            "id": 1214299029
        },
        {
            "city": "Arecibo",
            "city_ascii": "Arecibo",
            "lat": 18.4491,
            "lng": -66.7387,
            "country": "Puerto Rico",
            "iso2": "PR",
            "iso3": "PRI",
            "admin_name": "Puerto Rico",
            "capital": "",
            "population": 41556,
            "id": 1630023566
        },
        {
            "city": "Caibari\u00e9n",
            "city_ascii": "Caibarien",
            "lat": 22.5158,
            "lng": -79.4722,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "Villa Clara",
            "capital": "minor",
            "population": 39140,
            "id": 1192208164
        },
        {
            "city": "Hato Mayor",
            "city_ascii": "Hato Mayor",
            "lat": 18.764,
            "lng": -69.257,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Higuamo",
            "capital": "minor",
            "population": 35999,
            "id": 1214232592
        },
        {
            "city": "Nagua",
            "city_ascii": "Nagua",
            "lat": 19.376,
            "lng": -69.847,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Cibao Nordeste",
            "capital": "minor",
            "population": 33862,
            "id": 1214449469
        },
        {
            "city": "George Town",
            "city_ascii": "George Town",
            "lat": 19.2804,
            "lng": -81.33,
            "country": "Cayman Islands",
            "iso2": "KY",
            "iso3": "CYM",
            "admin_name": "",
            "capital": "primary",
            "population": 4268,
            "id": 1136159124
        }
    ]
}