module.exports = {
    CITIES: [{
            "city": "Tokyo",
            "city_ascii": "Tokyo",
            "lat": 35.685,
            "lng": 139.7514,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "T\u014dky\u014d",
            "capital": "primary",
            "population": 35676000,
            "id": 1392685764
        },
        {
            "city": "\u014csaka",
            "city_ascii": "Osaka",
            "lat": 34.75,
            "lng": 135.4601,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "\u014csaka",
            "capital": "admin",
            "population": 11294000,
            "id": 1392419823
        },
        {
            "city": "Yokohama",
            "city_ascii": "Yokohama",
            "lat": 35.32,
            "lng": 139.58,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Kanagawa",
            "capital": "admin",
            "population": 3697894,
            "id": 1392118339
        },
        {
            "city": "Nagoya",
            "city_ascii": "Nagoya",
            "lat": 35.155,
            "lng": 136.915,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Aichi",
            "capital": "admin",
            "population": 3230000,
            "id": 1392407472
        },
        {
            "city": "Fukuoka",
            "city_ascii": "Fukuoka",
            "lat": 33.595,
            "lng": 130.41,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Fukuoka",
            "capital": "admin",
            "population": 2792000,
            "id": 1392576294
        },
        {
            "city": "Sapporo",
            "city_ascii": "Sapporo",
            "lat": 43.075,
            "lng": 141.34,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Hokkaid\u014d",
            "capital": "admin",
            "population": 2544000,
            "id": 1392000195
        },
        {
            "city": "Sendai",
            "city_ascii": "Sendai",
            "lat": 38.2871,
            "lng": 141.0217,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Miyagi",
            "capital": "admin",
            "population": 2250000,
            "id": 1392457903
        },
        {
            "city": "Hiroshima",
            "city_ascii": "Hiroshima",
            "lat": 34.3878,
            "lng": 132.4429,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Hiroshima",
            "capital": "admin",
            "population": 2045000,
            "id": 1392373695
        },
        {
            "city": "Ky\u014dto",
            "city_ascii": "Kyoto",
            "lat": 35.03,
            "lng": 135.75,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Ky\u014dto",
            "capital": "admin",
            "population": 1805000,
            "id": 1392622735
        },
        {
            "city": "K\u014dbe",
            "city_ascii": "Kobe",
            "lat": 34.68,
            "lng": 135.17,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Hy\u014dgo",
            "capital": "admin",
            "population": 1528478,
            "id": 1392978082
        },
        {
            "city": "Kawanakajima",
            "city_ascii": "Kawanakajima",
            "lat": 35.53,
            "lng": 139.705,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Kanagawa",
            "capital": "",
            "population": 1437266,
            "id": 1392879600
        },
        {
            "city": "Kitaku",
            "city_ascii": "Kitaku",
            "lat": 33.8704,
            "lng": 130.82,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Fukuoka",
            "capital": "",
            "population": 997536,
            "id": 1392129541
        },
        {
            "city": "Hamamatsu",
            "city_ascii": "Hamamatsu",
            "lat": 34.7181,
            "lng": 137.7327,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Shizuoka",
            "capital": "",
            "population": 977023,
            "id": 1392174500
        },
        {
            "city": "Naha",
            "city_ascii": "Naha",
            "lat": 26.2072,
            "lng": 127.673,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Okinawa",
            "capital": "admin",
            "population": 905238,
            "id": 1392583118
        },
        {
            "city": "Okayama",
            "city_ascii": "Okayama",
            "lat": 34.672,
            "lng": 133.9171,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Okayama",
            "capital": "admin",
            "population": 866092,
            "id": 1392954750
        },
        {
            "city": "Kumamoto",
            "city_ascii": "Kumamoto",
            "lat": 32.8009,
            "lng": 130.7006,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Kumamoto",
            "capital": "admin",
            "population": 718232,
            "id": 1392106283
        },
        {
            "city": "Shizuoka",
            "city_ascii": "Shizuoka",
            "lat": 34.9858,
            "lng": 138.3854,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Shizuoka",
            "capital": "admin",
            "population": 701561,
            "id": 1392235505
        },
        {
            "city": "Utsunomiya",
            "city_ascii": "Utsunomiya",
            "lat": 36.55,
            "lng": 139.87,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Tochigi",
            "capital": "admin",
            "population": 667752,
            "id": 1392506125
        },
        {
            "city": "Nagano",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Nagano_montages.JPG/340px-Nagano_montages.JPG",
            "city_ascii": "Nagano",
            "lat": 36.65,
            "lng": 138.17,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Nagano",
            "capital": "admin",
            "population": 594311,
            "id": 1392603439
        },
        {
            "city": "Hachi\u014dji",
            "city_ascii": "Hachioji",
            "lat": 35.6577,
            "lng": 139.3261,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "T\u014dky\u014d",
            "capital": "",
            "population": 579399,
            "id": 1392172935
        },
        {
            "city": "Niigata",
            "city_ascii": "Niigata",
            "lat": 37.92,
            "lng": 139.04,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Niigata",
            "capital": "admin",
            "population": 569797,
            "id": 1392913753
        },
        {
            "city": "Kagoshima",
            "city_ascii": "Kagoshima",
            "lat": 31.586,
            "lng": 130.5611,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Kagoshima",
            "capital": "admin",
            "population": 555352,
            "id": 1392120675
        },
        {
            "city": "Kanazawa",
            "city_ascii": "Kanazawa",
            "lat": 36.56,
            "lng": 136.64,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Ishikawa",
            "capital": "admin",
            "population": 551249,
            "id": 1392684679
        },
        {
            "city": "\u014ctsu",
            "city_ascii": "Otsu",
            "lat": 35.0064,
            "lng": 135.8674,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Shiga",
            "capital": "admin",
            "population": 536976,
            "id": 1392164106
        },
        {
            "city": "Matsuyama",
            "city_ascii": "Matsuyama",
            "lat": 33.8455,
            "lng": 132.7658,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Ehime",
            "capital": "admin",
            "population": 533541,
            "id": 1392220893
        },
        {
            "city": "Tsu",
            "city_ascii": "Tsu",
            "lat": 34.7171,
            "lng": 136.5167,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Mie",
            "capital": "admin",
            "population": 500000,
            "id": 1392082102
        },
        {
            "city": "\u014cita",
            "city_ascii": "Oita",
            "lat": 33.2432,
            "lng": 131.5979,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "\u014cita",
            "capital": "admin",
            "population": 448907,
            "id": 1392081193
        },
        {
            "city": "Tokushima",
            "city_ascii": "Tokushima",
            "lat": 34.0674,
            "lng": 134.5525,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Tokushima",
            "capital": "admin",
            "population": 443760,
            "id": 1392795984
        },
        {
            "city": "Wakayama",
            "city_ascii": "Wakayama",
            "lat": 34.2231,
            "lng": 135.1677,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Wakayama",
            "capital": "admin",
            "population": 440006,
            "id": 1392907296
        },
        {
            "city": "Nagasaki",
            "city_ascii": "Nagasaki",
            "lat": 32.765,
            "lng": 129.885,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Nagasaki",
            "capital": "admin",
            "population": 435455,
            "id": 1392162566
        },
        {
            "city": "Gifu",
            "city_ascii": "Gifu",
            "lat": 35.4231,
            "lng": 136.7628,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Gifu",
            "capital": "admin",
            "population": 412895,
            "id": 1392097787
        },
        {
            "city": "Iwaki",
            "city_ascii": "Iwaki",
            "lat": 37.0553,
            "lng": 140.89,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Fukushima",
            "capital": "",
            "population": 357309,
            "id": 1392158088
        },
        {
            "city": "Asahikawa",
            "city_ascii": "Asahikawa",
            "lat": 43.755,
            "lng": 142.38,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Hokkaid\u014d",
            "capital": "",
            "population": 356612,
            "id": 1392380358
        },
        {
            "city": "Mito",
            "city_ascii": "Mito",
            "lat": 36.3704,
            "lng": 140.48,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Ibaraki",
            "capital": "admin",
            "population": 353892,
            "id": 1392665227
        },
        {
            "city": "Maebashi",
            "city_ascii": "Maebashi",
            "lat": 36.3927,
            "lng": 139.0727,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Gunma",
            "capital": "admin",
            "population": 344871,
            "id": 1392333295
        },
        {
            "city": "Tamuramachi-moriyama",
            "city_ascii": "Tamuramachi-moriyama",
            "lat": 37.41,
            "lng": 140.38,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Fukushima",
            "capital": "",
            "population": 340560,
            "id": 1392675180
        },
        {
            "city": "Kawagoe",
            "city_ascii": "Kawagoe",
            "lat": 35.9177,
            "lng": 139.4911,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Saitama",
            "capital": "",
            "population": 337931,
            "id": 1392825080
        },
        {
            "city": "K\u014dchi",
            "city_ascii": "Kochi",
            "lat": 33.5624,
            "lng": 133.5375,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "K\u014dchi",
            "capital": "admin",
            "population": 335570,
            "id": 1392086071
        },
        {
            "city": "Takamatsu",
            "city_ascii": "Takamatsu",
            "lat": 34.3447,
            "lng": 134.0448,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Kagawa",
            "capital": "admin",
            "population": 334223,
            "id": 1392427161
        },
        {
            "city": "Toyama",
            "city_ascii": "Toyama",
            "lat": 36.7,
            "lng": 137.23,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Toyama",
            "capital": "admin",
            "population": 332812,
            "id": 1392000560
        },
        {
            "city": "Miyazaki",
            "city_ascii": "Miyazaki",
            "lat": 31.9182,
            "lng": 131.4184,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Miyazaki",
            "capital": "admin",
            "population": 324384,
            "id": 1392216224
        },
        {
            "city": "Akita",
            "city_ascii": "Akita",
            "lat": 39.71,
            "lng": 140.09,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Akita",
            "capital": "admin",
            "population": 320069,
            "id": 1392129688
        },
        {
            "city": "Hakodate",
            "city_ascii": "Hakodate",
            "lat": 41.795,
            "lng": 140.74,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Hokkaid\u014d",
            "capital": "",
            "population": 302984,
            "id": 1392708558
        },
        {
            "city": "Aomori",
            "city_ascii": "Aomori",
            "lat": 40.825,
            "lng": 140.71,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Aomori",
            "capital": "admin",
            "population": 298394,
            "id": 1392083898
        },
        {
            "city": "Morioka",
            "city_ascii": "Morioka",
            "lat": 39.72,
            "lng": 141.13,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Iwate",
            "capital": "admin",
            "population": 295172,
            "id": 1392981957
        },
        {
            "city": "Fukushima",
            "city_ascii": "Fukushima",
            "lat": 37.74,
            "lng": 140.47,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Fukushima",
            "capital": "admin",
            "population": 294237,
            "id": 1392570027
        },
        {
            "city": "Yamagata",
            "city_ascii": "Yamagata",
            "lat": 38.2705,
            "lng": 140.32,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Yamagata",
            "capital": "admin",
            "population": 272209,
            "id": 1392300081
        },
        {
            "city": "Fukui",
            "city_ascii": "Fukui",
            "lat": 36.0704,
            "lng": 136.22,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Fukui",
            "capital": "admin",
            "population": 248707,
            "id": 1392897510
        },
        {
            "city": "Shinozaki",
            "city_ascii": "Shinozaki",
            "lat": 33.9654,
            "lng": 130.9454,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Fukuoka",
            "capital": "",
            "population": 245786,
            "id": 1392516557
        },
        {
            "city": "Hachimanch\u014d",
            "city_ascii": "Hachimancho",
            "lat": 40.51,
            "lng": 141.54,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Aomori",
            "capital": "",
            "population": 239046,
            "id": 1392220933
        },
        {
            "city": "Sato",
            "city_ascii": "Sato",
            "lat": 33.1631,
            "lng": 129.7177,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Nagasaki",
            "capital": "",
            "population": 237444,
            "id": 1392043131
        },
        {
            "city": "Minami\u014dzuma",
            "city_ascii": "Minamiozuma",
            "lat": 36.2404,
            "lng": 137.97,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Nagano",
            "capital": "",
            "population": 224926,
            "id": 1392373962
        },
        {
            "city": "Ashino",
            "city_ascii": "Ashino",
            "lat": 42.975,
            "lng": 144.3747,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Hokkaid\u014d",
            "capital": "",
            "population": 198566,
            "id": 1392810778
        },
        {
            "city": "K\u014dfu",
            "city_ascii": "Kofu",
            "lat": 35.6504,
            "lng": 138.5833,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Yamanashi",
            "capital": "admin",
            "population": 197540,
            "id": 1392307565
        },
        {
            "city": "Kure",
            "city_ascii": "Kure",
            "lat": 34.251,
            "lng": 132.5656,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Hiroshima",
            "capital": "",
            "population": 196991,
            "id": 1392991987
        },
        {
            "city": "Naka",
            "city_ascii": "Naka",
            "lat": 37.4504,
            "lng": 138.86,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Niigata",
            "capital": "",
            "population": 195318,
            "id": 1392479949
        },
        {
            "city": "\u014cbiraki",
            "city_ascii": "Obiraki",
            "lat": 40.57,
            "lng": 140.47,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Aomori",
            "capital": "",
            "population": 174972,
            "id": 1392794397
        },
        {
            "city": "Takaoka",
            "city_ascii": "Takaoka",
            "lat": 42.6504,
            "lng": 141.55,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Hokkaid\u014d",
            "capital": "",
            "population": 174806,
            "id": 1392760442
        },
        {
            "city": "Beppuch\u014d",
            "city_ascii": "Beppucho",
            "lat": 42.9304,
            "lng": 143.17,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Hokkaid\u014d",
            "capital": "",
            "population": 173890,
            "id": 1392712158
        },
        {
            "city": "Takaoka",
            "city_ascii": "Takaoka",
            "lat": 36.67,
            "lng": 137,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Toyama",
            "capital": "",
            "population": 170077,
            "id": 1392754231
        },
        {
            "city": "Matsue",
            "city_ascii": "Matsue",
            "lat": 35.467,
            "lng": 133.0666,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Shimane",
            "capital": "admin",
            "population": 156811,
            "id": 1392692238
        },
        {
            "city": "Muroran",
            "city_ascii": "Muroran",
            "lat": 42.35,
            "lng": 140.98,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Hokkaid\u014d",
            "capital": "",
            "population": 155676,
            "id": 1392259868
        },
        {
            "city": "Tottori",
            "city_ascii": "Tottori",
            "lat": 35.5004,
            "lng": 134.2333,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Tottori",
            "capital": "",
            "population": 154098,
            "id": 1392416969
        },
        {
            "city": "Otaru",
            "city_ascii": "Otaru",
            "lat": 43.1887,
            "lng": 140.9783,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Hokkaid\u014d",
            "capital": "",
            "population": 143792,
            "id": 1392240421
        },
        {
            "city": "K\u014dench\u014d",
            "city_ascii": "Koencho",
            "lat": 43.8504,
            "lng": 143.9,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Hokkaid\u014d",
            "capital": "",
            "population": 113137,
            "id": 1392099278
        },
        {
            "city": "Sakata",
            "city_ascii": "Sakata",
            "lat": 38.92,
            "lng": 139.8501,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Yamagata",
            "capital": "",
            "population": 100446,
            "id": 1392418961
        },
        {
            "city": "Saitama",
            "city_ascii": "Saitama",
            "lat": 35.9,
            "lng": 139.65,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Saitama",
            "capital": "admin",
            "population": "",
            "id": 1392017719
        },
        {
            "city": "Chiba",
            "city_ascii": "Chiba",
            "lat": 35.6,
            "lng": 140.1167,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Chiba",
            "capital": "admin",
            "population": "",
            "id": 1392107144
        },
        {
            "city": "Nara",
            "city_ascii": "Nara",
            "lat": 34.6833,
            "lng": 135.8333,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Nara",
            "capital": "admin",
            "population": "",
            "id": 1392520831
        },
        {
            "city": "Saga",
            "city_ascii": "Saga",
            "lat": 33.2333,
            "lng": 130.3,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Saga",
            "capital": "admin",
            "population": "",
            "id": 1392618841
        },
        {
            "city": "Tottori",
            "city_ascii": "Tottori",
            "lat": 35.5,
            "lng": 134.2333,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Tottori",
            "capital": "admin",
            "population": "",
            "id": 1392675192
        },
        {
            "city": "Yamaguchi",
            "city_ascii": "Yamaguchi",
            "lat": 34.1833,
            "lng": 131.4667,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Yamaguchi",
            "capital": "admin",
            "population": "",
            "id": 1392887215
        },
        {
            "city": "Tsuruoka",
            "city_ascii": "Tsuruoka",
            "lat": 38.7004,
            "lng": 139.8302,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Yamagata",
            "capital": "",
            "population": 99820,
            "id": 1392935450
        },
        {
            "city": "Maizuru",
            "city_ascii": "Maizuru",
            "lat": 35.4504,
            "lng": 135.3333,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Ky\u014dto",
            "capital": "",
            "population": 92465,
            "id": 1392353780
        },
        {
            "city": "Kaneyama",
            "city_ascii": "Kaneyama",
            "lat": 31.3833,
            "lng": 130.85,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "Kagoshima",
            "capital": "",
            "population": 82335,
            "id": 1392748014
        }
    ]
}