module.exports = { CITIES: [
  {
    "city": "Nairobi",
    "city_ascii": "Nairobi",
    "lat": -1.2833,
    "lng": 36.8167,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Nairobi City",
    "capital": "primary",
    "population": 3010000,
    "id": 1404000661
  },
  {
    "city": "Mombasa",
    "city_ascii": "Mombasa",
    "lat": -4.04,
    "lng": 39.6899,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Mombasa",
    "capital": "admin",
    "population": 882000,
    "id": 1404512373
  },
  {
    "city": "Kisumu",
    "city_ascii": "Kisumu",
    "lat": -0.09,
    "lng": 34.75,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Kisumu",
    "capital": "admin",
    "population": 395615,
    "id": 1404511920
  },
  {
    "city": "Nakuru",
    "city_ascii": "Nakuru",
    "lat": -0.28,
    "lng": 36.07,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Nakuru",
    "capital": "admin",
    "population": 364727,
    "id": 1404140179
  },
  {
    "city": "Eldoret",
    "city_ascii": "Eldoret",
    "lat": 0.52,
    "lng": 35.27,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Uasin Gishu",
    "capital": "admin",
    "population": 353381,
    "id": 1404676289
  },
  {
    "city": "Kitale",
    "city_ascii": "Kitale",
    "lat": 1.0305,
    "lng": 34.9899,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Trans Nzoia",
    "capital": "admin",
    "population": 150495,
    "id": 1404890081
  },
  {
    "city": "Machakos",
    "city_ascii": "Machakos",
    "lat": -1.5095,
    "lng": 37.26,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Machakos",
    "capital": "admin",
    "population": 144925,
    "id": 1404746781
  },
  {
    "city": "Thika",
    "city_ascii": "Thika",
    "lat": -1.0396,
    "lng": 37.09,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Kiambu",
    "capital": "",
    "population": 99322,
    "id": 1404482650
  },
  {
    "city": "Kericho",
    "city_ascii": "Kericho",
    "lat": -0.3596,
    "lng": 35.28,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Kericho",
    "capital": "admin",
    "population": 98852,
    "id": 1404338562
  },
  {
    "city": "Malindi",
    "city_ascii": "Malindi",
    "lat": -3.21,
    "lng": 40.1,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Kilifi",
    "capital": "",
    "population": 94016,
    "id": 1404380224
  },
  {
    "city": "Kilifi",
    "city_ascii": "Kilifi",
    "lat": -3.6096,
    "lng": 39.85,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Kilifi",
    "capital": "admin",
    "population": 80339,
    "id": 1404080121
  },
  {
    "city": "Garissa",
    "city_ascii": "Garissa",
    "lat": -0.4396,
    "lng": 39.67,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Garissa",
    "capital": "admin",
    "population": 67861,
    "id": 1404464692
  },
  {
    "city": "Kakamega",
    "city_ascii": "Kakamega",
    "lat": 0.2904,
    "lng": 34.73,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Kakamega",
    "capital": "admin",
    "population": 63426,
    "id": 1404614327
  },
  {
    "city": "Embu",
    "city_ascii": "Embu",
    "lat": -0.5196,
    "lng": 37.45,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Embu",
    "capital": "admin",
    "population": 58620,
    "id": 1404376456
  },
  {
    "city": "Bungoma",
    "city_ascii": "Bungoma",
    "lat": 0.5704,
    "lng": 34.56,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Bungoma",
    "capital": "admin",
    "population": 55962,
    "id": 1404689847
  },
  {
    "city": "Nyeri",
    "city_ascii": "Nyeri",
    "lat": -0.417,
    "lng": 36.951,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Nyeri",
    "capital": "admin",
    "population": 51084,
    "id": 1404924901
  },
  {
    "city": "Meru",
    "city_ascii": "Meru",
    "lat": 0.06,
    "lng": 37.64,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Meru",
    "capital": "admin",
    "population": 47226,
    "id": 1404588252
  },
  {
    "city": "Wajir",
    "city_ascii": "Wajir",
    "lat": 1.7504,
    "lng": 40.05,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Wajir",
    "capital": "admin",
    "population": 45771,
    "id": 1404067343
  },
  {
    "city": "Kisii",
    "city_ascii": "Kisii",
    "lat": -0.6696,
    "lng": 34.76,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Kisii",
    "capital": "admin",
    "population": 28547,
    "id": 1404617601
  },
  {
    "city": "Moyale",
    "city_ascii": "Moyale",
    "lat": 3.52,
    "lng": 39.05,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Marsabit",
    "capital": "",
    "population": 24837,
    "id": 1404689643
  },
  {
    "city": "Lamu",
    "city_ascii": "Lamu",
    "lat": -2.262,
    "lng": 40.9197,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Lamu",
    "capital": "admin",
    "population": 24525,
    "id": 1404163131
  },
  {
    "city": "Maralal",
    "city_ascii": "Maralal",
    "lat": 1.1105,
    "lng": 36.68,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Samburu",
    "capital": "admin",
    "population": 20841,
    "id": 1404895664
  },
  {
    "city": "Lodwar",
    "city_ascii": "Lodwar",
    "lat": 3.1304,
    "lng": 35.57,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Turkana",
    "capital": "admin",
    "population": 20219,
    "id": 1404993573
  },
  {
    "city": "Eldama Ravine",
    "city_ascii": "Eldama Ravine",
    "lat": 0.0504,
    "lng": 35.72,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Baringo",
    "capital": "",
    "population": 17581,
    "id": 1404468256
  },
  {
    "city": "Marsabit",
    "city_ascii": "Marsabit",
    "lat": 2.33,
    "lng": 37.98,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Marsabit",
    "capital": "admin",
    "population": 16460,
    "id": 1404055253
  },
  {
    "city": "Kiambu",
    "city_ascii": "Kiambu",
    "lat": -1.1714,
    "lng": 36.8356,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Kiambu",
    "capital": "admin",
    "population": "",
    "id": 1404390868
  },
  {
    "city": "Busia",
    "city_ascii": "Busia",
    "lat": 0.4586,
    "lng": 34.116,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Busia",
    "capital": "admin",
    "population": "",
    "id": 1404250734
  },
  {
    "city": "Kitui",
    "city_ascii": "Kitui",
    "lat": -1.367,
    "lng": 38.0106,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Kitui",
    "capital": "admin",
    "population": "",
    "id": 1404548296
  },
  {
    "city": "Isiolo",
    "city_ascii": "Isiolo",
    "lat": 0.3546,
    "lng": 37.5822,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Isiolo",
    "capital": "admin",
    "population": "",
    "id": 1404771203
  },
  {
    "city": "Homa Bay",
    "city_ascii": "Homa Bay",
    "lat": -0.5273,
    "lng": 34.4571,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Homa Bay",
    "capital": "admin",
    "population": "",
    "id": 1404321159
  },
  {
    "city": "Kabarnet",
    "city_ascii": "Kabarnet",
    "lat": 0.4919,
    "lng": 35.743,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Baringo",
    "capital": "admin",
    "population": "",
    "id": 1404620707
  },
  {
    "city": "Mandera",
    "city_ascii": "Mandera",
    "lat": 3.9414,
    "lng": 41.8625,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Mandera",
    "capital": "admin",
    "population": "",
    "id": 1404192737
  },
  {
    "city": "Migori",
    "city_ascii": "Migori",
    "lat": -1.0634,
    "lng": 34.4731,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Migori",
    "capital": "admin",
    "population": "",
    "id": 1404478510
  },
  {
    "city": "Kerugoya",
    "city_ascii": "Kerugoya",
    "lat": -0.4989,
    "lng": 37.2803,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Kirinyaga",
    "capital": "admin",
    "population": "",
    "id": 1404597807
  },
  {
    "city": "Iten",
    "city_ascii": "Iten",
    "lat": 0.6703,
    "lng": 35.5081,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Elgeyo/Marakwet",
    "capital": "admin",
    "population": "",
    "id": 1404000102
  },
  {
    "city": "Nyamira",
    "city_ascii": "Nyamira",
    "lat": -0.5633,
    "lng": 34.9358,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Nyamira",
    "capital": "admin",
    "population": "",
    "id": 1404000104
  },
  {
    "city": "Kapsabet",
    "city_ascii": "Kapsabet",
    "lat": 0.2039,
    "lng": 35.105,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Nandi",
    "capital": "admin",
    "population": "",
    "id": 1404814363
  },
  {
    "city": "Murang\u2019a",
    "city_ascii": "Murang'a",
    "lat": -0.721,
    "lng": 37.1526,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Murang\u2019a",
    "capital": "admin",
    "population": "",
    "id": 1404066738
  },
  {
    "city": "Sotik Post",
    "city_ascii": "Sotik Post",
    "lat": -0.7813,
    "lng": 35.3416,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Bomet",
    "capital": "admin",
    "population": "",
    "id": 1404087664
  },
  {
    "city": "Siaya",
    "city_ascii": "Siaya",
    "lat": 0.0607,
    "lng": 34.2881,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Siaya",
    "capital": "admin",
    "population": "",
    "id": 1404162576
  },
  {
    "city": "Kapenguria",
    "city_ascii": "Kapenguria",
    "lat": 1.2389,
    "lng": 35.1119,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "West Pokot",
    "capital": "admin",
    "population": "",
    "id": 1404228137
  },
  {
    "city": "Wote",
    "city_ascii": "Wote",
    "lat": -1.7808,
    "lng": 37.6288,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Makueni",
    "capital": "admin",
    "population": "",
    "id": 1404304549
  },
  {
    "city": "Mwatate",
    "city_ascii": "Mwatate",
    "lat": -3.505,
    "lng": 38.3772,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Taita/Taveta",
    "capital": "admin",
    "population": "",
    "id": 1404648092
  },
  {
    "city": "Kajiado",
    "city_ascii": "Kajiado",
    "lat": -1.8524,
    "lng": 36.7768,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Kajiado",
    "capital": "admin",
    "population": "",
    "id": 1404265412
  },
  {
    "city": "Hola",
    "city_ascii": "Hola",
    "lat": -1.4993,
    "lng": 40.0301,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Tana River",
    "capital": "admin",
    "population": "",
    "id": 1404396632
  },
  {
    "city": "Ol Kalou",
    "city_ascii": "Ol Kalou",
    "lat": -0.2643,
    "lng": 36.3788,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Nyandarua",
    "capital": "admin",
    "population": "",
    "id": 1404930645
  },
  {
    "city": "Narok",
    "city_ascii": "Narok",
    "lat": -1.0808,
    "lng": 35.8711,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Narok",
    "capital": "admin",
    "population": "",
    "id": 1404459814
  },
  {
    "city": "Kwale",
    "city_ascii": "Kwale",
    "lat": -4.1737,
    "lng": 39.4521,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Kwale",
    "capital": "admin",
    "population": "",
    "id": 1404769042
  },
  {
    "city": "Rumuruti",
    "city_ascii": "Rumuruti",
    "lat": 0.2725,
    "lng": 36.5381,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Laikipia",
    "capital": "admin",
    "population": "",
    "id": 1404005234
  },
  {
    "city": "Kathwana",
    "city_ascii": "Kathwana",
    "lat": -0.3314,
    "lng": 37.8686,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Tharaka-Nithi",
    "capital": "admin",
    "population": "",
    "id": 1404000105
  },
  {
    "city": "Kendu Bay",
    "city_ascii": "Kendu Bay",
    "lat": -0.3596,
    "lng": 34.64,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Homa Bay",
    "capital": "",
    "population": 91248,
    "id": 1404600696
  },
  {
    "city": "Sotik",
    "city_ascii": "Sotik",
    "lat": -0.6796,
    "lng": 35.12,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Bomet",
    "capital": "",
    "population": 71285,
    "id": 1404807525
  },
  {
    "city": "Naivasha",
    "city_ascii": "Naivasha",
    "lat": -0.7096,
    "lng": 36.43,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Nakuru",
    "capital": "",
    "population": 43983,
    "id": 1404904927
  },
  {
    "city": "Voi",
    "city_ascii": "Voi",
    "lat": -3.3696,
    "lng": 38.57,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Taita/Taveta",
    "capital": "",
    "population": 36487,
    "id": 1404504656
  },
  {
    "city": "Nanyuki",
    "city_ascii": "Nanyuki",
    "lat": 0.0204,
    "lng": 37.06,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Laikipia",
    "capital": "",
    "population": 36142,
    "id": 1404481993
  },
  {
    "city": "Namanga",
    "city_ascii": "Namanga",
    "lat": -2.5396,
    "lng": 36.8,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "",
    "capital": "",
    "population": 13193,
    "id": 1404000001
  },
  {
    "city": "Mwingi",
    "city_ascii": "Mwingi",
    "lat": -0.9296,
    "lng": 38.07,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Kitui",
    "capital": "",
    "population": 11219,
    "id": 1404312666
  },
  {
    "city": "Karungu",
    "city_ascii": "Karungu",
    "lat": -0.8496,
    "lng": 34.15,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Migori",
    "capital": "",
    "population": 2376,
    "id": 1404796412
  },
  {
    "city": "Witu",
    "city_ascii": "Witu",
    "lat": -2.3796,
    "lng": 40.43,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Lamu",
    "capital": "",
    "population": 5380,
    "id": 1404037095
  },
  {
    "city": "Konza",
    "city_ascii": "Konza",
    "lat": -1.7496,
    "lng": 37.12,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Machakos",
    "capital": "",
    "population": 2004,
    "id": 1404143289
  },
  {
    "city": "Tsavo",
    "city_ascii": "Tsavo",
    "lat": -2.9828,
    "lng": 38.4666,
    "country": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "admin_name": "Taita/Taveta",
    "capital": "",
    "population": 414,
    "id": 1404321644
  }
]}