module.exports = {
    CITIES: [{
            "city": "Riga",
            "city_ascii": "Riga",
            "lat": 56.95,
            "lng": 24.1,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "R\u012bga",
            "capital": "primary",
            "population": 742572,
            "id": 1428586192
        },
        {
            "city": "Daugavpils",
            "city_ascii": "Daugavpils",
            "lat": 55.88,
            "lng": 26.51,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Daugavpils Novads",
            "capital": "admin",
            "population": 111564,
            "id": 1428924928
        },
        {
            "city": "Liep\u0101ja",
            "city_ascii": "Liepaja",
            "lat": 56.51,
            "lng": 21.01,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Liep\u0101ja",
            "capital": "admin",
            "population": 85132,
            "id": 1428511842
        },
        {
            "city": "Jelgava",
            "city_ascii": "Jelgava",
            "lat": 56.6527,
            "lng": 23.7128,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Jelgavas Novads",
            "capital": "admin",
            "population": 67207,
            "id": 1428370571
        },
        {
            "city": "Ventspils",
            "city_ascii": "Ventspils",
            "lat": 57.3899,
            "lng": 21.5606,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Ventspils",
            "capital": "admin",
            "population": 42884,
            "id": 1428112098
        },
        {
            "city": "R\u0113zekne",
            "city_ascii": "Rezekne",
            "lat": 56.5,
            "lng": 27.3166,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "R\u0113zeknes Novads",
            "capital": "admin",
            "population": 38340,
            "id": 1428895373
        },
        {
            "city": "Valmiera",
            "city_ascii": "Valmiera",
            "lat": 57.5387,
            "lng": 25.4257,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Valmiera",
            "capital": "admin",
            "population": "",
            "id": 1428524787
        },
        {
            "city": "J\u0113kabpils",
            "city_ascii": "Jekabpils",
            "lat": 56.4833,
            "lng": 25.85,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "J\u0113kabpils Novads",
            "capital": "admin",
            "population": "",
            "id": 1428885452
        },
        {
            "city": "J\u016brmala",
            "city_ascii": "Jurmala",
            "lat": 56.9567,
            "lng": 23.7233,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "J\u016brmala",
            "capital": "admin",
            "population": "",
            "id": 1428952300
        },
        {
            "city": "Salaspils",
            "city_ascii": "Salaspils",
            "lat": 56.861,
            "lng": 24.3498,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Salaspils Novads",
            "capital": "admin",
            "population": "",
            "id": 1428270898
        },
        {
            "city": "Ulbroka",
            "city_ascii": "Ulbroka",
            "lat": 56.9363,
            "lng": 24.3039,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Stopi\u0146u Novads",
            "capital": "admin",
            "population": "",
            "id": 1428511061
        },
        {
            "city": "M\u0101rupe",
            "city_ascii": "Marupe",
            "lat": 56.9032,
            "lng": 24.0467,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "M\u0101rupes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428162714
        },
        {
            "city": "Saulkrasti",
            "city_ascii": "Saulkrasti",
            "lat": 57.2599,
            "lng": 24.4189,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Saulkrastu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428934591
        },
        {
            "city": "C\u0113sis",
            "city_ascii": "Cesis",
            "lat": 57.3091,
            "lng": 25.2761,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "C\u0113su Novads",
            "capital": "admin",
            "population": "",
            "id": 1428840269
        },
        {
            "city": "Aizkraukle",
            "city_ascii": "Aizkraukle",
            "lat": 56.6029,
            "lng": 25.2636,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Aizkraukles Novads",
            "capital": "admin",
            "population": "",
            "id": 1428407271
        },
        {
            "city": "Carnikava",
            "city_ascii": "Carnikava",
            "lat": 57.1293,
            "lng": 24.2842,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Carnikavas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428447982
        },
        {
            "city": "\u0136ekava",
            "city_ascii": "Kekava",
            "lat": 56.8296,
            "lng": 24.2318,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "\u0136ekavas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428331173
        },
        {
            "city": "In\u010dukalns",
            "city_ascii": "Incukalns",
            "lat": 57.0987,
            "lng": 24.6863,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "In\u010dukalna Novads",
            "capital": "admin",
            "population": "",
            "id": 1428675819
        },
        {
            "city": "Ik\u0161\u0137ile",
            "city_ascii": "Ikskile",
            "lat": 56.834,
            "lng": 24.4968,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Ik\u0161\u0137iles Novads",
            "capital": "admin",
            "population": "",
            "id": 1428284061
        },
        {
            "city": "Olaine",
            "city_ascii": "Olaine",
            "lat": 56.7947,
            "lng": 23.9358,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Olaines Novads",
            "capital": "admin",
            "population": "",
            "id": 1428220700
        },
        {
            "city": "\u0100da\u017ei",
            "city_ascii": "Adazi",
            "lat": 57.0705,
            "lng": 24.3371,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "\u0100da\u017eu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428843734
        },
        {
            "city": "Ozolnieki",
            "city_ascii": "Ozolnieki",
            "lat": 56.6899,
            "lng": 23.7761,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Ozolnieku Novads",
            "capital": "admin",
            "population": "",
            "id": 1428973455
        },
        {
            "city": "Garkalne",
            "city_ascii": "Garkalne",
            "lat": 57.0449,
            "lng": 24.4195,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Garkalnes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428447019
        },
        {
            "city": "Lielv\u0101rde",
            "city_ascii": "Lielvarde",
            "lat": 56.7213,
            "lng": 24.8062,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Lielv\u0101rdes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428614074
        },
        {
            "city": "Sigulda",
            "city_ascii": "Sigulda",
            "lat": 57.1538,
            "lng": 24.8595,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Siguldas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428703594
        },
        {
            "city": "Pi\u0146\u0137i",
            "city_ascii": "Pinki",
            "lat": 56.9419,
            "lng": 23.9137,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Bab\u012btes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428171019
        },
        {
            "city": "Ogre",
            "city_ascii": "Ogre",
            "lat": 56.8113,
            "lng": 24.6113,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Ogres Novads",
            "capital": "admin",
            "population": "",
            "id": 1428832851
        },
        {
            "city": "Skr\u012bveri",
            "city_ascii": "Skriveri",
            "lat": 56.6485,
            "lng": 25.1195,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Skr\u012bveru Novads",
            "capital": "admin",
            "population": "",
            "id": 1428849429
        },
        {
            "city": "Bauska",
            "city_ascii": "Bauska",
            "lat": 56.4079,
            "lng": 24.1944,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Bauskas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428015452
        },
        {
            "city": "Baldone",
            "city_ascii": "Baldone",
            "lat": 56.7445,
            "lng": 24.4008,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Baldones Novads",
            "capital": "admin",
            "population": "",
            "id": 1428735750
        },
        {
            "city": "Prei\u013ci",
            "city_ascii": "Preili",
            "lat": 56.294,
            "lng": 26.7248,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Prei\u013cu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428460035
        },
        {
            "city": "Iecava",
            "city_ascii": "Iecava",
            "lat": 56.5977,
            "lng": 24.2076,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Iecavas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428743931
        },
        {
            "city": "Prieku\u013ci",
            "city_ascii": "Priekuli",
            "lat": 57.3115,
            "lng": 25.3571,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Prieku\u013cu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428165145
        },
        {
            "city": "Tukums",
            "city_ascii": "Tukums",
            "lat": 56.9676,
            "lng": 23.1555,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Tukuma Novads",
            "capital": "admin",
            "population": "",
            "id": 1428304262
        },
        {
            "city": "Dobele",
            "city_ascii": "Dobele",
            "lat": 56.6237,
            "lng": 23.2751,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Dobeles Novads",
            "capital": "admin",
            "population": "",
            "id": 1428641580
        },
        {
            "city": "Vi\u013c\u0101ni",
            "city_ascii": "Vilani",
            "lat": 56.5505,
            "lng": 26.9298,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Vi\u013c\u0101nu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428636034
        },
        {
            "city": "L\u012bgatne",
            "city_ascii": "Ligatne",
            "lat": 57.2379,
            "lng": 25.0436,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "L\u012bgatnes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428643118
        },
        {
            "city": "Roja",
            "city_ascii": "Roja",
            "lat": 57.5015,
            "lng": 22.8088,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Rojas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428577367
        },
        {
            "city": "L\u012bv\u0101ni",
            "city_ascii": "Livani",
            "lat": 56.3567,
            "lng": 26.1761,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "L\u012bv\u0101nu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428769984
        },
        {
            "city": "Ropa\u017ei",
            "city_ascii": "Ropazi",
            "lat": 56.9747,
            "lng": 24.6329,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Ropa\u017eu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428220999
        },
        {
            "city": "Grobi\u0146a",
            "city_ascii": "Grobina",
            "lat": 56.5358,
            "lng": 21.1747,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Grobi\u0146as Novads",
            "capital": "admin",
            "population": "",
            "id": 1428780265
        },
        {
            "city": "Sm\u0101rde",
            "city_ascii": "Smarde",
            "lat": 56.9533,
            "lng": 23.3387,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Engures Novads",
            "capital": "admin",
            "population": "",
            "id": 1428580716
        },
        {
            "city": "Talsi",
            "city_ascii": "Talsi",
            "lat": 57.2465,
            "lng": 22.5876,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Talsu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428411666
        },
        {
            "city": "Kr\u0101slava",
            "city_ascii": "Kraslava",
            "lat": 55.8969,
            "lng": 27.172,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Kr\u0101slavas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428739484
        },
        {
            "city": "Pilsrund\u0101le",
            "city_ascii": "Pilsrundale",
            "lat": 56.4181,
            "lng": 24.0162,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Rund\u0101les Novads",
            "capital": "admin",
            "population": "",
            "id": 1428889985
        },
        {
            "city": "M\u0113rsrags",
            "city_ascii": "Mersrags",
            "lat": 57.3364,
            "lng": 23.1235,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "M\u0113rsraga Novads",
            "capital": "admin",
            "population": "",
            "id": 1428954276
        },
        {
            "city": "T\u0113rvete",
            "city_ascii": "Tervete",
            "lat": 56.4798,
            "lng": 23.3902,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "T\u0113rvetes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428176770
        },
        {
            "city": "M\u0101lpils",
            "city_ascii": "Malpils",
            "lat": 57.0101,
            "lng": 24.9578,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "M\u0101lpils Novads",
            "capital": "admin",
            "population": "",
            "id": 1428737728
        },
        {
            "city": "R\u016bjiena",
            "city_ascii": "Rujiena",
            "lat": 57.8961,
            "lng": 25.3342,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "R\u016bjienas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428387860
        },
        {
            "city": "Koknese",
            "city_ascii": "Koknese",
            "lat": 56.6516,
            "lng": 25.4364,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Kokneses Novads",
            "capital": "admin",
            "population": "",
            "id": 1428876472
        },
        {
            "city": "Saldus",
            "city_ascii": "Saldus",
            "lat": 56.6666,
            "lng": 22.4935,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Saldus Novads",
            "capital": "admin",
            "population": "",
            "id": 1428774997
        },
        {
            "city": "P\u013cavi\u0146as",
            "city_ascii": "Plavinas",
            "lat": 56.6177,
            "lng": 25.7194,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "P\u013cavi\u0146u Novads",
            "capital": "admin",
            "population": "",
            "id": 1428245037
        },
        {
            "city": "Ragana",
            "city_ascii": "Ragana",
            "lat": 57.1821,
            "lng": 24.7056,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Krimuldas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428990628
        },
        {
            "city": "Auce",
            "city_ascii": "Auce",
            "lat": 56.4611,
            "lng": 22.9028,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Auces Novads",
            "capital": "admin",
            "population": "",
            "id": 1428962592
        },
        {
            "city": "Limba\u017ei",
            "city_ascii": "Limbazi",
            "lat": 57.513,
            "lng": 24.724,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Limba\u017eu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428920312
        },
        {
            "city": "Ludza",
            "city_ascii": "Ludza",
            "lat": 56.5396,
            "lng": 27.7189,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Ludzas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428976928
        },
        {
            "city": "Cesvaine",
            "city_ascii": "Cesvaine",
            "lat": 56.9675,
            "lng": 26.3076,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Cesvaines Novads",
            "capital": "admin",
            "population": "",
            "id": 1428611306
        },
        {
            "city": "Aizpute",
            "city_ascii": "Aizpute",
            "lat": 56.7211,
            "lng": 21.6016,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Aizputes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428860274
        },
        {
            "city": "Kuld\u012bga",
            "city_ascii": "Kuldiga",
            "lat": 56.969,
            "lng": 21.968,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Kuld\u012bgas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428739306
        },
        {
            "city": "Kandava",
            "city_ascii": "Kandava",
            "lat": 57.0389,
            "lng": 22.7724,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Kandavas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428964284
        },
        {
            "city": "Smiltene",
            "city_ascii": "Smiltene",
            "lat": 57.4242,
            "lng": 25.9017,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Smiltenes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428035157
        },
        {
            "city": "Balvi",
            "city_ascii": "Balvi",
            "lat": 57.1287,
            "lng": 27.27,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Balvu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428606162
        },
        {
            "city": "Salacgr\u012bva",
            "city_ascii": "Salacgriva",
            "lat": 57.7531,
            "lng": 24.359,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Salacgr\u012bvas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428301933
        },
        {
            "city": "Il\u016bkste",
            "city_ascii": "Ilukste",
            "lat": 55.9779,
            "lng": 26.2978,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Il\u016bkstes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428832647
        },
        {
            "city": "Sala",
            "city_ascii": "Sala",
            "lat": 56.5047,
            "lng": 25.7618,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Salas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428593161
        },
        {
            "city": "Broc\u0113ni",
            "city_ascii": "Broceni",
            "lat": 56.6789,
            "lng": 22.5694,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Broc\u0113nu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428026538
        },
        {
            "city": "Varak\u013c\u0101ni",
            "city_ascii": "Varaklani",
            "lat": 56.6091,
            "lng": 26.7547,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Varak\u013c\u0101nu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428435689
        },
        {
            "city": "Koc\u0113ni",
            "city_ascii": "Koceni",
            "lat": 57.5198,
            "lng": 25.3404,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Koc\u0113nu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428151958
        },
        {
            "city": "Jaunpils",
            "city_ascii": "Jaunpils",
            "lat": 56.7314,
            "lng": 23.0125,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Jaunpils Novads",
            "capital": "admin",
            "population": "",
            "id": 1428617492
        },
        {
            "city": "Gulbene",
            "city_ascii": "Gulbene",
            "lat": 57.1734,
            "lng": 26.7527,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Gulbenes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428888445
        },
        {
            "city": "\u0136egums",
            "city_ascii": "Kegums",
            "lat": 56.7455,
            "lng": 24.725,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "\u0136eguma Novads",
            "capital": "admin",
            "population": "",
            "id": 1428359846
        },
        {
            "city": "Madona",
            "city_ascii": "Madona",
            "lat": 56.851,
            "lng": 26.2184,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Madonas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428548117
        },
        {
            "city": "Rauna",
            "city_ascii": "Rauna",
            "lat": 57.3337,
            "lng": 25.6085,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Raunas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428987270
        },
        {
            "city": "Priekule",
            "city_ascii": "Priekule",
            "lat": 56.4458,
            "lng": 21.5939,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Priekules Novads",
            "capital": "admin",
            "population": "",
            "id": 1428340962
        },
        {
            "city": "Burtnieki",
            "city_ascii": "Burtnieki",
            "lat": 57.6949,
            "lng": 25.275,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Burtnieku Novads",
            "capital": "admin",
            "population": "",
            "id": 1428423415
        },
        {
            "city": "M\u016brmui\u017ea",
            "city_ascii": "Murmuiza",
            "lat": 57.4731,
            "lng": 25.4917,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Bever\u012bnas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428958481
        },
        {
            "city": "Aglona",
            "city_ascii": "Aglona",
            "lat": 56.1327,
            "lng": 27.0068,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Aglonas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428424524
        },
        {
            "city": "N\u012bca",
            "city_ascii": "Nica",
            "lat": 56.3456,
            "lng": 21.0646,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "N\u012bcas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428762389
        },
        {
            "city": "Valka",
            "city_ascii": "Valka",
            "lat": 57.7767,
            "lng": 26.0118,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Valkas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428763918
        },
        {
            "city": "Zilupe",
            "city_ascii": "Zilupe",
            "lat": 56.386,
            "lng": 28.1218,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Zilupes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428917349
        },
        {
            "city": "Al\u016bksne",
            "city_ascii": "Aluksne",
            "lat": 57.4216,
            "lng": 27.0466,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Al\u016bksnes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428873095
        },
        {
            "city": "Akn\u012bste",
            "city_ascii": "Akniste",
            "lat": 56.1615,
            "lng": 25.7482,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Akn\u012bstes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428363907
        },
        {
            "city": "Vecumnieki",
            "city_ascii": "Vecumnieki",
            "lat": 56.6061,
            "lng": 24.5223,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Vecumnieku Novads",
            "capital": "admin",
            "population": "",
            "id": 1428888119
        },
        {
            "city": "Stren\u010di",
            "city_ascii": "Strenci",
            "lat": 57.6269,
            "lng": 25.6919,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Stren\u010du Novads",
            "capital": "admin",
            "population": "",
            "id": 1428746601
        },
        {
            "city": "Loja",
            "city_ascii": "Loja",
            "lat": 57.1534,
            "lng": 24.6433,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "S\u0113jas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428831058
        },
        {
            "city": "Skrunda",
            "city_ascii": "Skrunda",
            "lat": 56.6775,
            "lng": 22.0165,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Skrundas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428371210
        },
        {
            "city": "Lie\u0123i",
            "city_ascii": "Liegi",
            "lat": 56.5797,
            "lng": 21.3338,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Durbes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428643853
        },
        {
            "city": "K\u0101rsava",
            "city_ascii": "Karsava",
            "lat": 56.7874,
            "lng": 27.6732,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "K\u0101rsavas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428849607
        },
        {
            "city": "Jaunpiebalga",
            "city_ascii": "Jaunpiebalga",
            "lat": 57.1775,
            "lng": 26.0284,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Jaunpiebalgas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428003359
        },
        {
            "city": "Riebi\u0146i",
            "city_ascii": "Riebini",
            "lat": 56.3403,
            "lng": 26.7999,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Riebi\u0146u Novads",
            "capital": "admin",
            "population": "",
            "id": 1428663476
        },
        {
            "city": "Jaunjelgava",
            "city_ascii": "Jaunjelgava",
            "lat": 56.6132,
            "lng": 25.0832,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Jaunjelgavas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428755180
        },
        {
            "city": "Dagda",
            "city_ascii": "Dagda",
            "lat": 56.0961,
            "lng": 27.5328,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Dagdas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428145757
        },
        {
            "city": "Vi\u013caka",
            "city_ascii": "Vilaka",
            "lat": 57.1843,
            "lng": 27.6719,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Vi\u013cakas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428268339
        },
        {
            "city": "Aloja",
            "city_ascii": "Aloja",
            "lat": 57.7672,
            "lng": 24.8774,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Alojas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428805342
        },
        {
            "city": "Vai\u0146ode",
            "city_ascii": "Vainode",
            "lat": 56.4185,
            "lng": 21.8541,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Vai\u0146odes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428647067
        },
        {
            "city": "\u0112rg\u013ci",
            "city_ascii": "Ergli",
            "lat": 56.8988,
            "lng": 25.6429,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "\u0112rg\u013cu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428672513
        },
        {
            "city": "Mazsalaca",
            "city_ascii": "Mazsalaca",
            "lat": 57.8619,
            "lng": 25.0547,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Mazsalacas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428775090
        },
        {
            "city": "Stalbe",
            "city_ascii": "Stalbe",
            "lat": 57.3708,
            "lng": 25.0324,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "P\u0101rgaujas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428014091
        },
        {
            "city": "Vecpiebalga",
            "city_ascii": "Vecpiebalga",
            "lat": 57.0618,
            "lng": 25.8179,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Vecpiebalgas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428633596
        },
        {
            "city": "Alsunga",
            "city_ascii": "Alsunga",
            "lat": 56.9801,
            "lng": 21.564,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Alsungas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428710208
        },
        {
            "city": "Drabe\u0161i",
            "city_ascii": "Drabesi",
            "lat": 57.2433,
            "lng": 25.2803,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Amatas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428886151
        },
        {
            "city": "Vecv\u0101rkava",
            "city_ascii": "Vecvarkava",
            "lat": 56.1984,
            "lng": 26.5081,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "V\u0101rkavas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428075811
        },
        {
            "city": "Lub\u0101na",
            "city_ascii": "Lubana",
            "lat": 56.9043,
            "lng": 26.7161,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Lub\u0101nas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428963436
        },
        {
            "city": "Nauk\u0161\u0113ni",
            "city_ascii": "Naukseni",
            "lat": 57.8842,
            "lng": 25.458,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Nauk\u0161\u0113nu Novads",
            "capital": "admin",
            "population": "",
            "id": 1428372673
        },
        {
            "city": "Ape",
            "city_ascii": "Ape",
            "lat": 57.5394,
            "lng": 26.694,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Apes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428396055
        },
        {
            "city": "Baltinava",
            "city_ascii": "Baltinava",
            "lat": 56.9439,
            "lng": 27.644,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Baltinavas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428769707
        },
        {
            "city": "Dundaga",
            "city_ascii": "Dundaga",
            "lat": 57.505,
            "lng": 22.3504,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Dundagas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428711022
        },
        {
            "city": "Vies\u012bte",
            "city_ascii": "Viesite",
            "lat": 56.3465,
            "lng": 25.5581,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Vies\u012btes Novads",
            "capital": "admin",
            "population": "",
            "id": 1428998036
        },
        {
            "city": "Nereta",
            "city_ascii": "Nereta",
            "lat": 56.2044,
            "lng": 25.3077,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Neretas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428242925
        },
        {
            "city": "Cibla",
            "city_ascii": "Cibla",
            "lat": 56.5498,
            "lng": 27.8837,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Ciblas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428931914
        },
        {
            "city": "P\u0101vilosta",
            "city_ascii": "Pavilosta",
            "lat": 56.8898,
            "lng": 21.1817,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "P\u0101vilostas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428955629
        },
        {
            "city": "Rug\u0101ji",
            "city_ascii": "Rugaji",
            "lat": 57.0033,
            "lng": 27.1337,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Rug\u0101ju Novads",
            "capital": "admin",
            "population": "",
            "id": 1428746884
        },
        {
            "city": "Rucava",
            "city_ascii": "Rucava",
            "lat": 56.164,
            "lng": 21.1627,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "Rucavas Novads",
            "capital": "admin",
            "population": "",
            "id": 1428020890
        }
    ]
}