module.exports = {
    CITIES: [{
            "city": "Port of Spain",
            "city_ascii": "Port of Spain",
            "lat": 10.652,
            "lng": -61.517,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Port of Spain",
            "capital": "primary",
            "population": 294934,
            "id": 1780670676
        },
        {
            "city": "Bridgetown",
            "city_ascii": "Bridgetown",
            "lat": 13.102,
            "lng": -59.6165,
            "country": "Barbados",
            "iso2": "BB",
            "iso3": "BRB",
            "admin_name": "Saint Michael",
            "capital": "primary",
            "population": 191152,
            "id": 1052274244
        },
        {
            "city": "Castries",
            "city_ascii": "Castries",
            "lat": 14.002,
            "lng": -61,
            "country": "Saint Lucia",
            "iso2": "LC",
            "iso3": "LCA",
            "admin_name": "Castries",
            "capital": "primary",
            "population": 37963,
            "id": 1662922505
        },
        {
            "city": "Saint John\u2019s",
            "city_ascii": "Saint John's",
            "lat": 17.118,
            "lng": -61.85,
            "country": "Antigua And Barbuda",
            "iso2": "AG",
            "iso3": "ATG",
            "admin_name": "Saint John",
            "capital": "primary",
            "population": 35499,
            "id": 1028912067
        },
        {
            "city": "Saint George\u2019s",
            "city_ascii": "Saint George's",
            "lat": 12.0526,
            "lng": -61.7416,
            "country": "Grenada",
            "iso2": "GD",
            "iso3": "GRD",
            "admin_name": "Saint George",
            "capital": "primary",
            "population": 33734,
            "id": 1308891766
        },
        {
            "city": "Roseau",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/RoseauWide..jpg/300px-RoseauWide..jpg",
            "city_ascii": "Roseau",
            "lat": 15.301,
            "lng": -61.387,
            "country": "Dominica",
            "iso2": "DM",
            "iso3": "DMA",
            "admin_name": "Saint George",
            "capital": "primary",
            "population": 23336,
            "id": 1212060440
        },
        {
            "city": "Basseterre",
            "city_ascii": "Basseterre",
            "lat": 17.302,
            "lng": -62.717,
            "country": "Saint Kitts And Nevis",
            "iso2": "KN",
            "iso3": "KNA",
            "admin_name": "Saint George Basseterre",
            "capital": "primary",
            "population": 21887,
            "id": 1659198919
        },
        {
            "city": "San Fernando",
            "city_ascii": "San Fernando",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/STAPP_008_San_Fernando_Independence_Avenue_%28cropped%29.jpg/800px-STAPP_008_San_Fernando_Independence_Avenue_%28cropped%29.jpg",
            "lat": 10.2805,
            "lng": -61.4594,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "San Fernando",
            "capital": "admin",
            "population": 166039,
            "id": 1780361077
        },
        {
            "city": "Arima",
            "city_ascii": "Arima",
            "lat": 10.6374,
            "lng": -61.2823,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Arima",
            "capital": "admin",
            "population": "",
            "id": 1780753308
        },
        {
            "city": "Chaguanas",
            "city_ascii": "Chaguanas",
            "lat": 10.5167,
            "lng": -61.4167,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Chaguanas",
            "capital": "admin",
            "population": "",
            "id": 1780795054
        },
        {
            "city": "Scarborough",
            "city_ascii": "Scarborough",
            "lat": 11.1811,
            "lng": -60.7333,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Tobago",
            "capital": "admin",
            "population": "",
            "id": 1780875399
        },
        {
            "city": "Diego Martin",
            "city_ascii": "Diego Martin",
            "lat": 10.7208,
            "lng": -61.5662,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Diego Martin",
            "capital": "admin",
            "population": "",
            "id": 1780534918
        },
        {
            "city": "Point Fortin",
            "city_ascii": "Point Fortin",
            "lat": 10.1741,
            "lng": -61.6841,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Point Fortin",
            "capital": "admin",
            "population": "",
            "id": 1780702349
        },
        {
            "city": "Aranguez",
            "city_ascii": "Aranguez",
            "lat": 10.6472,
            "lng": -61.4461,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "San Juan/Laventille",
            "capital": "admin",
            "population": "",
            "id": 1780000001
        },
        {
            "city": "Tunapuna",
            "city_ascii": "Tunapuna",
            "lat": 10.6524,
            "lng": -61.3888,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Tunapuna/Piarco",
            "capital": "admin",
            "population": "",
            "id": 1780508155
        },
        {
            "city": "Debe",
            "city_ascii": "Debe",
            "lat": 10.2085,
            "lng": -61.4527,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Penal/Debe",
            "capital": "admin",
            "population": "",
            "id": 1780510715
        },
        {
            "city": "Couva",
            "city_ascii": "Couva",
            "lat": 10.4232,
            "lng": -61.4618,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Couva/Tabaquite/Talparo",
            "capital": "admin",
            "population": "",
            "id": 1780835692
        },
        {
            "city": "Siparia",
            "city_ascii": "Siparia",
            "lat": 10.1453,
            "lng": -61.5074,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Siparia",
            "capital": "admin",
            "population": "",
            "id": 1780418671
        },
        {
            "city": "Princes Town",
            "city_ascii": "Princes Town",
            "lat": 10.2718,
            "lng": -61.371,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Princes Town",
            "capital": "admin",
            "population": "",
            "id": 1780714817
        },
        {
            "city": "Sangre Grande",
            "city_ascii": "Sangre Grande",
            "lat": 10.5871,
            "lng": -61.1322,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Sangre Grande",
            "capital": "admin",
            "population": "",
            "id": 1780469686
        },
        {
            "city": "Rio Claro",
            "city_ascii": "Rio Claro",
            "lat": 10.3059,
            "lng": -61.1756,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Mayaro/Rio Claro",
            "capital": "admin",
            "population": "",
            "id": 1780883666
        }
    ]
}