module.exports = {
    CITIES: [{
            "city": "Vaduz",
            "city_ascii": "Vaduz",
            "lat": 47.1337,
            "lng": 9.5167,
            "country": "Liechtenstein",
            "iso2": "LI",
            "iso3": "LIE",
            "admin_name": "Vaduz",
            "capital": "primary",
            "population": 36281,
            "id": 1438317747
        },
        {
            "city": "Mauren",
            "city_ascii": "Mauren",
            "lat": 47.2205,
            "lng": 9.5426,
            "country": "Liechtenstein",
            "iso2": "LI",
            "iso3": "LIE",
            "admin_name": "Mauren",
            "capital": "admin",
            "population": "",
            "id": 1438767966
        },
        {
            "city": "Eschen",
            "city_ascii": "Eschen",
            "lat": 47.2109,
            "lng": 9.5216,
            "country": "Liechtenstein",
            "iso2": "LI",
            "iso3": "LIE",
            "admin_name": "Eschen",
            "capital": "admin",
            "population": "",
            "id": 1438692471
        },
        {
            "city": "Schellenberg",
            "city_ascii": "Schellenberg",
            "lat": 47.2325,
            "lng": 9.5463,
            "country": "Liechtenstein",
            "iso2": "LI",
            "iso3": "LIE",
            "admin_name": "Schellenberg",
            "capital": "admin",
            "population": "",
            "id": 1438649917
        },
        {
            "city": "Ruggell",
            "city_ascii": "Ruggell",
            "lat": 47.2408,
            "lng": 9.5247,
            "country": "Liechtenstein",
            "iso2": "LI",
            "iso3": "LIE",
            "admin_name": "Ruggell",
            "capital": "admin",
            "population": "",
            "id": 1438787609
        },
        {
            "city": "Gamprin",
            "city_ascii": "Gamprin",
            "lat": 47.2197,
            "lng": 9.5113,
            "country": "Liechtenstein",
            "iso2": "LI",
            "iso3": "LIE",
            "admin_name": "Gamprin",
            "capital": "admin",
            "population": "",
            "id": 1438568521
        },
        {
            "city": "Schaan",
            "city_ascii": "Schaan",
            "lat": 47.1661,
            "lng": 9.5096,
            "country": "Liechtenstein",
            "iso2": "LI",
            "iso3": "LIE",
            "admin_name": "Schaan",
            "capital": "admin",
            "population": "",
            "id": 1438982330
        },
        {
            "city": "Balzers",
            "city_ascii": "Balzers",
            "lat": 47.0667,
            "lng": 9.5025,
            "country": "Liechtenstein",
            "iso2": "LI",
            "iso3": "LIE",
            "admin_name": "Balzers",
            "capital": "admin",
            "population": "",
            "id": 1438263000
        },
        {
            "city": "Triesen",
            "city_ascii": "Triesen",
            "lat": 47.1101,
            "lng": 9.524,
            "country": "Liechtenstein",
            "iso2": "LI",
            "iso3": "LIE",
            "admin_name": "Triesen",
            "capital": "admin",
            "population": "",
            "id": 1438826448
        },
        {
            "city": "Planken",
            "city_ascii": "Planken",
            "lat": 47.1844,
            "lng": 9.5436,
            "country": "Liechtenstein",
            "iso2": "LI",
            "iso3": "LIE",
            "admin_name": "Planken",
            "capital": "admin",
            "population": "",
            "id": 1438419168
        },
        {
            "city": "Triesenberg",
            "city_ascii": "Triesenberg",
            "lat": 47.1182,
            "lng": 9.5444,
            "country": "Liechtenstein",
            "iso2": "LI",
            "iso3": "LIE",
            "admin_name": "Triesenberg",
            "capital": "admin",
            "population": "",
            "id": 1438813592
        }
    ]
}