module.exports = {
    CITIES: [{
            "city": "Vilnius",
            "city_ascii": "Vilnius",
            "lat": 54.6834,
            "lng": 25.3166,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Vilniaus Miestas",
            "capital": "primary",
            "population": 542366,
            "id": 1440887149
        },
        {
            "city": "Kaunas",
            "city_ascii": "Kaunas",
            "lat": 54.9504,
            "lng": 23.88,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Kauno Miestas",
            "capital": "admin",
            "population": 374643,
            "id": 1440302852
        },
        {
            "city": "Klaip\u0117da",
            "city_ascii": "Klaipeda",
            "lat": 55.7204,
            "lng": 21.1199,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Klaip\u0117dos Miestas",
            "capital": "admin",
            "population": 192307,
            "id": 1440897790
        },
        {
            "city": "\u0160iauliai",
            "city_ascii": "Siauliai",
            "lat": 55.9386,
            "lng": 23.325,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "\u0160iauli\u0173 Miestas",
            "capital": "admin",
            "population": 133528,
            "id": 1440593416
        },
        {
            "city": "Panev\u0117\u017eys",
            "city_ascii": "Panevezys",
            "lat": 55.74,
            "lng": 24.37,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Panev\u0117\u017eio Miestas",
            "capital": "admin",
            "population": 127405,
            "id": 1440120065
        },
        {
            "city": "Alytus",
            "city_ascii": "Alytus",
            "lat": 54.3964,
            "lng": 24.0414,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Alytaus Miestas",
            "capital": "admin",
            "population": "",
            "id": 1440273296
        },
        {
            "city": "Visaginas",
            "city_ascii": "Visaginas",
            "lat": 55.5968,
            "lng": 26.4398,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Visaginas",
            "capital": "admin",
            "population": "",
            "id": 1440984232
        },
        {
            "city": "Palanga",
            "city_ascii": "Palanga",
            "lat": 55.9203,
            "lng": 21.071,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Palangos Miestas",
            "capital": "admin",
            "population": "",
            "id": 1440868798
        },
        {
            "city": "Marijampol\u0117",
            "city_ascii": "Marijampole",
            "lat": 54.5599,
            "lng": 23.3541,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Marijampol\u0117",
            "capital": "admin",
            "population": "",
            "id": 1440180524
        },
        {
            "city": "Elektr\u0117nai",
            "city_ascii": "Elektrenai",
            "lat": 54.7863,
            "lng": 24.6626,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Elektr\u00e9nai",
            "capital": "admin",
            "population": "",
            "id": 1440272776
        },
        {
            "city": "Jonava",
            "city_ascii": "Jonava",
            "lat": 55.0801,
            "lng": 24.2754,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Jonava",
            "capital": "admin",
            "population": "",
            "id": 1440040612
        },
        {
            "city": "Druskininkai",
            "city_ascii": "Druskininkai",
            "lat": 54.0157,
            "lng": 23.987,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Druskininkai",
            "capital": "admin",
            "population": "",
            "id": 1440489111
        },
        {
            "city": "Ma\u017eeikiai",
            "city_ascii": "Mazeikiai",
            "lat": 56.3122,
            "lng": 22.3265,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Ma\u017eeikiai",
            "capital": "admin",
            "population": "",
            "id": 1440746512
        },
        {
            "city": "Kretinga",
            "city_ascii": "Kretinga",
            "lat": 55.8888,
            "lng": 21.2445,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Kretinga",
            "capital": "admin",
            "population": "",
            "id": 1440720895
        },
        {
            "city": "Trakai",
            "city_ascii": "Trakai",
            "lat": 54.6399,
            "lng": 24.936,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Trakai",
            "capital": "admin",
            "population": "",
            "id": 1440324561
        },
        {
            "city": "Bir\u0161tonas",
            "city_ascii": "Birstonas",
            "lat": 54.6048,
            "lng": 24.0311,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Bir\u0161tono",
            "capital": "admin",
            "population": "",
            "id": 1440134144
        },
        {
            "city": "Utena",
            "city_ascii": "Utena",
            "lat": 55.4976,
            "lng": 25.5992,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Utena",
            "capital": "admin",
            "population": "",
            "id": 1440298742
        },
        {
            "city": "Taurag\u0117",
            "city_ascii": "Taurage",
            "lat": 55.2522,
            "lng": 22.2897,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Taurag\u0117",
            "capital": "admin",
            "population": "",
            "id": 1440115384
        },
        {
            "city": "Plung\u0117",
            "city_ascii": "Plunge",
            "lat": 55.9077,
            "lng": 21.8456,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Plung\u0117",
            "capital": "admin",
            "population": "",
            "id": 1440542185
        },
        {
            "city": "\u0160ilut\u0117",
            "city_ascii": "Silute",
            "lat": 55.3453,
            "lng": 21.4733,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "\u0160ilut\u0117",
            "capital": "admin",
            "population": "",
            "id": 1440568024
        },
        {
            "city": "Vilkavi\u0161kis",
            "city_ascii": "Vilkaviskis",
            "lat": 54.648,
            "lng": 23.0305,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Vilkavi\u0161kis",
            "capital": "admin",
            "population": "",
            "id": 1440557692
        },
        {
            "city": "Tel\u0161iai",
            "city_ascii": "Telsiai",
            "lat": 55.9831,
            "lng": 22.2343,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Tel\u0161iai",
            "capital": "admin",
            "population": "",
            "id": 1440908000
        },
        {
            "city": "K\u0117dainiai",
            "city_ascii": "Kedainiai",
            "lat": 55.2878,
            "lng": 23.9727,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "K\u0117dainiai",
            "capital": "admin",
            "population": "",
            "id": 1440351434
        },
        {
            "city": "Kai\u0161iadorys",
            "city_ascii": "Kaisiadorys",
            "lat": 54.8653,
            "lng": 24.4682,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Kai\u0161iadorys",
            "capital": "admin",
            "population": "",
            "id": 1440257941
        },
        {
            "city": "Nida",
            "city_ascii": "Nida",
            "lat": 55.3086,
            "lng": 20.9965,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Neringa",
            "capital": "admin",
            "population": "",
            "id": 1440271703
        },
        {
            "city": "Prienai",
            "city_ascii": "Prienai",
            "lat": 54.636,
            "lng": 23.9458,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Prienai",
            "capital": "admin",
            "population": "",
            "id": 1440412268
        },
        {
            "city": "Ukmerg\u0117",
            "city_ascii": "Ukmerge",
            "lat": 55.2494,
            "lng": 24.7636,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Ukmerg\u0117",
            "capital": "admin",
            "population": "",
            "id": 1440784663
        },
        {
            "city": "Akmen\u0117",
            "city_ascii": "Akmene",
            "lat": 56.25,
            "lng": 22.75,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Akmen\u0117",
            "capital": "admin",
            "population": "",
            "id": 1440240618
        },
        {
            "city": "Kalvarija",
            "city_ascii": "Kalvarija",
            "lat": 54.4172,
            "lng": 23.2283,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Kalvarijos",
            "capital": "admin",
            "population": "",
            "id": 1440799248
        },
        {
            "city": "Radvili\u0161kis",
            "city_ascii": "Radviliskis",
            "lat": 55.8111,
            "lng": 23.5411,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Radvili\u0161kis",
            "capital": "admin",
            "population": "",
            "id": 1440712589
        },
        {
            "city": "Kazl\u0173 R\u016bda",
            "city_ascii": "Kazlu Ruda",
            "lat": 54.7497,
            "lng": 23.495,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Kazl\u0173 R\u016bdos",
            "capital": "admin",
            "population": "",
            "id": 1440371651
        },
        {
            "city": "Raseiniai",
            "city_ascii": "Raseiniai",
            "lat": 55.3797,
            "lng": 23.1239,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Raseiniai",
            "capital": "admin",
            "population": "",
            "id": 1440481520
        },
        {
            "city": "\u0160ilal\u0117",
            "city_ascii": "Silale",
            "lat": 55.4898,
            "lng": 22.1869,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "\u0160ilal\u0117",
            "capital": "admin",
            "population": "",
            "id": 1440106904
        },
        {
            "city": "\u0160akiai",
            "city_ascii": "Sakiai",
            "lat": 54.9534,
            "lng": 23.0478,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "\u0160akiai",
            "capital": "admin",
            "population": "",
            "id": 1440362808
        },
        {
            "city": "\u0160al\u010dininkai",
            "city_ascii": "Salcininkai",
            "lat": 54.3086,
            "lng": 25.3868,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "\u0160al\u010dininkai",
            "capital": "admin",
            "population": "",
            "id": 1440401402
        },
        {
            "city": "Joni\u0161kis",
            "city_ascii": "Joniskis",
            "lat": 56.2394,
            "lng": 23.6154,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Joni\u0161kis",
            "capital": "admin",
            "population": "",
            "id": 1440592411
        },
        {
            "city": "Pasvalys",
            "city_ascii": "Pasvalys",
            "lat": 56.0625,
            "lng": 24.3997,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Pasvalys",
            "capital": "admin",
            "population": "",
            "id": 1440957197
        },
        {
            "city": "Skuodas",
            "city_ascii": "Skuodas",
            "lat": 56.2706,
            "lng": 21.5321,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Skuodas",
            "capital": "admin",
            "population": "",
            "id": 1440264405
        },
        {
            "city": "\u0160irvintos",
            "city_ascii": "Sirvintos",
            "lat": 55.044,
            "lng": 24.9545,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "\u0160irvintos",
            "capital": "admin",
            "population": "",
            "id": 1440054141
        },
        {
            "city": "Roki\u0161kis",
            "city_ascii": "Rokiskis",
            "lat": 55.9587,
            "lng": 25.5947,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Roki\u0161kis",
            "capital": "admin",
            "population": "",
            "id": 1440918695
        },
        {
            "city": "Jurbarkas",
            "city_ascii": "Jurbarkas",
            "lat": 55.0756,
            "lng": 22.7642,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Jurbarkas",
            "capital": "admin",
            "population": "",
            "id": 1440845969
        },
        {
            "city": "Kelm\u0117",
            "city_ascii": "Kelme",
            "lat": 55.6301,
            "lng": 22.9349,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Kelm\u0117",
            "capital": "admin",
            "population": "",
            "id": 1440476751
        },
        {
            "city": "Kupi\u0161kis",
            "city_ascii": "Kupiskis",
            "lat": 55.8401,
            "lng": 24.9803,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Kupi\u0161kis",
            "capital": "admin",
            "population": "",
            "id": 1440122297
        },
        {
            "city": "Bir\u017eai",
            "city_ascii": "Birzai",
            "lat": 56.1986,
            "lng": 24.7521,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Bir\u017eai",
            "capital": "admin",
            "population": "",
            "id": 1440132489
        },
        {
            "city": "Pag\u0117giai",
            "city_ascii": "Pagegiai",
            "lat": 55.1379,
            "lng": 21.9138,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Pag\u00e9giai",
            "capital": "admin",
            "population": "",
            "id": 1440724133
        },
        {
            "city": "Pakruojis",
            "city_ascii": "Pakruojis",
            "lat": 55.9789,
            "lng": 23.8551,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Pakruojis",
            "capital": "admin",
            "population": "",
            "id": 1440570493
        },
        {
            "city": "Lazdijai",
            "city_ascii": "Lazdijai",
            "lat": 54.2333,
            "lng": 23.5147,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Lazdijai",
            "capital": "admin",
            "population": "",
            "id": 1440584882
        },
        {
            "city": "\u0160ven\u010dionys",
            "city_ascii": "Svencionys",
            "lat": 55.133,
            "lng": 26.1595,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "\u0160ven\u010dionys",
            "capital": "admin",
            "population": "",
            "id": 1440170338
        },
        {
            "city": "Anyk\u0161\u010diai",
            "city_ascii": "Anyksciai",
            "lat": 55.5246,
            "lng": 25.1066,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Anyk\u0161\u010diai",
            "capital": "admin",
            "population": "",
            "id": 1440174702
        },
        {
            "city": "Zarasai",
            "city_ascii": "Zarasai",
            "lat": 55.7322,
            "lng": 26.2512,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Zarasai",
            "capital": "admin",
            "population": "",
            "id": 1440450872
        },
        {
            "city": "Mol\u0117tai",
            "city_ascii": "Moletai",
            "lat": 55.2247,
            "lng": 25.4169,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Mol\u0117tai",
            "capital": "admin",
            "population": "",
            "id": 1440110307
        },
        {
            "city": "Rietavas",
            "city_ascii": "Rietavas",
            "lat": 55.7271,
            "lng": 21.9234,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Rietavo",
            "capital": "admin",
            "population": "",
            "id": 1440780088
        },
        {
            "city": "Ignalina",
            "city_ascii": "Ignalina",
            "lat": 55.3406,
            "lng": 26.1605,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Ignalina",
            "capital": "admin",
            "population": "",
            "id": 1440789779
        },
        {
            "city": "Var\u0117na",
            "city_ascii": "Varena",
            "lat": 54.2155,
            "lng": 24.5754,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Var\u0117na",
            "capital": "admin",
            "population": "",
            "id": 1440933251
        }
    ]
}