module.exports = {
    CITIES: [{
            "city": "Bamako",
            "city_ascii": "Bamako",
            "lat": 12.65,
            "lng": -8,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Bamako",
            "capital": "primary",
            "population": 1494000,
            "id": 1466965925
        },
        {
            "city": "Sikasso",
            "city_ascii": "Sikasso",
            "lat": 11.3204,
            "lng": -5.68,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Sikasso",
            "capital": "admin",
            "population": 225753,
            "id": 1466666150
        },
        {
            "city": "S\u00e9gou",
            "city_ascii": "Segou",
            "lat": 13.44,
            "lng": -6.26,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "S\u00e9gou",
            "capital": "admin",
            "population": 122952,
            "id": 1466684950
        },
        {
            "city": "Gao",
            "city_ascii": "Gao",
            "lat": 16.2666,
            "lng": -0.05,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Gao",
            "capital": "admin",
            "population": 116967,
            "id": 1466571211
        },
        {
            "city": "Mopti",
            "city_ascii": "Mopti",
            "lat": 14.49,
            "lng": -4.18,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Mopti",
            "capital": "admin",
            "population": 108456,
            "id": 1466352252
        },
        {
            "city": "Koutiala",
            "city_ascii": "Koutiala",
            "lat": 12.3904,
            "lng": -5.47,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Sikasso",
            "capital": "minor",
            "population": 104927,
            "id": 1466253368
        },
        {
            "city": "Kayes",
            "city_ascii": "Kayes",
            "lat": 14.45,
            "lng": -11.44,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Kayes",
            "capital": "admin",
            "population": 77207,
            "id": 1466546429
        },
        {
            "city": "Timbuktu",
            "city_ascii": "Timbuktu",
            "lat": 16.7666,
            "lng": -3.0166,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Tombouctou",
            "capital": "admin",
            "population": 68872,
            "id": 1466595315
        },
        {
            "city": "Koulikoro",
            "city_ascii": "Koulikoro",
            "lat": 12.8833,
            "lng": -7.55,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Koulikoro",
            "capital": "admin",
            "population": 23919,
            "id": 1466411645
        },
        {
            "city": "Kidal",
            "city_ascii": "Kidal",
            "lat": 18.4411,
            "lng": 1.4078,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Kidal",
            "capital": "admin",
            "population": "",
            "id": 1466444510
        },
        {
            "city": "Kati",
            "city_ascii": "Kati",
            "lat": 12.7504,
            "lng": -8.08,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Koulikoro",
            "capital": "minor",
            "population": 66895,
            "id": 1466006801
        },
        {
            "city": "Markala",
            "city_ascii": "Markala",
            "lat": 13.6704,
            "lng": -6.07,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "S\u00e9gou",
            "capital": "",
            "population": 53738,
            "id": 1466526342
        },
        {
            "city": "Kita",
            "city_ascii": "Kita",
            "lat": 13.0504,
            "lng": -9.4833,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Kayes",
            "capital": "minor",
            "population": 46435,
            "id": 1466078415
        },
        {
            "city": "San",
            "city_ascii": "San",
            "lat": 13.3004,
            "lng": -4.9,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "S\u00e9gou",
            "capital": "minor",
            "population": 41386,
            "id": 1466198810
        },
        {
            "city": "Bougouni",
            "city_ascii": "Bougouni",
            "lat": 11.4204,
            "lng": -7.49,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Sikasso",
            "capital": "minor",
            "population": 35450,
            "id": 1466902797
        },
        {
            "city": "Djenn\u00e9",
            "city_ascii": "Djenne",
            "lat": 13.9,
            "lng": -4.55,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Mopti",
            "capital": "minor",
            "population": 32944,
            "id": 1466017388
        },
        {
            "city": "Banamba",
            "city_ascii": "Banamba",
            "lat": 13.5504,
            "lng": -7.45,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Koulikoro",
            "capital": "minor",
            "population": 30591,
            "id": 1466760822
        },
        {
            "city": "Bour\u00e8m Guindou",
            "city_ascii": "Bourem Guindou",
            "lat": 16.9004,
            "lng": -0.35,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Gao",
            "capital": "",
            "population": 30000,
            "id": 1466124401
        },
        {
            "city": "Bafoulab\u00e9",
            "city_ascii": "Bafoulabe",
            "lat": 13.8004,
            "lng": -10.82,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Kayes",
            "capital": "minor",
            "population": 26823,
            "id": 1466740370
        },
        {
            "city": "Nara",
            "city_ascii": "Nara",
            "lat": 15.18,
            "lng": -7.28,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Koulikoro",
            "capital": "minor",
            "population": 18459,
            "id": 1466925477
        },
        {
            "city": "Kangaba",
            "city_ascii": "Kangaba",
            "lat": 11.9404,
            "lng": -8.44,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Koulikoro",
            "capital": "minor",
            "population": 17232,
            "id": 1466770326
        },
        {
            "city": "Nioro",
            "city_ascii": "Nioro",
            "lat": 15.2304,
            "lng": -9.59,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Kayes",
            "capital": "minor",
            "population": 14421,
            "id": 1466532076
        },
        {
            "city": "M\u00e9naka",
            "city_ascii": "Menaka",
            "lat": 15.9167,
            "lng": 2.4,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Gao",
            "capital": "minor",
            "population": 9110,
            "id": 1466373205
        },
        {
            "city": "Goundam",
            "city_ascii": "Goundam",
            "lat": 16.417,
            "lng": -3.6666,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Tombouctou",
            "capital": "minor",
            "population": 8456,
            "id": 1466655191
        },
        {
            "city": "Tessalit",
            "city_ascii": "Tessalit",
            "lat": 20.2014,
            "lng": 1.0888,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Kidal",
            "capital": "minor",
            "population": 6000,
            "id": 1466140377
        },
        {
            "city": "Y\u00e9liman\u00e9",
            "city_ascii": "Yelimane",
            "lat": 15.1337,
            "lng": -10.5666,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Kayes",
            "capital": "minor",
            "population": 988,
            "id": 1466380722
        },
        {
            "city": "Aguelhok",
            "city_ascii": "Aguelhok",
            "lat": 19.4549,
            "lng": 0.8564,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Kidal",
            "capital": "",
            "population": 9000,
            "id": 1466967655
        },
        {
            "city": "Sokolo",
            "city_ascii": "Sokolo",
            "lat": 14.7337,
            "lng": -6.1333,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "S\u00e9gou",
            "capital": "",
            "population": 4374,
            "id": 1466033359
        },
        {
            "city": "Araouane",
            "city_ascii": "Araouane",
            "lat": 18.9,
            "lng": -3.53,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Tombouctou",
            "capital": "",
            "population": 4026,
            "id": 1466354924
        },
        {
            "city": "Taoudenni",
            "city_ascii": "Taoudenni",
            "lat": 22.6666,
            "lng": -3.9834,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Tombouctou",
            "capital": "",
            "population": 3019,
            "id": 1466976172
        },
        {
            "city": "Satadougou",
            "city_ascii": "Satadougou",
            "lat": 12.617,
            "lng": -11.4066,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Kayes",
            "capital": "",
            "population": 706,
            "id": 1466591334
        }
    ]
}