module.exports = {
    CITIES: [{
            "city": "Casablanca",
            "city_ascii": "Casablanca",
            "lat": 33.6,
            "lng": -7.6164,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Casablanca-Settat",
            "capital": "admin",
            "population": 3181000,
            "id": 1504175315
        },
        {
            "city": "Rabat",
            "city_ascii": "Rabat",
            "lat": 34.0253,
            "lng": -6.8361,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Rabat-Sal\u00e9-K\u00e9nitra",
            "capital": "primary",
            "population": 1705000,
            "id": 1504023252
        },
        {
            "city": "F\u00e8s",
            "city_ascii": "Fes",
            "lat": 34.0546,
            "lng": -5.0004,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "F\u00e8s-Mekn\u00e8s",
            "capital": "admin",
            "population": 1002000,
            "id": 1504861997
        },
        {
            "city": "Marrakech",
            "city_ascii": "Marrakech",
            "lat": 31.63,
            "lng": -8,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Marrakech-Safi",
            "capital": "admin",
            "population": 872000,
            "id": 1504172585
        },
        {
            "city": "Agadir",
            "city_ascii": "Agadir",
            "lat": 30.44,
            "lng": -9.62,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Souss-Massa",
            "capital": "admin",
            "population": 825467,
            "id": 1504116858
        },
        {
            "city": "Tangier",
            "city_ascii": "Tangier",
            "lat": 35.7473,
            "lng": -5.8327,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Tanger-T\u00e9touan-Al Hoce\u00efma",
            "capital": "admin",
            "population": 750060,
            "id": 1504861504
        },
        {
            "city": "Mekn\u00e8s",
            "city_ascii": "Meknes",
            "lat": 33.9004,
            "lng": -5.56,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "F\u00e8s-Mekn\u00e8s",
            "capital": "",
            "population": 697628,
            "id": 1504333193
        },
        {
            "city": "Kenitra",
            "city_ascii": "Kenitra",
            "lat": 34.2704,
            "lng": -6.58,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Rabat-Sal\u00e9-K\u00e9nitra",
            "capital": "",
            "population": 551786,
            "id": 1504534876
        },
        {
            "city": "Oujda-Angad",
            "city_ascii": "Oujda-Angad",
            "lat": 34.69,
            "lng": -1.91,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Oriental",
            "capital": "admin",
            "population": 409391,
            "id": 1504891036
        },
        {
            "city": "Safi",
            "city_ascii": "Safi",
            "lat": 32.32,
            "lng": -9.24,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Marrakech-Safi",
            "capital": "",
            "population": 353476,
            "id": 1504000717
        },
        {
            "city": "Ksar El Kebir",
            "city_ascii": "Ksar El Kebir",
            "lat": 35.0204,
            "lng": -5.91,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Tanger-T\u00e9touan-Al Hoce\u00efma",
            "capital": "",
            "population": 306600,
            "id": 1504230428
        },
        {
            "city": "Errachidia",
            "city_ascii": "Errachidia",
            "lat": 31.9404,
            "lng": -4.45,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Dr\u00e2a-Tafilalet",
            "capital": "",
            "population": 228489,
            "id": 1504005759
        },
        {
            "city": "Taza",
            "city_ascii": "Taza",
            "lat": 34.2204,
            "lng": -4.02,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "F\u00e8s-Mekn\u00e8s",
            "capital": "",
            "population": 199633,
            "id": 1504405154
        },
        {
            "city": "El Jadid",
            "city_ascii": "El Jadid",
            "lat": 33.2604,
            "lng": -8.51,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Casablanca-Settat",
            "capital": "",
            "population": 180470,
            "id": 1504964063
        },
        {
            "city": "Settat",
            "city_ascii": "Settat",
            "lat": 33.0104,
            "lng": -7.62,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Casablanca-Settat",
            "capital": "",
            "population": 161748,
            "id": 1504720478
        },
        {
            "city": "Larache",
            "city_ascii": "Larache",
            "lat": 35.2004,
            "lng": -6.16,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Tanger-T\u00e9touan-Al Hoce\u00efma",
            "capital": "",
            "population": 120082,
            "id": 1504637172
        },
        {
            "city": "Guelmim",
            "city_ascii": "Guelmim",
            "lat": 28.98,
            "lng": -10.07,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Guelmim-Oued Noun",
            "capital": "admin",
            "population": 115267,
            "id": 1504110861
        },
        {
            "city": "Ouezzane",
            "city_ascii": "Ouezzane",
            "lat": 34.8103,
            "lng": -5.57,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Tanger-T\u00e9touan-Al Hoce\u00efma",
            "capital": "",
            "population": 69658,
            "id": 1504736892
        },
        {
            "city": "B\u00e9ni Mellal",
            "city_ascii": "Beni Mellal",
            "lat": 32.3373,
            "lng": -6.3498,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "B\u00e9ni Mellal-Kh\u00e9nifra",
            "capital": "admin",
            "population": "",
            "id": 1504131639
        },
        {
            "city": "Tan-Tan",
            "city_ascii": "Tan-Tan",
            "lat": 28.4304,
            "lng": -11.1,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Guelmim-Oued Noun",
            "capital": "",
            "population": 64868,
            "id": 1504164174
        },
        {
            "city": "Tiznit",
            "city_ascii": "Tiznit",
            "lat": 29.7104,
            "lng": -9.74,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Souss-Massa",
            "capital": "",
            "population": 57705,
            "id": 1504399838
        }
    ]
}