module.exports = {
    CITIES: [{
            "city": "Mexico City",
            "city_ascii": "Mexico City",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/1/15/Montaje.Ciudad_de_M%C3%A9xico.jpg",
            "lat": 19.4424,
            "lng": -99.131,
            "country": "Mexico",
            "iso2": "MX",
            "iso3": "MEX",
            "admin_name": "Ciudad de M\u00e9xico",
            "capital": "primary",
            "population": 19028000,
            "id": 1484247881
        },
        {
            "city": "Washington",
            "city_ascii": "Washington",
            "lat": 38.9047,
            "lng": -77.0163,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "District of Columbia",
            "capital": "primary",
            "population": 5289420,
            "id": 1840006060
        },
        {
            "city": "Atlanta",
            "city_ascii": "Atlanta",
            "lat": 33.7627,
            "lng": -84.4225,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Georgia",
            "capital": "admin",
            "population": 5228750,
            "id": 1840013660
        },
        {
            "city": "Toronto",
            "city_ascii": "Toronto",
            "lat": 43.7,
            "lng": -79.42,
            "country": "Canada",
            "iso2": "CA",
            "iso3": "CAN",
            "admin_name": "Ontario",
            "capital": "admin",
            "population": 5213000,
            "id": 1124279679
        },
        {
            "city": "Boston",
            "city_ascii": "Boston",
            "lat": 42.3188,
            "lng": -71.0846,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Massachusetts",
            "capital": "admin",
            "population": 4637537,
            "id": 1840000455
        },
        {
            "city": "Phoenix",
            "city_ascii": "Phoenix",
            "lat": 33.5722,
            "lng": -112.0891,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Arizona",
            "capital": "admin",
            "population": 4081849,
            "id": 1840020568
        },
        {
            "city": "Denver",
            "city_ascii": "Denver",
            "lat": 39.7621,
            "lng": -104.8759,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Colorado",
            "capital": "admin",
            "population": 2787266,
            "id": 1840018789
        },
        {
            "city": "Havana",
            "city_ascii": "Havana",
            "lat": 23.132,
            "lng": -82.3642,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "La Habana",
            "capital": "primary",
            "population": 2174000,
            "id": 1192752771
        },
        {
            "city": "Santo Domingo",
            "city_ascii": "Santo Domingo",
            "lat": 18.4701,
            "lng": -69.9001,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Ozama",
            "capital": "primary",
            "population": 2154000,
            "id": 1214636202
        },
        {
            "city": "Port-au-Prince",
            "city_ascii": "Port-au-Prince",
            "lat": 18.541,
            "lng": -72.336,
            "country": "Haiti",
            "iso2": "HT",
            "iso3": "HTI",
            "admin_name": "Ouest",
            "capital": "primary",
            "population": 1998000,
            "id": 1332401940
        },
        {
            "city": "Sacramento",
            "city_ascii": "Sacramento",
            "lat": 38.5667,
            "lng": -121.4683,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "California",
            "capital": "admin",
            "population": 1854698,
            "id": 1840021491
        },
        {
            "city": "Austin",
            "city_ascii": "Austin",
            "lat": 30.3006,
            "lng": -97.7517,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Texas",
            "capital": "admin",
            "population": 1638716,
            "id": 1840019590
        },
        {
            "city": "Indianapolis",
            "city_ascii": "Indianapolis",
            "lat": 39.7771,
            "lng": -86.1458,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Indiana",
            "capital": "admin",
            "population": 1564699,
            "id": 1840030084
        },
        {
            "city": "Columbus",
            "city_ascii": "Columbus",
            "lat": 39.986,
            "lng": -82.9851,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Ohio",
            "capital": "admin",
            "population": 1528314,
            "id": 1840003760
        },
        {
            "city": "San Salvador",
            "city_ascii": "San Salvador",
            "lat": 13.71,
            "lng": -89.203,
            "country": "El Salvador",
            "iso2": "SV",
            "iso3": "SLV",
            "admin_name": "San Salvador",
            "capital": "primary",
            "population": 1433000,
            "id": 1222647454
        },
        {
            "city": "Providence",
            "city_ascii": "Providence",
            "lat": 41.823,
            "lng": -71.4187,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Rhode Island",
            "capital": "admin",
            "population": 1206642,
            "id": 1840003289
        },
        {
            "city": "Ottawa",
            "city_ascii": "Ottawa",
            "lat": 45.4167,
            "lng": -75.7,
            "country": "Canada",
            "iso2": "CA",
            "iso3": "CAN",
            "admin_name": "Ontario",
            "capital": "primary",
            "population": 1145000,
            "id": 1124399363
        },
        {
            "city": "Salt Lake City",
            "city_ascii": "Salt Lake City",
            "lat": 40.7774,
            "lng": -111.93,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Utah",
            "capital": "admin",
            "population": 1098400,
            "id": 1840021383
        },
        {
            "city": "Nashville",
            "city_ascii": "Nashville",
            "lat": 36.1715,
            "lng": -86.7843,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Tennessee",
            "capital": "admin",
            "population": 1076645,
            "id": 1840036155
        },
        {
            "city": "Richmond",
            "city_ascii": "Richmond",
            "lat": 37.5295,
            "lng": -77.4756,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Virginia",
            "capital": "admin",
            "population": 1059907,
            "id": 1840001698
        },
        {
            "city": "Edmonton",
            "city_ascii": "Edmonton",
            "lat": 53.55,
            "lng": -113.5,
            "country": "Canada",
            "iso2": "CA",
            "iso3": "CAN",
            "admin_name": "Alberta",
            "capital": "admin",
            "population": 1058000,
            "id": 1124290735
        },
        {
            "city": "Guatemala City",
            "city_ascii": "Guatemala City",
            "lat": 14.6211,
            "lng": -90.527,
            "country": "Guatemala",
            "iso2": "GT",
            "iso3": "GTM",
            "admin_name": "Guatemala",
            "capital": "primary",
            "population": 1024000,
            "id": 1320197916
        },
        {
            "city": "Raleigh",
            "city_ascii": "Raleigh",
            "lat": 35.8324,
            "lng": -78.6438,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "North Carolina",
            "capital": "admin",
            "population": 1018336,
            "id": 1840014497
        },
        {
            "city": "Tegucigalpa",
            "city_ascii": "Tegucigalpa",
            "lat": 14.102,
            "lng": -87.2175,
            "country": "Honduras",
            "iso2": "HN",
            "iso3": "HND",
            "admin_name": "Francisco Moraz\u00e1n",
            "capital": "primary",
            "population": 946000,
            "id": 1340344059
        },
        {
            "city": "Kingston",
            "city_ascii": "Kingston",
            "lat": 17.9771,
            "lng": -76.7674,
            "country": "Jamaica",
            "iso2": "JM",
            "iso3": "JAM",
            "admin_name": "Kingston",
            "capital": "primary",
            "population": 937700,
            "id": 1388709177
        },
        {
            "city": "Managua",
            "city_ascii": "Managua",
            "lat": 12.153,
            "lng": -86.2685,
            "country": "Nicaragua",
            "iso2": "NI",
            "iso3": "NIC",
            "admin_name": "Managua",
            "capital": "primary",
            "population": 920000,
            "id": 1558296252
        },
        {
            "city": "Nassau",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Nassau%2C_Bahamas_welcome_gateway.JPG/1280px-Nassau%2C_Bahamas_welcome_gateway.JPG",
            "city_ascii": "Nassau",
            "lat": 25.0834,
            "lng": -77.35,
            "country": "Bahamas, The",
            "iso2": "BS",
            "iso3": "BHS",
            "admin_name": "",
            "capital": "primary",
            "population": 227940,
            "id": 1044318561
        },
        {
            "city": "Belmopan",
            "city_ascii": "Belmopan",
            "lat": 17.252,
            "lng": -88.7671,
            "country": "Belize",
            "iso2": "BZ",
            "iso3": "BLZ",
            "admin_name": "Cayo",
            "capital": "primary",
            "population": 15220,
            "id": 1084586375
        },
        {
            "city": "Oklahoma City",
            "city_ascii": "Oklahoma City",
            "lat": 35.4676,
            "lng": -97.5137,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Oklahoma",
            "capital": "admin",
            "population": 955998,
            "id": 1840020428
        },
        {
            "city": "Hartford",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Hartford_Skyline_from_Great_River_Park_%28Cropped%29.jpg",
            "city_ascii": "Hartford",
            "lat": 41.7661,
            "lng": -72.6834,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Connecticut",
            "capital": "admin",
            "population": 914751,
            "id": 1840004773
        },
        {
            "city": "Winnipeg",
            "city_ascii": "Winnipeg",
            "lat": 49.883,
            "lng": -97.166,
            "country": "Canada",
            "iso2": "CA",
            "iso3": "CAN",
            "admin_name": "Manitoba",
            "capital": "admin",
            "population": 632063,
            "id": 1124224963
        },
        {
            "city": "Qu\u00e9bec",
            "city_ascii": "Quebec",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Quebec_City_Montage_2016.jpg/800px-Quebec_City_Montage_2016.jpg",
            "lat": 46.84,
            "lng": -71.2456,
            "country": "Canada",
            "iso2": "CA",
            "iso3": "CAN",
            "admin_name": "Qu\u00e9bec",
            "capital": "admin",
            "population": 624177,
            "id": 1124823933
        },
        {
            "city": "Albany",
            "city_ascii": "Albany",
            "lat": 42.6664,
            "lng": -73.7987,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "New York",
            "capital": "admin",
            "population": 597270,
            "id": 1840000417
        },
        {
            "city": "Baton Rouge",
            "city_ascii": "Baton Rouge",
            "lat": 30.4419,
            "lng": -91.131,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Louisiana",
            "capital": "admin",
            "population": 583613,
            "id": 1840013941
        },
        {
            "city": "Columbia",
            "city_ascii": "Columbia",
            "lat": 34.0376,
            "lng": -80.9037,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "South Carolina",
            "capital": "admin",
            "population": 566166,
            "id": 1840014730
        },
        {
            "city": "Des Moines",
            "city_ascii": "Des Moines",
            "lat": 41.5725,
            "lng": -93.6105,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Iowa",
            "capital": "admin",
            "population": 481222,
            "id": 1840007069
        },
        {
            "city": "Little Rock",
            "city_ascii": "Little Rock",
            "lat": 34.7255,
            "lng": -92.358,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Arkansas",
            "capital": "admin",
            "population": 442699,
            "id": 1840015509
        },
        {
            "city": "Harrisburg",
            "city_ascii": "Harrisburg",
            "lat": 40.2752,
            "lng": -76.8843,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Pennsylvania",
            "capital": "admin",
            "population": 441580,
            "id": 1840001288
        },
        {
            "city": "Madison",
            "city_ascii": "Madison",
            "lat": 43.0827,
            "lng": -89.3923,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Wisconsin",
            "capital": "admin",
            "population": 439553,
            "id": 1840002915
        },
        {
            "city": "Boise",
            "city_ascii": "Boise",
            "lat": 43.6007,
            "lng": -116.2312,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Idaho",
            "capital": "admin",
            "population": 385218,
            "id": 1840027142
        },
        {
            "city": "Halifax",
            "city_ascii": "Halifax",
            "lat": 44.65,
            "lng": -63.6,
            "country": "Canada",
            "iso2": "CA",
            "iso3": "CAN",
            "admin_name": "Nova Scotia",
            "capital": "admin",
            "population": 359111,
            "id": 1124130981
        },
        {
            "city": "Jackson",
            "city_ascii": "Jackson",
            "lat": 32.3163,
            "lng": -90.2124,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Mississippi",
            "capital": "admin",
            "population": 338185,
            "id": 1840014895
        },
        {
            "city": "Lansing",
            "city_ascii": "Lansing",
            "lat": 42.7142,
            "lng": -84.5601,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Michigan",
            "capital": "admin",
            "population": 320928,
            "id": 1840003102
        },
        {
            "city": "St. Paul",
            "city_ascii": "St. Paul",
            "lat": 44.9477,
            "lng": -93.104,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Minnesota",
            "capital": "admin",
            "population": 306621,
            "id": 1840008940
        },
        {
            "city": "Trenton",
            "city_ascii": "Trenton",
            "lat": 40.2236,
            "lng": -74.7641,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "New Jersey",
            "capital": "admin",
            "population": 296869,
            "id": 1840001383
        },
        {
            "city": "Victoria",
            "city_ascii": "Victoria",
            "lat": 48.4333,
            "lng": -123.35,
            "country": "Canada",
            "iso2": "CA",
            "iso3": "CAN",
            "admin_name": "British Columbia",
            "capital": "admin",
            "population": 289625,
            "id": 1124147219
        },
        {
            "city": "Lincoln",
            "city_ascii": "Lincoln",
            "lat": 40.8088,
            "lng": -96.6796,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Nebraska",
            "capital": "admin",
            "population": 285118,
            "id": 1840009357
        },
        {
            "city": "Salem",
            "city_ascii": "Salem",
            "lat": 44.9232,
            "lng": -123.0245,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Oregon",
            "capital": "admin",
            "population": 259816,
            "id": 1840021224
        },
        {
            "city": "Montgomery",
            "city_ascii": "Montgomery",
            "lat": 32.3473,
            "lng": -86.2666,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Alabama",
            "capital": "admin",
            "population": 255908,
            "id": 1840008353
        },
        {
            "city": "Tallahassee",
            "city_ascii": "Tallahassee",
            "lat": 30.4551,
            "lng": -84.2527,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Florida",
            "capital": "admin",
            "population": 253030,
            "id": 1840015913
        },
        {
            "city": "Olympia",
            "city_ascii": "Olympia",
            "lat": 47.0417,
            "lng": -122.8959,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Washington",
            "capital": "admin",
            "population": 196078,
            "id": 1840019865
        },
        {
            "city": "Regina",
            "city_ascii": "Regina",
            "lat": 50.45,
            "lng": -104.617,
            "country": "Canada",
            "iso2": "CA",
            "iso3": "CAN",
            "admin_name": "Saskatchewan",
            "capital": "admin",
            "population": 176183,
            "id": 1124342541
        },
        {
            "city": "Springfield",
            "city_ascii": "Springfield",
            "lat": 39.771,
            "lng": -89.6537,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Illinois",
            "capital": "admin",
            "population": 159394,
            "id": 1840009517
        },
        {
            "city": "Topeka",
            "city_ascii": "Topeka",
            "lat": 39.0346,
            "lng": -95.6955,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Kansas",
            "capital": "admin",
            "population": 148960,
            "id": 1840001621
        },
        {
            "city": "Charleston",
            "city_ascii": "Charleston",
            "lat": 38.3484,
            "lng": -81.6323,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "West Virginia",
            "capital": "admin",
            "population": 142858,
            "id": 1840006196
        },
        {
            "city": "Saint John\u2019s",
            "city_ascii": "Saint John's",
            "lat": 47.585,
            "lng": -52.681,
            "country": "Canada",
            "iso2": "CA",
            "iso3": "CAN",
            "admin_name": "Newfoundland and Labrador",
            "capital": "admin",
            "population": 131469,
            "id": 1124741456
        },
        {
            "city": "Santa Fe",
            "city_ascii": "Santa Fe",
            "lat": 35.6619,
            "lng": -105.9819,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "New Mexico",
            "capital": "admin",
            "population": 110078,
            "id": 1840021707
        },
        {
            "city": "Bismarck",
            "city_ascii": "Bismarck",
            "lat": 46.814,
            "lng": -100.7695,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "North Dakota",
            "capital": "admin",
            "population": 97457,
            "id": 1840001926
        },
        {
            "city": "Cheyenne",
            "city_ascii": "Cheyenne",
            "lat": 41.1405,
            "lng": -104.7927,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Wyoming",
            "capital": "admin",
            "population": 78728,
            "id": 1840018713
        },
        {
            "city": "Jefferson City",
            "city_ascii": "Jefferson City",
            "lat": 38.5676,
            "lng": -92.1759,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Missouri",
            "capital": "admin",
            "population": 58279,
            "id": 1840008615
        },
        {
            "city": "Carson City",
            "city_ascii": "Carson City",
            "lat": 39.1511,
            "lng": -119.7474,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Nevada",
            "capital": "admin",
            "population": 57525,
            "id": 1840003826
        },
        {
            "city": "Fredericton",
            "city_ascii": "Fredericton",
            "lat": 45.95,
            "lng": -66.6333,
            "country": "Canada",
            "iso2": "CA",
            "iso3": "CAN",
            "admin_name": "New Brunswick",
            "capital": "admin",
            "population": 52337,
            "id": 1124061289
        },
        {
            "city": "Helena",
            "city_ascii": "Helena",
            "lat": 46.5965,
            "lng": -112.0199,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Montana",
            "capital": "admin",
            "population": 50227,
            "id": 1840019820
        },
        {
            "city": "Concord",
            "city_ascii": "Concord",
            "lat": 43.2305,
            "lng": -71.5595,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "New Hampshire",
            "capital": "admin",
            "population": 42935,
            "id": 1840002747
        },
        {
            "city": "Charlottetown",
            "city_ascii": "Charlottetown",
            "lat": 46.2493,
            "lng": -63.1313,
            "country": "Canada",
            "iso2": "CA",
            "iso3": "CAN",
            "admin_name": "Prince Edward Island",
            "capital": "admin",
            "population": 42402,
            "id": 1124897699
        },
        {
            "city": "Annapolis",
            "city_ascii": "Annapolis",
            "lat": 38.9706,
            "lng": -76.5047,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Maryland",
            "capital": "admin",
            "population": 39321,
            "id": 1840005928
        },
        {
            "city": "Frankfort",
            "city_ascii": "Frankfort",
            "lat": 38.1924,
            "lng": -84.8643,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Kentucky",
            "capital": "admin",
            "population": 38664,
            "id": 1840013210
        },
        {
            "city": "Pierre",
            "city_ascii": "Pierre",
            "lat": 44.3748,
            "lng": -100.3205,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "South Dakota",
            "capital": "admin",
            "population": 14803,
            "id": 1840000313
        },
        {
            "city": "Montpelier",
            "city_ascii": "Montpelier",
            "lat": 44.2658,
            "lng": -72.5717,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Vermont",
            "capital": "admin",
            "population": 7484,
            "id": 1840002187
        },
        {
            "city": "Dover",
            "city_ascii": "Dover",
            "lat": 40.0033,
            "lng": -76.8484,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "Pennsylvania",
            "capital": "admin",
            "population": 1991,
            "id": 1840001442
        },
        {
            "city": "George Town",
            "city_ascii": "George Town",
            "lat": 19.2804,
            "lng": -81.33,
            "country": "Cayman Islands",
            "iso2": "KY",
            "iso3": "CYM",
            "admin_name": "",
            "capital": "primary",
            "population": 4268,
            "id": 1136159124
        }
    ]
}