module.exports = {
    CITIES: [{
            "city": "Auckland",
            "city_ascii": "Auckland",
            "lat": -36.8481,
            "lng": 174.763,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Auckland",
            "capital": "admin",
            "population": 1377200,
            "id": 1554435911
        },
        {
            "city": "Wellington",
            "city_ascii": "Wellington",
            "lat": -41.3,
            "lng": 174.7833,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Wellington",
            "capital": "primary",
            "population": 393400,
            "id": 1554772152
        },
        {
            "city": "Manukau City",
            "city_ascii": "Manukau City",
            "lat": -37,
            "lng": 174.885,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Auckland",
            "capital": "",
            "population": 375600,
            "id": 1554797148
        },
        {
            "city": "Christchurch",
            "city_ascii": "Christchurch",
            "lat": -43.535,
            "lng": 172.63,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Canterbury",
            "capital": "admin",
            "population": 363200,
            "id": 1554377228
        },
        {
            "city": "Waitakere",
            "city_ascii": "Waitakere",
            "lat": -36.8524,
            "lng": 174.5543,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Auckland",
            "capital": "",
            "population": 208100,
            "id": 1554034359
        },
        {
            "city": "Northcote",
            "city_ascii": "Northcote",
            "lat": -36.7913,
            "lng": 174.7758,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Auckland",
            "capital": "",
            "population": 205605,
            "id": 1554717659
        },
        {
            "city": "Hamilton",
            "city_ascii": "Hamilton",
            "lat": -37.7783,
            "lng": 175.2896,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Waikato",
            "capital": "admin",
            "population": 148200,
            "id": 1554873040
        },
        {
            "city": "Tauranga",
            "city_ascii": "Tauranga",
            "lat": -37.6964,
            "lng": 176.1536,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Bay of Plenty",
            "capital": "",
            "population": 121500,
            "id": 1554759867
        },
        {
            "city": "Dunedin",
            "city_ascii": "Dunedin",
            "lat": -45.8854,
            "lng": 170.491,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Otago",
            "capital": "admin",
            "population": 117700,
            "id": 1554475997
        },
        {
            "city": "Lower Hutt",
            "city_ascii": "Lower Hutt",
            "lat": -41.2037,
            "lng": 174.9123,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Wellington",
            "capital": "",
            "population": 102400,
            "id": 1554623632
        },
        {
            "city": "Palmerston North",
            "city_ascii": "Palmerston North",
            "lat": -40.3527,
            "lng": 175.6072,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Manawatu-Wanganui",
            "capital": "admin",
            "population": 82400,
            "id": 1554138183
        },
        {
            "city": "Nelson",
            "city_ascii": "Nelson",
            "lat": -41.2926,
            "lng": 173.2474,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Nelson",
            "capital": "admin",
            "population": 60800,
            "id": 1554017097
        },
        {
            "city": "Napier",
            "city_ascii": "Napier",
            "lat": -39.49,
            "lng": 176.9265,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Hawke\u2019s Bay",
            "capital": "admin",
            "population": 57800,
            "id": 1554064936
        },
        {
            "city": "Whangarei",
            "city_ascii": "Whangarei",
            "lat": -35.7256,
            "lng": 174.323,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Northland",
            "capital": "admin",
            "population": 52200,
            "id": 1554000636
        },
        {
            "city": "Invercargill",
            "city_ascii": "Invercargill",
            "lat": -46.4094,
            "lng": 168.365,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Southland",
            "capital": "admin",
            "population": 49200,
            "id": 1554148942
        },
        {
            "city": "Upper Hutt",
            "city_ascii": "Upper Hutt",
            "lat": -41.1355,
            "lng": 175.029,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Wellington",
            "capital": "",
            "population": 39200,
            "id": 1554000042
        },
        {
            "city": "Gisborne",
            "city_ascii": "Gisborne",
            "lat": -38.6633,
            "lng": 178.0181,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Gisborne",
            "capital": "admin",
            "population": 34300,
            "id": 1554359840
        },
        {
            "city": "Blenheim",
            "city_ascii": "Blenheim",
            "lat": -41.5135,
            "lng": 173.955,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Marlborough",
            "capital": "admin",
            "population": 30300,
            "id": 1554001426
        },
        {
            "city": "Whakatane",
            "city_ascii": "Whakatane",
            "lat": -37.9574,
            "lng": 176.9828,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Bay of Plenty",
            "capital": "admin",
            "population": 18700,
            "id": 1554253729
        },
        {
            "city": "Greymouth",
            "city_ascii": "Greymouth",
            "lat": -42.4716,
            "lng": 171.2231,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "West Coast",
            "capital": "admin",
            "population": 10100,
            "id": 1554984303
        },
        {
            "city": "Waitangi",
            "city_ascii": "Waitangi",
            "lat": -44.0263,
            "lng": -176.3696,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Chatham Islands",
            "capital": "admin",
            "population": 300,
            "id": 1554847194
        },
        {
            "city": "Richmond",
            "city_ascii": "Richmond",
            "lat": -41.339,
            "lng": 173.185,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Tasman",
            "capital": "admin",
            "population": "",
            "id": 1554001427
        },
        {
            "city": "Stratford",
            "city_ascii": "Stratford",
            "lat": -39.3409,
            "lng": 174.2845,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Taranaki",
            "capital": "admin",
            "population": "",
            "id": 1554001293
        },
        {
            "city": "Rotorua",
            "city_ascii": "Rotorua",
            "lat": -38.1317,
            "lng": 176.2483,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Bay of Plenty",
            "capital": "",
            "population": 56200,
            "id": 1554000379
        },
        {
            "city": "New Plymouth",
            "city_ascii": "New Plymouth",
            "lat": -39.0556,
            "lng": 174.0748,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Taranaki",
            "capital": "",
            "population": 52500,
            "id": 1554939405
        },
        {
            "city": "Porirua",
            "city_ascii": "Porirua",
            "lat": -41.1219,
            "lng": 174.8524,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Wellington",
            "capital": "",
            "population": 52500,
            "id": 1554561880
        },
        {
            "city": "Whanganui",
            "city_ascii": "Whanganui",
            "lat": -39.9326,
            "lng": 175.0393,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Manawatu-Wanganui",
            "capital": "",
            "population": 43200,
            "id": 1554827998
        },
        {
            "city": "Timaru",
            "city_ascii": "Timaru",
            "lat": -44.3972,
            "lng": 171.2425,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Canterbury",
            "capital": "",
            "population": 27200,
            "id": 1554243304
        },
        {
            "city": "Pukekohe East",
            "city_ascii": "Pukekohe East",
            "lat": -37.2015,
            "lng": 174.9033,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "",
            "capital": "",
            "population": 26300,
            "id": 1554599644
        },
        {
            "city": "Paraparaumu",
            "city_ascii": "Paraparaumu",
            "lat": -40.9034,
            "lng": 174.9989,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Wellington",
            "capital": "",
            "population": 25263,
            "id": 1554166459
        },
        {
            "city": "Taupo",
            "city_ascii": "Taupo",
            "lat": -38.693,
            "lng": 176.0771,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Waikato",
            "capital": "",
            "population": 22600,
            "id": 1554654784
        },
        {
            "city": "Masterton",
            "city_ascii": "Masterton",
            "lat": -40.9439,
            "lng": 175.6456,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Wellington",
            "capital": "",
            "population": 20200,
            "id": 1554641049
        },
        {
            "city": "Levin",
            "city_ascii": "Levin",
            "lat": -40.6124,
            "lng": 175.2772,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Manawatu-Wanganui",
            "capital": "",
            "population": 19550,
            "id": 1554983635
        },
        {
            "city": "Ashton",
            "city_ascii": "Ashton",
            "lat": -43.8983,
            "lng": 171.7486,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Canterbury",
            "capital": "",
            "population": 17700,
            "id": 1554784264
        },
        {
            "city": "Queenstown",
            "city_ascii": "Queenstown",
            "lat": -45.0227,
            "lng": 168.7251,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Otago",
            "capital": "",
            "population": 16600,
            "id": 1554582165
        },
        {
            "city": "Cambridge",
            "city_ascii": "Cambridge",
            "lat": -37.8894,
            "lng": 175.4703,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Waikato",
            "capital": "",
            "population": 15192,
            "id": 1554000848
        },
        {
            "city": "Tokoroa",
            "city_ascii": "Tokoroa",
            "lat": -38.2245,
            "lng": 175.8705,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Waikato",
            "capital": "",
            "population": 13350,
            "id": 1554951529
        },
        {
            "city": "Hawera",
            "city_ascii": "Hawera",
            "lat": -39.5795,
            "lng": 174.278,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Taranaki",
            "capital": "",
            "population": 11100,
            "id": 1554872573
        },
        {
            "city": "Kairaki",
            "city_ascii": "Kairaki",
            "lat": -43.3813,
            "lng": 172.651,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Canterbury",
            "capital": "",
            "population": 10200,
            "id": 1554001309
        },
        {
            "city": "Thames",
            "city_ascii": "Thames",
            "lat": -37.1384,
            "lng": 175.5853,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Waikato",
            "capital": "",
            "population": 6756,
            "id": 1554802053
        },
        {
            "city": "Kerikeri",
            "city_ascii": "Kerikeri",
            "lat": -35.2285,
            "lng": 173.9507,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Northland",
            "capital": "",
            "population": 5856,
            "id": 1554530676
        },
        {
            "city": "Kaitaia",
            "city_ascii": "Kaitaia",
            "lat": -35.1099,
            "lng": 173.2727,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Northland",
            "capital": "",
            "population": 5202,
            "id": 1554000934
        },
        {
            "city": "Wanaka",
            "city_ascii": "Wanaka",
            "lat": -44.698,
            "lng": 169.1449,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Otago",
            "capital": "",
            "population": 5037,
            "id": 1554152950
        },
        {
            "city": "Turangi",
            "city_ascii": "Turangi",
            "lat": -38.9889,
            "lng": 175.8142,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Waikato",
            "capital": "",
            "population": 3240,
            "id": 1554981086
        },
        {
            "city": "Hokitika",
            "city_ascii": "Hokitika",
            "lat": -42.7072,
            "lng": 171.01,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "West Coast",
            "capital": "",
            "population": 3078,
            "id": 1554205461
        },
        {
            "city": "Renwick",
            "city_ascii": "Renwick",
            "lat": -41.2805,
            "lng": 174.0166,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Marlborough",
            "capital": "",
            "population": 2928,
            "id": 1554865401
        },
        {
            "city": "Kaikoura",
            "city_ascii": "Kaikoura",
            "lat": -42.4012,
            "lng": 173.6897,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Canterbury",
            "capital": "",
            "population": 2172,
            "id": 1554578431
        },
        {
            "city": "Te Anau",
            "city_ascii": "Te Anau",
            "lat": -45.4074,
            "lng": 167.7585,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Southland",
            "capital": "",
            "population": 1857,
            "id": 1554603580
        },
        {
            "city": "Halfmoon Bay",
            "city_ascii": "Halfmoon Bay",
            "lat": -46.8876,
            "lng": 168.1666,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Southland",
            "capital": "",
            "population": 310,
            "id": 1554077152
        },
        {
            "city": "Glencoe",
            "city_ascii": "Glencoe",
            "lat": -46.0947,
            "lng": 168.9604,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Southland",
            "capital": "",
            "population": 9750,
            "id": 1554979133
        },
        {
            "city": "Westport",
            "city_ascii": "Westport",
            "lat": -41.7638,
            "lng": 171.6028,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "West Coast",
            "capital": "",
            "population": 3900,
            "id": 1554650685
        }
    ]
}