module.exports = {
    CITIES: [{
            "city": "Lagos",
            "city_ascii": "Lagos",
            "lat": 6.4433,
            "lng": 3.3915,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Lagos",
            "capital": "minor",
            "population": 9466000,
            "id": 1566593751
        },
        {
            "city": "Kano",
            "city_ascii": "Kano",
            "lat": 12,
            "lng": 8.52,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Kano",
            "capital": "admin",
            "population": 3140000,
            "id": 1566422868
        },
        {
            "city": "Ibadan",
            "city_ascii": "Ibadan",
            "lat": 7.38,
            "lng": 3.93,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Oyo",
            "capital": "admin",
            "population": 2628000,
            "id": 1566366407
        },
        {
            "city": "Abuja",
            "city_ascii": "Abuja",
            "lat": 9.0833,
            "lng": 7.5333,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Federal Capital Territory",
            "capital": "primary",
            "population": 1576000,
            "id": 1566342270
        },
        {
            "city": "Kaduna",
            "city_ascii": "Kaduna",
            "lat": 10.52,
            "lng": 7.44,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Kaduna",
            "capital": "admin",
            "population": 1442000,
            "id": 1566368729
        },
        {
            "city": "Benin City",
            "city_ascii": "Benin City",
            "lat": 6.3405,
            "lng": 5.62,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Edo",
            "capital": "admin",
            "population": 1190000,
            "id": 1566080151
        },
        {
            "city": "Ikare",
            "city_ascii": "Ikare",
            "lat": 7.5304,
            "lng": 5.76,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Ondo",
            "capital": "minor",
            "population": 1099931,
            "id": 1566683694
        },
        {
            "city": "Port Harcourt",
            "city_ascii": "Port Harcourt",
            "lat": 4.81,
            "lng": 7.01,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Rivers",
            "capital": "admin",
            "population": 1020000,
            "id": 1566070649
        },
        {
            "city": "Ogbomoso",
            "city_ascii": "Ogbomoso",
            "lat": 8.13,
            "lng": 4.24,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Oyo",
            "capital": "minor",
            "population": 951000,
            "id": 1566373448
        },
        {
            "city": "Aba",
            "city_ascii": "Aba",
            "lat": 5.1004,
            "lng": 7.35,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Abia",
            "capital": "minor",
            "population": 897560,
            "id": 1566262000
        },
        {
            "city": "Maiduguri",
            "city_ascii": "Maiduguri",
            "lat": 11.85,
            "lng": 13.16,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Borno",
            "capital": "admin",
            "population": 896000,
            "id": 1566540296
        },
        {
            "city": "Zaria",
            "city_ascii": "Zaria",
            "lat": 11.08,
            "lng": 7.71,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Kaduna",
            "capital": "minor",
            "population": 889000,
            "id": 1566287704
        },
        {
            "city": "Warri",
            "city_ascii": "Warri",
            "lat": 5.52,
            "lng": 5.76,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Delta",
            "capital": "minor",
            "population": 830106,
            "id": 1566325734
        },
        {
            "city": "Jos",
            "city_ascii": "Jos",
            "lat": 9.93,
            "lng": 8.89,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Plateau",
            "capital": "admin",
            "population": 816824,
            "id": 1566773679
        },
        {
            "city": "Ilorin",
            "city_ascii": "Ilorin",
            "lat": 8.49,
            "lng": 4.55,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Kwara",
            "capital": "admin",
            "population": 771000,
            "id": 1566480168
        },
        {
            "city": "Oyo",
            "city_ascii": "Oyo",
            "lat": 7.8504,
            "lng": 3.93,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Oyo",
            "capital": "minor",
            "population": 736072,
            "id": 1566930579
        },
        {
            "city": "Sokoto",
            "city_ascii": "Sokoto",
            "lat": 13.06,
            "lng": 5.24,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Sokoto",
            "capital": "admin",
            "population": 732178,
            "id": 1566574518
        },
        {
            "city": "Enugu",
            "city_ascii": "Enugu",
            "lat": 6.45,
            "lng": 7.5,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Enugu",
            "capital": "admin",
            "population": 688862,
            "id": 1566212729
        },
        {
            "city": "Abeokuta",
            "city_ascii": "Abeokuta",
            "lat": 7.1604,
            "lng": 3.35,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Ogun",
            "capital": "admin",
            "population": 593100,
            "id": 1566979497
        },
        {
            "city": "Uyo",
            "city_ascii": "Uyo",
            "lat": 5.008,
            "lng": 7.85,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Akwa Ibom",
            "capital": "admin",
            "population": 554906,
            "id": 1566061694
        },
        {
            "city": "Awka",
            "city_ascii": "Awka",
            "lat": 6.2104,
            "lng": 7.07,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Anambra",
            "capital": "admin",
            "population": 500000,
            "id": 1566560581
        },
        {
            "city": "Ile-Ife",
            "city_ascii": "Ile-Ife",
            "lat": 7.4804,
            "lng": 4.56,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Osun",
            "capital": "minor",
            "population": 482365,
            "id": 1566756897
        },
        {
            "city": "Calabar",
            "city_ascii": "Calabar",
            "lat": 4.9604,
            "lng": 8.33,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Cross River",
            "capital": "admin",
            "population": 461796,
            "id": 1566495489
        },
        {
            "city": "Ado-Ekiti",
            "city_ascii": "Ado-Ekiti",
            "lat": 7.6304,
            "lng": 5.22,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Ekiti",
            "capital": "admin",
            "population": 446749,
            "id": 1566196391
        },
        {
            "city": "Katsina",
            "city_ascii": "Katsina",
            "lat": 12.9904,
            "lng": 7.6,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Katsina",
            "capital": "admin",
            "population": 432149,
            "id": 1566777297
        },
        {
            "city": "Akure",
            "city_ascii": "Akure",
            "lat": 7.2504,
            "lng": 5.2,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Ondo",
            "capital": "admin",
            "population": 420594,
            "id": 1566568277
        },
        {
            "city": "Osogbo",
            "city_ascii": "Osogbo",
            "lat": 7.7704,
            "lng": 4.56,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Osun",
            "capital": "admin",
            "population": 408245,
            "id": 1566395088
        },
        {
            "city": "Bauchi",
            "city_ascii": "Bauchi",
            "lat": 10.3104,
            "lng": 9.84,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Bauchi",
            "capital": "admin",
            "population": 316149,
            "id": 1566483284
        },
        {
            "city": "Sapele",
            "city_ascii": "Sapele",
            "lat": 5.8904,
            "lng": 5.68,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Delta",
            "capital": "minor",
            "population": 309162,
            "id": 1566310893
        },
        {
            "city": "Makurdi",
            "city_ascii": "Makurdi",
            "lat": 7.73,
            "lng": 8.53,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Benue",
            "capital": "admin",
            "population": 292645,
            "id": 1566873994
        },
        {
            "city": "Minna",
            "city_ascii": "Minna",
            "lat": 9.62,
            "lng": 6.55,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Niger",
            "capital": "admin",
            "population": 291905,
            "id": 1566285237
        },
        {
            "city": "Owo",
            "city_ascii": "Owo",
            "lat": 7.2004,
            "lng": 5.59,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Ondo",
            "capital": "minor",
            "population": 276574,
            "id": 1566833788
        },
        {
            "city": "Gombe",
            "city_ascii": "Gombe",
            "lat": 10.2904,
            "lng": 11.17,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Gombe",
            "capital": "admin",
            "population": 270366,
            "id": 1566855445
        },
        {
            "city": "Umuahia",
            "city_ascii": "Umuahia",
            "lat": 5.532,
            "lng": 7.486,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Abia",
            "capital": "admin",
            "population": 264662,
            "id": 1566217980
        },
        {
            "city": "Ondo",
            "city_ascii": "Ondo",
            "lat": 7.0904,
            "lng": 4.84,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Ondo",
            "capital": "minor",
            "population": 257005,
            "id": 1566993724
        },
        {
            "city": "Damaturu",
            "city_ascii": "Damaturu",
            "lat": 11.749,
            "lng": 11.966,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Yobe",
            "capital": "admin",
            "population": 255895,
            "id": 1566897107
        },
        {
            "city": "Iwo",
            "city_ascii": "Iwo",
            "lat": 7.63,
            "lng": 4.18,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Osun",
            "capital": "minor",
            "population": 250443,
            "id": 1566462707
        },
        {
            "city": "Gusau",
            "city_ascii": "Gusau",
            "lat": 12.1704,
            "lng": 6.66,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Zamfara",
            "capital": "admin",
            "population": 226857,
            "id": 1566383682
        },
        {
            "city": "Mubi",
            "city_ascii": "Mubi",
            "lat": 10.2703,
            "lng": 13.27,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Adamawa",
            "capital": "minor",
            "population": 225705,
            "id": 1566265170
        },
        {
            "city": "Owerri",
            "city_ascii": "Owerri",
            "lat": 5.493,
            "lng": 7.026,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Imo",
            "capital": "admin",
            "population": 215038,
            "id": 1566679132
        },
        {
            "city": "Ijebu-Ode",
            "city_ascii": "Ijebu-Ode",
            "lat": 6.8204,
            "lng": 3.92,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Ogun",
            "capital": "minor",
            "population": 209175,
            "id": 1566495747
        },
        {
            "city": "Funtua",
            "city_ascii": "Funtua",
            "lat": 11.5204,
            "lng": 7.32,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Katsina",
            "capital": "minor",
            "population": 180475,
            "id": 1566877863
        },
        {
            "city": "Bida",
            "city_ascii": "Bida",
            "lat": 9.0804,
            "lng": 6.01,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Niger",
            "capital": "minor",
            "population": 173849,
            "id": 1566468363
        },
        {
            "city": "Lafia",
            "city_ascii": "Lafia",
            "lat": 8.4904,
            "lng": 8.52,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Nasarawa",
            "capital": "admin",
            "population": 127236,
            "id": 1566042542
        },
        {
            "city": "Gashua",
            "city_ascii": "Gashua",
            "lat": 12.8705,
            "lng": 11.04,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Yobe",
            "capital": "minor",
            "population": 125817,
            "id": 1566925429
        },
        {
            "city": "Bama",
            "city_ascii": "Bama",
            "lat": 11.5204,
            "lng": 13.69,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Borno",
            "capital": "minor",
            "population": 118121,
            "id": 1566590565
        },
        {
            "city": "Jalingo",
            "city_ascii": "Jalingo",
            "lat": 8.9004,
            "lng": 11.36,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Taraba",
            "capital": "admin",
            "population": 117757,
            "id": 1566732241
        },
        {
            "city": "Nsukka",
            "city_ascii": "Nsukka",
            "lat": 6.867,
            "lng": 7.3834,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Enugu",
            "capital": "minor",
            "population": 111017,
            "id": 1566882360
        },
        {
            "city": "Nguru",
            "city_ascii": "Nguru",
            "lat": 12.8804,
            "lng": 10.45,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Yobe",
            "capital": "minor",
            "population": 111014,
            "id": 1566737779
        },
        {
            "city": "Birnin Kebbi",
            "city_ascii": "Birnin Kebbi",
            "lat": 12.4504,
            "lng": 4.1999,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Kebbi",
            "capital": "admin",
            "population": 108164,
            "id": 1566191812
        },
        {
            "city": "Azare",
            "city_ascii": "Azare",
            "lat": 11.6804,
            "lng": 10.19,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Bauchi",
            "capital": "minor",
            "population": 105687,
            "id": 1566322480
        },
        {
            "city": "Yola",
            "city_ascii": "Yola",
            "lat": 9.21,
            "lng": 12.48,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Adamawa",
            "capital": "admin",
            "population": 96006,
            "id": 1566782065
        },
        {
            "city": "Lokoja",
            "city_ascii": "Lokoja",
            "lat": 7.8004,
            "lng": 6.7399,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Kogi",
            "capital": "admin",
            "population": 60579,
            "id": 1566772925
        },
        {
            "city": "Dutse",
            "city_ascii": "Dutse",
            "lat": 11.7992,
            "lng": 9.3503,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Jigawa",
            "capital": "admin",
            "population": 17129,
            "id": 1566855083
        },
        {
            "city": "Ikeja",
            "city_ascii": "Ikeja",
            "lat": 6.5965,
            "lng": 3.3421,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Lagos",
            "capital": "admin",
            "population": "",
            "id": 1566486388
        },
        {
            "city": "Asaba",
            "city_ascii": "Asaba",
            "lat": 6.1985,
            "lng": 6.7274,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Delta",
            "capital": "admin",
            "population": "",
            "id": 1566322425
        },
        {
            "city": "Yenagoa",
            "city_ascii": "Yenagoa",
            "lat": 4.9267,
            "lng": 6.2676,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Bayelsa",
            "capital": "admin",
            "population": "",
            "id": 1566468984
        },
        {
            "city": "Abakaliki",
            "city_ascii": "Abakaliki",
            "lat": 6.3249,
            "lng": 8.1137,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Ebonyi",
            "capital": "admin",
            "population": "",
            "id": 1566879878
        },
        {
            "city": "Kontagora",
            "city_ascii": "Kontagora",
            "lat": 10.4004,
            "lng": 5.4699,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Niger",
            "capital": "minor",
            "population": 98754,
            "id": 1566599231
        },
        {
            "city": "Iseyin",
            "city_ascii": "Iseyin",
            "lat": 7.97,
            "lng": 3.59,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Oyo",
            "capital": "minor",
            "population": 98071,
            "id": 1566714777
        },
        {
            "city": "Biu",
            "city_ascii": "Biu",
            "lat": 10.6204,
            "lng": 12.19,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Borno",
            "capital": "minor",
            "population": 95005,
            "id": 1566675681
        },
        {
            "city": "Wukari",
            "city_ascii": "Wukari",
            "lat": 7.8704,
            "lng": 9.78,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Taraba",
            "capital": "minor",
            "population": 92933,
            "id": 1566025302
        },
        {
            "city": "Potiskum",
            "city_ascii": "Potiskum",
            "lat": 11.7104,
            "lng": 11.08,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Yobe",
            "capital": "minor",
            "population": 86002,
            "id": 1566461523
        },
        {
            "city": "Keffi",
            "city_ascii": "Keffi",
            "lat": 8.849,
            "lng": 7.8736,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Nasarawa",
            "capital": "minor",
            "population": 85911,
            "id": 1566364417
        },
        {
            "city": "Numan",
            "city_ascii": "Numan",
            "lat": 9.4604,
            "lng": 12.04,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Adamawa",
            "capital": "minor",
            "population": 77617,
            "id": 1566815415
        },
        {
            "city": "Idah",
            "city_ascii": "Idah",
            "lat": 7.1104,
            "lng": 6.7399,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Kogi",
            "capital": "minor",
            "population": 75087,
            "id": 1566566689
        },
        {
            "city": "Onitsha",
            "city_ascii": "Onitsha",
            "lat": 6.1404,
            "lng": 6.78,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Anambra",
            "capital": "minor",
            "population": 73374,
            "id": 1566593483
        },
        {
            "city": "Otukpo",
            "city_ascii": "Otukpo",
            "lat": 7.1904,
            "lng": 8.13,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Benue",
            "capital": "minor",
            "population": 68220,
            "id": 1566465153
        },
        {
            "city": "Kumo",
            "city_ascii": "Kumo",
            "lat": 10.0457,
            "lng": 11.2131,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Gombe",
            "capital": "minor",
            "population": 35712,
            "id": 1566501095
        },
        {
            "city": "Ikot Abasi",
            "city_ascii": "Ikot Abasi",
            "lat": 4.5704,
            "lng": 7.56,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Akwa Ibom",
            "capital": "minor",
            "population": 34911,
            "id": 1566812706
        },
        {
            "city": "Koko",
            "city_ascii": "Koko",
            "lat": 11.4232,
            "lng": 4.517,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Kebbi",
            "capital": "",
            "population": 25792,
            "id": 1566646210
        },
        {
            "city": "Orlu",
            "city_ascii": "Orlu",
            "lat": 5.7837,
            "lng": 7.0333,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Imo",
            "capital": "minor",
            "population": 9351,
            "id": 1566062510
        }
    ]
}