module.exports = {
    CITIES: [{
            "city": "Manila",
            "city_ascii": "Manila",
            "lat": 14.6042,
            "lng": 120.9822,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Manila",
            "capital": "primary",
            "population": 11100000,
            "id": 1608618140
        },
        {
            "city": "Quezon City",
            "city_ascii": "Quezon City",
            "lat": 14.6504,
            "lng": 121.03,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Quezon",
            "capital": "admin",
            "population": 2761720,
            "id": 1608974097
        },
        {
            "city": "Davao",
            "city_ascii": "Davao",
            "lat": 7.11,
            "lng": 125.63,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Davao",
            "capital": "admin",
            "population": 1402000,
            "id": 1608906877
        },
        {
            "city": "Cagayan de Oro",
            "city_ascii": "Cagayan de Oro",
            "lat": 8.4508,
            "lng": 124.6853,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Cagayan de Oro",
            "capital": "admin",
            "population": 1121561,
            "id": 1608831546
        },
        {
            "city": "General Santos",
            "city_ascii": "General Santos",
            "lat": 6.1108,
            "lng": 125.1747,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "General Santos",
            "capital": "admin",
            "population": 950530,
            "id": 1608171585
        },
        {
            "city": "Bacolod",
            "city_ascii": "Bacolod",
            "lat": 10.6317,
            "lng": 122.9817,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Bacolod",
            "capital": "admin",
            "population": 949354,
            "id": 1608244137
        },
        {
            "city": "Cebu City",
            "city_ascii": "Cebu City",
            "lat": 10.32,
            "lng": 123.9001,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Cebu",
            "capital": "admin",
            "population": 815000,
            "id": 1608136151
        },
        {
            "city": "Zamboanga City",
            "city_ascii": "Zamboanga City",
            "lat": 6.92,
            "lng": 122.08,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Zamboanga",
            "capital": "admin",
            "population": 773000,
            "id": 1608189351
        },
        {
            "city": "Naga City",
            "city_ascii": "Naga City",
            "lat": 13.6192,
            "lng": 123.1814,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Naga",
            "capital": "admin",
            "population": 741635,
            "id": 1608775993
        },
        {
            "city": "Iligan",
            "city_ascii": "Iligan",
            "lat": 8.1712,
            "lng": 124.2154,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Iligan",
            "capital": "admin",
            "population": 464599,
            "id": 1608000268
        },
        {
            "city": "Baguio City",
            "city_ascii": "Baguio City",
            "lat": 16.43,
            "lng": 120.5699,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Baguio",
            "capital": "admin",
            "population": 447824,
            "id": 1608164766
        },
        {
            "city": "Batangas",
            "city_ascii": "Batangas",
            "lat": 13.7817,
            "lng": 121.0217,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Batangas",
            "capital": "admin",
            "population": 424508,
            "id": 1608417616
        },
        {
            "city": "Pasay City",
            "city_ascii": "Pasay City",
            "lat": 14.5504,
            "lng": 121,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Pasay",
            "capital": "admin",
            "population": 403064,
            "id": 1608448280
        },
        {
            "city": "Iloilo",
            "city_ascii": "Iloilo",
            "lat": 10.705,
            "lng": 122.545,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Iloilo",
            "capital": "admin",
            "population": 387681,
            "id": 1608875987
        },
        {
            "city": "Legazpi City",
            "city_ascii": "Legazpi City",
            "lat": 13.17,
            "lng": 123.75,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Albay",
            "capital": "admin",
            "population": 320081,
            "id": 1608693683
        },
        {
            "city": "Angeles City",
            "city_ascii": "Angeles City",
            "lat": 15.1451,
            "lng": 120.5451,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Angeles",
            "capital": "admin",
            "population": 314493,
            "id": 1608036027
        },
        {
            "city": "Olongapo",
            "city_ascii": "Olongapo",
            "lat": 14.8296,
            "lng": 120.2828,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Olongapo",
            "capital": "admin",
            "population": 304388,
            "id": 1608001640
        },
        {
            "city": "Cadiz",
            "city_ascii": "Cadiz",
            "lat": 10.9587,
            "lng": 123.3086,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Negros Occidental",
            "capital": "",
            "population": 283157,
            "id": 1608224037
        },
        {
            "city": "Tacloban",
            "city_ascii": "Tacloban",
            "lat": 11.2504,
            "lng": 125,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Tacloban",
            "capital": "admin",
            "population": 280006,
            "id": 1608710592
        },
        {
            "city": "Cotabato",
            "city_ascii": "Cotabato",
            "lat": 7.2169,
            "lng": 124.2484,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Cotabato",
            "capital": "admin",
            "population": 279519,
            "id": 1608753128
        },
        {
            "city": "San Pablo",
            "city_ascii": "San Pablo",
            "lat": 14.0696,
            "lng": 121.3226,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Laguna",
            "capital": "",
            "population": 240830,
            "id": 1608801564
        },
        {
            "city": "Cabanatuan City",
            "city_ascii": "Cabanatuan City",
            "lat": 15.5021,
            "lng": 120.9617,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Nueva Ecija",
            "capital": "",
            "population": 220250,
            "id": 1608247694
        },
        {
            "city": "Laoag",
            "city_ascii": "Laoag",
            "lat": 18.1988,
            "lng": 120.5936,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Ilocos Norte",
            "capital": "admin",
            "population": 207048,
            "id": 1608043510
        },
        {
            "city": "Butuan",
            "city_ascii": "Butuan",
            "lat": 8.9495,
            "lng": 125.5436,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Butuan",
            "capital": "admin",
            "population": 190557,
            "id": 1608000722
        },
        {
            "city": "Tarlac City",
            "city_ascii": "Tarlac City",
            "lat": 15.4838,
            "lng": 120.5834,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Tarlac",
            "capital": "admin",
            "population": 183930,
            "id": 1608237027
        },
        {
            "city": "Ormoc",
            "city_ascii": "Ormoc",
            "lat": 11.0643,
            "lng": 124.6075,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Ormoc",
            "capital": "admin",
            "population": 167584,
            "id": 1608269612
        },
        {
            "city": "Dagupan City",
            "city_ascii": "Dagupan City",
            "lat": 16.0479,
            "lng": 120.3408,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Dagupan",
            "capital": "admin",
            "population": 163676,
            "id": 1608530964
        },
        {
            "city": "Pagadian",
            "city_ascii": "Pagadian",
            "lat": 7.853,
            "lng": 123.507,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Zamboanga del Sur",
            "capital": "admin",
            "population": 159590,
            "id": 1608329397
        },
        {
            "city": "Puerto Princesa",
            "city_ascii": "Puerto Princesa",
            "lat": 9.7543,
            "lng": 118.7444,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Puerto Princesa",
            "capital": "admin",
            "population": 157144,
            "id": 1608455700
        },
        {
            "city": "Tuguegarao",
            "city_ascii": "Tuguegarao",
            "lat": 17.6131,
            "lng": 121.7269,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Cagayan",
            "capital": "admin",
            "population": 115105,
            "id": 1608110634
        },
        {
            "city": "Roxas City",
            "city_ascii": "Roxas City",
            "lat": 11.5853,
            "lng": 122.7511,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Capiz",
            "capital": "admin",
            "population": 102688,
            "id": 1608344583
        },
        {
            "city": "Ozamiz City",
            "city_ascii": "Ozamiz City",
            "lat": 8.1462,
            "lng": 123.8444,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Misamis Occidental",
            "capital": "",
            "population": 97806,
            "id": 1608100412
        },
        {
            "city": "Surigao",
            "city_ascii": "Surigao",
            "lat": 9.7843,
            "lng": 125.4888,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Surigao del Norte",
            "capital": "admin",
            "population": 87832,
            "id": 1608611556
        },
        {
            "city": "Calbayog City",
            "city_ascii": "Calbayog City",
            "lat": 12.0672,
            "lng": 124.6042,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Samar",
            "capital": "",
            "population": 67921,
            "id": 1608088739
        },
        {
            "city": "Vigan",
            "city_ascii": "Vigan",
            "lat": 17.5747,
            "lng": 120.3869,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Ilocos Sur",
            "capital": "admin",
            "population": 48545,
            "id": 1608368724
        },
        {
            "city": "Magugpo Poblacion",
            "city_ascii": "Magugpo Poblacion",
            "lat": 7.3821,
            "lng": 125.8017,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Davao del Norte",
            "capital": "",
            "population": 6726,
            "id": 1608255342
        },
        {
            "city": "San Carlos",
            "city_ascii": "San Carlos",
            "lat": 10.5504,
            "lng": 123.38,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Negros Occidental",
            "capital": "",
            "population": 6353,
            "id": 1608048026
        },
        {
            "city": "Gingoog",
            "city_ascii": "Gingoog",
            "lat": 8.8304,
            "lng": 125.13,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Misamis Oriental",
            "capital": "",
            "population": 218,
            "id": 1608630986
        },
        {
            "city": "Antipolo",
            "city_ascii": "Antipolo",
            "lat": 14.5886,
            "lng": 121.1757,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Rizal",
            "capital": "admin",
            "population": "",
            "id": 1608824345
        },
        {
            "city": "Navotas",
            "city_ascii": "Navotas",
            "lat": 14.6477,
            "lng": 120.9591,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Navotas",
            "capital": "admin",
            "population": "",
            "id": 1608538447
        },
        {
            "city": "Mandaluyong City",
            "city_ascii": "Mandaluyong City",
            "lat": 14.5832,
            "lng": 121.0409,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Mandaluyong",
            "capital": "admin",
            "population": "",
            "id": 1608166320
        },
        {
            "city": "Mandaue City",
            "city_ascii": "Mandaue City",
            "lat": 10.3237,
            "lng": 123.9436,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Mandaue",
            "capital": "admin",
            "population": "",
            "id": 1608794590
        },
        {
            "city": "Pasig City",
            "city_ascii": "Pasig City",
            "lat": 14.5604,
            "lng": 121.0812,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Pasig",
            "capital": "admin",
            "population": "",
            "id": 1608278212
        },
        {
            "city": "Caloocan City",
            "city_ascii": "Caloocan City",
            "lat": 14.6492,
            "lng": 120.9826,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Caloocan",
            "capital": "admin",
            "population": "",
            "id": 1608897690
        },
        {
            "city": "San Juan",
            "city_ascii": "San Juan",
            "lat": 14.6,
            "lng": 121.0333,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "San Juan",
            "capital": "admin",
            "population": "",
            "id": 1608817515
        },
        {
            "city": "Valenzuela",
            "city_ascii": "Valenzuela",
            "lat": 14.6936,
            "lng": 120.9656,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Valenzuela",
            "capital": "admin",
            "population": "",
            "id": 1608492120
        },
        {
            "city": "City of Para\u00f1aque",
            "city_ascii": "City of Paranaque",
            "lat": 14.4978,
            "lng": 120.9907,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Para\u00f1aque",
            "capital": "admin",
            "population": "",
            "id": 1608379532
        },
        {
            "city": "Lucena",
            "city_ascii": "Lucena",
            "lat": 13.9348,
            "lng": 121.6127,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Lucena",
            "capital": "admin",
            "population": "",
            "id": 1608000461
        },
        {
            "city": "Masbate",
            "city_ascii": "Masbate",
            "lat": 12.3687,
            "lng": 123.6225,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Masbate",
            "capital": "admin",
            "population": "",
            "id": 1608802236
        },
        {
            "city": "Tandag",
            "city_ascii": "Tandag",
            "lat": 9.0783,
            "lng": 126.1986,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Surigao del Sur",
            "capital": "admin",
            "population": "",
            "id": 1608155856
        },
        {
            "city": "Malabon",
            "city_ascii": "Malabon",
            "lat": 14.6691,
            "lng": 120.972,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Malabon",
            "capital": "admin",
            "population": "",
            "id": 1608045841
        },
        {
            "city": "Oroquieta",
            "city_ascii": "Oroquieta",
            "lat": 8.4859,
            "lng": 123.8048,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Misamis Occidental",
            "capital": "admin",
            "population": "",
            "id": 1608239509
        },
        {
            "city": "Catarman",
            "city_ascii": "Catarman",
            "lat": 12.4989,
            "lng": 124.6377,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Northern Samar",
            "capital": "admin",
            "population": "",
            "id": 1608432162
        },
        {
            "city": "La Trinidad",
            "city_ascii": "La Trinidad",
            "lat": 16.4556,
            "lng": 120.5903,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Benguet",
            "capital": "admin",
            "population": "",
            "id": 1608000107
        },
        {
            "city": "Marawi City",
            "city_ascii": "Marawi City",
            "lat": 8.0034,
            "lng": 124.2839,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Lanao del Sur",
            "capital": "admin",
            "population": "",
            "id": 1608812117
        },
        {
            "city": "Taguig City",
            "city_ascii": "Taguig City",
            "lat": 14.5289,
            "lng": 121.0723,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Taguig",
            "capital": "admin",
            "population": "",
            "id": 1608766695
        },
        {
            "city": "Lapu-Lapu City",
            "city_ascii": "Lapu-Lapu City",
            "lat": 10.3103,
            "lng": 123.9494,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Lapu-Lapu",
            "capital": "admin",
            "population": "",
            "id": 1608430676
        },
        {
            "city": "Balanga",
            "city_ascii": "Balanga",
            "lat": 14.6761,
            "lng": 120.5361,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Bataan",
            "capital": "admin",
            "population": "",
            "id": 1608467104
        },
        {
            "city": "Santiago",
            "city_ascii": "Santiago",
            "lat": 16.6881,
            "lng": 121.5472,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Santiago",
            "capital": "admin",
            "population": "",
            "id": 1608477470
        },
        {
            "city": "Dumaguete City",
            "city_ascii": "Dumaguete City",
            "lat": 9.307,
            "lng": 123.3074,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Negros Oriental",
            "capital": "admin",
            "population": "",
            "id": 1608682936
        },
        {
            "city": "Marikina City",
            "city_ascii": "Marikina City",
            "lat": 14.6414,
            "lng": 121.1118,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Marikina",
            "capital": "admin",
            "population": "",
            "id": 1608000077
        },
        {
            "city": "Sorsogon",
            "city_ascii": "Sorsogon",
            "lat": 12.9708,
            "lng": 124.0053,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Sorsogon",
            "capital": "admin",
            "population": "",
            "id": 1608265953
        },
        {
            "city": "Kalibo",
            "city_ascii": "Kalibo",
            "lat": 11.7086,
            "lng": 122.3648,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Aklan",
            "capital": "admin",
            "population": "",
            "id": 1608268539
        },
        {
            "city": "Kidapawan",
            "city_ascii": "Kidapawan",
            "lat": 7.0083,
            "lng": 125.0894,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Cotabato",
            "capital": "admin",
            "population": "",
            "id": 1608883158
        },
        {
            "city": "San Jose",
            "city_ascii": "San Jose",
            "lat": 10.745,
            "lng": 121.9415,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Antique",
            "capital": "admin",
            "population": "",
            "id": 1608138574
        },
        {
            "city": "Daet",
            "city_ascii": "Daet",
            "lat": 14.1122,
            "lng": 122.9553,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Camarines Norte",
            "capital": "admin",
            "population": "",
            "id": 1608562606
        },
        {
            "city": "Virac",
            "city_ascii": "Virac",
            "lat": 13.5848,
            "lng": 124.2374,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Catanduanes",
            "capital": "admin",
            "population": "",
            "id": 1608265120
        },
        {
            "city": "Bayombong",
            "city_ascii": "Bayombong",
            "lat": 16.4812,
            "lng": 121.1497,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Nueva Vizcaya",
            "capital": "admin",
            "population": "",
            "id": 1608066874
        },
        {
            "city": "Jolo",
            "city_ascii": "Jolo",
            "lat": 6.0522,
            "lng": 121.0022,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Sulu",
            "capital": "admin",
            "population": "",
            "id": 1608685440
        },
        {
            "city": "Bongao",
            "city_ascii": "Bongao",
            "lat": 5.0292,
            "lng": 119.7731,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Tawi-Tawi",
            "capital": "admin",
            "population": "",
            "id": 1608490585
        },
        {
            "city": "Calapan",
            "city_ascii": "Calapan",
            "lat": 13.4108,
            "lng": 121.1797,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Oriental Mindoro",
            "capital": "admin",
            "population": "",
            "id": 1608578259
        },
        {
            "city": "Tagum",
            "city_ascii": "Tagum",
            "lat": 7.4475,
            "lng": 125.8094,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Davao del Norte",
            "capital": "admin",
            "population": "",
            "id": 1608755366
        },
        {
            "city": "Muntinlupa City",
            "city_ascii": "Muntinlupa City",
            "lat": 14.4135,
            "lng": 121.0263,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Muntinlupa",
            "capital": "admin",
            "population": "",
            "id": 1608473406
        },
        {
            "city": "Catbalogan",
            "city_ascii": "Catbalogan",
            "lat": 11.7753,
            "lng": 124.8861,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Samar",
            "capital": "admin",
            "population": "",
            "id": 1608878798
        },
        {
            "city": "Digos",
            "city_ascii": "Digos",
            "lat": 6.7497,
            "lng": 125.3572,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Davao del Sur",
            "capital": "admin",
            "population": "",
            "id": 1608635653
        },
        {
            "city": "Makati City",
            "city_ascii": "Makati City",
            "lat": 14.5501,
            "lng": 121.036,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Makati",
            "capital": "admin",
            "population": "",
            "id": 1608725647
        },
        {
            "city": "Isulan",
            "city_ascii": "Isulan",
            "lat": 6.6294,
            "lng": 124.6051,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Sultan Kudarat",
            "capital": "admin",
            "population": "",
            "id": 1608085930
        },
        {
            "city": "Trece Martires City",
            "city_ascii": "Trece Martires City",
            "lat": 14.2832,
            "lng": 120.8677,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Cavite",
            "capital": "admin",
            "population": "",
            "id": 1608990723
        },
        {
            "city": "Boac",
            "city_ascii": "Boac",
            "lat": 13.4463,
            "lng": 121.84,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Marinduque",
            "capital": "admin",
            "population": "",
            "id": 1608972476
        },
        {
            "city": "Tubod",
            "city_ascii": "Tubod",
            "lat": 8.0555,
            "lng": 123.7904,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Lanao del Norte",
            "capital": "admin",
            "population": "",
            "id": 1608442374
        },
        {
            "city": "Mamburao",
            "city_ascii": "Mamburao",
            "lat": 13.2233,
            "lng": 120.596,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Occidental Mindoro",
            "capital": "admin",
            "population": "",
            "id": 1608912012
        },
        {
            "city": "Nabunturan",
            "city_ascii": "Nabunturan",
            "lat": 7.6029,
            "lng": 125.9629,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Compostela Valley",
            "capital": "admin",
            "population": "",
            "id": 1608879246
        },
        {
            "city": "Malita",
            "city_ascii": "Malita",
            "lat": 6.415,
            "lng": 125.6117,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Davao Occidental",
            "capital": "admin",
            "population": "",
            "id": 1608802375
        },
        {
            "city": "Maasin",
            "city_ascii": "Maasin",
            "lat": 10.1336,
            "lng": 124.8447,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Southern Leyte",
            "capital": "admin",
            "population": "",
            "id": 1608244406
        },
        {
            "city": "Bangued",
            "city_ascii": "Bangued",
            "lat": 17.5982,
            "lng": 120.6155,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Abra",
            "capital": "admin",
            "population": "",
            "id": 1608442037
        },
        {
            "city": "Mambajao",
            "city_ascii": "Mambajao",
            "lat": 9.2504,
            "lng": 124.7156,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Camiguin",
            "capital": "admin",
            "population": "",
            "id": 1608281273
        },
        {
            "city": "Naval",
            "city_ascii": "Naval",
            "lat": 11.5612,
            "lng": 124.3952,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Biliran",
            "capital": "admin",
            "population": "",
            "id": 1608929611
        },
        {
            "city": "Dipolog",
            "city_ascii": "Dipolog",
            "lat": 8.5883,
            "lng": 123.3409,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Zamboanga del Norte",
            "capital": "admin",
            "population": "",
            "id": 1608664300
        },
        {
            "city": "San Fernando",
            "city_ascii": "San Fernando",
            "lat": 16.6186,
            "lng": 120.3194,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "La Union",
            "capital": "admin",
            "population": "",
            "id": 1608635527
        },
        {
            "city": "Iba",
            "city_ascii": "Iba",
            "lat": 15.3276,
            "lng": 119.978,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Zambales",
            "capital": "admin",
            "population": "",
            "id": 1608986957
        },
        {
            "city": "Malolos",
            "city_ascii": "Malolos",
            "lat": 14.8443,
            "lng": 120.8104,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Bulacan",
            "capital": "admin",
            "population": "",
            "id": 1608358783
        },
        {
            "city": "Lingayen",
            "city_ascii": "Lingayen",
            "lat": 16.0218,
            "lng": 120.2319,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Pangasinan",
            "capital": "admin",
            "population": "",
            "id": 1608464071
        },
        {
            "city": "Romblon",
            "city_ascii": "Romblon",
            "lat": 12.5751,
            "lng": 122.2708,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Romblon",
            "capital": "admin",
            "population": "",
            "id": 1608428749
        },
        {
            "city": "Alabel",
            "city_ascii": "Alabel",
            "lat": 6.1018,
            "lng": 125.2905,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Sarangani",
            "capital": "admin",
            "population": "",
            "id": 1608579431
        },
        {
            "city": "Baler",
            "city_ascii": "Baler",
            "lat": 15.7589,
            "lng": 121.5607,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Aurora",
            "capital": "admin",
            "population": "",
            "id": 1608495530
        },
        {
            "city": "Siquijor",
            "city_ascii": "Siquijor",
            "lat": 9.2142,
            "lng": 123.515,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Siquijor",
            "capital": "admin",
            "population": "",
            "id": 1608692949
        },
        {
            "city": "Borongan",
            "city_ascii": "Borongan",
            "lat": 11.6081,
            "lng": 125.4319,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Eastern Samar",
            "capital": "admin",
            "population": "",
            "id": 1608990192
        },
        {
            "city": "City of Isabela",
            "city_ascii": "City of Isabela",
            "lat": 6.7041,
            "lng": 121.9712,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Basilan",
            "capital": "admin",
            "population": "",
            "id": 1608621038
        },
        {
            "city": "San Fernando",
            "city_ascii": "San Fernando",
            "lat": 15.0343,
            "lng": 120.6844,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Pampanga",
            "capital": "admin",
            "population": "",
            "id": 1608862124
        },
        {
            "city": "Lagawe",
            "city_ascii": "Lagawe",
            "lat": 16.8,
            "lng": 121.1192,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Ifugao",
            "capital": "admin",
            "population": "",
            "id": 1608396110
        },
        {
            "city": "Malaybalay",
            "city_ascii": "Malaybalay",
            "lat": 8.1575,
            "lng": 125.1278,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Bukidnon",
            "capital": "admin",
            "population": "",
            "id": 1608859265
        },
        {
            "city": "Ipil",
            "city_ascii": "Ipil",
            "lat": 7.7844,
            "lng": 122.5861,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Zamboanga Sibugay",
            "capital": "admin",
            "population": "",
            "id": 1608307222
        },
        {
            "city": "Palayan City",
            "city_ascii": "Palayan City",
            "lat": 15.5415,
            "lng": 121.0848,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Nueva Ecija",
            "capital": "admin",
            "population": "",
            "id": 1608192136
        },
        {
            "city": "Ilagan",
            "city_ascii": "Ilagan",
            "lat": 17.1485,
            "lng": 121.8892,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Isabela",
            "capital": "admin",
            "population": "",
            "id": 1608190610
        },
        {
            "city": "Basco",
            "city_ascii": "Basco",
            "lat": 20.4486,
            "lng": 121.9702,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Batanes",
            "capital": "admin",
            "population": "",
            "id": 1608620601
        },
        {
            "city": "Shariff Aguak",
            "city_ascii": "Shariff Aguak",
            "lat": 6.8647,
            "lng": 124.4417,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Maguindanao",
            "capital": "admin",
            "population": "",
            "id": 1608346338
        },
        {
            "city": "Cabarroguis",
            "city_ascii": "Cabarroguis",
            "lat": 16.5111,
            "lng": 121.5212,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Quirino",
            "capital": "admin",
            "population": "",
            "id": 1608312278
        },
        {
            "city": "Jordan",
            "city_ascii": "Jordan",
            "lat": 10.6584,
            "lng": 122.5963,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Guimaras",
            "capital": "admin",
            "population": "",
            "id": 1608769914
        },
        {
            "city": "Bontoc",
            "city_ascii": "Bontoc",
            "lat": 17.0899,
            "lng": 120.978,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Mountain",
            "capital": "admin",
            "population": "",
            "id": 1608526537
        },
        {
            "city": "Kabugao",
            "city_ascii": "Kabugao",
            "lat": 18.0231,
            "lng": 121.184,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Apayao",
            "capital": "admin",
            "population": "",
            "id": 1608841504
        },
        {
            "city": "Prosperidad",
            "city_ascii": "Prosperidad",
            "lat": 8.58,
            "lng": 125.8964,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Agusan del Sur",
            "capital": "admin",
            "population": "",
            "id": 1608461552
        },
        {
            "city": "Cabadbaran",
            "city_ascii": "Cabadbaran",
            "lat": 9.1236,
            "lng": 125.5344,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Agusan del Norte",
            "capital": "admin",
            "population": "",
            "id": 1608889253
        },
        {
            "city": "Santa Cruz",
            "city_ascii": "Santa Cruz",
            "lat": 14.1167,
            "lng": 121.2833,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Laguna",
            "capital": "admin",
            "population": "",
            "id": 1608131481
        },
        {
            "city": "Mati",
            "city_ascii": "Mati",
            "lat": 6.9551,
            "lng": 126.2166,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Davao Oriental",
            "capital": "admin",
            "population": "",
            "id": 1608000731
        },
        {
            "city": "Koronadal",
            "city_ascii": "Koronadal",
            "lat": 6.2541,
            "lng": 124.9922,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "South Cotabato",
            "capital": "admin",
            "population": "",
            "id": 1608108139
        },
        {
            "city": "San Jose",
            "city_ascii": "San Jose",
            "lat": 10.18,
            "lng": 125.5683,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Dinagat Islands",
            "capital": "admin",
            "population": "",
            "id": 1608435522
        },
        {
            "city": "Tabuk",
            "city_ascii": "Tabuk",
            "lat": 17.4084,
            "lng": 121.2785,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Kalinga",
            "capital": "admin",
            "population": "",
            "id": 1608980358
        },
        {
            "city": "Pili",
            "city_ascii": "Pili",
            "lat": 13.7177,
            "lng": 123.7448,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Camarines Sur",
            "capital": "admin",
            "population": "",
            "id": 1608825988
        }
    ]
}