module.exports = {
    CITIES: [{
            "city": "S\u00e3o Paulo",
            "city_ascii": "Sao Paulo",
            "lat": -23.5587,
            "lng": -46.625,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "S\u00e3o Paulo",
            "capital": "admin",
            "population": 18845000,
            "id": 1076532519
        },
        {
            "city": "Buenos Aires",
            "city_ascii": "Buenos Aires",
            "lat": -34.6025,
            "lng": -58.3975,
            "country": "Argentina",
            "iso2": "AR",
            "iso3": "ARG",
            "admin_name": "Buenos Aires, Ciudad Aut\u00f3noma de",
            "capital": "primary",
            "population": 12795000,
            "id": 1032717330
        },
        {
            "city": "Rio de Janeiro",
            "city_ascii": "Rio de Janeiro",
            "lat": -22.925,
            "lng": -43.225,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Rio de Janeiro",
            "capital": "admin",
            "population": 11748000,
            "id": 1076887657
        },
        {
            "city": "Lima",
            "city_ascii": "Lima",
            "lat": -12.048,
            "lng": -77.0501,
            "country": "Peru",
            "iso2": "PE",
            "iso3": "PER",
            "admin_name": "Lima",
            "capital": "primary",
            "population": 8012000,
            "id": 1604728603
        },
        {
            "city": "Bogot\u00e1",
            "city_ascii": "Bogota",
            "lat": 4.5964,
            "lng": -74.0833,
            "country": "Colombia",
            "iso2": "CO",
            "iso3": "COL",
            "admin_name": "Bogot\u00e1",
            "capital": "primary",
            "population": 7772000,
            "id": 1170483426
        },
        {
            "city": "Santiago",
            "city_ascii": "Santiago",
            "lat": -33.45,
            "lng": -70.667,
            "country": "Chile",
            "iso2": "CL",
            "iso3": "CHL",
            "admin_name": "Regi\u00f3n Metropolitana",
            "capital": "primary",
            "population": 5720000,
            "id": 1152554349
        },
        {
            "city": "Belo Horizonte",
            "city_ascii": "Belo Horizonte",
            "lat": -19.915,
            "lng": -43.915,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Minas Gerais",
            "capital": "admin",
            "population": 5575000,
            "id": 1076967355
        },
        {
            "city": "Porto Alegre",
            "city_ascii": "Porto Alegre",
            "lat": -30.05,
            "lng": -51.2,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Rio Grande do Sul",
            "capital": "admin",
            "population": 3917000,
            "id": 1076658221
        },
        {
            "city": "Bras\u00edlia",
            "city_ascii": "Brasilia",
            "lat": -15.7833,
            "lng": -47.9161,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Distrito Federal",
            "capital": "primary",
            "population": 3716996,
            "id": 1076144436
        },
        {
            "city": "Recife",
            "city_ascii": "Recife",
            "lat": -8.0756,
            "lng": -34.9156,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Pernambuco",
            "capital": "admin",
            "population": 3651000,
            "id": 1076137337
        },
        {
            "city": "Fortaleza",
            "city_ascii": "Fortaleza",
            "lat": -3.75,
            "lng": -38.58,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Cear\u00e1",
            "capital": "admin",
            "population": 3602319,
            "id": 1076567885
        },
        {
            "city": "Salvador",
            "city_ascii": "Salvador",
            "lat": -12.97,
            "lng": -38.48,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Bahia",
            "capital": "admin",
            "population": 3484000,
            "id": 1076923789
        },
        {
            "city": "Curitiba",
            "city_ascii": "Curitiba",
            "lat": -25.42,
            "lng": -49.32,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Paran\u00e1",
            "capital": "admin",
            "population": 3084000,
            "id": 1076701712
        },
        {
            "city": "Caracas",
            "city_ascii": "Caracas",
            "lat": 10.501,
            "lng": -66.917,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Distrito Capital",
            "capital": "primary",
            "population": 2985000,
            "id": 1862748204
        },
        {
            "city": "Bel\u00e9m",
            "city_ascii": "Belem",
            "lat": -1.45,
            "lng": -48.48,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Par\u00e1",
            "capital": "admin",
            "population": 2167000,
            "id": 1076646823
        },
        {
            "city": "Santo Domingo",
            "city_ascii": "Santo Domingo",
            "lat": 18.4701,
            "lng": -69.9001,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Ozama",
            "capital": "primary",
            "population": 2154000,
            "id": 1214636202
        },
        {
            "city": "Goi\u00e2nia",
            "city_ascii": "Goiania",
            "lat": -16.72,
            "lng": -49.3,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Goi\u00e1s",
            "capital": "admin",
            "population": 2022000,
            "id": 1076034054
        },
        {
            "city": "Asunci\u00f3n",
            "city_ascii": "Asuncion",
            "lat": -25.2964,
            "lng": -57.6415,
            "country": "Paraguay",
            "iso2": "PY",
            "iso3": "PRY",
            "admin_name": "Asunci\u00f3n",
            "capital": "primary",
            "population": 1870000,
            "id": 1600057911
        },
        {
            "city": "Manaus",
            "city_ascii": "Manaus",
            "lat": -3.1,
            "lng": -60,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Amazonas",
            "capital": "admin",
            "population": 1753000,
            "id": 1076607274
        },
        {
            "city": "Vit\u00f3ria",
            "city_ascii": "Vitoria",
            "lat": -20.324,
            "lng": -40.366,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Esp\u00edrito Santo",
            "capital": "admin",
            "population": 1704000,
            "id": 1076376829
        },
        {
            "city": "Quito",
            "city_ascii": "Quito",
            "lat": -0.215,
            "lng": -78.5001,
            "country": "Ecuador",
            "iso2": "EC",
            "iso3": "ECU",
            "admin_name": "Pichincha",
            "capital": "primary",
            "population": 1701000,
            "id": 1218441993
        },
        {
            "city": "La Paz",
            "city_ascii": "La Paz",
            "lat": -16.498,
            "lng": -68.15,
            "country": "Bolivia",
            "iso2": "BO",
            "iso3": "BOL",
            "admin_name": "La Paz",
            "capital": "primary",
            "population": 1590000,
            "id": 1068000064
        },
        {
            "city": "Montevideo",
            "city_ascii": "Montevideo",
            "lat": -34.858,
            "lng": -56.1711,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Montevideo",
            "capital": "primary",
            "population": 1513000,
            "id": 1858107000
        },
        {
            "city": "Macei\u00f3",
            "city_ascii": "Maceio",
            "lat": -9.62,
            "lng": -35.73,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Alagoas",
            "capital": "admin",
            "population": 1186000,
            "id": 1076440479
        },
        {
            "city": "Natal",
            "city_ascii": "Natal",
            "lat": -5.78,
            "lng": -35.24,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Rio Grande do Norte",
            "capital": "admin",
            "population": 1088000,
            "id": 1076697777
        },
        {
            "city": "S\u00e3o Lu\u00eds",
            "city_ascii": "Sao Luis",
            "lat": -2.516,
            "lng": -44.266,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Maranh\u00e3o",
            "capital": "admin",
            "population": 1038000,
            "id": 1076819308
        },
        {
            "city": "Florian\u00f3polis",
            "city_ascii": "Florianopolis",
            "lat": -27.58,
            "lng": -48.52,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Santa Catarina",
            "capital": "admin",
            "population": 1023000,
            "id": 1076190259
        },
        {
            "city": "Port of Spain",
            "city_ascii": "Port of Spain",
            "lat": 10.652,
            "lng": -61.517,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Port of Spain",
            "capital": "primary",
            "population": 294934,
            "id": 1780670676
        },
        {
            "city": "Georgetown",
            "city_ascii": "Georgetown",
            "lat": 6.802,
            "lng": -58.167,
            "country": "Guyana",
            "iso2": "GY",
            "iso3": "GUY",
            "admin_name": "Demerara-Mahaica",
            "capital": "primary",
            "population": 264350,
            "id": 1328160906
        },
        {
            "city": "Paramaribo",
            "city_ascii": "Paramaribo",
            "lat": 5.835,
            "lng": -55.167,
            "country": "Suriname",
            "iso2": "SR",
            "iso3": "SUR",
            "admin_name": "Paramaribo",
            "capital": "primary",
            "population": 254169,
            "id": 1740518660
        },
        {
            "city": "Sucre",
            "city_ascii": "Sucre",
            "lat": -19.041,
            "lng": -65.2595,
            "country": "Bolivia",
            "iso2": "BO",
            "iso3": "BOL",
            "admin_name": "Chuquisaca",
            "capital": "primary",
            "population": 224838,
            "id": 1068823873
        },
        {
            "city": "Bridgetown",
            "city_ascii": "Bridgetown",
            "lat": 13.102,
            "lng": -59.6165,
            "country": "Barbados",
            "iso2": "BB",
            "iso3": "BRB",
            "admin_name": "Saint Michael",
            "capital": "primary",
            "population": 191152,
            "id": 1052274244
        },
        {
            "city": "Willemstad",
            "city_ascii": "Willemstad",
            "lat": 12.2004,
            "lng": -69.02,
            "country": "Cura\u00e7ao",
            "iso2": "CW",
            "iso3": "CUW",
            "admin_name": "",
            "capital": "primary",
            "population": 146813,
            "id": 1531000000
        },
        {
            "city": "Oranjestad",
            "city_ascii": "Oranjestad",
            "lat": 12.5304,
            "lng": -70.029,
            "country": "Aruba",
            "iso2": "AW",
            "iso3": "ABW",
            "admin_name": "",
            "capital": "primary",
            "population": 68775,
            "id": 1533513057
        },
        {
            "city": "Kingstown",
            "city_ascii": "Kingstown",
            "lat": 13.1483,
            "lng": -61.2121,
            "country": "Saint Vincent And The Grenadines",
            "iso2": "VC",
            "iso3": "VCT",
            "admin_name": "Saint George",
            "capital": "primary",
            "population": 49485,
            "id": 1670376659
        },
        {
            "city": "Castries",
            "city_ascii": "Castries",
            "lat": 14.002,
            "lng": -61,
            "country": "Saint Lucia",
            "iso2": "LC",
            "iso3": "LCA",
            "admin_name": "Castries",
            "capital": "primary",
            "population": 37963,
            "id": 1662922505
        },
        {
            "city": "Saint John\u2019s",
            "city_ascii": "Saint John's",
            "lat": 17.118,
            "lng": -61.85,
            "country": "Antigua And Barbuda",
            "iso2": "AG",
            "iso3": "ATG",
            "admin_name": "Saint John",
            "capital": "primary",
            "population": 35499,
            "id": 1028912067
        },
        {
            "city": "Saint George\u2019s",
            "city_ascii": "Saint George's",
            "lat": 12.0526,
            "lng": -61.7416,
            "country": "Grenada",
            "iso2": "GD",
            "iso3": "GRD",
            "admin_name": "Saint George",
            "capital": "primary",
            "population": 33734,
            "id": 1308891766
        },
        {
            "city": "Roseau",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/RoseauWide..jpg/300px-RoseauWide..jpg",
            "city_ascii": "Roseau",
            "lat": 15.301,
            "lng": -61.387,
            "country": "Dominica",
            "iso2": "DM",
            "iso3": "DMA",
            "admin_name": "Saint George",
            "capital": "primary",
            "population": 23336,
            "id": 1212060440
        },
        {
            "city": "Basseterre",
            "city_ascii": "Basseterre",
            "lat": 17.302,
            "lng": -62.717,
            "country": "Saint Kitts And Nevis",
            "iso2": "KN",
            "iso3": "KNA",
            "admin_name": "Saint George Basseterre",
            "capital": "primary",
            "population": 21887,
            "id": 1659198919
        },
        {
            "city": "Philipsburg",
            "city_ascii": "Philipsburg",
            "lat": 18.0255,
            "lng": -63.045,
            "country": "Sint Maarten",
            "iso2": "SX",
            "iso3": "SXM",
            "admin_name": "",
            "capital": "primary",
            "population": "",
            "id": 1534859858
        },
        {
            "city": "Jo\u00e3o Pessoa",
            "city_ascii": "Joao Pessoa",
            "lat": -7.1011,
            "lng": -34.8761,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Para\u00edba",
            "capital": "admin",
            "population": 956000,
            "id": 1076922014
        },
        {
            "city": "Teresina",
            "city_ascii": "Teresina",
            "lat": -5.095,
            "lng": -42.78,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Piau\u00ed",
            "capital": "admin",
            "population": 907000,
            "id": 1076727667
        },
        {
            "city": "Cuiab\u00e1",
            "city_ascii": "Cuiaba",
            "lat": -15.5696,
            "lng": -56.085,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Mato Grosso",
            "capital": "admin",
            "population": 806000,
            "id": 1076112309
        },
        {
            "city": "Campo Grande",
            "city_ascii": "Campo Grande",
            "lat": -20.45,
            "lng": -54.6166,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Mato Grosso do Sul",
            "capital": "admin",
            "population": 778000,
            "id": 1076660445
        },
        {
            "city": "Aracaju",
            "city_ascii": "Aracaju",
            "lat": -10.9,
            "lng": -37.12,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Sergipe",
            "capital": "admin",
            "population": 685356,
            "id": 1076527830
        },
        {
            "city": "Macap\u00e1",
            "city_ascii": "Macapa",
            "lat": 0.033,
            "lng": -51.05,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Amap\u00e1",
            "capital": "admin",
            "population": 499166,
            "id": 1076189884
        },
        {
            "city": "Porto Velho",
            "city_ascii": "Porto Velho",
            "lat": -8.75,
            "lng": -63.9,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Rond\u00f4nia",
            "capital": "admin",
            "population": 306180,
            "id": 1076045591
        },
        {
            "city": "Rio Branco",
            "city_ascii": "Rio Branco",
            "lat": -9.9666,
            "lng": -67.8,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Acre",
            "capital": "admin",
            "population": 257642,
            "id": 1076391263
        },
        {
            "city": "Palmas",
            "city_ascii": "Palmas",
            "lat": -10.2377,
            "lng": -48.2878,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Tocantins",
            "capital": "admin",
            "population": 235315,
            "id": 1076052802
        },
        {
            "city": "Boa Vista",
            "city_ascii": "Boa Vista",
            "lat": 2.8161,
            "lng": -60.666,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Roraima",
            "capital": "admin",
            "population": 235150,
            "id": 1076621300
        },
        {
            "city": "Puerto Baquerizo Moreno",
            "city_ascii": "Puerto Baquerizo Moreno",
            "lat": -0.9,
            "lng": -89.6,
            "country": "Ecuador",
            "iso2": "EC",
            "iso3": "ECU",
            "admin_name": "Gal\u00e1pagos",
            "capital": "admin",
            "population": 6030,
            "id": 1218093882
        },
        {
            "city": "Santa Cruz",
            "city_ascii": "Santa Cruz",
            "lat": -0.5333,
            "lng": -90.35,
            "country": "Ecuador",
            "iso2": "EC",
            "iso3": "ECU",
            "admin_name": "Gal\u00e1pagos",
            "capital": "",
            "population": 11262,
            "id": 1218773967
        },
        {
            "city": "George Town",
            "city_ascii": "George Town",
            "lat": 19.2804,
            "lng": -81.33,
            "country": "Cayman Islands",
            "iso2": "KY",
            "iso3": "CYM",
            "admin_name": "",
            "capital": "primary",
            "population": 4268,
            "id": 1136159124
        },
        {
            "city": "Puerto Villamil",
            "city_ascii": "Puerto Villamil",
            "lat": -0.9333,
            "lng": -91.0167,
            "country": "Ecuador",
            "iso2": "EC",
            "iso3": "ECU",
            "admin_name": "Gal\u00e1pagos",
            "capital": "",
            "population": 2200,
            "id": 1218383536
        },
        {
            "city": "Stanley",
            "city_ascii": "Stanley",
            "lat": -51.7,
            "lng": -57.85,
            "country": "Falkland Islands (Islas Malvinas)",
            "iso2": "FK",
            "iso3": "FLK",
            "admin_name": "",
            "capital": "",
            "population": 2213,
            "id": 1238780509
        },
        {
            "city": "Hanga Roa",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Moais%2C_Isla_de_Pascua._-_panoramio.jpg/1280px-Moais%2C_Isla_de_Pascua._-_panoramio.jpg",
            "city_ascii": "Hanga Roa",
            "lat": -27.133333,
            "lng": -109.416667,
            "country": "Chile",
            "iso2": "CL",
            "iso3": "CHL",
            "admin_name": "Easter Island",
            "capital": "admin",
            "population": 3304,
            "id": 9999999999
        }
    ]
}