module.exports = { CITIES: [
  {
    "city": "Johannesburg",
    "city_ascii": "Johannesburg",
    "lat": -26.17,
    "lng": 28.03,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Gauteng",
    "capital": "admin",
    "population": 3435000,
    "id": 1710550792
  },
  {
    "city": "Cape Town",
    "city_ascii": "Cape Town",
    "lat": -33.92,
    "lng": 18.435,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Western Cape",
    "capital": "primary",
    "population": 3215000,
    "id": 1710680650
  },
  {
    "city": "Benoni",
    "city_ascii": "Benoni",
    "lat": -26.1496,
    "lng": 28.3299,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Gauteng",
    "capital": "",
    "population": 2986000,
    "id": 1710880986
  },
  {
    "city": "Durban",
    "city_ascii": "Durban",
    "lat": -29.865,
    "lng": 30.98,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "KwaZulu-Natal",
    "capital": "",
    "population": 2729000,
    "id": 1710149138
  },
  {
    "city": "Pretoria",
    "city_ascii": "Pretoria",
    "lat": -25.7069,
    "lng": 28.2294,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Gauteng",
    "capital": "primary",
    "population": 1338000,
    "id": 1710176249
  },
  {
    "city": "Vereeniging",
    "city_ascii": "Vereeniging",
    "lat": -26.6496,
    "lng": 27.96,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Gauteng",
    "capital": "",
    "population": 1074000,
    "id": 1710271883
  },
  {
    "city": "Port Elizabeth",
    "city_ascii": "Port Elizabeth",
    "lat": -33.97,
    "lng": 25.6,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Eastern Cape",
    "capital": "",
    "population": 1021000,
    "id": 1710918997
  },
  {
    "city": "Bloemfontein",
    "city_ascii": "Bloemfontein",
    "lat": -29.12,
    "lng": 26.2299,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Free State",
    "capital": "primary",
    "population": 463064,
    "id": 1710495933
  },
  {
    "city": "Pietermaritzburg",
    "city_ascii": "Pietermaritzburg",
    "lat": -29.61,
    "lng": 30.39,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "KwaZulu-Natal",
    "capital": "admin",
    "population": 750845,
    "id": 1710690280
  },
  {
    "city": "Welkom",
    "city_ascii": "Welkom",
    "lat": -27.97,
    "lng": 26.73,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Free State",
    "capital": "",
    "population": 431944,
    "id": 1710480365
  },
  {
    "city": "East London",
    "city_ascii": "East London",
    "lat": -32.97,
    "lng": 27.87,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Eastern Cape",
    "capital": "",
    "population": 338627,
    "id": 1710178149
  },
  {
    "city": "Thohoyandou",
    "city_ascii": "Thohoyandou",
    "lat": -22.95,
    "lng": 30.48,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Limpopo",
    "capital": "",
    "population": 269707,
    "id": 1710219075
  },
  {
    "city": "Springs",
    "city_ascii": "Springs",
    "lat": -26.2696,
    "lng": 28.43,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Gauteng",
    "capital": "",
    "population": 236083,
    "id": 1710058382
  },
  {
    "city": "Uitenhage",
    "city_ascii": "Uitenhage",
    "lat": -33.7596,
    "lng": 25.39,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Eastern Cape",
    "capital": "",
    "population": 228912,
    "id": 1710276157
  },
  {
    "city": "Polokwane",
    "city_ascii": "Polokwane",
    "lat": -23.89,
    "lng": 29.45,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Limpopo",
    "capital": "admin",
    "population": 220045,
    "id": 1710908010
  },
  {
    "city": "Paarl",
    "city_ascii": "Paarl",
    "lat": -33.6996,
    "lng": 18.96,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Western Cape",
    "capital": "",
    "population": 187865,
    "id": 1710440011
  },
  {
    "city": "Klerksdorp",
    "city_ascii": "Klerksdorp",
    "lat": -26.88,
    "lng": 26.62,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "North West",
    "capital": "",
    "population": 178921,
    "id": 1710416691
  },
  {
    "city": "George",
    "city_ascii": "George",
    "lat": -33.95,
    "lng": 22.45,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Western Cape",
    "capital": "",
    "population": 174582,
    "id": 1710164136
  },
  {
    "city": "Rustenburg",
    "city_ascii": "Rustenburg",
    "lat": -25.65,
    "lng": 27.24,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "North West",
    "capital": "",
    "population": 165976,
    "id": 1710326039
  },
  {
    "city": "Kimberley",
    "city_ascii": "Kimberley",
    "lat": -28.7468,
    "lng": 24.77,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Northern Cape",
    "capital": "admin",
    "population": 165264,
    "id": 1710282622
  },
  {
    "city": "Bhisho",
    "city_ascii": "Bhisho",
    "lat": -32.87,
    "lng": 27.39,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Eastern Cape",
    "capital": "admin",
    "population": 160997,
    "id": 1710672530
  },
  {
    "city": "Middelburg",
    "city_ascii": "Middelburg",
    "lat": -25.7596,
    "lng": 29.47,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Mpumalanga",
    "capital": "",
    "population": 154706,
    "id": 1710495632
  },
  {
    "city": "Vryheid",
    "city_ascii": "Vryheid",
    "lat": -27.76,
    "lng": 30.79,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "KwaZulu-Natal",
    "capital": "",
    "population": 150012,
    "id": 1710716158
  },
  {
    "city": "Umtata",
    "city_ascii": "Umtata",
    "lat": -31.58,
    "lng": 28.79,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Eastern Cape",
    "capital": "",
    "population": 137772,
    "id": 1710651314
  },
  {
    "city": "Worcester",
    "city_ascii": "Worcester",
    "lat": -33.64,
    "lng": 19.4399,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Western Cape",
    "capital": "",
    "population": 127597,
    "id": 1710498245
  },
  {
    "city": "Potchefstroom",
    "city_ascii": "Potchefstroom",
    "lat": -26.6996,
    "lng": 27.1,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "North West",
    "capital": "",
    "population": 123669,
    "id": 1710838885
  },
  {
    "city": "Brits",
    "city_ascii": "Brits",
    "lat": -25.6296,
    "lng": 27.78,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "North West",
    "capital": "",
    "population": 122497,
    "id": 1710468143
  },
  {
    "city": "Queenstown",
    "city_ascii": "Queenstown",
    "lat": -31.8996,
    "lng": 26.88,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Eastern Cape",
    "capital": "",
    "population": 105309,
    "id": 1710110028
  },
  {
    "city": "Mmabatho",
    "city_ascii": "Mmabatho",
    "lat": -25.83,
    "lng": 25.61,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "North West",
    "capital": "",
    "population": 104428,
    "id": 1710524815
  },
  {
    "city": "Kroonstad",
    "city_ascii": "Kroonstad",
    "lat": -27.66,
    "lng": 27.21,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Free State",
    "capital": "",
    "population": 103992,
    "id": 1710508288
  },
  {
    "city": "Bethal",
    "city_ascii": "Bethal",
    "lat": -26.4696,
    "lng": 29.45,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Mpumalanga",
    "capital": "",
    "population": 101919,
    "id": 1710328253
  },
  {
    "city": "Upington",
    "city_ascii": "Upington",
    "lat": -28.46,
    "lng": 21.23,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Northern Cape",
    "capital": "",
    "population": 71373,
    "id": 1710210449
  },
  {
    "city": "Graaff-Reinet",
    "city_ascii": "Graaff-Reinet",
    "lat": -32.3,
    "lng": 24.54,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Eastern Cape",
    "capital": "",
    "population": 62896,
    "id": 1710616617
  },
  {
    "city": "Vryburg",
    "city_ascii": "Vryburg",
    "lat": -26.96,
    "lng": 24.73,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "North West",
    "capital": "",
    "population": 49588,
    "id": 1710969597
  },
  {
    "city": "Cradock",
    "city_ascii": "Cradock",
    "lat": -32.1995,
    "lng": 25.61,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Eastern Cape",
    "capital": "",
    "population": 32898,
    "id": 1710933404
  },
  {
    "city": "Mahikeng",
    "city_ascii": "Mahikeng",
    "lat": -25.8652,
    "lng": 25.6442,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "North West",
    "capital": "admin",
    "population": "",
    "id": 1710965423
  },
  {
    "city": "Nelspruit",
    "city_ascii": "Nelspruit",
    "lat": -25.4745,
    "lng": 30.9703,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Mpumalanga",
    "capital": "admin",
    "population": "",
    "id": 1710114438
  },
  {
    "city": "Grahamstown",
    "city_ascii": "Grahamstown",
    "lat": -33.2996,
    "lng": 26.52,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Eastern Cape",
    "capital": "",
    "population": 91548,
    "id": 1710671857
  },
  {
    "city": "Bethlehem",
    "city_ascii": "Bethlehem",
    "lat": -28.2196,
    "lng": 28.3,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Free State",
    "capital": "",
    "population": 83654,
    "id": 1710750307
  },
  {
    "city": "Oudtshoorn",
    "city_ascii": "Oudtshoorn",
    "lat": -33.58,
    "lng": 22.19,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Western Cape",
    "capital": "",
    "population": 76708,
    "id": 1710502855
  },
  {
    "city": "Standerton",
    "city_ascii": "Standerton",
    "lat": -26.9395,
    "lng": 29.24,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Mpumalanga",
    "capital": "",
    "population": 74021,
    "id": 1710222465
  },
  {
    "city": "Saldanha",
    "city_ascii": "Saldanha",
    "lat": -33.01,
    "lng": 17.93,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Western Cape",
    "capital": "",
    "population": 68284,
    "id": 1710078862
  },
  {
    "city": "Tzaneen",
    "city_ascii": "Tzaneen",
    "lat": -23.8195,
    "lng": 30.17,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Limpopo",
    "capital": "",
    "population": 67245,
    "id": 1710120942
  },
  {
    "city": "Knysna",
    "city_ascii": "Knysna",
    "lat": -34.0329,
    "lng": 23.0333,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Western Cape",
    "capital": "",
    "population": 63106,
    "id": 1710311704
  },
  {
    "city": "Port Shepstone",
    "city_ascii": "Port Shepstone",
    "lat": -30.7195,
    "lng": 30.46,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "KwaZulu-Natal",
    "capital": "",
    "population": 52793,
    "id": 1710443227
  },
  {
    "city": "Ladysmith",
    "city_ascii": "Ladysmith",
    "lat": -28.5495,
    "lng": 29.78,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "KwaZulu-Natal",
    "capital": "",
    "population": 47375,
    "id": 1710998347
  },
  {
    "city": "Beaufort West",
    "city_ascii": "Beaufort West",
    "lat": -32.3496,
    "lng": 22.57,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Western Cape",
    "capital": "",
    "population": 44737,
    "id": 1710940488
  },
  {
    "city": "Aliwal North",
    "city_ascii": "Aliwal North",
    "lat": -30.6896,
    "lng": 26.71,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Eastern Cape",
    "capital": "",
    "population": 44436,
    "id": 1710445896
  },
  {
    "city": "Volksrust",
    "city_ascii": "Volksrust",
    "lat": -27.3596,
    "lng": 29.89,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Mpumalanga",
    "capital": "",
    "population": 43378,
    "id": 1710664906
  },
  {
    "city": "Lebowakgomo",
    "city_ascii": "Lebowakgomo",
    "lat": -24.1996,
    "lng": 29.5,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Limpopo",
    "capital": "",
    "population": 33308,
    "id": 1710999076
  },
  {
    "city": "De Aar",
    "city_ascii": "De Aar",
    "lat": -30.65,
    "lng": 24,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Northern Cape",
    "capital": "",
    "population": 32318,
    "id": 1710551900
  },
  {
    "city": "Hermanus",
    "city_ascii": "Hermanus",
    "lat": -34.4096,
    "lng": 19.2299,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Western Cape",
    "capital": "",
    "population": 25153,
    "id": 1710409701
  },
  {
    "city": "Ulundi",
    "city_ascii": "Ulundi",
    "lat": -28.3296,
    "lng": 31.41,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "KwaZulu-Natal",
    "capital": "",
    "population": 20753,
    "id": 1710823263
  },
  {
    "city": "Komatipoort",
    "city_ascii": "Komatipoort",
    "lat": -25.4096,
    "lng": 31.94,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Mpumalanga",
    "capital": "",
    "population": 20508,
    "id": 1710137353
  },
  {
    "city": "Musina",
    "city_ascii": "Musina",
    "lat": -22.34,
    "lng": 30.03,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Limpopo",
    "capital": "",
    "population": 20191,
    "id": 1710956370
  },
  {
    "city": "Middelburg",
    "city_ascii": "Middelburg",
    "lat": -31.5,
    "lng": 25.01,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Eastern Cape",
    "capital": "",
    "population": 18164,
    "id": 1710010705
  },
  {
    "city": "Port Alfred",
    "city_ascii": "Port Alfred",
    "lat": -33.5995,
    "lng": 26.88,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Eastern Cape",
    "capital": "",
    "population": 17959,
    "id": 1710920478
  },
  {
    "city": "Bloemhof",
    "city_ascii": "Bloemhof",
    "lat": -27.6496,
    "lng": 25.59,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "North West",
    "capital": "",
    "population": 17122,
    "id": 1710321800
  },
  {
    "city": "Mossel Bay",
    "city_ascii": "Mossel Bay",
    "lat": -34.17,
    "lng": 22.13,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Western Cape",
    "capital": "",
    "population": 16743,
    "id": 1710597106
  },
  {
    "city": "Bredasdorp",
    "city_ascii": "Bredasdorp",
    "lat": -34.5295,
    "lng": 20.03,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Western Cape",
    "capital": "",
    "population": 14936,
    "id": 1710282172
  },
  {
    "city": "Swellendam",
    "city_ascii": "Swellendam",
    "lat": -34.0196,
    "lng": 20.43,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Western Cape",
    "capital": "",
    "population": 13674,
    "id": 1710416218
  },
  {
    "city": "Colesberg",
    "city_ascii": "Colesberg",
    "lat": -30.7195,
    "lng": 25.1,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Northern Cape",
    "capital": "",
    "population": 12423,
    "id": 1710885210
  },
  {
    "city": "Brandfort",
    "city_ascii": "Brandfort",
    "lat": -28.6996,
    "lng": 26.47,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Free State",
    "capital": "",
    "population": 12091,
    "id": 1710953731
  },
  {
    "city": "Prieska",
    "city_ascii": "Prieska",
    "lat": -29.6595,
    "lng": 22.73,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Northern Cape",
    "capital": "",
    "population": 11236,
    "id": 1710649877
  },
  {
    "city": "Springbok",
    "city_ascii": "Springbok",
    "lat": -29.6667,
    "lng": 17.8833,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Northern Cape",
    "capital": "",
    "population": 10438,
    "id": 1710894218
  },
  {
    "city": "Kuruman",
    "city_ascii": "Kuruman",
    "lat": -27.4496,
    "lng": 23.42,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Northern Cape",
    "capital": "",
    "population": 10006,
    "id": 1710332978
  },
  {
    "city": "Port Saint John\u2019s",
    "city_ascii": "Port Saint John's",
    "lat": -31.6279,
    "lng": 29.5283,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Eastern Cape",
    "capital": "",
    "population": 5939,
    "id": 1710506018
  },
  {
    "city": "Carnarvon",
    "city_ascii": "Carnarvon",
    "lat": -30.9496,
    "lng": 22.1333,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Northern Cape",
    "capital": "",
    "population": 5785,
    "id": 1710331786
  },
  {
    "city": "Pofadder",
    "city_ascii": "Pofadder",
    "lat": -29.1329,
    "lng": 19.3834,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Northern Cape",
    "capital": "",
    "population": 4220,
    "id": 1710817164
  },
  {
    "city": "Vanrhynsdorp",
    "city_ascii": "Vanrhynsdorp",
    "lat": -31.6166,
    "lng": 18.7333,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Western Cape",
    "capital": "",
    "population": 3331,
    "id": 1710187274
  },
  {
    "city": "Alexander Bay",
    "city_ascii": "Alexander Bay",
    "lat": -28.6083,
    "lng": 16.5033,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "Northern Cape",
    "capital": "",
    "population": 1500,
    "id": 1710616152
  },
  {
    "city": "Ubombo",
    "city_ascii": "Ubombo",
    "lat": -27.5661,
    "lng": 32.0833,
    "country": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "admin_name": "KwaZulu-Natal",
    "capital": "",
    "population": 564,
    "id": 1710203500
  }
]}