module.exports = {
    CITIES: [{
            "city": "Seoul",
            "city_ascii": "Seoul",
            "lat": 37.5663,
            "lng": 126.9997,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Seoul",
            "capital": "primary",
            "population": 9796000,
            "id": 1410836482
        },
        {
            "city": "Busan",
            "city_ascii": "Busan",
            "lat": 35.0951,
            "lng": 129.01,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Busan",
            "capital": "admin",
            "population": 3480000,
            "id": 1410601465
        },
        {
            "city": "Incheon",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/8/86/%EC%9D%B8%EC%B2%9C%EB%8F%84%ED%98%B8%EB%B6%80%EC%B2%AD%EC%82%AC_%EC%95%84%EB%AC%B8.jpg",
            "city_ascii": "Incheon",
            "lat": 37.4761,
            "lng": 126.6422,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Incheon",
            "capital": "admin",
            "population": 2550000,
            "id": 1410160313
        },
        {
            "city": "Daegu",
            "city_ascii": "Daegu",
            "lat": 35.8668,
            "lng": 128.607,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Daegu",
            "capital": "admin",
            "population": 2460000,
            "id": 1410095252
        },
        {
            "city": "Daejeon",
            "city_ascii": "Daejeon",
            "lat": 36.3355,
            "lng": 127.425,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Daejeon",
            "capital": "admin",
            "population": 1468000,
            "id": 1410993875
        },
        {
            "city": "Gwangju",
            "city_ascii": "Gwangju",
            "lat": 35.171,
            "lng": 126.9104,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Gwangju",
            "capital": "admin",
            "population": 1440000,
            "id": 1410000087
        },
        {
            "city": "Changwon",
            "city_ascii": "Changwon",
            "lat": 35.2191,
            "lng": 128.5836,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Gyeongnam",
            "capital": "admin",
            "population": 1081499,
            "id": 1410592618
        },
        {
            "city": "Suwon",
            "city_ascii": "Suwon",
            "lat": 37.2578,
            "lng": 127.0109,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Gyeonggi",
            "capital": "admin",
            "population": 1078000,
            "id": 1410679777
        },
        {
            "city": "Ulsan",
            "city_ascii": "Ulsan",
            "lat": 35.5467,
            "lng": 129.317,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Ulsan",
            "capital": "admin",
            "population": 1061000,
            "id": 1410134602
        },
        {
            "city": "S\u014fngnam",
            "city_ascii": "Songnam",
            "lat": 37.4386,
            "lng": 127.1378,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Gyeonggi",
            "capital": "",
            "population": 942000,
            "id": 1410622472
        },
        {
            "city": "Goyang",
            "city_ascii": "Goyang",
            "lat": 37.6527,
            "lng": 126.8372,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Gyeonggi",
            "capital": "minor",
            "population": 903000,
            "id": 1410511255
        },
        {
            "city": "Bucheon",
            "city_ascii": "Bucheon",
            "lat": 37.4989,
            "lng": 126.7831,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Gyeonggi",
            "capital": "minor",
            "population": 866000,
            "id": 1410428222
        },
        {
            "city": "Cheongju",
            "city_ascii": "Cheongju",
            "lat": 36.6439,
            "lng": 127.5012,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Chungbuk",
            "capital": "admin",
            "population": 775096,
            "id": 1410964361
        },
        {
            "city": "Ansan",
            "city_ascii": "Ansan",
            "lat": 37.3481,
            "lng": 126.8595,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Gyeonggi",
            "capital": "",
            "population": 739493,
            "id": 1410585171
        },
        {
            "city": "Jeonju",
            "city_ascii": "Jeonju",
            "lat": 35.8314,
            "lng": 127.1404,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Jeonbuk",
            "capital": "minor",
            "population": 711424,
            "id": 1410494847
        },
        {
            "city": "Pohang",
            "city_ascii": "Pohang",
            "lat": 36.0209,
            "lng": 129.3715,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Gyeongbuk",
            "capital": "minor",
            "population": 435266,
            "id": 1410983252
        },
        {
            "city": "Jeju",
            "city_ascii": "Jeju",
            "lat": 33.5101,
            "lng": 126.5219,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Jeju",
            "capital": "admin",
            "population": 408364,
            "id": 1410364424
        },
        {
            "city": "Yeosu",
            "city_ascii": "Yeosu",
            "lat": 34.7368,
            "lng": 127.7458,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Jeonnam",
            "capital": "minor",
            "population": 341994,
            "id": 1410002025
        },
        {
            "city": "Iksan",
            "city_ascii": "Iksan",
            "lat": 35.941,
            "lng": 126.9454,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Jeonbuk",
            "capital": "",
            "population": 283501,
            "id": 1410134391
        },
        {
            "city": "Mokpo",
            "city_ascii": "Mokpo",
            "lat": 34.8068,
            "lng": 126.3958,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Jeonnam",
            "capital": "minor",
            "population": 268402,
            "id": 1410279439
        },
        {
            "city": "Kunsan",
            "city_ascii": "Kunsan",
            "lat": 35.9818,
            "lng": 126.716,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Jeonbuk",
            "capital": "",
            "population": 244080,
            "id": 1410913202
        },
        {
            "city": "W\u014fnju",
            "city_ascii": "Wonju",
            "lat": 37.3551,
            "lng": 127.9396,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Gangwon",
            "capital": "",
            "population": 243387,
            "id": 1410782685
        },
        {
            "city": "Chuncheon",
            "city_ascii": "Chuncheon",
            "lat": 37.8747,
            "lng": 127.7342,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Gangwon",
            "capital": "admin",
            "population": 226509,
            "id": 1410231130
        },
        {
            "city": "Gangneung",
            "city_ascii": "Gangneung",
            "lat": 37.7559,
            "lng": 128.8962,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Gangwon",
            "capital": "minor",
            "population": 180611,
            "id": 1410450550
        },
        {
            "city": "Ky\u014fngju",
            "city_ascii": "Kyongju",
            "lat": 35.8428,
            "lng": 129.2117,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Gyeongbuk",
            "capital": "",
            "population": 155237,
            "id": 1410173146
        },
        {
            "city": "Andong",
            "city_ascii": "Andong",
            "lat": 36.5659,
            "lng": 128.725,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Gyeongbuk",
            "capital": "admin",
            "population": 129319,
            "id": 1410095935
        },
        {
            "city": "Sejong",
            "city_ascii": "Sejong",
            "lat": 36.6092,
            "lng": 127.2919,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Sejong",
            "capital": "admin",
            "population": "",
            "id": 1410002592
        },
        {
            "city": "Hongseong",
            "city_ascii": "Hongseong",
            "lat": 36.6009,
            "lng": 126.665,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Chungnam",
            "capital": "admin",
            "population": "",
            "id": 1410822139
        },
        {
            "city": "Muan",
            "city_ascii": "Muan",
            "lat": 34.9897,
            "lng": 126.4714,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Jeonnam",
            "capital": "admin",
            "population": "",
            "id": 1410001061
        },
        {
            "city": "Sokcho",
            "city_ascii": "Sokcho",
            "lat": 38.2087,
            "lng": 128.5912,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Gangwon",
            "capital": "minor",
            "population": 85430,
            "id": 1410921315
        },
        {
            "city": "Eumseong",
            "city_ascii": "Eumseong",
            "lat": 36.9353,
            "lng": 127.6897,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Chungbuk",
            "capital": "",
            "population": 10077,
            "id": 1410812829
        }
    ]
}