module.exports = {
    CITIES: [{
            "city": "Madrid",
            "city_ascii": "Madrid",
            "lat": 40.4,
            "lng": -3.6834,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Madrid",
            "capital": "primary",
            "population": 5567000,
            "id": 1724616994
        },
        {
            "city": "Barcelona",
            "city_ascii": "Barcelona",
            "lat": 41.3833,
            "lng": 2.1834,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Catalonia",
            "capital": "admin",
            "population": 4920000,
            "id": 1724594040
        },
        {
            "city": "Sevilla",
            "city_ascii": "Sevilla",
            "lat": 37.405,
            "lng": -5.98,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Andalusia",
            "capital": "admin",
            "population": 1212045,
            "id": 1724991838
        },
        {
            "city": "Bilbao",
            "city_ascii": "Bilbao",
            "lat": 43.25,
            "lng": -2.93,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Basque Country",
            "capital": "minor",
            "population": 875552,
            "id": 1724331267
        },
        {
            "city": "Valencia",
            "city_ascii": "Valencia",
            "lat": 39.485,
            "lng": -0.4,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Valencia",
            "capital": "admin",
            "population": 808000,
            "id": 1724981666
        },
        {
            "city": "Zaragoza",
            "city_ascii": "Zaragoza",
            "lat": 41.65,
            "lng": -0.89,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Aragon",
            "capital": "admin",
            "population": 649404,
            "id": 1724907391
        },
        {
            "city": "M\u00e1laga",
            "city_ascii": "Malaga",
            "lat": 36.7204,
            "lng": -4.42,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Andalusia",
            "capital": "minor",
            "population": 550058,
            "id": 1724397372
        },
        {
            "city": "Murcia",
            "city_ascii": "Murcia",
            "lat": 37.98,
            "lng": -1.13,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Murcia",
            "capital": "admin",
            "population": 406807,
            "id": 1724107739
        },
        {
            "city": "Granada",
            "city_ascii": "Granada",
            "lat": 37.165,
            "lng": -3.585,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Andalusia",
            "capital": "minor",
            "population": 388290,
            "id": 1724929320
        },
        {
            "city": "Vigo",
            "city_ascii": "Vigo",
            "lat": 42.22,
            "lng": -8.73,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Galicia",
            "capital": "",
            "population": 378952,
            "id": 1724045676
        },
        {
            "city": "Palma",
            "city_ascii": "Palma",
            "lat": 39.5743,
            "lng": 2.6542,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Balearic Islands",
            "capital": "admin",
            "population": 375773,
            "id": 1724728111
        },
        {
            "city": "A Coru\u00f1a",
            "city_ascii": "A Coruna",
            "lat": 43.33,
            "lng": -8.42,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Galicia",
            "capital": "minor",
            "population": 370610,
            "id": 1724417375
        },
        {
            "city": "Donostia",
            "city_ascii": "Donostia",
            "lat": 43.3204,
            "lng": -1.98,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Basque Country",
            "capital": "minor",
            "population": 357468,
            "id": 1724910555
        },
        {
            "city": "Gij\u00f3n",
            "city_ascii": "Gijon",
            "lat": 43.53,
            "lng": -5.67,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Asturias",
            "capital": "",
            "population": 335972,
            "id": 1724170659
        },
        {
            "city": "Valladolid",
            "city_ascii": "Valladolid",
            "lat": 41.65,
            "lng": -4.75,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Castille-Leon",
            "capital": "admin",
            "population": 322304,
            "id": 1724133771
        },
        {
            "city": "C\u00f3rdoba",
            "city_ascii": "Cordoba",
            "lat": 37.88,
            "lng": -4.77,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Andalusia",
            "capital": "minor",
            "population": 321376,
            "id": 1724706440
        },
        {
            "city": "Alicante",
            "city_ascii": "Alicante",
            "lat": 38.3512,
            "lng": -0.4836,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Valencia",
            "capital": "minor",
            "population": 315863,
            "id": 1724923163
        },
        {
            "city": "C\u00e1diz",
            "city_ascii": "Cadiz",
            "lat": 36.535,
            "lng": -6.225,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Andalusia",
            "capital": "minor",
            "population": 283157,
            "id": 1724502822
        },
        {
            "city": "Pamplona",
            "city_ascii": "Pamplona",
            "lat": 42.82,
            "lng": -1.65,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Navarre",
            "capital": "admin",
            "population": 274545,
            "id": 1724483329
        },
        {
            "city": "Oviedo",
            "city_ascii": "Oviedo",
            "lat": 43.3505,
            "lng": -5.83,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Asturias",
            "capital": "admin",
            "population": 235651,
            "id": 1724090743
        },
        {
            "city": "Vitoria-Gasteiz",
            "city_ascii": "Vitoria-Gasteiz",
            "lat": 42.85,
            "lng": -2.67,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Basque Country",
            "capital": "admin",
            "population": 224578,
            "id": 1724975338
        },
        {
            "city": "Santander",
            "city_ascii": "Santander",
            "lat": 43.3805,
            "lng": -3.8,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Cantabria",
            "capital": "admin",
            "population": 208763,
            "id": 1724247413
        },
        {
            "city": "Cartagena",
            "city_ascii": "Cartagena",
            "lat": 37.6004,
            "lng": -0.98,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Murcia",
            "capital": "",
            "population": 201274,
            "id": 1724143241
        },
        {
            "city": "Marbella",
            "city_ascii": "Marbella",
            "lat": 36.5166,
            "lng": -4.8833,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Andalusia",
            "capital": "",
            "population": 186131,
            "id": 1724685705
        },
        {
            "city": "Matar\u00f3",
            "city_ascii": "Mataro",
            "lat": 41.54,
            "lng": 2.45,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Catalonia",
            "capital": "",
            "population": 183293,
            "id": 1724901780
        },
        {
            "city": "Castell\u00f3n de la Plana",
            "city_ascii": "Castellon de la Plana",
            "lat": 39.9704,
            "lng": -0.05,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Valencia",
            "capital": "minor",
            "population": 180610,
            "id": 1724579885
        },
        {
            "city": "Almer\u00eda",
            "city_ascii": "Almeria",
            "lat": 36.8303,
            "lng": -2.43,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Andalusia",
            "capital": "minor",
            "population": 179405,
            "id": 1724745640
        },
        {
            "city": "Burgos",
            "city_ascii": "Burgos",
            "lat": 42.3504,
            "lng": -3.68,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Castille-Leon",
            "capital": "minor",
            "population": 170183,
            "id": 1724993285
        },
        {
            "city": "Salamanca",
            "city_ascii": "Salamanca",
            "lat": 40.9704,
            "lng": -5.67,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Castille-Leon",
            "capital": "minor",
            "population": 162353,
            "id": 1724960825
        },
        {
            "city": "Albacete",
            "city_ascii": "Albacete",
            "lat": 39.0003,
            "lng": -1.87,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Castille-La Mancha",
            "capital": "minor",
            "population": 158094,
            "id": 1724000069
        },
        {
            "city": "Huelva",
            "city_ascii": "Huelva",
            "lat": 37.2504,
            "lng": -6.9299,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Andalusia",
            "capital": "minor",
            "population": 144174,
            "id": 1724420824
        },
        {
            "city": "Logro\u00f1o",
            "city_ascii": "Logrono",
            "lat": 42.4704,
            "lng": -2.43,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "La Rioja",
            "capital": "admin",
            "population": 143698,
            "id": 1724721513
        },
        {
            "city": "Ciudad de Melilla",
            "city_ascii": "Ciudad de Melilla",
            "lat": 35.3,
            "lng": -2.95,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Melilla",
            "capital": "",
            "population": 141308,
            "id": 1724144891
        },
        {
            "city": "Badajoz",
            "city_ascii": "Badajoz",
            "lat": 38.8804,
            "lng": -6.97,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Extremadura",
            "capital": "minor",
            "population": 140133,
            "id": 1724759742
        },
        {
            "city": "Le\u00f3n",
            "city_ascii": "Leon",
            "lat": 42.58,
            "lng": -5.57,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Castille-Leon",
            "capital": "minor",
            "population": 136227,
            "id": 1724907542
        },
        {
            "city": "Tarragona",
            "city_ascii": "Tarragona",
            "lat": 41.1204,
            "lng": 1.25,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Catalonia",
            "capital": "minor",
            "population": 126291,
            "id": 1724296961
        },
        {
            "city": "Ourense",
            "city_ascii": "Ourense",
            "lat": 42.33,
            "lng": -7.87,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Galicia",
            "capital": "minor",
            "population": 118107,
            "id": 1724571895
        },
        {
            "city": "Ja\u00e9n",
            "city_ascii": "Jaen",
            "lat": 37.7704,
            "lng": -3.8,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Andalusia",
            "capital": "minor",
            "population": 116400,
            "id": 1724699771
        },
        {
            "city": "Algeciras",
            "city_ascii": "Algeciras",
            "lat": 36.1267,
            "lng": -5.4665,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Andalusia",
            "capital": "",
            "population": 111027,
            "id": 1724355681
        },
        {
            "city": "Santiago de Compostela",
            "city_ascii": "Santiago de Compostela",
            "lat": 42.8829,
            "lng": -8.5411,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Galicia",
            "capital": "admin",
            "population": 92430,
            "id": 1724547778
        },
        {
            "city": "Ciudad de Ceuta",
            "city_ascii": "Ciudad de Ceuta",
            "lat": 35.889,
            "lng": -5.307,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Ceuta",
            "capital": "",
            "population": 78674,
            "id": 1724324416
        },
        {
            "city": "Toledo",
            "city_ascii": "Toledo",
            "lat": 39.867,
            "lng": -4.0167,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Castille-La Mancha",
            "capital": "admin",
            "population": 74632,
            "id": 1724171411
        },
        {
            "city": "M\u00e9rida",
            "city_ascii": "Merida",
            "lat": 38.912,
            "lng": -6.338,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Extremadura",
            "capital": "admin",
            "population": 52423,
            "id": 1724941889
        },
        {
            "city": "Lorca",
            "city_ascii": "Lorca",
            "lat": 37.6886,
            "lng": -1.6985,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Murcia",
            "capital": "",
            "population": 86119,
            "id": 1724565149
        },
        {
            "city": "Guadalajara",
            "city_ascii": "Guadalajara",
            "lat": 40.6337,
            "lng": -3.1666,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Castille-La Mancha",
            "capital": "minor",
            "population": 72850,
            "id": 1724317859
        },
        {
            "city": "Linares",
            "city_ascii": "Linares",
            "lat": 38.0833,
            "lng": -3.6334,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Andalusia",
            "capital": "",
            "population": 59761,
            "id": 1724047784
        }
    ]
}