module.exports = {
    CITIES: [{
            "city": "Geneva",
            "city_ascii": "Geneva",
            "lat": 46.21,
            "lng": 6.14,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Gen\u00e8ve",
            "capital": "admin",
            "population": 1240000,
            "id": 1756810813
        },
        {
            "city": "Z\u00fcrich",
            "city_ascii": "Zurich",
            "lat": 47.38,
            "lng": 8.55,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Z\u00fcrich",
            "capital": "admin",
            "population": 1108000,
            "id": 1756539143
        },
        {
            "city": "Bern",
            "city_ascii": "Bern",
            "lat": 46.9167,
            "lng": 7.467,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Bern",
            "capital": "primary",
            "population": 275329,
            "id": 1756374318
        },
        {
            "city": "Basel",
            "city_ascii": "Basel",
            "lat": 47.5804,
            "lng": 7.59,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Basel-Stadt",
            "capital": "admin",
            "population": 830000,
            "id": 1756731313
        },
        {
            "city": "Lausanne",
            "city_ascii": "Lausanne",
            "lat": 46.5304,
            "lng": 6.65,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Vaud",
            "capital": "admin",
            "population": 265702,
            "id": 1756055099
        },
        {
            "city": "Lucerne",
            "city_ascii": "Lucerne",
            "lat": 47.0504,
            "lng": 8.28,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Luzern",
            "capital": "admin",
            "population": 250000,
            "id": 1756544536
        },
        {
            "city": "Lugano",
            "city_ascii": "Lugano",
            "lat": 46.0004,
            "lng": 8.9667,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Ticino",
            "capital": "",
            "population": 105388,
            "id": 1756503816
        },
        {
            "city": "Biel/Bienne",
            "city_ascii": "Biel/Bienne",
            "lat": 47.1666,
            "lng": 7.25,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Bern",
            "capital": "",
            "population": 78708,
            "id": 1756649723
        },
        {
            "city": "Sankt Gallen",
            "city_ascii": "Sankt Gallen",
            "lat": 47.423,
            "lng": 9.362,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Sankt Gallen",
            "capital": "admin",
            "population": 70572,
            "id": 1756343098
        },
        {
            "city": "Chur",
            "city_ascii": "Chur",
            "lat": 46.85,
            "lng": 9.5,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Graub\u00fcnden",
            "capital": "admin",
            "population": 38293,
            "id": 1756471395
        },
        {
            "city": "Fribourg",
            "city_ascii": "Fribourg",
            "lat": 46.8,
            "lng": 7.15,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Fribourg",
            "capital": "admin",
            "population": 32827,
            "id": 1756145667
        },
        {
            "city": "Neuch\u00e2tel",
            "city_ascii": "Neuchatel",
            "lat": 46.999,
            "lng": 6.923,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Neuch\u00e2tel",
            "capital": "admin",
            "population": 31270,
            "id": 1756726571
        },
        {
            "city": "Zug",
            "city_ascii": "Zug",
            "lat": 47.179,
            "lng": 8.487,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Zug",
            "capital": "admin",
            "population": 23435,
            "id": 1756703208
        },
        {
            "city": "Solothurn",
            "city_ascii": "Solothurn",
            "lat": 47.212,
            "lng": 7.537,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Solothurn",
            "capital": "",
            "population": 14853,
            "id": 1756021237
        },
        {
            "city": "Schwyz",
            "city_ascii": "Schwyz",
            "lat": 47.02,
            "lng": 8.648,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Schwyz",
            "capital": "admin",
            "population": 14177,
            "id": 1756270644
        },
        {
            "city": "Liestal",
            "city_ascii": "Liestal",
            "lat": 47.483,
            "lng": 7.737,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Basel-Landschaft",
            "capital": "admin",
            "population": 12832,
            "id": 1756371637
        },
        {
            "city": "Sarnen",
            "city_ascii": "Sarnen",
            "lat": 46.899,
            "lng": 8.243,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Obwalden",
            "capital": "admin",
            "population": 9410,
            "id": 1756451113
        },
        {
            "city": "Altdorf",
            "city_ascii": "Altdorf",
            "lat": 46.879,
            "lng": 8.638,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Uri",
            "capital": "admin",
            "population": 8678,
            "id": 1756957308
        },
        {
            "city": "Stans",
            "city_ascii": "Stans",
            "lat": 46.95,
            "lng": 8.3833,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Nidwalden",
            "capital": "admin",
            "population": 7475,
            "id": 1756019042
        },
        {
            "city": "Glarus",
            "city_ascii": "Glarus",
            "lat": 47.05,
            "lng": 9.0667,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Glarus",
            "capital": "admin",
            "population": 5681,
            "id": 1756095767
        },
        {
            "city": "Appenzell",
            "city_ascii": "Appenzell",
            "lat": 47.3333,
            "lng": 9.4167,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Appenzell Innerrhoden",
            "capital": "admin",
            "population": 5649,
            "id": 1756770881
        },
        {
            "city": "Solothurn",
            "city_ascii": "Solothurn",
            "lat": 47.2066,
            "lng": 7.5166,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Solothurn",
            "capital": "admin",
            "population": "",
            "id": 1756650126
        },
        {
            "city": "Aarau",
            "city_ascii": "Aarau",
            "lat": 47.3896,
            "lng": 8.0524,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Aargau",
            "capital": "admin",
            "population": "",
            "id": 1756722157
        },
        {
            "city": "Schaffhausen",
            "city_ascii": "Schaffhausen",
            "lat": 47.6973,
            "lng": 8.6349,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Schaffhausen",
            "capital": "admin",
            "population": "",
            "id": 1756849233
        },
        {
            "city": "Del\u00e9mont",
            "city_ascii": "Delemont",
            "lat": 47.3664,
            "lng": 7.329,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Jura",
            "capital": "admin",
            "population": "",
            "id": 1756748908
        },
        {
            "city": "Schaffhausen",
            "city_ascii": "Schaffhausen",
            "lat": 47.706,
            "lng": 8.633,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Schaffhausen",
            "capital": "",
            "population": 33863,
            "id": 1756003651
        },
        {
            "city": "Sion",
            "city_ascii": "Sion",
            "lat": 46.239,
            "lng": 7.354,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Valais",
            "capital": "",
            "population": 28045,
            "id": 1756457392
        },
        {
            "city": "Frauenfeld",
            "city_ascii": "Frauenfeld",
            "lat": 47.568,
            "lng": 9.108,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Thurgau",
            "capital": "",
            "population": 21979,
            "id": 1756399413
        },
        {
            "city": "Bellinzona",
            "city_ascii": "Bellinzona",
            "lat": 46.197,
            "lng": 9.02,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Ticino",
            "capital": "",
            "population": 16572,
            "id": 1756130026
        },
        {
            "city": "Aarau",
            "city_ascii": "Aarau",
            "lat": 47.39,
            "lng": 8.034,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Aargau",
            "capital": "",
            "population": 15501,
            "id": 1756007454
        },
        {
            "city": "Herisau",
            "city_ascii": "Herisau",
            "lat": 47.3833,
            "lng": 9.2833,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Appenzell Ausserrhoden",
            "capital": "",
            "population": 15438,
            "id": 1756581563
        },
        {
            "city": "Del\u00e9mont",
            "city_ascii": "Delemont",
            "lat": 47.37,
            "lng": 7.345,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Jura",
            "capital": "",
            "population": 11315,
            "id": 1756015980
        }
    ]
}