module.exports = {
    CITIES: [{
            "city": "Bangkok",
            "city_ascii": "Bangkok",
            "lat": 13.75,
            "lng": 100.5166,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Krung Thep Maha Nakhon",
            "capital": "primary",
            "population": 6704000,
            "id": 1764068610
        },
        {
            "city": "Chiang Mai",
            "city_ascii": "Chiang Mai",
            "lat": 18.8,
            "lng": 98.98,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Chiang Mai",
            "capital": "admin",
            "population": 397211,
            "id": 1764662886
        },
        {
            "city": "Samut Prakan",
            "city_ascii": "Samut Prakan",
            "lat": 13.6069,
            "lng": 100.6115,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Samut Prakan",
            "capital": "admin",
            "population": 388920,
            "id": 1764159228
        },
        {
            "city": "Nakhon Ratchasima",
            "city_ascii": "Nakhon Ratchasima",
            "lat": 15,
            "lng": 102.1,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Nakhon Ratchasima",
            "capital": "admin",
            "population": 334984,
            "id": 1764752197
        },
        {
            "city": "Hat Yai",
            "city_ascii": "Hat Yai",
            "lat": 6.9964,
            "lng": 100.4714,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Songkhla",
            "capital": "minor",
            "population": 317954,
            "id": 1764161022
        },
        {
            "city": "Ubon Ratchathani",
            "city_ascii": "Ubon Ratchathani",
            "lat": 15.25,
            "lng": 104.83,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Ubon Ratchathani",
            "capital": "admin",
            "population": 273893,
            "id": 1764611048
        },
        {
            "city": "Nonthaburi",
            "city_ascii": "Nonthaburi",
            "lat": 13.8337,
            "lng": 100.4833,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Nonthaburi",
            "capital": "admin",
            "population": 258550,
            "id": 1764667935
        },
        {
            "city": "Khon Kaen",
            "city_ascii": "Khon Kaen",
            "lat": 16.42,
            "lng": 102.83,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Khon Kaen",
            "capital": "admin",
            "population": 251056,
            "id": 1764003406
        },
        {
            "city": "Udon Thani",
            "city_ascii": "Udon Thani",
            "lat": 17.4048,
            "lng": 102.7893,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Udon Thani",
            "capital": "admin",
            "population": 247231,
            "id": 1764676047
        },
        {
            "city": "Nakhon Si Thammarat",
            "city_ascii": "Nakhon Si Thammarat",
            "lat": 8.4,
            "lng": 99.97,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Nakhon Si Thammarat",
            "capital": "admin",
            "population": 232335,
            "id": 1764409111
        },
        {
            "city": "Chon Buri",
            "city_ascii": "Chon Buri",
            "lat": 13.4004,
            "lng": 101,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Chon Buri",
            "capital": "admin",
            "population": 226618,
            "id": 1764202077
        },
        {
            "city": "Lampang",
            "city_ascii": "Lampang",
            "lat": 18.2916,
            "lng": 99.4813,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Lampang",
            "capital": "admin",
            "population": 204081,
            "id": 1764081847
        },
        {
            "city": "Si Racha",
            "city_ascii": "Si Racha",
            "lat": 13.159,
            "lng": 100.9287,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Chon Buri",
            "capital": "minor",
            "population": 178916,
            "id": 1764003327
        },
        {
            "city": "Phitsanulok",
            "city_ascii": "Phitsanulok",
            "lat": 16.8283,
            "lng": 100.2729,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Phitsanulok",
            "capital": "admin",
            "population": 164017,
            "id": 1764140981
        },
        {
            "city": "Surat Thani",
            "city_ascii": "Surat Thani",
            "lat": 9.1501,
            "lng": 99.3401,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Surat Thani",
            "capital": "admin",
            "population": 157627,
            "id": 1764338230
        },
        {
            "city": "Pathum Thani",
            "city_ascii": "Pathum Thani",
            "lat": 14.0171,
            "lng": 100.5333,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Pathum Thani",
            "capital": "admin",
            "population": 154412,
            "id": 1764434288
        },
        {
            "city": "Pattani",
            "city_ascii": "Pattani",
            "lat": 6.864,
            "lng": 101.25,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Pattani",
            "capital": "admin",
            "population": 150000,
            "id": 1764277891
        },
        {
            "city": "Yala",
            "city_ascii": "Yala",
            "lat": 6.5505,
            "lng": 101.2851,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Yala",
            "capital": "admin",
            "population": 148140,
            "id": 1764430323
        },
        {
            "city": "Trang",
            "city_ascii": "Trang",
            "lat": 7.5634,
            "lng": 99.608,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Trang",
            "capital": "admin",
            "population": 147820,
            "id": 1764343817
        },
        {
            "city": "Phra Nakhon Si Ayutthaya",
            "city_ascii": "Phra Nakhon Si Ayutthaya",
            "lat": 14.3588,
            "lng": 100.5684,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Phra Nakhon Si Ayutthaya",
            "capital": "admin",
            "population": 145615,
            "id": 1764002329
        },
        {
            "city": "Phuket",
            "city_ascii": "Phuket",
            "lat": 7.8765,
            "lng": 98.3815,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Phuket",
            "capital": "admin",
            "population": 141618,
            "id": 1764327831
        },
        {
            "city": "Nakhon Pathom",
            "city_ascii": "Nakhon Pathom",
            "lat": 13.818,
            "lng": 100.064,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Nakhon Pathom",
            "capital": "admin",
            "population": 117927,
            "id": 1764251992
        },
        {
            "city": "Chiang Rai",
            "city_ascii": "Chiang Rai",
            "lat": 19.9119,
            "lng": 99.8265,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Chiang Rai",
            "capital": "admin",
            "population": 117127,
            "id": 1764748484
        },
        {
            "city": "Nakhon Sawan",
            "city_ascii": "Nakhon Sawan",
            "lat": 15.7,
            "lng": 100.07,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Nakhon Sawan",
            "capital": "admin",
            "population": 111915,
            "id": 1764821078
        },
        {
            "city": "Ratchaburi",
            "city_ascii": "Ratchaburi",
            "lat": 13.5419,
            "lng": 99.8215,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Ratchaburi",
            "capital": "admin",
            "population": 106996,
            "id": 1764773366
        },
        {
            "city": "Nong Khai",
            "city_ascii": "Nong Khai",
            "lat": 17.8733,
            "lng": 102.7479,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Nong Khai",
            "capital": "admin",
            "population": 104505,
            "id": 1764279113
        },
        {
            "city": "Chanthaburi",
            "city_ascii": "Chanthaburi",
            "lat": 12.6133,
            "lng": 102.0979,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Chanthaburi",
            "capital": "admin",
            "population": 99819,
            "id": 1764151688
        },
        {
            "city": "Phetchaburi",
            "city_ascii": "Phetchaburi",
            "lat": 13.1133,
            "lng": 99.9412,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Phetchaburi",
            "capital": "admin",
            "population": 90497,
            "id": 1764000534
        },
        {
            "city": "Chumphon",
            "city_ascii": "Chumphon",
            "lat": 10.5127,
            "lng": 99.1872,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Chumphon",
            "capital": "admin",
            "population": 85686,
            "id": 1764012939
        },
        {
            "city": "Nan",
            "city_ascii": "Nan",
            "lat": 18.7868,
            "lng": 100.7715,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Nan",
            "capital": "admin",
            "population": 82483,
            "id": 1764061223
        },
        {
            "city": "Prachin Buri",
            "city_ascii": "Prachin Buri",
            "lat": 14.0572,
            "lng": 101.3768,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Prachin Buri",
            "capital": "admin",
            "population": 79757,
            "id": 1764262472
        },
        {
            "city": "Uttaradit",
            "city_ascii": "Uttaradit",
            "lat": 17.6316,
            "lng": 100.0972,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Uttaradit",
            "capital": "admin",
            "population": 76630,
            "id": 1764146253
        },
        {
            "city": "Sakon Nakhon",
            "city_ascii": "Sakon Nakhon",
            "lat": 17.1679,
            "lng": 104.1479,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Sakon Nakhon",
            "capital": "admin",
            "population": 76237,
            "id": 1764476362
        },
        {
            "city": "Saraburi",
            "city_ascii": "Saraburi",
            "lat": 14.5304,
            "lng": 100.88,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Sara Buri",
            "capital": "admin",
            "population": 70769,
            "id": 1764111243
        },
        {
            "city": "Narathiwat",
            "city_ascii": "Narathiwat",
            "lat": 6.4318,
            "lng": 101.8214,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Narathiwat",
            "capital": "admin",
            "population": 68112,
            "id": 1764748532
        },
        {
            "city": "Kanchanaburi",
            "city_ascii": "Kanchanaburi",
            "lat": 14.0174,
            "lng": 99.522,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Kanchanaburi",
            "capital": "admin",
            "population": 63699,
            "id": 1764455558
        },
        {
            "city": "Samut Sakhon",
            "city_ascii": "Samut Sakhon",
            "lat": 13.536,
            "lng": 100.274,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Samut Sakhon",
            "capital": "admin",
            "population": 63498,
            "id": 1764502057
        },
        {
            "city": "Surin",
            "city_ascii": "Surin",
            "lat": 14.8868,
            "lng": 103.4915,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Surin",
            "capital": "admin",
            "population": 62536,
            "id": 1764813179
        },
        {
            "city": "Kamphaeng Phet",
            "city_ascii": "Kamphaeng Phet",
            "lat": 16.473,
            "lng": 99.529,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Kamphaeng Phet",
            "capital": "admin",
            "population": 58787,
            "id": 1764367755
        },
        {
            "city": "Chaiyaphum",
            "city_ascii": "Chaiyaphum",
            "lat": 15.804,
            "lng": 102.0386,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Chaiyaphum",
            "capital": "admin",
            "population": 58350,
            "id": 1764784757
        },
        {
            "city": "Lop Buri",
            "city_ascii": "Lop Buri",
            "lat": 14.804,
            "lng": 100.6186,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Lop Buri",
            "capital": "admin",
            "population": 57761,
            "id": 1764574750
        },
        {
            "city": "Nakhon Phanom",
            "city_ascii": "Nakhon Phanom",
            "lat": 17.3945,
            "lng": 104.7695,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Nakhon Phanom",
            "capital": "admin",
            "population": 55377,
            "id": 1764103547
        },
        {
            "city": "Kalasin",
            "city_ascii": "Kalasin",
            "lat": 16.428,
            "lng": 103.509,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Kalasin",
            "capital": "admin",
            "population": 55102,
            "id": 1764060973
        },
        {
            "city": "Suphan Buri",
            "city_ascii": "Suphan Buri",
            "lat": 14.471,
            "lng": 100.129,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Suphan Buri",
            "capital": "admin",
            "population": 53399,
            "id": 1764759549
        },
        {
            "city": "Maha Sarakham",
            "city_ascii": "Maha Sarakham",
            "lat": 16.184,
            "lng": 103.298,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Maha Sarakham",
            "capital": "admin",
            "population": 51584,
            "id": 1764568961
        },
        {
            "city": "Phetchabun",
            "city_ascii": "Phetchabun",
            "lat": 16.419,
            "lng": 101.159,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Phetchabun",
            "capital": "admin",
            "population": 50656,
            "id": 1764518331
        },
        {
            "city": "Chachoengsao",
            "city_ascii": "Chachoengsao",
            "lat": 13.679,
            "lng": 101.076,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Chachoengsao",
            "capital": "admin",
            "population": 49741,
            "id": 1764632382
        },
        {
            "city": "Songkhla",
            "city_ascii": "Songkhla",
            "lat": 7.21,
            "lng": 100.56,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Songkhla",
            "capital": "admin",
            "population": 48616,
            "id": 1764543650
        },
        {
            "city": "Buri Ram",
            "city_ascii": "Buri Ram",
            "lat": 15.0004,
            "lng": 103.1166,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Buriram",
            "capital": "admin",
            "population": 47292,
            "id": 1764141031
        },
        {
            "city": "Si Sa Ket",
            "city_ascii": "Si Sa Ket",
            "lat": 15.1203,
            "lng": 104.3298,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Sisaket",
            "capital": "admin",
            "population": 44751,
            "id": 1764002764
        },
        {
            "city": "Phatthalung",
            "city_ascii": "Phatthalung",
            "lat": 7.615,
            "lng": 100.081,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Phatthalung",
            "capital": "admin",
            "population": 43522,
            "id": 1764240863
        },
        {
            "city": "Roi Et",
            "city_ascii": "Roi Et",
            "lat": 16.051,
            "lng": 103.655,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Roi Et",
            "capital": "admin",
            "population": 39328,
            "id": 1764216668
        },
        {
            "city": "Phrae",
            "city_ascii": "Phrae",
            "lat": 18.1533,
            "lng": 100.1629,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Phrae",
            "capital": "admin",
            "population": 38538,
            "id": 1764209592
        },
        {
            "city": "Rayong",
            "city_ascii": "Rayong",
            "lat": 12.6718,
            "lng": 101.2815,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Rayong",
            "capital": "admin",
            "population": 37035,
            "id": 1764920057
        },
        {
            "city": "Phichit",
            "city_ascii": "Phichit",
            "lat": 16.439,
            "lng": 100.349,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Phichit",
            "capital": "admin",
            "population": 35760,
            "id": 1764024236
        },
        {
            "city": "Loei",
            "city_ascii": "Loei",
            "lat": 17.4919,
            "lng": 101.7315,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Loei",
            "capital": "admin",
            "population": 35273,
            "id": 1764996883
        },
        {
            "city": "Samut Songkhram",
            "city_ascii": "Samut Songkhram",
            "lat": 13.413,
            "lng": 100.001,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Samut Songkhram",
            "capital": "admin",
            "population": 35065,
            "id": 1764305010
        },
        {
            "city": "Satun",
            "city_ascii": "Satun",
            "lat": 6.6167,
            "lng": 100.0667,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Satun",
            "capital": "admin",
            "population": 34544,
            "id": 1764836023
        },
        {
            "city": "Prachuap Khiri Khan",
            "city_ascii": "Prachuap Khiri Khan",
            "lat": 11.803,
            "lng": 99.8,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Prachuap Khiri Khan",
            "capital": "admin",
            "population": 33521,
            "id": 1764877766
        },
        {
            "city": "Tak",
            "city_ascii": "Tak",
            "lat": 16.8847,
            "lng": 99.1293,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Tak",
            "capital": "admin",
            "population": 33146,
            "id": 1764055292
        },
        {
            "city": "Krabi",
            "city_ascii": "Krabi",
            "lat": 8.052,
            "lng": 98.912,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Krabi",
            "capital": "admin",
            "population": 31219,
            "id": 1764587855
        },
        {
            "city": "Ranong",
            "city_ascii": "Ranong",
            "lat": 9.962,
            "lng": 98.638,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Ranong",
            "capital": "admin",
            "population": 24561,
            "id": 1764623795
        },
        {
            "city": "Uthai Thani",
            "city_ascii": "Uthai Thani",
            "lat": 15.3819,
            "lng": 100.0264,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Uthai Thani",
            "capital": "admin",
            "population": 22219,
            "id": 1764844835
        },
        {
            "city": "Yasothon",
            "city_ascii": "Yasothon",
            "lat": 15.788,
            "lng": 104.151,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Yasothon",
            "capital": "admin",
            "population": 21643,
            "id": 1764520637
        },
        {
            "city": "Trat",
            "city_ascii": "Trat",
            "lat": 12.237,
            "lng": 102.509,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Trat",
            "capital": "admin",
            "population": 21590,
            "id": 1764126822
        },
        {
            "city": "Nakhon Nayok",
            "city_ascii": "Nakhon Nayok",
            "lat": 14.2,
            "lng": 101.216,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Nakhon Nayok",
            "capital": "admin",
            "population": 21309,
            "id": 1764068248
        },
        {
            "city": "Phayao",
            "city_ascii": "Phayao",
            "lat": 19.1707,
            "lng": 99.9083,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Phayao",
            "capital": "admin",
            "population": 21058,
            "id": 1764291128
        },
        {
            "city": "Sing Buri",
            "city_ascii": "Sing Buri",
            "lat": 14.887,
            "lng": 100.401,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Sing Buri",
            "capital": "admin",
            "population": 20046,
            "id": 1764482111
        },
        {
            "city": "Chai Nat",
            "city_ascii": "Chai Nat",
            "lat": 15.179,
            "lng": 100.126,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Chai Nat",
            "capital": "admin",
            "population": 15469,
            "id": 1764848732
        },
        {
            "city": "Lamphun",
            "city_ascii": "Lamphun",
            "lat": 18.503,
            "lng": 99.074,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Lamphun",
            "capital": "admin",
            "population": 14030,
            "id": 1764104264
        },
        {
            "city": "Ang Thong",
            "city_ascii": "Ang Thong",
            "lat": 14.5833,
            "lng": 100.45,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Ang Thong",
            "capital": "admin",
            "population": 13738,
            "id": 1764529940
        },
        {
            "city": "Sukhothai",
            "city_ascii": "Sukhothai",
            "lat": 17.0119,
            "lng": 99.7515,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Sukhothai",
            "capital": "admin",
            "population": 10276,
            "id": 1764175777
        },
        {
            "city": "Phangnga",
            "city_ascii": "Phangnga",
            "lat": 8.451,
            "lng": 98.534,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Phangnga",
            "capital": "admin",
            "population": 9676,
            "id": 1764855952
        },
        {
            "city": "Mae Hong Son",
            "city_ascii": "Mae Hong Son",
            "lat": 19.301,
            "lng": 97.969,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Mae Hong Son",
            "capital": "admin",
            "population": 9109,
            "id": 1764090874
        },
        {
            "city": "Mukdahan",
            "city_ascii": "Mukdahan",
            "lat": 16.5453,
            "lng": 104.7235,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Mukdahan",
            "capital": "admin",
            "population": "",
            "id": 1764994534
        },
        {
            "city": "Nong Bua Lamphu",
            "city_ascii": "Nong Bua Lamphu",
            "lat": 17.2041,
            "lng": 102.4407,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Nong Bua Lamphu",
            "capital": "admin",
            "population": "",
            "id": 1764333285
        },
        {
            "city": "Amnat Charoen",
            "city_ascii": "Amnat Charoen",
            "lat": 15.8585,
            "lng": 104.6288,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Amnat Charoen",
            "capital": "admin",
            "population": "",
            "id": 1764038011
        },
        {
            "city": "Sa Kaeo",
            "city_ascii": "Sa Kaeo",
            "lat": 13.8141,
            "lng": 102.0722,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Sa Kaeo",
            "capital": "admin",
            "population": "",
            "id": 1764207048
        },
        {
            "city": "Bueng Kan",
            "city_ascii": "Bueng Kan",
            "lat": 18.363,
            "lng": 103.6519,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Bueng Kan",
            "capital": "admin",
            "population": "",
            "id": 1764944006
        },
        {
            "city": "Hua Hin",
            "city_ascii": "Hua Hin",
            "lat": 12.5697,
            "lng": 99.9443,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Prachuap Khiri Khan",
            "capital": "minor",
            "population": 50456,
            "id": 1764352388
        },
        {
            "city": "Mae Sot",
            "city_ascii": "Mae Sot",
            "lat": 16.7162,
            "lng": 98.5708,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Tak",
            "capital": "minor",
            "population": 45781,
            "id": 1764198529
        },
        {
            "city": "Thung Song",
            "city_ascii": "Thung Song",
            "lat": 8.154,
            "lng": 99.7286,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Nakhon Si Thammarat",
            "capital": "minor",
            "population": 28223,
            "id": 1764422992
        },
        {
            "city": "Aranyaprathet",
            "city_ascii": "Aranyaprathet",
            "lat": 13.6824,
            "lng": 102.4969,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Sa Kaeo",
            "capital": "minor",
            "population": 22472,
            "id": 1764167237
        },
        {
            "city": "Bua Yai",
            "city_ascii": "Bua Yai",
            "lat": 15.584,
            "lng": 102.4186,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Nakhon Ratchasima",
            "capital": "minor",
            "population": 18269,
            "id": 1764992879
        }
    ]
}