module.exports = {
    CITIES: [
        // 7 Ancient Wonders
        {
            "city": "Great Pyramid of Giza",
            "city_ascii": "",
            "lat": 29.979175,
            "lng": 31.134358,
            "country": "",
            "iso2": "EG",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza"
        },
        {
            "city": "Hanging Gardens of Babylon",
            "city_ascii": "",
            "lat": 32.5355,
            "lng": 44.4275,
            "country": "",
            "population": 0,
            "iso2": "IQ",
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Hanging_Gardens_of_Babylon"
        },
        {
            "city": "Temple of Artemis at Ephesus",
            "city_ascii": "",
            "lat": 37.949722,
            "lng": 27.363889,
            "country": "",
            "iso2": "TR",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Temple_of_Artemis"
        },
        {
            "city": "Statue of Zeus at Olympia",
            "city_ascii": "",
            "lat": 37.637861,
            "lng": 21.63,
            "country": "",
            "iso2": "GR",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Statue_of_Zeus_at_Olympia"
        },
        {
            "city": "Mausoleum at Halicarnassus",
            "city_ascii": "",
            "lat": 37.0379,
            "lng": 27.4241,
            "country": "",
            "iso2": "TR",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Mausoleum_at_Halicarnassus"
        },
        {
            "city": "Colossus of Rhodes",
            "city_ascii": "",
            "lat": 36.451111,
            "lng": 28.227778,
            "country": "",
            "iso2": "GR",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Colossus_of_Rhodes"
        },
        {
            "city": "Lighthouse of Alexandria",
            "city_ascii": "",
            "lat": 31.213889,
            "lng": 29.885556,
            "country": "",
            "iso2": "EG",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Lighthouse_of_Alexandria"
        },
        // 8th wonders
        {
            "city": "Angkor Wat (អង្គរវត្ត)",
            "city_ascii": "",
            "lat": 13.4125,
            "lng": 103.866667,
            "country": "",
            "population": 0,
            "iso2": "KH",
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Angkor_Wat"
        },
        {
            "city": "Citadelle Laferri\u00e8re",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Citadelle_Laferri%C3%A8re.jpg/1280px-Citadelle_Laferri%C3%A8re.jpg",
            "city_ascii": "Citadelle Laferriere",
            "lat": 19.573611,
            "lng": -72.243889,
            "country": "",
            "iso2": "HT",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Citadelle_Laferrier"
        },
        {
            "city": "The Amber Room in the Catherine Palace",
            "city_ascii": "",
            "lat": 59.9375,
            "lng": 30.308611,
            "country": "",
            "iso2": "RU",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Amber_Room"
        },
        {
            "city": "Borobudur Temple",
            "city_ascii": "",
            "lat": -7.608,
            "lng": 110.204,
            "country": "",
            "iso2": "ID",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Borobudur"
        },
        {
            "city": "Monasterio del Escorial",
            "city_ascii": "",
            "lat": 40.588889,
            "lng": -4.147778,
            "country": "",
            "iso2": "ES",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/El_Escorial"
        },
        {
            "city": "Loch Lomond",
            "city_ascii": "",
            "lat": 56.0833333,
            "lng": -4.5666667,
            "country": "",
            "iso2": "GB",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Loch_Lomond"
        },
        {
            "city": "Acadia",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Bass_Harbor_Lighthouse_b.jpg/1920px-Bass_Harbor_Lighthouse_b.jpg",
            "city_ascii": "",
            "lat": 44.338974,
            "lng": -68.27343,
            "country": "United States",
            "iso2": "US",
            "iso3": "",
            "admin_name": "Nat’l Park",
            "capital": "",
            "population": "",
            "id": ""
        },
        {
            "city": "Banff",
            "city_ascii": "",
            "lat": 51.5,
            "lng": -116,
            "country": "Canada",
            "iso2": "CA",
            "admin_name": "Nat’l Park",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Banff_National_Park"
        },
        {
            "city": "Gatineau Park",
            "city_ascii": "",
            "lat": 45.583333,
            "lng": -76,
            "country": "Canada",
            "iso2": "CA",
            "admin_name": "",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Gatineau_Park"
        },
        {
            "city": "Centers for Disease Control and Prevention (CDC)",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/CDC_HDR_I.jpg/1280px-CDC_HDR_I.jpg",
            "city_ascii": "",
            "lat": 33.799444,
            "lng": -84.328333,
            "country": "",
            "population": 0,
            "iso2": "US",
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Centers_for_Disease_Control_and_Prevention"
        },
        {
            "city": "de facto Capital of the European Union",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Quartier_europ%C3%A9en_Bruxelles_2011-06_CROP.jpg/1024px-Quartier_europ%C3%A9en_Bruxelles_2011-06_CROP.jpg",
            "city_ascii": "",
            "lat": 50.84,
            "lng": 4.38,
            "iso2": "EU",
            "country": "",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Brussels_and_the_European_Union"
        },
        {
            "city": "Heliopolis",
            "city_ascii": "",
            "lat": 30.129333,
            "lng": 31.307528,
            "country": "Ancient Egypt",
            "iso2": "EG",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Heliopolis_(ancient_Egypt)"
        },
        {
            "city": "Butrint",
            "city_ascii": "",
            "lat": 39.745556,
            "lng": 20.020556,
            "country": "Ancient Greece / Rome",
            "population": 0,
            "iso2": "AL",
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Butrint"
        },
        {
            "city": "Hadrian's Wall",
            "city_ascii": "",
            "lat": 55.024167,
            "lng": -2.2925,
            "iso2": "GB",
            "country": "",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Hadrian%27s_Wall"
        },
        {
            "city": "Antonine Wall",
            "city_ascii": "",
            "lat": 55.967,
            "lng": -4.067,
            "iso2": "GB",
            "country": "",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Antonine_Wall"
        },
        {
            "city": "Trajan's Column",
            "city_ascii": "",
            "lat": 41.895833,
            "lng": 12.484167,
            "country": "",
            "population": 0,
            "iso2": "IT",
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Trajan%27s_Column"
        },
        {
            "city": "Devil's Island (penal colony of Cayenne)",
            "city_ascii": "",
            "lat": 5.293611,
            "lng": -52.583056,
            "country": "",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Devil%27s_Island"
        },
        {
            "city": "Death place of Ferdinand Magellan",
            "city_ascii": "",
            "lat": 10.3,
            "lng": 123.966667,
            "iso2": "PH",
            "country": "",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Ferdinand_Magellan#Death"
        },
        {
            "city": "Elba (Napoleon Bonaparte's Island of Exile)",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/3/35/Portoferraio_aerea.jpg",
            "city_ascii": "",
            "lat": 42.782711,
            "lng": 10.286335,
            "country": "",
            "iso2": "IT",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Napoleon#Exile_to_Elba"
        },
        {
            "city": "Large Underground Xenon Experiment (LUX)",
            "city_ascii": "",
            "lat": 44.352,
            "lng": -103.751,
            "iso2": "US",
            "country": "",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Large_Underground_Xenon_experiment"
        },
        {
            "city": "Boll Weevil Monument",
            "city_ascii": "",
            "lat": 31.314444,
            "lng": -85.854028,
            "iso2": "US",
            "country": "",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Boll_Weevil_Monument"
        },
        {
            "city": "Annual Nobel Prize Ceremony (excluding Peace Prize)",
            "city_ascii": "",
            "lat": 59.329444,
            "lng": 18.068611,
            "country": "",
            "population": 0,
            "iso2": "SE",
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Nobel_Prize"
        },
        {
            "city": "Annual Nobel Peace Prize Ceremony",
            "city_ascii": "",
            "lat": 59.916667,
            "lng": 10.733333,
            "country": "",
            "population": 0,
            "capital": "",
            "iso2": "NO",
            "wiki": "https://en.wikipedia.org/wiki/Nobel_Prize"
        },
        {
            "city": "Kindlifresserbrunnen (The Child Eater Statue)",
            "city_ascii": "",
            "lat": 46.948519,
            "lng": 7.447447,
            "iso2": "CH",
            "country": "",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Kindlifresserbrunnen"
        },
        {
            "city": "Blue Mustang Statue (Blucifer)",
            "img_link": "https://upload.wikimedia.org/wikipedia/en/9/90/Blucifer_Sculpture.png",
            "city_ascii": "",
            "lat": 39.83414,
            "lng": -104.67638,
            "country": "",
            "population": 0,
            "iso2": "US",
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Blue_Mustang"
        },
        {
            "city": "Smithsonian Institution",
            "city_ascii": "",
            "lat": 38.889,
            "lng": -77.026,
            "country": "",
            "population": 0,
            "iso2": "US",
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Smithsonian_Institution"
        },
        {
            "city": "Gereja Ayam ('Chicken Church')",
            "city_ascii": "",
            "iso2": "ID",
            "lat": -7.605694,
            "lng": 110.1805,
            "country": "",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Gereja_Ayam"
        },
        {
            "city": "Manneken Pis ('Little Pissing Man')",
            "city_ascii": "",
            "lat": 50.84499,
            "lng": 4.34998,
            "iso2": "BE",
            "country": "",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Manneken_Pis"
        },
        {
            "city": "Birth/Death Place of Johannes Gutenberg",
            "city_ascii": "",
            "lat": 50,
            "lng": 8.266667,
            "country": "",
            "iso2": "DE",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Johannes_Gutenberg"
        },
        {
            "city": "Ivan Pavlov's Dog Study",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/a/aa/Ivan_Pavlov_research_on_dog%27s_reflex_setup.jpg",
            "city_ascii": "",
            "lat": 59.942,
            "lng": 30.299,
            "country": "",
            "iso2": "RU",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Classical_conditioning#Pavlov's_research"
        },
        {
            "city": "Eratosthenes Measures Earth's Circumference",
            "city_ascii": "",
            "lat": 31.2,
            "lng": 29.916667,
            "country": "",
            "iso2": "EG",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Eratosthenes#Measurement_of_the_Earth's_circumference"
        },
        {
            "city": "Michelson-Morley Experiment disproves luminiferous aether theory",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/f/f4/Michelson_morley_experiment_1887.jpg",
            "city_ascii": "",
            "lat": 41.504,
            "lng": -81.608,
            "country": "",
            "iso2": "US",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Michelson–Morley_experiment"
        },
        {
            "city": "Marie Curie Discovers Polonium and Radium",
            "city_ascii": "",
            "lat": 48.856613,
            "lng": 2.352222,
            "iso2": "FR",
            "country": "",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Marie_Curie#New_elements"
        },
        {
            "city": "Robert Millikan Oil Drop Experiment",
            "city_ascii": "",
            "lat": 41.789722,
            "lng": -87.599722,
            "country": "",
            "iso2": "US",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Oil_drop_experiment"
        },
        {
            "city": "Florence Nightingale Pioneers Modern Nursing",
            "city_ascii": "",
            "lat": 41.008056,
            "lng": 29.015833,
            "country": "",
            "iso2": "TR",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Florence_Nightingale#Statistics_and_sanitary_reform"
        },
        {
            "city": "Hell",
            "city_ascii": "",
            "lat": 63.4444,
            "lng": 10.9227,
            "country": "Norway",
            "iso2": "NO",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Hell,_Norway"
        },
        {
            "city": "Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/5/5b/New_Zealand_0577.jpg",
            "city_ascii": "",
            "lat": -40.346,
            "lng": 176.5402,
            "iso2": "NZ",
            "country": "New Zealand",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu"
        },
        {
            "city": "Boring",
            "city_ascii": "",
            "lat": 45.43,
            "lng": -122.373611,
            "country": "United States",
            "population": 0,
            "capital": "",
            "iso2": "US",
            "admin_name": "Oregon",
            "wiki": "https://en.wikipedia.org/wiki/Boring,_Oregon"
        },
        {
            "city": "No Name",
            "city_ascii": "",
            "lat": 39.560278,
            "lng": -107.293333,
            "country": "United States",
            "population": 0,
            "admin_name": "Colorado",
            "iso2": "US",
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/No_Name,_Colorado"
        },
        {
            "city": "Poo",
            "city_ascii": "",
            "lat": 43.30791,
            "lng": -4.83514,
            "country": "Spain",
            "iso2": "ES",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Poo_(Cabrales)"
        },
        {
            "city": "Middelfart",
            "city_ascii": "",
            "lat": 55.498611,
            "lng": 9.744444,
            "iso2": "DK",
            "country": "Denmark",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Middelfart"
        },
        {
            "city": "Batman",
            "city_ascii": "",
            "lat": 37.880556,
            "lng": 41.1275,
            "country": "Turkey",
            "iso2": "TR",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Batman,_Turkey"
        },
        {
            "city": "The Biggest Ball of Twine Built by a Single Person",
            "city_ascii": "",
            "lat": 45.096389,
            "lng": -94.410833,
            "iso2": "US",
            "admin_name": "Minnesota",
            "country": "United States",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Biggest_ball_of_twine#Largest_ball_of_sisal_twine_built_by_a_single_person"
        },
        {
            "city": "Hetch Hetchy Valley",
            "city_ascii": "",
            "lat": 37.9475,
            "lng": -119.7869,
            "iso2": "US",
            "country": "",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Hetch_Hetchy"
        },
        {
            "city": "Everglades",
            "city_ascii": "",
            "lat": 25.3125,
            "lng": -80.6875,
            "iso2": "US",
            "country": "United States",
            "admin_name": "Nat’l Park",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Everglades_National_Park"
        },
        {
            "city": "Gros Morne",
            "city_ascii": "",
            "lat": 49.689444,
            "lng": -57.738056,
            "country": "Canada",
            "iso2": "CA",
            "admin_name": "Nat’l Park",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Gros_Morne_National_Park"
        },
        {
            "city": "Jasper",
            "city_ascii": "",
            "lat": 52.8,
            "lng": -117.9,
            "country": "Canada",
            "iso2": "CA",
            "admin_name": "Nat’l Park",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Jasper_National_Park"
        },
        {
            "city": "Kluane",
            "city_ascii": "",
            "lat": 60.61943,
            "lng": -138.331,
            "country": "Canada",
            "iso2": "CA",
            "admin_name": "Nat’l Park",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Kluane_National_Park_and_Reserve"
        },
        {
            "city": "Pacific Rim",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/West_coast_trail_tsusiat_falls1.jpg/1920px-West_coast_trail_tsusiat_falls1.jpg",
            "city_ascii": "",
            "lat": 48.636111,
            "lng": -124.769167,
            "country": "Canada",
            "iso2": "CA",
            "admin_name": "Nat’l Park",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Pacific_Rim_National_Park_Reserve"
        },
        {
            "city": "Yoho",
            "city_ascii": "",
            "lat": 51.395278,
            "lng": -116.486667,
            "country": "Canada",
            "iso2": "CA",
            "admin_name": "Nat’l Park",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Yoho_National_Park"
        },
        {
            "city": "Code of Hammurabi Discovery Site",
            "city_ascii": "",
            "lat": 32.190556,
            "lng": 48.257778,
            "country": "",
            "iso2": "IR",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Code_of_Hammurabi"
        },
        {
            "city": "Susa",
            "city_ascii": "",
            "lat": 32.190556,
            "lng": 48.257778,
            "country": "Parthian / Sasanian Empire",
            "iso2": "IR",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Susa"
        },
        {
            "city": "Istakhr",
            "city_ascii": "",
            "lat": 29.980833,
            "lng": 52.909444,
            "country": "Sasanian Empire",
            "iso2": "IR",
            "population": 0,
            "capital": "primary",
            "wiki": "https://en.wikipedia.org/wiki/Istakhr"
        },
        {
            "city": "Karakorum",
            "city_ascii": "",
            "lat": 47.210278,
            "lng": 102.847778,
            "country": "Mongol Empire",
            "iso2": "MN",
            "population": 0,
            "capital": "primary",
            "wiki": "https://en.wikipedia.org/wiki/Karakorum"
        },
        {
            "city": "Cirta",
            "city_ascii": "",
            "lat": 36.3675,
            "lng": 6.611944,
            "country": "Berber Kingdom of Numidia",
            "population": 0,
            "iso2": "DZ",
            "capital": "primary",
            "wiki": "https://en.wikipedia.org/wiki/Cirta"
        },
        {
            "city": "Kerma",
            "city_ascii": "",
            "lat": 19.600803,
            "lng": 30.409731,
            "country": "Kerma Kingdom of Nubia",
            "iso2": "SD",
            "population": 0,
            "capital": "primary",
            "wiki": "https://en.wikipedia.org/wiki/Kerma"
        },
        {
            "city": "Harappa",
            "city_ascii": "",
            "lat": 30.628889,
            "lng": 72.863889,
            "country": "Indus Valley Civilization",
            "iso2": "PK",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Harappa"
        },
        {
            "city": "Yangcheng (陽城)",
            "city_ascii": "",
            "img_link": "https://www.ancient.eu/img/r/p/500x600/4375.jpg.webp?v=1600805702",
            "lat": 34.455278,
            "lng": 113.025278,
            "country": "Xia Dynasty, China",
            "iso2": "CN",
            "population": 0,
            "capital": "primary",
            "wiki": "https://en.wikipedia.org/wiki/Yangcheng_(historical_city)"
        },
        {
            "city": "Chang'an (长安)",
            "city_ascii": "",
            "lat": 34.266667,
            "lng": 108.9,
            "iso2": "CN",
            "country": "Han Dynasty, China",
            "population": 0,
            "capital": "primary",
            "wiki": "https://en.wikipedia.org/wiki/Chang%27an"
        },
        {
            "city": "New Echota",
            "city_ascii": "",
            "lat": 34.539444,
            "lng": -84.908611,
            "country": "Cherokee Nation (pre-1830)",
            "population": 0,
            "iso2": "CE",
            "capital": "primary",
            "wiki": "https://en.wikipedia.org/wiki/New_Echota"
        },
        {
            "city": "Rössing Uranium Mine",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/5/51/Arandis_Mine_quer.jpg",
            "city_ascii": "",
            "lat": -22.484167,
            "lng": 15.048889,
            "iso2": "NA",
            "country": "Namibia",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Rössing_uranium_mine"
        },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "",
        //   "country": "",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "",
        //   "country": "",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "",
        //   "country": "",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "",
        //   "country": "",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },

    ]
};