module.exports = {
    CITIES: [{
            "city": "Istanbul",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/b/ba/Istanbul_collage_5j.jpg",
            "city_ascii": "Istanbul",
            "lat": 41.105,
            "lng": 29.01,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "\u0130stanbul",
            "capital": "admin",
            "population": 10061000,
            "id": 1792756324
        },
        {
            "city": "Ankara",
            "city_ascii": "Ankara",
            "lat": 39.9272,
            "lng": 32.8644,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Ankara",
            "capital": "primary",
            "population": 3716000,
            "id": 1792572891
        },
        {
            "city": "\u0130zmir",
            "city_ascii": "Izmir",
            "lat": 38.4361,
            "lng": 27.1518,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "\u0130zmir",
            "capital": "admin",
            "population": 2587000,
            "id": 1792725579
        },
        {
            "city": "Bursa",
            "city_ascii": "Bursa",
            "lat": 40.2,
            "lng": 29.07,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Bursa",
            "capital": "admin",
            "population": 1492000,
            "id": 1792903330
        },
        {
            "city": "Adana",
            "city_ascii": "Adana",
            "lat": 36.995,
            "lng": 35.32,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Adana",
            "capital": "admin",
            "population": 1293000,
            "id": 1792783772
        },
        {
            "city": "Gaziantep",
            "city_ascii": "Gaziantep",
            "lat": 37.075,
            "lng": 37.385,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Gaziantep",
            "capital": "admin",
            "population": 1044000,
            "id": 1792911843
        },
        {
            "city": "Konya",
            "city_ascii": "Konya",
            "lat": 37.875,
            "lng": 32.475,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Konya",
            "capital": "admin",
            "population": 919000,
            "id": 1792014004
        },
        {
            "city": "Tarsus",
            "city_ascii": "Tarsus",
            "lat": 36.9204,
            "lng": 34.88,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Mersin",
            "capital": "minor",
            "population": 894318,
            "id": 1792003860
        },
        {
            "city": "Antalya",
            "city_ascii": "Antalya",
            "lat": 36.89,
            "lng": 30.7,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Antalya",
            "capital": "admin",
            "population": 783000,
            "id": 1792988434
        },
        {
            "city": "Trabzon",
            "city_ascii": "Trabzon",
            "lat": 40.98,
            "lng": 39.72,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Trabzon",
            "capital": "admin",
            "population": 764714,
            "id": 1792019202
        },
        {
            "city": "Diyarbak\u0131r",
            "city_ascii": "Diyarbakir",
            "lat": 37.9204,
            "lng": 40.23,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Diyarbak\u0131r",
            "capital": "admin",
            "population": 644763,
            "id": 1792536241
        },
        {
            "city": "Samsun",
            "city_ascii": "Samsun",
            "lat": 41.28,
            "lng": 36.3437,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Samsun",
            "capital": "admin",
            "population": 609339,
            "id": 1792169057
        },
        {
            "city": "Kayseri",
            "city_ascii": "Kayseri",
            "lat": 38.735,
            "lng": 35.49,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Kayseri",
            "capital": "admin",
            "population": 592840,
            "id": 1792945815
        },
        {
            "city": "Eski\u015fehir",
            "city_ascii": "Eskisehir",
            "lat": 39.795,
            "lng": 30.53,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Eski\u015fehir",
            "capital": "admin",
            "population": 514869,
            "id": 1792933981
        },
        {
            "city": "Kocaeli",
            "city_ascii": "Kocaeli",
            "lat": 40.776,
            "lng": 29.9306,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Kocaeli",
            "capital": "admin",
            "population": 466504,
            "id": 1792965114
        },
        {
            "city": "Malatya",
            "city_ascii": "Malatya",
            "lat": 38.3704,
            "lng": 38.3,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Malatya",
            "capital": "admin",
            "population": 461574,
            "id": 1792485155
        },
        {
            "city": "\u015eanl\u0131urfa",
            "city_ascii": "Sanliurfa",
            "lat": 37.17,
            "lng": 38.795,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "\u015eanl\u0131urfa",
            "capital": "admin",
            "population": 449549,
            "id": 1792937570
        },
        {
            "city": "Erzurum",
            "city_ascii": "Erzurum",
            "lat": 39.9204,
            "lng": 41.29,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Erzurum",
            "capital": "admin",
            "population": 420691,
            "id": 1792511957
        },
        {
            "city": "Kahramanmara\u015f",
            "city_ascii": "Kahramanmaras",
            "lat": 37.61,
            "lng": 36.945,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Kahramanmara\u015f",
            "capital": "admin",
            "population": 376045,
            "id": 1792726797
        },
        {
            "city": "Denizli",
            "city_ascii": "Denizli",
            "lat": 37.7704,
            "lng": 29.08,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Denizli",
            "capital": "admin",
            "population": 372344,
            "id": 1792161179
        },
        {
            "city": "Van",
            "city_ascii": "Van",
            "lat": 38.4954,
            "lng": 43.4,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Van",
            "capital": "admin",
            "population": 371713,
            "id": 1792940471
        },
        {
            "city": "Hatay",
            "city_ascii": "Hatay",
            "lat": 36.2304,
            "lng": 36.12,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Hatay",
            "capital": "admin",
            "population": 305564,
            "id": 1792115763
        },
        {
            "city": "Batman",
            "city_ascii": "Batman",
            "lat": 37.8904,
            "lng": 41.14,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Batman",
            "capital": "admin",
            "population": 302074,
            "id": 1792630786
        },
        {
            "city": "\u0130skenderun",
            "city_ascii": "Iskenderun",
            "lat": 36.5804,
            "lng": 36.17,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Hatay",
            "capital": "minor",
            "population": 297943,
            "id": 1792962911
        },
        {
            "city": "Rize",
            "city_ascii": "Rize",
            "lat": 41.0208,
            "lng": 40.5219,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Rize",
            "capital": "admin",
            "population": 279450,
            "id": 1792024731
        },
        {
            "city": "Elaz\u0131\u011f",
            "city_ascii": "Elazig",
            "lat": 38.68,
            "lng": 39.23,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Elaz\u0131\u011f",
            "capital": "admin",
            "population": 271492,
            "id": 1792156766
        },
        {
            "city": "Sivas",
            "city_ascii": "Sivas",
            "lat": 39.7454,
            "lng": 37.035,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Sivas",
            "capital": "admin",
            "population": 264022,
            "id": 1792938326
        },
        {
            "city": "Bal\u0131kesir",
            "city_ascii": "Balikesir",
            "lat": 39.6504,
            "lng": 27.89,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Bal\u0131kesir",
            "capital": "admin",
            "population": 261516,
            "id": 1792020804
        },
        {
            "city": "Sakarya",
            "city_ascii": "Sakarya",
            "lat": 40.8,
            "lng": 30.415,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Sakarya",
            "capital": "admin",
            "population": 260109,
            "id": 1792191587
        },
        {
            "city": "Manisa",
            "city_ascii": "Manisa",
            "lat": 38.6304,
            "lng": 27.44,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Manisa",
            "capital": "admin",
            "population": 243971,
            "id": 1792804328
        },
        {
            "city": "Ad\u0131yaman",
            "city_ascii": "Adiyaman",
            "lat": 37.7704,
            "lng": 38.2799,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Ad\u0131yaman",
            "capital": "admin",
            "population": 223744,
            "id": 1792686663
        },
        {
            "city": "K\u0131r\u0131kkale",
            "city_ascii": "Kirikkale",
            "lat": 39.8504,
            "lng": 33.53,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "K\u0131r\u0131kkale",
            "capital": "admin",
            "population": 211138,
            "id": 1792859558
        },
        {
            "city": "Ayd\u0131n",
            "city_ascii": "Aydin",
            "lat": 37.85,
            "lng": 27.85,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Ayd\u0131n",
            "capital": "admin",
            "population": 198857,
            "id": 1792696058
        },
        {
            "city": "K\u00fctahya",
            "city_ascii": "Kutahya",
            "lat": 39.42,
            "lng": 29.93,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "K\u00fctahya",
            "capital": "admin",
            "population": 185008,
            "id": 1792671735
        },
        {
            "city": "\u00c7orum",
            "city_ascii": "Corum",
            "lat": 40.52,
            "lng": 34.95,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "\u00c7orum",
            "capital": "admin",
            "population": 183418,
            "id": 1792065200
        },
        {
            "city": "Isparta",
            "city_ascii": "Isparta",
            "lat": 37.77,
            "lng": 30.53,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Isparta",
            "capital": "admin",
            "population": 172334,
            "id": 1792105249
        },
        {
            "city": "Afyonkarahisar",
            "city_ascii": "Afyonkarahisar",
            "lat": 38.7504,
            "lng": 30.55,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Afyonkarahisar",
            "capital": "admin",
            "population": 156992,
            "id": 1792855788
        },
        {
            "city": "Zonguldak",
            "city_ascii": "Zonguldak",
            "lat": 41.4304,
            "lng": 31.78,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Zonguldak",
            "capital": "admin",
            "population": 156918,
            "id": 1792410633
        },
        {
            "city": "Ordu",
            "city_ascii": "Ordu",
            "lat": 41.0004,
            "lng": 37.8699,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Ordu",
            "capital": "admin",
            "population": 155117,
            "id": 1792540951
        },
        {
            "city": "U\u015fak",
            "city_ascii": "Usak",
            "lat": 38.6804,
            "lng": 29.42,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "U\u015fak",
            "capital": "admin",
            "population": 152862,
            "id": 1792360822
        },
        {
            "city": "Nusaybin",
            "city_ascii": "Nusaybin",
            "lat": 37.075,
            "lng": 41.2184,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Mardin",
            "capital": "minor",
            "population": 152668,
            "id": 1792327949
        },
        {
            "city": "Tokat",
            "city_ascii": "Tokat",
            "lat": 40.306,
            "lng": 36.563,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Tokat",
            "capital": "admin",
            "population": 129702,
            "id": 1792534905
        },
        {
            "city": "Erzincan",
            "city_ascii": "Erzincan",
            "lat": 39.7526,
            "lng": 39.4928,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Erzincan",
            "capital": "admin",
            "population": 129407,
            "id": 1792742754
        },
        {
            "city": "Karab\u00fck",
            "city_ascii": "Karabuk",
            "lat": 41.2,
            "lng": 32.6,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Karab\u00fck",
            "capital": "admin",
            "population": 128564,
            "id": 1792834766
        },
        {
            "city": "Edirne",
            "city_ascii": "Edirne",
            "lat": 41.6704,
            "lng": 26.57,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Edirne",
            "capital": "admin",
            "population": 126470,
            "id": 1792102607
        },
        {
            "city": "Tekirda\u011f",
            "city_ascii": "Tekirdag",
            "lat": 40.9909,
            "lng": 27.51,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Tekirda\u011f",
            "capital": "admin",
            "population": 122287,
            "id": 1792519395
        },
        {
            "city": "Karaman",
            "city_ascii": "Karaman",
            "lat": 37.1815,
            "lng": 33.215,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Karaman",
            "capital": "admin",
            "population": 120399,
            "id": 1792285496
        },
        {
            "city": "Siirt",
            "city_ascii": "Siirt",
            "lat": 37.944,
            "lng": 41.933,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Siirt",
            "capital": "admin",
            "population": 114034,
            "id": 1792190820
        },
        {
            "city": "Giresun",
            "city_ascii": "Giresun",
            "lat": 40.913,
            "lng": 38.39,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Giresun",
            "capital": "admin",
            "population": 98864,
            "id": 1792486859
        },
        {
            "city": "Bolu",
            "city_ascii": "Bolu",
            "lat": 40.7363,
            "lng": 31.6061,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Bolu",
            "capital": "admin",
            "population": 96629,
            "id": 1792807068
        },
        {
            "city": "K\u0131r\u015fehir",
            "city_ascii": "Kirsehir",
            "lat": 39.142,
            "lng": 34.171,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "K\u0131r\u015fehir",
            "capital": "admin",
            "population": 94336,
            "id": 1792825471
        },
        {
            "city": "Ni\u011fde",
            "city_ascii": "Nigde",
            "lat": 37.976,
            "lng": 34.694,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Ni\u011fde",
            "capital": "admin",
            "population": 91039,
            "id": 1792867993
        },
        {
            "city": "Yozgat",
            "city_ascii": "Yozgat",
            "lat": 39.818,
            "lng": 34.815,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Yozgat",
            "capital": "admin",
            "population": 87881,
            "id": 1792862455
        },
        {
            "city": "A\u011fr\u0131",
            "city_ascii": "Agri",
            "lat": 39.7198,
            "lng": 43.0513,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "A\u011fr\u0131",
            "capital": "admin",
            "population": 87854,
            "id": 1792385654
        },
        {
            "city": "\u00c7anakkale",
            "city_ascii": "Canakkale",
            "lat": 40.1459,
            "lng": 26.4064,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "\u00c7anakkale",
            "capital": "admin",
            "population": 87791,
            "id": 1792403093
        },
        {
            "city": "Amasya",
            "city_ascii": "Amasya",
            "lat": 40.6537,
            "lng": 35.833,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Amasya",
            "capital": "admin",
            "population": 82896,
            "id": 1792344167
        },
        {
            "city": "Mu\u015f",
            "city_ascii": "Mus",
            "lat": 38.749,
            "lng": 41.4969,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Mu\u015f",
            "capital": "admin",
            "population": 82536,
            "id": 1792530937
        },
        {
            "city": "Kilis",
            "city_ascii": "Kilis",
            "lat": 36.7204,
            "lng": 37.12,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Kilis",
            "capital": "admin",
            "population": 82301,
            "id": 1792866362
        },
        {
            "city": "Bing\u00f6l",
            "city_ascii": "Bingol",
            "lat": 38.885,
            "lng": 40.498,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Bing\u00f6l",
            "capital": "admin",
            "population": 80568,
            "id": 1792920183
        },
        {
            "city": "Hakkari",
            "city_ascii": "Hakkari",
            "lat": 37.5744,
            "lng": 43.7408,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Hakk\u00e2ri",
            "capital": "admin",
            "population": 77699,
            "id": 1792629133
        },
        {
            "city": "Kars",
            "city_ascii": "Kars",
            "lat": 40.6085,
            "lng": 43.0975,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Kars",
            "capital": "admin",
            "population": 77486,
            "id": 1792000464
        },
        {
            "city": "Nev\u015fehir",
            "city_ascii": "Nevsehir",
            "lat": 38.624,
            "lng": 34.724,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Nev\u015fehir",
            "capital": "admin",
            "population": 75527,
            "id": 1792583760
        },
        {
            "city": "\u00c7ank\u0131r\u0131",
            "city_ascii": "Cankiri",
            "lat": 40.607,
            "lng": 33.621,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "\u00c7ank\u0131r\u0131",
            "capital": "admin",
            "population": 71379,
            "id": 1792584248
        },
        {
            "city": "Mardin",
            "city_ascii": "Mardin",
            "lat": 37.3115,
            "lng": 40.7427,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Mardin",
            "capital": "admin",
            "population": 71373,
            "id": 1792546179
        },
        {
            "city": "Kastamonu",
            "city_ascii": "Kastamonu",
            "lat": 41.389,
            "lng": 33.783,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Kastamonu",
            "capital": "admin",
            "population": 70402,
            "id": 1792386602
        },
        {
            "city": "Burdur",
            "city_ascii": "Burdur",
            "lat": 37.7167,
            "lng": 30.2833,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Burdur",
            "capital": "admin",
            "population": 66158,
            "id": 1792413556
        },
        {
            "city": "Bitlis",
            "city_ascii": "Bitlis",
            "lat": 38.394,
            "lng": 42.123,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Bitlis",
            "capital": "admin",
            "population": 62811,
            "id": 1792490436
        },
        {
            "city": "K\u0131rklareli",
            "city_ascii": "Kirklareli",
            "lat": 41.743,
            "lng": 27.226,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "K\u0131rklareli",
            "capital": "admin",
            "population": 58223,
            "id": 1792182918
        },
        {
            "city": "Mu\u011fla",
            "city_ascii": "Mugla",
            "lat": 37.2164,
            "lng": 28.3639,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Mu\u011fla",
            "capital": "admin",
            "population": 48183,
            "id": 1792992104
        },
        {
            "city": "Bilecik",
            "city_ascii": "Bilecik",
            "lat": 40.15,
            "lng": 29.983,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Bilecik",
            "capital": "admin",
            "population": 40285,
            "id": 1792408667
        },
        {
            "city": "Sinop",
            "city_ascii": "Sinop",
            "lat": 42.023,
            "lng": 35.153,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Sinop",
            "capital": "admin",
            "population": 34834,
            "id": 1792497865
        },
        {
            "city": "Artvin",
            "city_ascii": "Artvin",
            "lat": 41.183,
            "lng": 41.818,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Artvin",
            "capital": "admin",
            "population": 32272,
            "id": 1792320984
        },
        {
            "city": "G\u00fcm\u00fc\u015fhane",
            "city_ascii": "Gumushane",
            "lat": 40.464,
            "lng": 39.484,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "G\u00fcm\u00fc\u015fhane",
            "capital": "admin",
            "population": 32250,
            "id": 1792559945
        },
        {
            "city": "Tunceli",
            "city_ascii": "Tunceli",
            "lat": 39.1167,
            "lng": 39.5333,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Tunceli",
            "capital": "admin",
            "population": 29062,
            "id": 1792507574
        },
        {
            "city": "Mersin",
            "city_ascii": "Mersin",
            "lat": 36.8004,
            "lng": 34.6128,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Mersin",
            "capital": "admin",
            "population": "",
            "id": 1792520282
        },
        {
            "city": "Yalova",
            "city_ascii": "Yalova",
            "lat": 40.655,
            "lng": 29.2769,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Yalova",
            "capital": "admin",
            "population": "",
            "id": 1792838138
        },
        {
            "city": "Osmaniye",
            "city_ascii": "Osmaniye",
            "lat": 37.0742,
            "lng": 36.2478,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Osmaniye",
            "capital": "admin",
            "population": "",
            "id": 1792340207
        },
        {
            "city": "D\u00fczce",
            "city_ascii": "Duzce",
            "lat": 40.8389,
            "lng": 31.1639,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "D\u00fczce",
            "capital": "admin",
            "population": "",
            "id": 1792999306
        },
        {
            "city": "Bart\u0131n",
            "city_ascii": "Bartin",
            "lat": 41.6358,
            "lng": 32.3375,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Bart\u0131n",
            "capital": "admin",
            "population": "",
            "id": 1792863603
        },
        {
            "city": "I\u011fd\u0131r",
            "city_ascii": "Igdir",
            "lat": 39.9237,
            "lng": 44.045,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "I\u011fd\u0131r",
            "capital": "admin",
            "population": "",
            "id": 1792813007
        },
        {
            "city": "Aksaray",
            "city_ascii": "Aksaray",
            "lat": 38.3725,
            "lng": 34.0254,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Aksaray",
            "capital": "admin",
            "population": "",
            "id": 1792650390
        },
        {
            "city": "Ardahan",
            "city_ascii": "Ardahan",
            "lat": 41.1087,
            "lng": 42.7022,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Ardahan",
            "capital": "admin",
            "population": "",
            "id": 1792379425
        },
        {
            "city": "\u015e\u0131rnak",
            "city_ascii": "Sirnak",
            "lat": 37.5139,
            "lng": 42.4543,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "\u015e\u0131rnak",
            "capital": "admin",
            "population": "",
            "id": 1792867633
        },
        {
            "city": "Bayburt",
            "city_ascii": "Bayburt",
            "lat": 40.2563,
            "lng": 40.2229,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Bayburt",
            "capital": "admin",
            "population": "",
            "id": 1792400872
        },
        {
            "city": "Bafra",
            "city_ascii": "Bafra",
            "lat": 41.5682,
            "lng": 35.9069,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Samsun",
            "capital": "minor",
            "population": 97452,
            "id": 1792560571
        },
        {
            "city": "Samanda\u011f",
            "city_ascii": "Samandag",
            "lat": 36.1171,
            "lng": 35.9333,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Hatay",
            "capital": "minor",
            "population": 93638,
            "id": 1792813864
        },
        {
            "city": "Polatl\u0131",
            "city_ascii": "Polatli",
            "lat": 39.5842,
            "lng": 32.1472,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Ankara",
            "capital": "minor",
            "population": 93262,
            "id": 1792124981
        },
        {
            "city": "Ere\u011fli",
            "city_ascii": "Eregli",
            "lat": 37.5063,
            "lng": 34.0517,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Konya",
            "capital": "minor",
            "population": 92117,
            "id": 1792110470
        },
        {
            "city": "L\u00fcleburgaz",
            "city_ascii": "Luleburgaz",
            "lat": 41.4067,
            "lng": 27.3552,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "K\u0131rklareli",
            "capital": "minor",
            "population": 90899,
            "id": 1792000752
        },
        {
            "city": "S\u00f6ke",
            "city_ascii": "Soke",
            "lat": 37.7512,
            "lng": 27.4103,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Ayd\u0131n",
            "capital": "minor",
            "population": 77341,
            "id": 1792512916
        },
        {
            "city": "Tatvan",
            "city_ascii": "Tatvan",
            "lat": 38.5066,
            "lng": 42.2816,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Bitlis",
            "capital": "minor",
            "population": 73222,
            "id": 1792530559
        }
    ]
}