module.exports = {
    CITIES: [{
            "city": "Ashgabat",
            "city_ascii": "Ashgabat",
            "lat": 37.95,
            "lng": 58.3833,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "",
            "capital": "primary",
            "population": 727700,
            "id": 1795049992
        },
        {
            "city": "T\u00fcrkmenabat",
            "city_ascii": "Turkmenabat",
            "lat": 39.11,
            "lng": 63.58,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "Lebap",
            "capital": "admin",
            "population": 234817,
            "id": 1795079064
        },
        {
            "city": "Da\u015foguz",
            "city_ascii": "Dasoguz",
            "lat": 41.84,
            "lng": 59.965,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "Da\u015foguz",
            "capital": "admin",
            "population": 201424,
            "id": 1795167397
        },
        {
            "city": "Mary",
            "city_ascii": "Mary",
            "lat": 37.6,
            "lng": 61.8333,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "Mary",
            "capital": "admin",
            "population": 178708,
            "id": 1795413265
        },
        {
            "city": "Balkanabat",
            "city_ascii": "Balkanabat",
            "lat": 39.5124,
            "lng": 54.3649,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "Balkan",
            "capital": "admin",
            "population": 110827,
            "id": 1795885709
        },
        {
            "city": "\u00c4new",
            "city_ascii": "Anew",
            "lat": 37.8875,
            "lng": 58.516,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "Ahal",
            "capital": "admin",
            "population": "",
            "id": 1795817680
        },
        {
            "city": "T\u00fcrkmenba\u015fy",
            "city_ascii": "Turkmenbasy",
            "lat": 40.023,
            "lng": 52.9697,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "Balkan",
            "capital": "",
            "population": 68292,
            "id": 1795987646
        },
        {
            "city": "Tejen",
            "city_ascii": "Tejen",
            "lat": 37.3786,
            "lng": 60.496,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "Ahal",
            "capital": "",
            "population": 67294,
            "id": 1795500486
        },
        {
            "city": "Serdar",
            "city_ascii": "Serdar",
            "lat": 38.9755,
            "lng": 56.2778,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "Balkan",
            "capital": "",
            "population": 48458,
            "id": 1795429041
        },
        {
            "city": "Abadan",
            "city_ascii": "Abadan",
            "lat": 38.0517,
            "lng": 58.21,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "Ahal",
            "capital": "",
            "population": 40813,
            "id": 1795394170
        },
        {
            "city": "Kaka",
            "city_ascii": "Kaka",
            "lat": 37.3503,
            "lng": 59.6,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "Ahal",
            "capital": "",
            "population": 38381,
            "id": 1795223342
        },
        {
            "city": "Atamyrat",
            "city_ascii": "Atamyrat",
            "lat": 37.8248,
            "lng": 65.1997,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "Lebap",
            "capital": "",
            "population": 33242,
            "id": 1795595010
        },
        {
            "city": "K\u00f6ne\u00fcrgench",
            "city_ascii": "Koneurgench",
            "lat": 42.3167,
            "lng": 59.1667,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "",
            "capital": "",
            "population": 31400,
            "id": 1795588005
        },
        {
            "city": "\u00c7eleken",
            "city_ascii": "Celeken",
            "lat": 39.4362,
            "lng": 53.1226,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "Balkan",
            "capital": "",
            "population": 1206,
            "id": 1795554809
        }
    ]
}