module.exports = {
    CITIES: [{
            "city": "Kampala",
            "city_ascii": "Kampala",
            "lat": 0.3167,
            "lng": 32.5833,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kampala",
            "capital": "primary",
            "population": 1420000,
            "id": 1800406299
        },
        {
            "city": "Mbale",
            "city_ascii": "Mbale",
            "lat": 1.0904,
            "lng": 34.17,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Mbale",
            "capital": "admin",
            "population": 402368,
            "id": 1800265900
        },
        {
            "city": "Jinja",
            "city_ascii": "Jinja",
            "lat": 0.4404,
            "lng": 33.1999,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Jinja",
            "capital": "admin",
            "population": 301619,
            "id": 1800632405
        },
        {
            "city": "Arua",
            "city_ascii": "Arua",
            "lat": 3.0204,
            "lng": 30.9,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Arua",
            "capital": "admin",
            "population": 250000,
            "id": 1800812511
        },
        {
            "city": "Entebbe",
            "city_ascii": "Entebbe",
            "lat": 0.0604,
            "lng": 32.46,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Wakiso",
            "capital": "",
            "population": 175128,
            "id": 1800535915
        },
        {
            "city": "Tororo",
            "city_ascii": "Tororo",
            "lat": 0.7104,
            "lng": 34.17,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Tororo",
            "capital": "admin",
            "population": 150000,
            "id": 1800214991
        },
        {
            "city": "Gulu",
            "city_ascii": "Gulu",
            "lat": 2.78,
            "lng": 32.28,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Gulu",
            "capital": "admin",
            "population": 146858,
            "id": 1800406007
        },
        {
            "city": "Lira",
            "city_ascii": "Lira",
            "lat": 2.2604,
            "lng": 32.89,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Lira",
            "capital": "admin",
            "population": 135445,
            "id": 1800877735
        },
        {
            "city": "Mbarara",
            "city_ascii": "Mbarara",
            "lat": -0.5996,
            "lng": 30.65,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Mbarara",
            "capital": "admin",
            "population": 83700,
            "id": 1800554483
        },
        {
            "city": "Kasese",
            "city_ascii": "Kasese",
            "lat": 0.2325,
            "lng": 29.9883,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kasese",
            "capital": "admin",
            "population": 67269,
            "id": 1800924936
        },
        {
            "city": "Masaka",
            "city_ascii": "Masaka",
            "lat": -0.3296,
            "lng": 31.73,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Masaka",
            "capital": "admin",
            "population": 65373,
            "id": 1800731885
        },
        {
            "city": "Kitgum",
            "city_ascii": "Kitgum",
            "lat": 3.3004,
            "lng": 32.87,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kitgum",
            "capital": "admin",
            "population": 56891,
            "id": 1800380883
        },
        {
            "city": "Busia",
            "city_ascii": "Busia",
            "lat": 0.4544,
            "lng": 34.0758,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Busia",
            "capital": "admin",
            "population": 47100,
            "id": 1800460306
        },
        {
            "city": "Iganga",
            "city_ascii": "Iganga",
            "lat": 0.6092,
            "lng": 33.4686,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Iganga",
            "capital": "admin",
            "population": 45024,
            "id": 1800987671
        },
        {
            "city": "Kabale",
            "city_ascii": "Kabale",
            "lat": -1.2496,
            "lng": 29.98,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kabale",
            "capital": "admin",
            "population": 44600,
            "id": 1800408751
        },
        {
            "city": "Fort Portal",
            "city_ascii": "Fort Portal",
            "lat": 0.671,
            "lng": 30.275,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kabarole",
            "capital": "admin",
            "population": 42670,
            "id": 1800139086
        },
        {
            "city": "Mityana",
            "city_ascii": "Mityana",
            "lat": 0.4004,
            "lng": 32.05,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Mityana",
            "capital": "admin",
            "population": 41131,
            "id": 1800284151
        },
        {
            "city": "Adjumani",
            "city_ascii": "Adjumani",
            "lat": 3.3614,
            "lng": 31.8097,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Adjumani",
            "capital": "admin",
            "population": 34700,
            "id": 1800855823
        },
        {
            "city": "Masindi",
            "city_ascii": "Masindi",
            "lat": 1.6744,
            "lng": 31.715,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Masindi",
            "capital": "admin",
            "population": 31486,
            "id": 1800409287
        },
        {
            "city": "Pallisa",
            "city_ascii": "Pallisa",
            "lat": 1.145,
            "lng": 33.7094,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Pallisa",
            "capital": "admin",
            "population": 30745,
            "id": 1800214906
        },
        {
            "city": "Nebbi",
            "city_ascii": "Nebbi",
            "lat": 2.4758,
            "lng": 31.1025,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Nebbi",
            "capital": "admin",
            "population": 30354,
            "id": 1800598019
        },
        {
            "city": "Moyo",
            "city_ascii": "Moyo",
            "lat": 3.6504,
            "lng": 31.72,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Moyo",
            "capital": "admin",
            "population": 22434,
            "id": 1800294178
        },
        {
            "city": "Kayunga",
            "city_ascii": "Kayunga",
            "lat": 0.7025,
            "lng": 32.8886,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kayunga",
            "capital": "admin",
            "population": 21704,
            "id": 1800678001
        },
        {
            "city": "Mubende",
            "city_ascii": "Mubende",
            "lat": 0.5904,
            "lng": 31.37,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Mubende",
            "capital": "admin",
            "population": 18936,
            "id": 1800105368
        },
        {
            "city": "Pakwach",
            "city_ascii": "Pakwach",
            "lat": 2.4704,
            "lng": 31.48,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "",
            "capital": "admin",
            "population": 17541,
            "id": 1800204374
        },
        {
            "city": "Ntungamo",
            "city_ascii": "Ntungamo",
            "lat": -0.8794,
            "lng": 30.2642,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Ntungamo",
            "capital": "admin",
            "population": 16400,
            "id": 1800042819
        },
        {
            "city": "Kiboga",
            "city_ascii": "Kiboga",
            "lat": 0.9161,
            "lng": 31.7742,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kiboga",
            "capital": "admin",
            "population": 14512,
            "id": 1800749650
        },
        {
            "city": "Sironko",
            "city_ascii": "Sironko",
            "lat": 1.25,
            "lng": 34.3,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Sironko",
            "capital": "admin",
            "population": 14100,
            "id": 1800419144
        },
        {
            "city": "Kumi",
            "city_ascii": "Kumi",
            "lat": 1.4608,
            "lng": 33.9361,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kumi",
            "capital": "admin",
            "population": 13000,
            "id": 1800429770
        },
        {
            "city": "Kisoro",
            "city_ascii": "Kisoro",
            "lat": -1.3539,
            "lng": 29.6983,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kisoro",
            "capital": "admin",
            "population": 12900,
            "id": 1800685460
        },
        {
            "city": "Kamuli",
            "city_ascii": "Kamuli",
            "lat": 0.9472,
            "lng": 33.1197,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kamuli",
            "capital": "admin",
            "population": 12764,
            "id": 1800849421
        },
        {
            "city": "Mpigi",
            "city_ascii": "Mpigi",
            "lat": 0.225,
            "lng": 32.3136,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Mpigi",
            "capital": "admin",
            "population": 11082,
            "id": 1800370948
        },
        {
            "city": "Katakwi",
            "city_ascii": "Katakwi",
            "lat": 1.8911,
            "lng": 33.9661,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Katakwi",
            "capital": "admin",
            "population": 8400,
            "id": 1800303827
        },
        {
            "city": "Nakasongola",
            "city_ascii": "Nakasongola",
            "lat": 1.3089,
            "lng": 32.4564,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Nakasongola",
            "capital": "admin",
            "population": 6921,
            "id": 1800270160
        },
        {
            "city": "Kibale",
            "city_ascii": "Kibale",
            "lat": 0.8,
            "lng": 31.0667,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kibaale",
            "capital": "admin",
            "population": 5200,
            "id": 1800784000
        },
        {
            "city": "Kalangala",
            "city_ascii": "Kalangala",
            "lat": -0.3089,
            "lng": 32.225,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kalangala",
            "capital": "admin",
            "population": 5200,
            "id": 1800446257
        },
        {
            "city": "Kaberamaido",
            "city_ascii": "Kaberamaido",
            "lat": 1.7389,
            "lng": 33.1594,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kaberamaido",
            "capital": "admin",
            "population": 3400,
            "id": 1800845749
        },
        {
            "city": "Kaabong",
            "city_ascii": "Kaabong",
            "lat": 3.5204,
            "lng": 34.12,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kaabong",
            "capital": "admin",
            "population": 1137,
            "id": 1800299361
        },
        {
            "city": "Soroti",
            "city_ascii": "Soroti",
            "lat": 1.7104,
            "lng": 33.6,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Soroti",
            "capital": "admin",
            "population": 1038,
            "id": 1800434608
        },
        {
            "city": "Moroto",
            "city_ascii": "Moroto",
            "lat": 2.5403,
            "lng": 34.64,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Moroto",
            "capital": "admin",
            "population": 371,
            "id": 1800980026
        },
        {
            "city": "Koboko",
            "city_ascii": "Koboko",
            "lat": 3.4136,
            "lng": 30.9599,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Koboko",
            "capital": "admin",
            "population": "",
            "id": 1800307801
        },
        {
            "city": "Bugiri",
            "city_ascii": "Bugiri",
            "lat": 0.5714,
            "lng": 33.7417,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Bugiri",
            "capital": "admin",
            "population": "",
            "id": 1800917331
        },
        {
            "city": "Kapchorwa",
            "city_ascii": "Kapchorwa",
            "lat": 1.3965,
            "lng": 34.4509,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kapchorwa",
            "capital": "admin",
            "population": "",
            "id": 1800170407
        },
        {
            "city": "Bundibugyo",
            "city_ascii": "Bundibugyo",
            "lat": 0.7085,
            "lng": 30.0634,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Bundibugyo",
            "capital": "admin",
            "population": "",
            "id": 1800500326
        },
        {
            "city": "Hoima",
            "city_ascii": "Hoima",
            "lat": 1.4356,
            "lng": 31.3436,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Hoima",
            "capital": "admin",
            "population": "",
            "id": 1800806239
        },
        {
            "city": "Mukono",
            "city_ascii": "Mukono",
            "lat": 0.3533,
            "lng": 32.7553,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Mukono",
            "capital": "admin",
            "population": "",
            "id": 1800864322
        },
        {
            "city": "Yumbe",
            "city_ascii": "Yumbe",
            "lat": 3.4651,
            "lng": 31.2469,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Yumbe",
            "capital": "admin",
            "population": "",
            "id": 1800297508
        },
        {
            "city": "Bududa",
            "city_ascii": "Bududa",
            "lat": 1.0112,
            "lng": 34.3311,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Bududa",
            "capital": "admin",
            "population": "",
            "id": 1800970850
        },
        {
            "city": "Wakiso",
            "city_ascii": "Wakiso",
            "lat": 0.4044,
            "lng": 32.4594,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Wakiso",
            "capital": "admin",
            "population": "",
            "id": 1800102352
        },
        {
            "city": "Lyantonde",
            "city_ascii": "Lyantonde",
            "lat": -0.4031,
            "lng": 31.1572,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Lyantonde",
            "capital": "admin",
            "population": "",
            "id": 1800896564
        },
        {
            "city": "Mayuge",
            "city_ascii": "Mayuge",
            "lat": 0.4578,
            "lng": 33.4806,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Mayuge",
            "capital": "admin",
            "population": "",
            "id": 1800300606
        },
        {
            "city": "Bulambuli",
            "city_ascii": "Bulambuli",
            "lat": 1.1667,
            "lng": 34.3833,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Bulambuli",
            "capital": "admin",
            "population": "",
            "id": 1800071156
        },
        {
            "city": "Maracha",
            "city_ascii": "Maracha",
            "lat": 3.2704,
            "lng": 30.9553,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Maracha",
            "capital": "admin",
            "population": "",
            "id": 1800799569
        },
        {
            "city": "Luwero",
            "city_ascii": "Luwero",
            "lat": 0.8492,
            "lng": 32.4731,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Luwero",
            "capital": "admin",
            "population": "",
            "id": 1800067821
        },
        {
            "city": "Namayingo",
            "city_ascii": "Namayingo",
            "lat": 0.2398,
            "lng": 33.8849,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Namayingo",
            "capital": "admin",
            "population": "",
            "id": 1800633600
        },
        {
            "city": "Luuka Town",
            "city_ascii": "Luuka Town",
            "lat": 0.7008,
            "lng": 33.3002,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Luuka",
            "capital": "admin",
            "population": "",
            "id": 1800000051
        },
        {
            "city": "Kibuku",
            "city_ascii": "Kibuku",
            "lat": 1.0433,
            "lng": 33.7975,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kibuku",
            "capital": "admin",
            "population": "",
            "id": 1800098358
        },
        {
            "city": "Bupoto",
            "city_ascii": "Bupoto",
            "lat": 0.9061,
            "lng": 34.3578,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "",
            "capital": "admin",
            "population": "",
            "id": 1800358976
        },
        {
            "city": "Apac",
            "city_ascii": "Apac",
            "lat": 1.9845,
            "lng": 32.534,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Apac",
            "capital": "admin",
            "population": "",
            "id": 1800174030
        },
        {
            "city": "Rubirizi",
            "city_ascii": "Rubirizi",
            "lat": -0.2989,
            "lng": 30.1336,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Rubirizi",
            "capital": "admin",
            "population": "",
            "id": 1800947890
        },
        {
            "city": "Buikwe",
            "city_ascii": "Buikwe",
            "lat": 0.3375,
            "lng": 33.0106,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Buikwe",
            "capital": "admin",
            "population": "",
            "id": 1800745891
        },
        {
            "city": "Kagadi",
            "city_ascii": "Kagadi",
            "lat": 0.9378,
            "lng": 30.8089,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "",
            "capital": "admin",
            "population": "",
            "id": 1800935733
        },
        {
            "city": "Bushenyi",
            "city_ascii": "Bushenyi",
            "lat": -0.5853,
            "lng": 30.2114,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Bushenyi",
            "capital": "admin",
            "population": "",
            "id": 1800740334
        },
        {
            "city": "Kaliro",
            "city_ascii": "Kaliro",
            "lat": 0.8949,
            "lng": 33.5048,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kaliro",
            "capital": "admin",
            "population": "",
            "id": 1800764757
        },
        {
            "city": "Butebo",
            "city_ascii": "Butebo",
            "lat": 1.1942,
            "lng": 33.9222,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "",
            "capital": "admin",
            "population": "",
            "id": 1800710436
        },
        {
            "city": "Namutumba",
            "city_ascii": "Namutumba",
            "lat": 0.8363,
            "lng": 33.6858,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Namutumba",
            "capital": "admin",
            "population": "",
            "id": 1800673440
        },
        {
            "city": "Manafwa",
            "city_ascii": "Manafwa",
            "lat": 0.9784,
            "lng": 34.3743,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Manafwa",
            "capital": "admin",
            "population": "",
            "id": 1800257696
        },
        {
            "city": "Ibanda",
            "city_ascii": "Ibanda",
            "lat": -0.1539,
            "lng": 30.5319,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Ibanda",
            "capital": "admin",
            "population": "",
            "id": 1800636734
        },
        {
            "city": "Rukungiri",
            "city_ascii": "Rukungiri",
            "lat": -0.8411,
            "lng": 29.9419,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Rukungiri",
            "capital": "admin",
            "population": "",
            "id": 1800982268
        },
        {
            "city": "Gombe",
            "city_ascii": "Gombe",
            "lat": 0.1818,
            "lng": 32.1158,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Butambala",
            "capital": "admin",
            "population": "",
            "id": 1800068643
        },
        {
            "city": "Kyenjojo",
            "city_ascii": "Kyenjojo",
            "lat": 0.6328,
            "lng": 30.6214,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kyenjojo",
            "capital": "admin",
            "population": "",
            "id": 1800420914
        },
        {
            "city": "Mitoma",
            "city_ascii": "Mitoma",
            "lat": -0.6842,
            "lng": 30.07,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Mitooma",
            "capital": "admin",
            "population": "",
            "id": 1800173507
        },
        {
            "city": "Kalungu",
            "city_ascii": "Kalungu",
            "lat": -0.1667,
            "lng": 31.7569,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kalungu",
            "capital": "admin",
            "population": "",
            "id": 1800770335
        },
        {
            "city": "Bukomansimbi",
            "city_ascii": "Bukomansimbi",
            "lat": -0.1578,
            "lng": 31.6042,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Bukomansimbi",
            "capital": "admin",
            "population": "",
            "id": 1800146127
        },
        {
            "city": "Rubanda",
            "city_ascii": "Rubanda",
            "lat": -1.1883,
            "lng": 29.8461,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "",
            "capital": "admin",
            "population": "",
            "id": 1800066560
        },
        {
            "city": "Kasaali",
            "city_ascii": "Kasaali",
            "lat": -0.6167,
            "lng": 31.55,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "",
            "capital": "admin",
            "population": "",
            "id": 1800217765
        },
        {
            "city": "Butaleja",
            "city_ascii": "Butaleja",
            "lat": 0.9166,
            "lng": 33.9563,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Butaleja",
            "capital": "admin",
            "population": "",
            "id": 1800859767
        },
        {
            "city": "Serere",
            "city_ascii": "Serere",
            "lat": 1.518,
            "lng": 33.4589,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Serere",
            "capital": "admin",
            "population": "",
            "id": 1800171092
        },
        {
            "city": "Amuria",
            "city_ascii": "Amuria",
            "lat": 2.0036,
            "lng": 33.6511,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Amuria",
            "capital": "admin",
            "population": "",
            "id": 1800838006
        },
        {
            "city": "Kibiito",
            "city_ascii": "Kibiito",
            "lat": 0.4772,
            "lng": 30.1925,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "",
            "capital": "admin",
            "population": "",
            "id": 1800035606
        },
        {
            "city": "Kibingo",
            "city_ascii": "Kibingo",
            "lat": -0.626,
            "lng": 30.4359,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Sheema",
            "capital": "admin",
            "population": "",
            "id": 1800484853
        },
        {
            "city": "Bukedea",
            "city_ascii": "Bukedea",
            "lat": 1.3169,
            "lng": 34.0506,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Bukedea",
            "capital": "admin",
            "population": "",
            "id": 1800687979
        },
        {
            "city": "Nakaseke",
            "city_ascii": "Nakaseke",
            "lat": 0.7517,
            "lng": 32.385,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Nakaseke",
            "capital": "admin",
            "population": "",
            "id": 1800304390
        },
        {
            "city": "Binyin",
            "city_ascii": "Binyin",
            "lat": 1.4167,
            "lng": 34.5333,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kween",
            "capital": "admin",
            "population": "",
            "id": 1800440664
        },
        {
            "city": "Mparo",
            "city_ascii": "Mparo",
            "lat": -1.1647,
            "lng": 30.0378,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "",
            "capital": "admin",
            "population": "",
            "id": 1800207938
        },
        {
            "city": "Kole",
            "city_ascii": "Kole",
            "lat": 2.4002,
            "lng": 32.8003,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kole",
            "capital": "admin",
            "population": "",
            "id": 1800826218
        },
        {
            "city": "Zombo",
            "city_ascii": "Zombo",
            "lat": 2.5135,
            "lng": 30.9091,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Zombo",
            "capital": "admin",
            "population": "",
            "id": 1800293674
        },
        {
            "city": "Rakai",
            "city_ascii": "Rakai",
            "lat": -0.72,
            "lng": 31.4839,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Rakai",
            "capital": "admin",
            "population": "",
            "id": 1800039440
        },
        {
            "city": "Lwengo",
            "city_ascii": "Lwengo",
            "lat": -0.4161,
            "lng": 31.4081,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Lwengo",
            "capital": "admin",
            "population": "",
            "id": 1800583650
        },
        {
            "city": "Bukwa",
            "city_ascii": "Bukwa",
            "lat": 1.2592,
            "lng": 34.7539,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Bukwa",
            "capital": "admin",
            "population": "",
            "id": 1800276050
        },
        {
            "city": "Dokolo",
            "city_ascii": "Dokolo",
            "lat": 1.9167,
            "lng": 33.172,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Dokolo",
            "capital": "admin",
            "population": "",
            "id": 1800478941
        },
        {
            "city": "Kamwenge",
            "city_ascii": "Kamwenge",
            "lat": 0.2111,
            "lng": 30.4208,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kamwenge",
            "capital": "admin",
            "population": "",
            "id": 1800010095
        },
        {
            "city": "Ngora",
            "city_ascii": "Ngora",
            "lat": 1.4314,
            "lng": 33.7772,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Ngora",
            "capital": "admin",
            "population": "",
            "id": 1800020551
        },
        {
            "city": "Alebtong",
            "city_ascii": "Alebtong",
            "lat": 2.2447,
            "lng": 33.2547,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Alebtong",
            "capital": "admin",
            "population": "",
            "id": 1800244501
        },
        {
            "city": "Kanungu",
            "city_ascii": "Kanungu",
            "lat": -0.9575,
            "lng": 29.7897,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kanungu",
            "capital": "admin",
            "population": "",
            "id": 1800715667
        },
        {
            "city": "Kanoni",
            "city_ascii": "Kanoni",
            "lat": 0.1772,
            "lng": 31.8811,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Gomba",
            "capital": "admin",
            "population": "",
            "id": 1800973979
        },
        {
            "city": "Oyam",
            "city_ascii": "Oyam",
            "lat": 2.235,
            "lng": 32.385,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Oyam",
            "capital": "admin",
            "population": "",
            "id": 1800867016
        },
        {
            "city": "Sembabule",
            "city_ascii": "Sembabule",
            "lat": -0.0772,
            "lng": 31.4567,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Sembabule",
            "capital": "admin",
            "population": "",
            "id": 1800497536
        },
        {
            "city": "Kakumiro",
            "city_ascii": "Kakumiro",
            "lat": 0.7806,
            "lng": 31.3236,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "",
            "capital": "admin",
            "population": "",
            "id": 1800894285
        },
        {
            "city": "Buyende",
            "city_ascii": "Buyende",
            "lat": 1.1517,
            "lng": 33.155,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Buyende",
            "capital": "admin",
            "population": "",
            "id": 1800567800
        },
        {
            "city": "Isingiro",
            "city_ascii": "Isingiro",
            "lat": -0.8686,
            "lng": 30.8302,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Isingiro",
            "capital": "admin",
            "population": "",
            "id": 1800843586
        },
        {
            "city": "Kyegegwa",
            "city_ascii": "Kyegegwa",
            "lat": 0.5022,
            "lng": 31.0414,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kyegegwa",
            "capital": "admin",
            "population": "",
            "id": 1800719333
        },
        {
            "city": "Buhweju",
            "city_ascii": "Buhweju",
            "lat": -0.3503,
            "lng": 30.3003,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Buhweju",
            "capital": "admin",
            "population": "",
            "id": 1800414512
        },
        {
            "city": "Amolatar",
            "city_ascii": "Amolatar",
            "lat": 1.6378,
            "lng": 32.8448,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Amolatar",
            "capital": "admin",
            "population": "",
            "id": 1800458737
        },
        {
            "city": "Lamwo",
            "city_ascii": "Lamwo",
            "lat": 3.5297,
            "lng": 32.8016,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Lamwo",
            "capital": "admin",
            "population": "",
            "id": 1800495740
        },
        {
            "city": "Palenga",
            "city_ascii": "Palenga",
            "lat": 2.6131,
            "lng": 32.3369,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "",
            "capital": "admin",
            "population": "",
            "id": 1800679810
        },
        {
            "city": "Kotido",
            "city_ascii": "Kotido",
            "lat": 2.9806,
            "lng": 34.1331,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kotido",
            "capital": "admin",
            "population": "",
            "id": 1800371285
        },
        {
            "city": "Pader",
            "city_ascii": "Pader",
            "lat": 3.05,
            "lng": 33.2167,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Pader",
            "capital": "admin",
            "population": "",
            "id": 1800105199
        },
        {
            "city": "Agago",
            "city_ascii": "Agago",
            "lat": 2.8338,
            "lng": 33.3336,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Agago",
            "capital": "admin",
            "population": "",
            "id": 1800321499
        },
        {
            "city": "Bulisa",
            "city_ascii": "Bulisa",
            "lat": 2.1178,
            "lng": 31.4116,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Buliisa",
            "capital": "admin",
            "population": "",
            "id": 1800842426
        },
        {
            "city": "Amudat",
            "city_ascii": "Amudat",
            "lat": 1.95,
            "lng": 34.95,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Amudat",
            "capital": "admin",
            "population": "",
            "id": 1800886754
        },
        {
            "city": "Napak",
            "city_ascii": "Napak",
            "lat": 2.2514,
            "lng": 34.2501,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Napak",
            "capital": "admin",
            "population": "",
            "id": 1800784014
        },
        {
            "city": "Kiryandongo",
            "city_ascii": "Kiryandongo",
            "lat": 1.8763,
            "lng": 32.0622,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kiryandongo",
            "capital": "admin",
            "population": "",
            "id": 1800154303
        },
        {
            "city": "Kiruhura",
            "city_ascii": "Kiruhura",
            "lat": -0.2356,
            "lng": 30.8725,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kiruhura",
            "capital": "admin",
            "population": "",
            "id": 1800198933
        },
        {
            "city": "Abim",
            "city_ascii": "Abim",
            "lat": 2.7017,
            "lng": 33.6761,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Abim",
            "capital": "admin",
            "population": "",
            "id": 1800199589
        },
        {
            "city": "Ntoroko",
            "city_ascii": "Ntoroko",
            "lat": 1.0411,
            "lng": 30.4811,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Ntoroko",
            "capital": "admin",
            "population": "",
            "id": 1800207074
        },
        {
            "city": "Otuke",
            "city_ascii": "Otuke",
            "lat": 2.5004,
            "lng": 33.5007,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Otuke",
            "capital": "admin",
            "population": "",
            "id": 1800657796
        },
        {
            "city": "Amuru",
            "city_ascii": "Amuru",
            "lat": 2.8139,
            "lng": 31.9387,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Amuru",
            "capital": "admin",
            "population": "",
            "id": 1800642608
        },
        {
            "city": "Nakapiripirit",
            "city_ascii": "Nakapiripirit",
            "lat": 1.9167,
            "lng": 34.7833,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Nakapiripirit",
            "capital": "admin",
            "population": "",
            "id": 1800663685
        },
        {
            "city": "Kyankwanzi",
            "city_ascii": "Kyankwanzi",
            "lat": 1.1987,
            "lng": 31.8062,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kyankwanzi",
            "capital": "admin",
            "population": "",
            "id": 1800427588
        },
        {
            "city": "Nwoya",
            "city_ascii": "Nwoya",
            "lat": 2.6342,
            "lng": 32.0011,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Nwoya",
            "capital": "admin",
            "population": "",
            "id": 1800205431
        },
        {
            "city": "Kitamilo",
            "city_ascii": "Kitamilo",
            "lat": 0.2222,
            "lng": 33.2061,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Buvuma",
            "capital": "admin",
            "population": "",
            "id": 1800610172
        },
        {
            "city": "Bombo",
            "city_ascii": "Bombo",
            "lat": 0.5833,
            "lng": 32.5333,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Luwero",
            "capital": "",
            "population": 75000,
            "id": 1800926068
        },
        {
            "city": "Katwe",
            "city_ascii": "Katwe",
            "lat": -0.1296,
            "lng": 29.92,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kasese",
            "capital": "",
            "population": 1957,
            "id": 1800329579
        },
        {
            "city": "Masindi Port",
            "city_ascii": "Masindi Port",
            "lat": 1.7004,
            "lng": 32.0699,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kiryandongo",
            "capital": "",
            "population": 8319,
            "id": 1800188907
        }
    ]
}