module.exports = {
    CITIES: [{
            "city": "London",
            "city_ascii": "London",
            "lat": 51.5,
            "lng": -0.1167,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "London, City of",
            "capital": "primary",
            "population": 8567000,
            "id": 1826645935
        },
        {
            "city": "Birmingham",
            "city_ascii": "Birmingham",
            "lat": 52.475,
            "lng": -1.92,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Birmingham",
            "capital": "admin",
            "population": 2285000,
            "id": 1826423213
        },
        {
            "city": "Manchester",
            "city_ascii": "Manchester",
            "lat": 53.5004,
            "lng": -2.248,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Manchester",
            "capital": "admin",
            "population": 2230000,
            "id": 1826246335
        },
        {
            "city": "Leeds",
            "city_ascii": "Leeds",
            "lat": 53.83,
            "lng": -1.58,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Leeds",
            "capital": "admin",
            "population": 1529000,
            "id": 1826343963
        },
        {
            "city": "Sheffield",
            "city_ascii": "Sheffield",
            "lat": 53.3667,
            "lng": -1.5,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Sheffield",
            "capital": "admin",
            "population": 1292900,
            "id": 1826289852
        },
        {
            "city": "Glasgow",
            "city_ascii": "Glasgow",
            "lat": 55.8744,
            "lng": -4.2507,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Glasgow City",
            "capital": "admin",
            "population": 1160000,
            "id": 1826836462
        },
        {
            "city": "Newcastle upon Tyne",
            "city_ascii": "Newcastle upon Tyne",
            "lat": 55.0004,
            "lng": -1.6,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Newcastle upon Tyne",
            "capital": "admin",
            "population": 882000,
            "id": 1826292220
        },
        {
            "city": "Caerdydd",
            "city_ascii": "Caerdydd",
            "lat": 51.5,
            "lng": -3.225,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Cardiff",
            "capital": "admin",
            "population": 861400,
            "id": 1826362422
        },
        {
            "city": "Nottingham",
            "city_ascii": "Nottingham",
            "lat": 52.9703,
            "lng": -1.17,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Nottingham",
            "capital": "admin",
            "population": 825600,
            "id": 1826122597
        },
        {
            "city": "Liverpool",
            "city_ascii": "Liverpool",
            "lat": 53.416,
            "lng": -2.918,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Liverpool",
            "capital": "admin",
            "population": 811000,
            "id": 1826558678
        },
        {
            "city": "Southend-on-Sea",
            "city_ascii": "Southend-on-Sea",
            "lat": 51.55,
            "lng": 0.72,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Southend-on-Sea",
            "capital": "admin",
            "population": 618386,
            "id": 1826524208
        },
        {
            "city": "Bristol",
            "city_ascii": "Bristol",
            "lat": 51.45,
            "lng": -2.5833,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Bristol, City of",
            "capital": "admin",
            "population": 553528,
            "id": 1826921049
        },
        {
            "city": "Edinburgh",
            "city_ascii": "Edinburgh",
            "lat": 55.9483,
            "lng": -3.2191,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Edinburgh, City of",
            "capital": "admin",
            "population": 504966,
            "id": 1826492520
        },
        {
            "city": "Brighton",
            "city_ascii": "Brighton",
            "lat": 50.8303,
            "lng": -0.17,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Brighton and Hove",
            "capital": "",
            "population": 503008,
            "id": 1826609057
        },
        {
            "city": "Bradford",
            "city_ascii": "Bradford",
            "lat": 53.8,
            "lng": -1.75,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Bradford",
            "capital": "admin",
            "population": 501700,
            "id": 1826687116
        },
        {
            "city": "Leicester",
            "city_ascii": "Leicester",
            "lat": 52.63,
            "lng": -1.1332,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Leicester",
            "capital": "admin",
            "population": 457983,
            "id": 1826431946
        },
        {
            "city": "Sunderland",
            "city_ascii": "Sunderland",
            "lat": 54.92,
            "lng": -1.38,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Sunderland",
            "capital": "admin",
            "population": 452934,
            "id": 1826736387
        },
        {
            "city": "Belfast",
            "city_ascii": "Belfast",
            "lat": 54.6,
            "lng": -5.96,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Belfast",
            "capital": "",
            "population": 450406,
            "id": 1826509389
        },
        {
            "city": "Portsmouth",
            "city_ascii": "Portsmouth",
            "lat": 50.8003,
            "lng": -1.08,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Portsmouth",
            "capital": "admin",
            "population": 442252,
            "id": 1826964096
        },
        {
            "city": "Bournemouth",
            "city_ascii": "Bournemouth",
            "lat": 50.73,
            "lng": -1.9,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Bournemouth",
            "capital": "admin",
            "population": 426945,
            "id": 1826769743
        },
        {
            "city": "Middlesbrough",
            "city_ascii": "Middlesbrough",
            "lat": 54.5804,
            "lng": -1.23,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Redcar and Cleveland",
            "capital": "admin",
            "population": 416042,
            "id": 1826407067
        },
        {
            "city": "Stoke-on-Trent",
            "city_ascii": "Stoke-on-Trent",
            "lat": 53.0004,
            "lng": -2.18,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Stoke-on-Trent",
            "capital": "admin",
            "population": 390801,
            "id": 1826799578
        },
        {
            "city": "Coventry",
            "city_ascii": "Coventry",
            "lat": 52.4204,
            "lng": -1.5,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Coventry",
            "capital": "admin",
            "population": 388271,
            "id": 1826979198
        },
        {
            "city": "Southampton",
            "city_ascii": "Southampton",
            "lat": 50.9,
            "lng": -1.4,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Southampton",
            "capital": "admin",
            "population": 384417,
            "id": 1826602892
        },
        {
            "city": "Reading",
            "city_ascii": "Reading",
            "lat": 51.47,
            "lng": -0.98,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Reading",
            "capital": "admin",
            "population": 369804,
            "id": 1826869043
        },
        {
            "city": "Kingston upon Hull",
            "city_ascii": "Kingston upon Hull",
            "lat": 53.7504,
            "lng": -0.33,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Kingston upon Hull, City of",
            "capital": "admin",
            "population": 302296,
            "id": 1826028894
        },
        {
            "city": "Abertawe",
            "city_ascii": "Abertawe",
            "lat": 51.63,
            "lng": -3.95,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Swansea",
            "capital": "admin",
            "population": 294339,
            "id": 1826574888
        },
        {
            "city": "Blackpool",
            "city_ascii": "Blackpool",
            "lat": 53.8304,
            "lng": -3.05,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Blackpool",
            "capital": "admin",
            "population": 272792,
            "id": 1826093175
        },
        {
            "city": "Plymouth",
            "city_ascii": "Plymouth",
            "lat": 50.3854,
            "lng": -4.16,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Plymouth",
            "capital": "admin",
            "population": 247297,
            "id": 1826947183
        },
        {
            "city": "Luton",
            "city_ascii": "Luton",
            "lat": 51.8804,
            "lng": -0.42,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Luton",
            "capital": "admin",
            "population": 235958,
            "id": 1826630574
        },
        {
            "city": "Oxford",
            "city_ascii": "Oxford",
            "lat": 51.7704,
            "lng": -1.25,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Oxfordshire",
            "capital": "admin",
            "population": 192796,
            "id": 1826689568
        },
        {
            "city": "Norwich",
            "city_ascii": "Norwich",
            "lat": 52.6304,
            "lng": 1.3,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Norfolk",
            "capital": "admin",
            "population": 190756,
            "id": 1826688051
        },
        {
            "city": "Aberdeen",
            "city_ascii": "Aberdeen",
            "lat": 57.1704,
            "lng": -2.08,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Aberdeen City",
            "capital": "admin",
            "population": 189364,
            "id": 1826324306
        },
        {
            "city": "York",
            "city_ascii": "York",
            "lat": 53.9704,
            "lng": -1.08,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "York",
            "capital": "admin",
            "population": 158947,
            "id": 1826149980
        },
        {
            "city": "Dundee",
            "city_ascii": "Dundee",
            "lat": 56.4704,
            "lng": -3,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Dundee City",
            "capital": "admin",
            "population": 151592,
            "id": 1826581481
        },
        {
            "city": "Ipswich",
            "city_ascii": "Ipswich",
            "lat": 52.0703,
            "lng": 1.17,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Suffolk",
            "capital": "admin",
            "population": 143767,
            "id": 1826629486
        },
        {
            "city": "Peterborough",
            "city_ascii": "Peterborough",
            "lat": 52.5804,
            "lng": -0.25,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Peterborough",
            "capital": "admin",
            "population": 140141,
            "id": 1826626144
        },
        {
            "city": "Cambridge",
            "city_ascii": "Cambridge",
            "lat": 52.2004,
            "lng": 0.1166,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Cambridgeshire",
            "capital": "admin",
            "population": 128488,
            "id": 1826229713
        },
        {
            "city": "Exeter",
            "city_ascii": "Exeter",
            "lat": 50.7004,
            "lng": -3.53,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Devon",
            "capital": "admin",
            "population": 113118,
            "id": 1826840903
        },
        {
            "city": "Bath",
            "city_ascii": "Bath",
            "lat": 51.3837,
            "lng": -2.35,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Bath and North East Somerset",
            "capital": "admin",
            "population": 93238,
            "id": 1826611282
        },
        {
            "city": "Chester",
            "city_ascii": "Chester",
            "lat": 53.2,
            "lng": -2.92,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Cheshire West and Chester",
            "capital": "admin",
            "population": 89531,
            "id": 1826441668
        },
        {
            "city": "Derry",
            "city_ascii": "Derry",
            "lat": 55.0004,
            "lng": -7.3333,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Derry and Strabane",
            "capital": "admin",
            "population": 83652,
            "id": 1826603241
        },
        {
            "city": "Greenock",
            "city_ascii": "Greenock",
            "lat": 55.9333,
            "lng": -4.75,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Inverclyde",
            "capital": "admin",
            "population": 74635,
            "id": 1826864377
        },
        {
            "city": "Carlisle",
            "city_ascii": "Carlisle",
            "lat": 54.88,
            "lng": -2.93,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Cumbria",
            "capital": "admin",
            "population": 72633,
            "id": 1826843688
        },
        {
            "city": "Scarborough",
            "city_ascii": "Scarborough",
            "lat": 54.2804,
            "lng": -0.43,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "North Yorkshire",
            "capital": "",
            "population": 70571,
            "id": 1826723231
        },
        {
            "city": "Ayr",
            "city_ascii": "Ayr",
            "lat": 55.4504,
            "lng": -4.6167,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "South Ayrshire",
            "capital": "admin",
            "population": 69042,
            "id": 1826430700
        },
        {
            "city": "Inverness",
            "city_ascii": "Inverness",
            "lat": 57.4671,
            "lng": -4.2333,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Highland",
            "capital": "admin",
            "population": 45158,
            "id": 1826161019
        },
        {
            "city": "Perth",
            "city_ascii": "Perth",
            "lat": 56.4003,
            "lng": -3.47,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Perth and Kinross",
            "capital": "admin",
            "population": 39654,
            "id": 1826081674
        },
        {
            "city": "Dover",
            "city_ascii": "Dover",
            "lat": 51.1337,
            "lng": 1.3,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Kent",
            "capital": "",
            "population": 36384,
            "id": 1826963129
        },
        {
            "city": "Dumfries",
            "city_ascii": "Dumfries",
            "lat": 55.0671,
            "lng": -3.55,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Dumfries and Galloway",
            "capital": "admin",
            "population": 31044,
            "id": 1826801547
        },
        {
            "city": "Omagh",
            "city_ascii": "Omagh",
            "lat": 54.6,
            "lng": -7.3,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Fermanagh and Omagh",
            "capital": "admin",
            "population": 21056,
            "id": 1826686995
        },
        {
            "city": "Penzance",
            "city_ascii": "Penzance",
            "lat": 50.1337,
            "lng": -5.55,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Cornwall",
            "capital": "",
            "population": 20812,
            "id": 1826600240
        },
        {
            "city": "Fort William",
            "city_ascii": "Fort William",
            "lat": 56.8165,
            "lng": -5.1121,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Highland",
            "capital": "",
            "population": 9652,
            "id": 1826742184
        },
        {
            "city": "Kirkwall",
            "city_ascii": "Kirkwall",
            "lat": 58.967,
            "lng": -2.95,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Orkney Islands",
            "capital": "admin",
            "population": 8500,
            "id": 1826208698
        },
        {
            "city": "Lerwick",
            "city_ascii": "Lerwick",
            "lat": 60.15,
            "lng": -1.15,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Shetland Islands",
            "capital": "admin",
            "population": 6594,
            "id": 1826896340
        },
        {
            "city": "Wick",
            "city_ascii": "Wick",
            "lat": 58.4333,
            "lng": -3.0834,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "Highland",
            "capital": "",
            "population": 7147,
            "id": 1826766399
        }
    ]
}