module.exports = {
    CITIES: [{
            "city": "Montevideo",
            "city_ascii": "Montevideo",
            "lat": -34.858,
            "lng": -56.1711,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Montevideo",
            "capital": "primary",
            "population": 1513000,
            "id": 1858107000
        },
        {
            "city": "Rivera",
            "city_ascii": "Rivera",
            "lat": -30.8996,
            "lng": -55.56,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Rivera",
            "capital": "admin",
            "population": 200000,
            "id": 1858819782
        },
        {
            "city": "Punta del Este",
            "city_ascii": "Punta del Este",
            "lat": -34.97,
            "lng": -54.95,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Maldonado",
            "capital": "",
            "population": 159000,
            "id": 1858267433
        },
        {
            "city": "Salto",
            "city_ascii": "Salto",
            "lat": -31.3903,
            "lng": -57.9687,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Salto",
            "capital": "admin",
            "population": 105690,
            "id": 1858575950
        },
        {
            "city": "Paysand\u00fa",
            "city_ascii": "Paysandu",
            "lat": -32.33,
            "lng": -58.08,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Paysand\u00fa",
            "capital": "admin",
            "population": 79016,
            "id": 1858756515
        },
        {
            "city": "Melo",
            "city_ascii": "Melo",
            "lat": -32.3595,
            "lng": -54.18,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Cerro Largo",
            "capital": "admin",
            "population": 55494,
            "id": 1858600801
        },
        {
            "city": "Maldonado",
            "city_ascii": "Maldonado",
            "lat": -34.91,
            "lng": -54.96,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Maldonado",
            "capital": "admin",
            "population": 55478,
            "id": 1858958595
        },
        {
            "city": "Tacuaremb\u00f3",
            "city_ascii": "Tacuarembo",
            "lat": -31.71,
            "lng": -55.98,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Tacuaremb\u00f3",
            "capital": "admin",
            "population": 54277,
            "id": 1858952595
        },
        {
            "city": "Mercedes",
            "city_ascii": "Mercedes",
            "lat": -33.2595,
            "lng": -58.03,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Soriano",
            "capital": "admin",
            "population": 42359,
            "id": 1858182538
        },
        {
            "city": "Artigas",
            "city_ascii": "Artigas",
            "lat": -30.416,
            "lng": -56.486,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Artigas",
            "capital": "admin",
            "population": 41909,
            "id": 1858646839
        },
        {
            "city": "Minas",
            "city_ascii": "Minas",
            "lat": -34.37,
            "lng": -55.23,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Lavalleja",
            "capital": "admin",
            "population": 41180,
            "id": 1858724823
        },
        {
            "city": "San Jos\u00e9",
            "city_ascii": "San Jose",
            "lat": -34.35,
            "lng": -56.71,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "San Jos\u00e9",
            "capital": "admin",
            "population": 36529,
            "id": 1858927597
        },
        {
            "city": "Durazno",
            "city_ascii": "Durazno",
            "lat": -33.41,
            "lng": -56.51,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Durazno",
            "capital": "admin",
            "population": 34037,
            "id": 1858006236
        },
        {
            "city": "Florida",
            "city_ascii": "Florida",
            "lat": -34.099,
            "lng": -56.215,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Florida",
            "capital": "admin",
            "population": 32234,
            "id": 1858077099
        },
        {
            "city": "Treinta y Tres",
            "city_ascii": "Treinta y Tres",
            "lat": -33.23,
            "lng": -54.38,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Treinta y Tres",
            "capital": "admin",
            "population": 27684,
            "id": 1858879204
        },
        {
            "city": "Rocha",
            "city_ascii": "Rocha",
            "lat": -34.483,
            "lng": -54.333,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Rocha",
            "capital": "admin",
            "population": 26874,
            "id": 1858936449
        },
        {
            "city": "Fray Bentos",
            "city_ascii": "Fray Bentos",
            "lat": -33.139,
            "lng": -58.304,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "R\u00edo Negro",
            "capital": "admin",
            "population": 23279,
            "id": 1858727525
        },
        {
            "city": "Bella Uni\u00f3n",
            "city_ascii": "Bella Union",
            "lat": -30.2596,
            "lng": -57.6,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Artigas",
            "capital": "",
            "population": 22723,
            "id": 1858883224
        },
        {
            "city": "Colonia del Sacramento",
            "city_ascii": "Colonia del Sacramento",
            "lat": -34.48,
            "lng": -57.84,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Colonia",
            "capital": "admin",
            "population": 21714,
            "id": 1858338569
        },
        {
            "city": "Canelones",
            "city_ascii": "Canelones",
            "lat": -34.538,
            "lng": -56.284,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Canelones",
            "capital": "admin",
            "population": 19698,
            "id": 1858741797
        },
        {
            "city": "Carmelo",
            "city_ascii": "Carmelo",
            "lat": -33.9896,
            "lng": -58.3,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Colonia",
            "capital": "",
            "population": 16921,
            "id": 1858670999
        },
        {
            "city": "Santa Luc\u00eda",
            "city_ascii": "Santa Lucia",
            "lat": -34.47,
            "lng": -56.4,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Canelones",
            "capital": "",
            "population": 16438,
            "id": 1858287723
        },
        {
            "city": "Castillos",
            "city_ascii": "Castillos",
            "lat": -34.1696,
            "lng": -53.83,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Rocha",
            "capital": "",
            "population": 7686,
            "id": 1858885344
        },
        {
            "city": "Lascano",
            "city_ascii": "Lascano",
            "lat": -33.6696,
            "lng": -54.2,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Rocha",
            "capital": "",
            "population": 6976,
            "id": 1858593854
        },
        {
            "city": "Trinidad",
            "city_ascii": "Trinidad",
            "lat": -33.5169,
            "lng": -56.8981,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Flores",
            "capital": "admin",
            "population": "",
            "id": 1858693926
        },
        {
            "city": "Trinidad",
            "city_ascii": "Trinidad",
            "lat": -33.544,
            "lng": -56.901,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Flores",
            "capital": "",
            "population": 21093,
            "id": 1858903609
        },
        {
            "city": "Paso de los Toros",
            "city_ascii": "Paso de los Toros",
            "lat": -32.81,
            "lng": -56.51,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Durazno",
            "capital": "",
            "population": 13221,
            "id": 1858768851
        },
        {
            "city": "Vergara",
            "city_ascii": "Vergara",
            "lat": -32.93,
            "lng": -53.95,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Treinta y Tres",
            "capital": "",
            "population": 3998,
            "id": 1858979569
        },
        {
            "city": "La Paloma",
            "city_ascii": "La Paloma",
            "lat": -34.67,
            "lng": -54.17,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Rocha",
            "capital": "",
            "population": 3230,
            "id": 1858559267
        },
        {
            "city": "Aigu\u00e1",
            "city_ascii": "Aigua",
            "lat": -34.2,
            "lng": -54.75,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Maldonado",
            "capital": "",
            "population": 2692,
            "id": 1858068520
        },
        {
            "city": "Baltasar Brum",
            "city_ascii": "Baltasar Brum",
            "lat": -30.73,
            "lng": -57.32,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Artigas",
            "capital": "",
            "population": 2517,
            "id": 1858039985
        },
        {
            "city": "Tranqueras",
            "city_ascii": "Tranqueras",
            "lat": -31.2,
            "lng": -55.75,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Rivera",
            "capital": "",
            "population": 7474,
            "id": 1858843479
        },
        {
            "city": "Jos\u00e9 Batlle y Ord\u00f3\u00f1ez",
            "city_ascii": "Jose Batlle y Ordonez",
            "lat": -33.47,
            "lng": -55.12,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Lavalleja",
            "capital": "",
            "population": 2438,
            "id": 1858852252
        }
    ]
}