module.exports = {
    CITIES: [
        {
          "city": "St. Peter's Baldachin",
          "city_ascii": "",
          "lat": 41.902222,
          "lng": 12.453333,
          "iso2": "VA",
          "country": "Vatican City",
          "population": 0,
          "capital": "",
          "wiki": ""
        },
        {
          "city": "Fontana della Pigna",
          "city_ascii": "",
          "lat": 41.906389,
          "lng": 12.454444,
          "iso2": "VA",
          "country": "Vatican City",
          "population": 0,
          "capital": "",
          "wiki": ""
        },
        {
          "city": "Tomb of Pope Alexander VII",
          "city_ascii": "",
          "lat": 41.902222,
          "lng": 12.453333,
          "iso2": "VA",
          "country": "Vatican City",
          "population": 0,
          "capital": "",
          "wiki": ""
        },
        {
          "city": "Paul VI Audience Hall",
          "city_ascii": "",
          "lat": 41.900694,
          "lng": 12.454694,
          "iso2": "VA",
          "country": "Vatican City",
          "population": 0,
          "capital": "",
          "wiki": ""
        },
        {
          "city": "Teutonic Cemetery",
          "city_ascii": "",
          "lat": 41.9014,
          "lng": 12.4544,
          "iso2": "VA",
          "country": "Vatican City",
          "population": 0,
          "capital": "",
          "wiki": ""
        },
        {
          "city": "St. Peter's Square",
          "city_ascii": "",
          "lat": 41.9022,
          "lng": 12.4572,
          "iso2": "VA",
          "country": "Vatican City",
          "population": 0,
          "capital": "",
          "wiki": ""
        },
        {
          "city": "Papal Apartments",
          "city_ascii": "",
          "lat": 41.903611,
          "lng": 12.456389,
          "iso2": "VA",
          "country": "Vatican City",
          "population": 0,
          "capital": "",
          "wiki": ""
        },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },

    ]
};