module.exports = {
    CITIES: [{
            "city": "St. Peter's Baldachin",
            "city_ascii": "St. Peter's Baldachin",
            "lat": 41.902222,
            "lng": 12.453333,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Fontana della Pigna",
            "city_ascii": "Fontana della Pigna",
            "lat": 41.906389,
            "lng": 12.454444,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Tomb of Pope Alexander VII",
            "city_ascii": "Tomb of Pope Alexander VII",
            "lat": 41.902222,
            "lng": 12.453333,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Paul VI Audience Hall",
            "city_ascii": "Paul VI Audience Hall",
            "lat": 41.900694,
            "lng": 12.454694,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Teutonic Cemetery",
            "city_ascii": "Teutonic Cemetery",
            "lat": 41.9014,
            "lng": 12.4544,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "St. Peter's Square",
            "city_ascii": "St. Peter's Square",
            "lat": 41.9022,
            "lng": 12.4572,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Papal Apartments",
            "city_ascii": "Papal Apartments",
            "lat": 41.903611,
            "lng": 12.456389,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Governor's Palace",
            "city_ascii": "Governor's Palace",
            "lat": 41.902381,
            "lng": 12.451225,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Palace_of_the_Governorate._Vatican_City_State..jpg/1920px-Palace_of_the_Governorate._Vatican_City_State..jpg",
            "wiki": ""
        },
        {
            "city": "Saint John's Tower",
            "city_ascii": "Saint John's Tower",
            "lat": 41.901547,
            "lng": 12.447594,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Mater Ecclesiae Monastery",
            "city_ascii": "Mater Ecclesiae Monastery",
            "lat": 41.903889,
            "lng": 12.451111,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Porta Cavalleggeri",
            "city_ascii": "Porta Cavalleggeri",
            "lat": 41.904167,
            "lng": 12.455278,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Saint Peter's Basilica",
            "city_ascii": "Saint Peter's Basilica",
            "lat": 41.902222,
            "lng": 12.453333,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Pietà (Michelangelo)",
            "city_ascii": "Pietà (Michelangelo)",
            "lat": 41.902222,
            "lng": 12.453333,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Sistine Chapel",
            "city_ascii": "Sistine Chapel",
            "lat": 41.903056,
            "lng": 12.454444,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Vatican Necropolis",
            "city_ascii": "Vatican Necropolis",
            "lat": 41.902301,
            "lng": 12.453293,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Pinacoteca Vaticana",
            "city_ascii": "Pinacoteca Vaticana",
            "lat": 41.906389,
            "lng": 12.454444,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Vatican City Helioport",
            "city_ascii": "Vatican City Helioport",
            "lat": 41.902,
            "lng": 12.4465,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Vatican_City_Heliport"
        },
        {
            "city": "Institute for the Works of Religion",
            "city_ascii": "Institute for the Works of Religion",
            "lat": 41.90378,
            "lng": 12.45669,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Apostolic Palace",
            "city_ascii": "Apostolic Palace",
            "lat": 41.903611,
            "lng": 12.456389,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Vatican City Railway Station",
            "city_ascii": "Vatican City Railway Station",
            "lat": 41.901,
            "lng": 12.4512,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Vatican_City_railway_station"
        },
        {
            "city": "Vatican Obelisk",
            "city_ascii": "Vatican Obelisk",
            "lat": 41.90225,
            "lng": 12.45725,
            "iso2": "VA",
            "country": "Vatican City",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/5/55/Vatican_Piazza_San_Pietro_Obelisk_slim.jpg",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Vatican Hill",
            "city_ascii": "Vatican Hill",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/5/58/Pieter_van_Edingen_Van_Aelst_-_The_Miraculous_Draught_of_Fishes_-_WGA07459.jpg",
            "lat": 41.903611,
            "lng": 12.450278,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Niccoline Chapel",
            "city_ascii": "Niccoline Chapel",
            "lat": 41.9034,
            "lng": 12.454619,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Porta Pertusa",
            "city_ascii": "Porta Pertusa",
            "lat": 41.9012,
            "lng": 12.4473,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Porta Angelica",
            "city_ascii": "Porta Angelica",
            "lat": 41.9062,
            "lng": 12.4567,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": ""
        },
        {
            "city": "Saint Peter's Tomb",
            "city_ascii": "Saint Peter's Tomb",
            "lat": 41.9022,
            "lng": 12.4533,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Saint_Peter%27s_tomb"
        },
        {
            "city": "Pio-Clementine Museum",
            "city_ascii": "Pio-Clementine Museum",
            "lat": 41.9067,
            "lng": 12.4542,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Pio-Clementine_Museum"
        },
        {
            "city": "Raphael Rooms",
            "city_ascii": "Raphael Rooms",
            "lat": 41.9047,
            "lng": 12.4553,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Raphael_Rooms"
        },
        {
            "city": "Gallery of Maps",
            "city_ascii": "Gallery of Maps",
            "lat": 41.9056,
            "lng": 12.4547,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Gallery_of_Maps"
        },
        {
            "city": "Bramante Staircase",
            "city_ascii": "Bramante Staircase",
            "lat": 41.9069,
            "lng": 12.4542,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Bramante_staircase"
        },
        {
            "city": "Vatican Apostolic Library",
            "city_ascii": "Vatican Apostolic Library",
            "lat": 41.905,
            "lng": 12.4544,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Vatican_Apostolic_Library"
        },
        {
            "city": "Vatican Apostolic Archive",
            "city_ascii": "Vatican Apostolic Archive",
            "lat": 41.9042,
            "lng": 12.4558,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Vatican_Apostolic_Archive"
        },
        {
            "city": "Vatican Gardens",
            "city_ascii": "Vatican Gardens",
            "lat": 41.903,
            "lng": 12.449,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Vatican_Gardens"
        },
        {
            "city": "Domus Sanctae Marthae",
            "city_ascii": "Domus Sanctae Marthae",
            "lat": 41.9003,
            "lng": 12.4544,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Domus_Sanctae_Marthae"
        },
        {
            "city": "Casina Pio IV",
            "city_ascii": "Casina Pio IV",
            "lat": 41.906,
            "lng": 12.450,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Casina_Pio_IV"
        },
        {
            "city": "Tower of the Winds",
            "city_ascii": "Tower of the Winds",
            "lat": 41.9056,
            "lng": 12.455,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Tower_of_the_Winds_(Vatican)"
        },
        {
            "city": "Vatican Grottoes",
            "city_ascii": "Vatican Grottoes",
            "lat": 41.9022,
            "lng": 12.4533,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Vatican_Grottoes"
        },
        {
            "city": "Dome of St. Peter's Basilica",
            "city_ascii": "Dome of St. Peter's Basilica",
            "lat": 41.9025,
            "lng": 12.4533,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/St._Peter%27s_Basilica"
        },
        {
            "city": "Swiss Guard Barracks",
            "city_ascii": "Swiss Guard Barracks",
            "lat": 41.9053,
            "lng": 12.4578,
            "iso2": "VA",
            "country": "Vatican City",
            "population": 0,
            "capital": "",
            "wiki": "https://en.wikipedia.org/wiki/Pontifical_Swiss_Guard"
        },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },
        // {
        //   "city": "",
        //   "city_ascii": "",
        //   "lat": ,
        //   "lng": ,
        //   "iso2": "VA",
        //   "country": "Vatican City",
        //   "population": 0,
        //   "capital": "",
        //   "wiki": ""
        // },

    ]
};