module.exports = {
    CITIES: [{
            "city": "Caracas",
            "city_ascii": "Caracas",
            "lat": 10.501,
            "lng": -66.917,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Distrito Capital",
            "capital": "primary",
            "population": 2985000,
            "id": 1862748204
        },
        {
            "city": "Maracaibo",
            "city_ascii": "Maracaibo",
            "lat": 10.73,
            "lng": -71.66,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Zulia",
            "capital": "admin",
            "population": 2072000,
            "id": 1862072711
        },
        {
            "city": "Valencia",
            "city_ascii": "Valencia",
            "lat": 10.23,
            "lng": -67.98,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Carabobo",
            "capital": "admin",
            "population": 1770000,
            "id": 1862309871
        },
        {
            "city": "Barquisimeto",
            "city_ascii": "Barquisimeto",
            "lat": 10.05,
            "lng": -69.3,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Lara",
            "capital": "admin",
            "population": 1116000,
            "id": 1862860739
        },
        {
            "city": "Maracay",
            "city_ascii": "Maracay",
            "lat": 10.2469,
            "lng": -67.5958,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Aragua",
            "capital": "admin",
            "population": 1007000,
            "id": 1862284350
        },
        {
            "city": "Ciudad Guayana",
            "city_ascii": "Ciudad Guayana",
            "lat": 8.37,
            "lng": -62.62,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Bol\u00edvar",
            "capital": "minor",
            "population": 746535,
            "id": 1862889027
        },
        {
            "city": "Barcelona",
            "city_ascii": "Barcelona",
            "lat": 10.1304,
            "lng": -64.72,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Anzo\u00e1tegui",
            "capital": "admin",
            "population": 600954,
            "id": 1862418619
        },
        {
            "city": "Puerto La Cruz",
            "city_ascii": "Puerto La Cruz",
            "lat": 10.17,
            "lng": -64.68,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Anzo\u00e1tegui",
            "capital": "minor",
            "population": 546616,
            "id": 1862856141
        },
        {
            "city": "Cabimas",
            "city_ascii": "Cabimas",
            "lat": 10.43,
            "lng": -71.45,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Zulia",
            "capital": "minor",
            "population": 441094,
            "id": 1862398719
        },
        {
            "city": "San Crist\u00f3bal",
            "city_ascii": "San Cristobal",
            "lat": 7.77,
            "lng": -72.25,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "T\u00e1chira",
            "capital": "admin",
            "population": 438798,
            "id": 1862252264
        },
        {
            "city": "Matur\u00edn",
            "city_ascii": "Maturin",
            "lat": 9.75,
            "lng": -63.17,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Monagas",
            "capital": "admin",
            "population": 410972,
            "id": 1862546949
        },
        {
            "city": "M\u00e9rida",
            "city_ascii": "Merida",
            "lat": 8.4,
            "lng": -71.13,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "M\u00e9rida",
            "capital": "admin",
            "population": 345489,
            "id": 1862668122
        },
        {
            "city": "Ciudad Bol\u00edvar",
            "city_ascii": "Ciudad Bolivar",
            "lat": 8.1,
            "lng": -63.6,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Bol\u00edvar",
            "capital": "admin",
            "population": 338000,
            "id": 1862318264
        },
        {
            "city": "Cuman\u00e1",
            "city_ascii": "Cumana",
            "lat": 10.45,
            "lng": -64.18,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Sucre",
            "capital": "admin",
            "population": 317603,
            "id": 1862583279
        },
        {
            "city": "Maiquet\u00eda",
            "city_ascii": "Maiquetia",
            "lat": 10.6004,
            "lng": -66.97,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Vargas",
            "capital": "minor",
            "population": 315442,
            "id": 1862822831
        },
        {
            "city": "Los Teques",
            "city_ascii": "Los Teques",
            "lat": 10.42,
            "lng": -67.02,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Miranda",
            "capital": "admin",
            "population": 303470,
            "id": 1862066931
        },
        {
            "city": "Barinas",
            "city_ascii": "Barinas",
            "lat": 8.6,
            "lng": -70.25,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Barinas",
            "capital": "admin",
            "population": 284289,
            "id": 1862647790
        },
        {
            "city": "Acarigua",
            "city_ascii": "Acarigua",
            "lat": 9.5804,
            "lng": -69.2,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Portuguesa",
            "capital": "minor",
            "population": 260921,
            "id": 1862134462
        },
        {
            "city": "Punto Fijo",
            "city_ascii": "Punto Fijo",
            "lat": 11.72,
            "lng": -70.21,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Falc\u00f3n",
            "capital": "minor",
            "population": 234736,
            "id": 1862535644
        },
        {
            "city": "El Tigre",
            "city_ascii": "El Tigre",
            "lat": 8.8903,
            "lng": -64.26,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Anzo\u00e1tegui",
            "capital": "minor",
            "population": 197440,
            "id": 1862428934
        },
        {
            "city": "Porlamar",
            "city_ascii": "Porlamar",
            "lat": 10.9604,
            "lng": -63.85,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Nueva Esparta",
            "capital": "minor",
            "population": 196934,
            "id": 1862693736
        },
        {
            "city": "Coro",
            "city_ascii": "Coro",
            "lat": 11.42,
            "lng": -69.68,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Falc\u00f3n",
            "capital": "admin",
            "population": 195227,
            "id": 1862429150
        },
        {
            "city": "Valera",
            "city_ascii": "Valera",
            "lat": 9.32,
            "lng": -70.62,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Trujillo",
            "capital": "minor",
            "population": 191167,
            "id": 1862735261
        },
        {
            "city": "Puerto Cabello",
            "city_ascii": "Puerto Cabello",
            "lat": 10.4704,
            "lng": -68.17,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Carabobo",
            "capital": "minor",
            "population": 174000,
            "id": 1862031193
        },
        {
            "city": "Ocumare del Tuy",
            "city_ascii": "Ocumare del Tuy",
            "lat": 10.12,
            "lng": -66.78,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Miranda",
            "capital": "minor",
            "population": 166072,
            "id": 1862015576
        },
        {
            "city": "Guanare",
            "city_ascii": "Guanare",
            "lat": 9.05,
            "lng": -69.75,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Portuguesa",
            "capital": "admin",
            "population": 151642,
            "id": 1862645590
        },
        {
            "city": "Carora",
            "city_ascii": "Carora",
            "lat": 10.19,
            "lng": -70.08,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Lara",
            "capital": "minor",
            "population": 149711,
            "id": 1862485109
        },
        {
            "city": "Car\u00fapano",
            "city_ascii": "Carupano",
            "lat": 10.67,
            "lng": -63.23,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Sucre",
            "capital": "minor",
            "population": 126293,
            "id": 1862777685
        },
        {
            "city": "San Fernando",
            "city_ascii": "San Fernando",
            "lat": 7.9,
            "lng": -67.4699,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Apure",
            "capital": "admin",
            "population": 122701,
            "id": 1862404343
        },
        {
            "city": "Anaco",
            "city_ascii": "Anaco",
            "lat": 9.44,
            "lng": -64.46,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Anzo\u00e1tegui",
            "capital": "minor",
            "population": 117596,
            "id": 1862074247
        },
        {
            "city": "Calabozo",
            "city_ascii": "Calabozo",
            "lat": 8.9304,
            "lng": -67.44,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Gu\u00e1rico",
            "capital": "minor",
            "population": 117132,
            "id": 1862623441
        },
        {
            "city": "San Juan de los Morros",
            "city_ascii": "San Juan de los Morros",
            "lat": 9.901,
            "lng": -67.354,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Gu\u00e1rico",
            "capital": "admin",
            "population": 87739,
            "id": 1862865294
        },
        {
            "city": "San Carlos",
            "city_ascii": "San Carlos",
            "lat": 9.658,
            "lng": -68.59,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Cojedes",
            "capital": "admin",
            "population": 77192,
            "id": 1862109303
        },
        {
            "city": "San Felipe",
            "city_ascii": "San Felipe",
            "lat": 10.336,
            "lng": -68.746,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Yaracuy",
            "capital": "admin",
            "population": 76766,
            "id": 1862716082
        },
        {
            "city": "Puerto Ayacucho",
            "city_ascii": "Puerto Ayacucho",
            "lat": 5.6639,
            "lng": -67.6236,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Amazonas",
            "capital": "admin",
            "population": 52526,
            "id": 1862027409
        },
        {
            "city": "Tucupita",
            "city_ascii": "Tucupita",
            "lat": 9.0605,
            "lng": -62.06,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Delta Amacuro",
            "capital": "admin",
            "population": 51534,
            "id": 1862849758
        },
        {
            "city": "Trujillo",
            "city_ascii": "Trujillo",
            "lat": 9.3804,
            "lng": -70.44,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Trujillo",
            "capital": "admin",
            "population": 50353,
            "id": 1862212549
        },
        {
            "city": "La Asunci\u00f3n",
            "city_ascii": "La Asuncion",
            "lat": 11.0333,
            "lng": -63.8833,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Nueva Esparta",
            "capital": "admin",
            "population": 35084,
            "id": 1862490314
        },
        {
            "city": "La Guaira",
            "city_ascii": "La Guaira",
            "lat": 10.6004,
            "lng": -66.93,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Vargas",
            "capital": "admin",
            "population": "",
            "id": 1862282663
        },
        {
            "city": "San Carlos del Zulia",
            "city_ascii": "San Carlos del Zulia",
            "lat": 9.0104,
            "lng": -71.92,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Zulia",
            "capital": "minor",
            "population": 97288,
            "id": 1862219492
        },
        {
            "city": "Valle de La Pascua",
            "city_ascii": "Valle de La Pascua",
            "lat": 9.21,
            "lng": -66.02,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Gu\u00e1rico",
            "capital": "minor",
            "population": 89080,
            "id": 1862904072
        },
        {
            "city": "Machiques",
            "city_ascii": "Machiques",
            "lat": 10.0704,
            "lng": -72.5499,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Zulia",
            "capital": "minor",
            "population": 62968,
            "id": 1862003182
        },
        {
            "city": "Upata",
            "city_ascii": "Upata",
            "lat": 8.0204,
            "lng": -62.41,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Bol\u00edvar",
            "capital": "minor",
            "population": 53685,
            "id": 1862794619
        },
        {
            "city": "Zaraza",
            "city_ascii": "Zaraza",
            "lat": 9.3404,
            "lng": -65.32,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Gu\u00e1rico",
            "capital": "minor",
            "population": 41483,
            "id": 1862643668
        },
        {
            "city": "Altagracia de Orituco",
            "city_ascii": "Altagracia de Orituco",
            "lat": 9.8504,
            "lng": -66.38,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Gu\u00e1rico",
            "capital": "minor",
            "population": 40052,
            "id": 1862533029
        },
        {
            "city": "Santa Rita",
            "city_ascii": "Santa Rita",
            "lat": 10.5318,
            "lng": -71.5039,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Zulia",
            "capital": "minor",
            "population": 31810,
            "id": 1862676200
        },
        {
            "city": "Guasdualito",
            "city_ascii": "Guasdualito",
            "lat": 7.24,
            "lng": -70.74,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Apure",
            "capital": "minor",
            "population": 30860,
            "id": 1862834503
        },
        {
            "city": "Chaguarama",
            "city_ascii": "Chaguarama",
            "lat": 9.2159,
            "lng": -63.7523,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Anzo\u00e1tegui",
            "capital": "",
            "population": 15000,
            "id": 1862477708
        },
        {
            "city": "La Esmeralda",
            "city_ascii": "La Esmeralda",
            "lat": 3.1738,
            "lng": -65.5466,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Amazonas",
            "capital": "minor",
            "population": 150,
            "id": 1862255876
        },
        {
            "city": "El Dorado",
            "city_ascii": "El Dorado",
            "lat": 6.7333,
            "lng": -61.6333,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Bol\u00edvar",
            "capital": "",
            "population": 2383,
            "id": 1862242782
        },
        {
            "city": "El Manteco",
            "city_ascii": "El Manteco",
            "lat": 7.3504,
            "lng": -62.5333,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Bol\u00edvar",
            "capital": "",
            "population": 2215,
            "id": 1862113510
        }
    ]
}