module.exports = {
    CITIES: [{
            "city": "Tokyo",
            "city_ascii": "Tokyo",
            "lat": 35.685,
            "lng": 139.7514,
            "country": "Japan",
            "iso2": "JP",
            "iso3": "JPN",
            "admin_name": "T\u014dky\u014d",
            "capital": "primary",
            "population": 35676000,
            "id": 1392685764
        },
        {
            "city": "Mexico City",
            "city_ascii": "Mexico City",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/1/15/Montaje.Ciudad_de_M%C3%A9xico.jpg",
            "lat": 19.4424,
            "lng": -99.131,
            "country": "Mexico",
            "iso2": "MX",
            "iso3": "MEX",
            "admin_name": "Ciudad de M\u00e9xico",
            "capital": "primary",
            "population": 19028000,
            "id": 1484247881
        },
        {
            "city": "Dhaka",
            "city_ascii": "Dhaka",
            "lat": 23.7231,
            "lng": 90.4086,
            "country": "Bangladesh",
            "iso2": "BD",
            "iso3": "BGD",
            "admin_name": "Dhaka",
            "capital": "primary",
            "population": 12797394,
            "id": 1050529279
        },
        {
            "city": "Buenos Aires",
            "city_ascii": "Buenos Aires",
            "lat": -34.6025,
            "lng": -58.3975,
            "country": "Argentina",
            "iso2": "AR",
            "iso3": "ARG",
            "admin_name": "Buenos Aires, Ciudad Aut\u00f3noma de",
            "capital": "primary",
            "population": 12795000,
            "id": 1032717330
        },
        {
            "city": "Cairo",
            "city_ascii": "Cairo",
            "lat": 30.05,
            "lng": 31.25,
            "country": "Egypt",
            "iso2": "EG",
            "iso3": "EGY",
            "admin_name": "Al Q\u0101hirah",
            "capital": "primary",
            "population": 11893000,
            "id": 1818253931
        },
        {
            "city": "Beijing",
            "city_ascii": "Beijing",
            "lat": 39.9289,
            "lng": 116.3883,
            "country": "China",
            "iso2": "CN",
            "iso3": "CHN",
            "admin_name": "Beijing",
            "capital": "primary",
            "population": 11106000,
            "id": 1156228865
        },
        {
            "city": "Manila",
            "city_ascii": "Manila",
            "lat": 14.6042,
            "lng": 120.9822,
            "country": "Philippines",
            "iso2": "PH",
            "iso3": "PHL",
            "admin_name": "Manila",
            "capital": "primary",
            "population": 11100000,
            "id": 1608618140
        },
        {
            "city": "Moscow",
            "city_ascii": "Moscow",
            "lat": 55.7522,
            "lng": 37.6155,
            "country": "Russia",
            "iso2": "RU",
            "iso3": "RUS",
            "admin_name": "Moskva",
            "capital": "primary",
            "population": 10452000,
            "id": 1643318494
        },
        {
            "city": "Paris",
            "city_ascii": "Paris",
            "lat": 48.8667,
            "lng": 2.3333,
            "country": "France",
            "iso2": "FR",
            "iso3": "FRA",
            "admin_name": "\u00cele-de-France",
            "capital": "primary",
            "population": 9904000,
            "id": 1250015082
        },
        {
            "city": "Seoul",
            "city_ascii": "Seoul",
            "lat": 37.5663,
            "lng": 126.9997,
            "country": "Korea, South",
            "iso2": "KR",
            "iso3": "KOR",
            "admin_name": "Seoul",
            "capital": "primary",
            "population": 9796000,
            "id": 1410836482
        },
        {
            "city": "Jakarta",
            "city_ascii": "Jakarta",
            "lat": -6.1744,
            "lng": 106.8294,
            "country": "Indonesia",
            "iso2": "ID",
            "iso3": "IDN",
            "admin_name": "Jakarta",
            "capital": "primary",
            "population": 9125000,
            "id": 1360771077
        },
        {
            "city": "London",
            "city_ascii": "London",
            "lat": 51.5,
            "lng": -0.1167,
            "country": "United Kingdom",
            "iso2": "GB",
            "iso3": "GBR",
            "admin_name": "London, City of",
            "capital": "primary",
            "population": 8567000,
            "id": 1826645935
        },
        {
            "city": "Lima",
            "city_ascii": "Lima",
            "lat": -12.048,
            "lng": -77.0501,
            "country": "Peru",
            "iso2": "PE",
            "iso3": "PER",
            "admin_name": "Lima",
            "capital": "primary",
            "population": 8012000,
            "id": 1604728603
        },
        {
            "city": "Tehran",
            "city_ascii": "Tehran",
            "lat": 35.6719,
            "lng": 51.4243,
            "country": "Iran",
            "iso2": "IR",
            "iso3": "IRN",
            "admin_name": "Tehr\u0101n",
            "capital": "primary",
            "population": 7873000,
            "id": 1364305026
        },
        {
            "city": "Kinshasa",
            "city_ascii": "Kinshasa",
            "lat": -4.3297,
            "lng": 15.315,
            "country": "Congo (Kinshasa)",
            "iso2": "CD",
            "iso3": "COD",
            "admin_name": "Kinshasa",
            "capital": "primary",
            "population": 7843000,
            "id": 1180000363
        },
        {
            "city": "Bogot\u00e1",
            "city_ascii": "Bogota",
            "lat": 4.5964,
            "lng": -74.0833,
            "country": "Colombia",
            "iso2": "CO",
            "iso3": "COL",
            "admin_name": "Bogot\u00e1",
            "capital": "primary",
            "population": 7772000,
            "id": 1170483426
        },
        {
            "city": "Taipei",
            "city_ascii": "Taipei",
            "lat": 25.0358,
            "lng": 121.5683,
            "country": "Taiwan",
            "iso2": "TW",
            "iso3": "TWN",
            "admin_name": "Taipei",
            "capital": "primary",
            "population": 6900273,
            "id": 1158881289
        },
        {
            "city": "Bangkok",
            "city_ascii": "Bangkok",
            "lat": 13.75,
            "lng": 100.5166,
            "country": "Thailand",
            "iso2": "TH",
            "iso3": "THA",
            "admin_name": "Krung Thep Maha Nakhon",
            "capital": "primary",
            "population": 6704000,
            "id": 1764068610
        },
        {
            "city": "Santiago",
            "city_ascii": "Santiago",
            "lat": -33.45,
            "lng": -70.667,
            "country": "Chile",
            "iso2": "CL",
            "iso3": "CHL",
            "admin_name": "Regi\u00f3n Metropolitana",
            "capital": "primary",
            "population": 5720000,
            "id": 1152554349
        },
        {
            "city": "Madrid",
            "city_ascii": "Madrid",
            "lat": 40.4,
            "lng": -3.6834,
            "country": "Spain",
            "iso2": "ES",
            "iso3": "ESP",
            "admin_name": "Madrid",
            "capital": "primary",
            "population": 5567000,
            "id": 1724616994
        },
        {
            "city": "Washington",
            "city_ascii": "Washington",
            "lat": 38.9047,
            "lng": -77.0163,
            "country": "United States",
            "iso2": "US",
            "iso3": "USA",
            "admin_name": "District of Columbia",
            "capital": "primary",
            "population": 5289420,
            "id": 1840006060
        },
        {
            "city": "Singapore",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Marina_Bay_Sands_from_Gardens_By_The_Bay.jpg",
            "city_ascii": "Singapore",
            "lat": 1.293,
            "lng": 103.8558,
            "country": "Singapore",
            "iso2": "SG",
            "iso3": "SGP",
            "admin_name": "",
            "capital": "primary",
            "population": 5183700,
            "id": 1702341327
        },
        {
            "city": "Luanda",
            "city_ascii": "Luanda",
            "lat": -8.8383,
            "lng": 13.2344,
            "country": "Angola",
            "iso2": "AO",
            "iso3": "AGO",
            "admin_name": "Luanda",
            "capital": "primary",
            "population": 5172900,
            "id": 1024949724
        },
        {
            "city": "Baghdad",
            "city_ascii": "Baghdad",
            "lat": 33.3386,
            "lng": 44.3939,
            "country": "Iraq",
            "iso2": "IQ",
            "iso3": "IRQ",
            "admin_name": "Baghd\u0101d",
            "capital": "primary",
            "population": 5054000,
            "id": 1368596238
        },
        {
            "city": "Khartoum",
            "city_ascii": "Khartoum",
            "lat": 15.5881,
            "lng": 32.5342,
            "country": "Sudan",
            "iso2": "SD",
            "iso3": "SDN",
            "admin_name": "Khartoum",
            "capital": "primary",
            "population": 4754000,
            "id": 1729268475
        },
        {
            "city": "Riyadh",
            "city_ascii": "Riyadh",
            "lat": 24.6408,
            "lng": 46.7727,
            "country": "Saudi Arabia",
            "iso2": "SA",
            "iso3": "SAU",
            "admin_name": "Ar Riy\u0101\u1e11",
            "capital": "primary",
            "population": 4465000,
            "id": 1682999334
        },
        {
            "city": "Hanoi",
            "city_ascii": "Hanoi",
            "lat": 21.0333,
            "lng": 105.85,
            "country": "Vietnam",
            "iso2": "VN",
            "iso3": "VNM",
            "admin_name": "H\u00e0 N\u1ed9i",
            "capital": "primary",
            "population": 4378000,
            "id": 1704413791
        },
        {
            "city": "Yangon",
            "city_ascii": "Yangon",
            "lat": 16.7834,
            "lng": 96.1667,
            "country": "Myanmar",
            "iso2": "MM",
            "iso3": "MMR",
            "admin_name": "Yangon",
            "capital": "primary",
            "population": 4088000,
            "id": 1104616656
        },
        {
            "city": "Bras\u00edlia",
            "city_ascii": "Brasilia",
            "lat": -15.7833,
            "lng": -47.9161,
            "country": "Brazil",
            "iso2": "BR",
            "iso3": "BRA",
            "admin_name": "Distrito Federal",
            "capital": "primary",
            "population": 3716996,
            "id": 1076144436
        },
        {
            "city": "Ankara",
            "city_ascii": "Ankara",
            "lat": 39.9272,
            "lng": 32.8644,
            "country": "Turkey",
            "iso2": "TR",
            "iso3": "TUR",
            "admin_name": "Ankara",
            "capital": "primary",
            "population": 3716000,
            "id": 1792572891
        },
        {
            "city": "Berlin",
            "city_ascii": "Berlin",
            "lat": 52.5218,
            "lng": 13.4015,
            "country": "Germany",
            "iso2": "DE",
            "iso3": "DEU",
            "admin_name": "Berlin",
            "capital": "primary",
            "population": 3406000,
            "id": 1276451290
        },
        {
            "city": "Algiers",
            "city_ascii": "Algiers",
            "lat": 36.7631,
            "lng": 3.0506,
            "country": "Algeria",
            "iso2": "DZ",
            "iso3": "DZA",
            "admin_name": "Alger",
            "capital": "primary",
            "population": 3354000,
            "id": 1012973369
        },
        {
            "city": "Rome",
            "city_ascii": "Rome",
            "lat": 41.896,
            "lng": 12.4833,
            "country": "Italy",
            "iso2": "IT",
            "iso3": "ITA",
            "admin_name": "Lazio",
            "capital": "primary",
            "population": 3339000,
            "id": 1380382862
        },
        {
            "city": "Pyongyang",
            "city_ascii": "Pyongyang",
            "lat": 39.0194,
            "lng": 125.7547,
            "country": "Korea, North",
            "iso2": "KP",
            "iso3": "PRK",
            "admin_name": "P\u2019y\u014fngyang",
            "capital": "primary",
            "population": 3300000,
            "id": 1408738594
        },
        {
            "city": "Kabul",
            "city_ascii": "Kabul",
            "lat": 34.5167,
            "lng": 69.1833,
            "country": "Afghanistan",
            "iso2": "AF",
            "iso3": "AFG",
            "admin_name": "K\u0101bul",
            "capital": "primary",
            "population": 3277000,
            "id": 1004993580
        },
        {
            "city": "Athens",
            "city_ascii": "Athens",
            "lat": 37.9833,
            "lng": 23.7333,
            "country": "Greece",
            "iso2": "GR",
            "iso3": "GRC",
            "admin_name": "Attik\u00ed",
            "capital": "primary",
            "population": 3242000,
            "id": 1300715560
        },
        {
            "city": "Cape Town",
            "city_ascii": "Cape Town",
            "lat": -33.92,
            "lng": 18.435,
            "country": "South Africa",
            "iso2": "ZA",
            "iso3": "ZAF",
            "admin_name": "Western Cape",
            "capital": "primary",
            "population": 3215000,
            "id": 1710680650
        },
        {
            "city": "Addis Ababa",
            "city_ascii": "Addis Ababa",
            "lat": 9.0333,
            "lng": 38.7,
            "country": "Ethiopia",
            "iso2": "ET",
            "iso3": "ETH",
            "admin_name": "\u0100d\u012bs \u0100beba",
            "capital": "primary",
            "population": 3100000,
            "id": 1231824991
        },
        {
            "city": "Nairobi",
            "city_ascii": "Nairobi",
            "lat": -1.2833,
            "lng": 36.8167,
            "country": "Kenya",
            "iso2": "KE",
            "iso3": "KEN",
            "admin_name": "Nairobi City",
            "capital": "primary",
            "population": 3010000,
            "id": 1404000661
        },
        {
            "city": "Caracas",
            "city_ascii": "Caracas",
            "lat": 10.501,
            "lng": -66.917,
            "country": "Venezuela",
            "iso2": "VE",
            "iso3": "VEN",
            "admin_name": "Distrito Capital",
            "capital": "primary",
            "population": 2985000,
            "id": 1862748204
        },
        {
            "city": "Lisbon",
            "city_ascii": "Lisbon",
            "lat": 38.7227,
            "lng": -9.1449,
            "country": "Portugal",
            "iso2": "PT",
            "iso3": "PRT",
            "admin_name": "Lisboa",
            "capital": "primary",
            "population": 2812000,
            "id": 1620619017
        },
        {
            "city": "Kyiv",
            "city_ascii": "Kyiv",
            "lat": 50.4334,
            "lng": 30.5166,
            "country": "Ukraine",
            "iso2": "UA",
            "iso3": "UKR",
            "admin_name": "Kyyiv, Misto",
            "capital": "primary",
            "population": 2709000,
            "id": 1804382913
        },
        {
            "city": "Dakar",
            "city_ascii": "Dakar",
            "lat": 14.7158,
            "lng": -17.4731,
            "country": "Senegal",
            "iso2": "SN",
            "iso3": "SEN",
            "admin_name": "Dakar",
            "capital": "primary",
            "population": 2604000,
            "id": 1686604760
        },
        {
            "city": "Damascus",
            "city_ascii": "Damascus",
            "lat": 33.5,
            "lng": 36.3,
            "country": "Syria",
            "iso2": "SY",
            "iso3": "SYR",
            "admin_name": "Dimashq",
            "capital": "primary",
            "population": 2466000,
            "id": 1760685964
        },
        {
            "city": "Tunis",
            "city_ascii": "Tunis",
            "lat": 36.8028,
            "lng": 10.1797,
            "country": "Tunisia",
            "iso2": "TN",
            "iso3": "TUN",
            "admin_name": "Tunis",
            "capital": "primary",
            "population": 2412500,
            "id": 1788742103
        },
        {
            "city": "Vienna",
            "city_ascii": "Vienna",
            "lat": 48.2,
            "lng": 16.3666,
            "country": "Austria",
            "iso2": "AT",
            "iso3": "AUT",
            "admin_name": "Wien",
            "capital": "primary",
            "population": 2400000,
            "id": 1040261752
        },
        {
            "city": "Tripoli",
            "city_ascii": "Tripoli",
            "lat": 32.8925,
            "lng": 13.18,
            "country": "Libya",
            "iso2": "LY",
            "iso3": "LBY",
            "admin_name": "\u0162ar\u0101bulus",
            "capital": "primary",
            "population": 2189000,
            "id": 1434201852
        },
        {
            "city": "Tashkent",
            "city_ascii": "Tashkent",
            "lat": 41.3117,
            "lng": 69.2949,
            "country": "Uzbekistan",
            "iso2": "UZ",
            "iso3": "UZB",
            "admin_name": "Toshkent",
            "capital": "primary",
            "population": 2184000,
            "id": 1860331871
        },
        {
            "city": "Havana",
            "city_ascii": "Havana",
            "lat": 23.132,
            "lng": -82.3642,
            "country": "Cuba",
            "iso2": "CU",
            "iso3": "CUB",
            "admin_name": "La Habana",
            "capital": "primary",
            "population": 2174000,
            "id": 1192752771
        },
        {
            "city": "Santo Domingo",
            "city_ascii": "Santo Domingo",
            "lat": 18.4701,
            "lng": -69.9001,
            "country": "Dominican Republic",
            "iso2": "DO",
            "iso3": "DOM",
            "admin_name": "Ozama",
            "capital": "primary",
            "population": 2154000,
            "id": 1214636202
        },
        {
            "city": "Baku",
            "city_ascii": "Baku",
            "lat": 40.3953,
            "lng": 49.8622,
            "country": "Azerbaijan",
            "iso2": "AZ",
            "iso3": "AZE",
            "admin_name": "Bak\u0131",
            "capital": "primary",
            "population": 2122300,
            "id": 1031946365
        },
        {
            "city": "Accra",
            "city_ascii": "Accra",
            "lat": 5.55,
            "lng": -0.2167,
            "country": "Ghana",
            "iso2": "GH",
            "iso3": "GHA",
            "admin_name": "Greater Accra",
            "capital": "primary",
            "population": 2121000,
            "id": 1288299415
        },
        {
            "city": "Kuwait City",
            "city_ascii": "Kuwait City",
            "lat": 29.3697,
            "lng": 47.9783,
            "country": "Kuwait",
            "iso2": "KW",
            "iso3": "KWT",
            "admin_name": "Al \u2018\u0100\u015fimah",
            "capital": "primary",
            "population": 2063000,
            "id": 1414102075
        },
        {
            "city": "Sanaa",
            "city_ascii": "Sanaa",
            "lat": 15.3547,
            "lng": 44.2066,
            "country": "Yemen",
            "iso2": "YE",
            "iso3": "YEM",
            "admin_name": "Am\u0101nat al \u2018\u0100\u015fimah",
            "capital": "primary",
            "population": 2008000,
            "id": 1887750814
        },
        {
            "city": "Port-au-Prince",
            "city_ascii": "Port-au-Prince",
            "lat": 18.541,
            "lng": -72.336,
            "country": "Haiti",
            "iso2": "HT",
            "iso3": "HTI",
            "admin_name": "Ouest",
            "capital": "primary",
            "population": 1998000,
            "id": 1332401940
        },
        {
            "city": "Bucharest",
            "city_ascii": "Bucharest",
            "lat": 44.4334,
            "lng": 26.0999,
            "country": "Romania",
            "iso2": "RO",
            "iso3": "ROU",
            "admin_name": "Bucure\u015fti",
            "capital": "primary",
            "population": 1942000,
            "id": 1642414442
        },
        {
            "city": "Asunci\u00f3n",
            "city_ascii": "Asuncion",
            "lat": -25.2964,
            "lng": -57.6415,
            "country": "Paraguay",
            "iso2": "PY",
            "iso3": "PRY",
            "admin_name": "Asunci\u00f3n",
            "capital": "primary",
            "population": 1870000,
            "id": 1600057911
        },
        {
            "city": "Beirut",
            "city_ascii": "Beirut",
            "lat": 33.872,
            "lng": 35.5097,
            "country": "Lebanon",
            "iso2": "LB",
            "iso3": "LBN",
            "admin_name": "Beyrouth",
            "capital": "primary",
            "population": 1846000,
            "id": 1422847713
        },
        {
            "city": "Minsk",
            "city_ascii": "Minsk",
            "lat": 53.9,
            "lng": 27.5666,
            "country": "Belarus",
            "iso2": "BY",
            "iso3": "BLR",
            "admin_name": "Minsk",
            "capital": "primary",
            "population": 1805000,
            "id": 1112348503
        },
        {
            "city": "Brussels",
            "city_ascii": "Brussels",
            "lat": 50.8333,
            "lng": 4.3333,
            "country": "Belgium",
            "iso2": "BE",
            "iso3": "BEL",
            "admin_name": "Brussels-Capital Region",
            "capital": "primary",
            "population": 1743000,
            "id": 1056469830
        },
        {
            "city": "Warsaw",
            "city_ascii": "Warsaw",
            "lat": 52.25,
            "lng": 21,
            "country": "Poland",
            "iso2": "PL",
            "iso3": "POL",
            "admin_name": "Mazowieckie",
            "capital": "primary",
            "population": 1707000,
            "id": 1616024847
        },
        {
            "city": "Rabat",
            "city_ascii": "Rabat",
            "lat": 34.0253,
            "lng": -6.8361,
            "country": "Morocco",
            "iso2": "MA",
            "iso3": "MAR",
            "admin_name": "Rabat-Sal\u00e9-K\u00e9nitra",
            "capital": "primary",
            "population": 1705000,
            "id": 1504023252
        },
        {
            "city": "Quito",
            "city_ascii": "Quito",
            "lat": -0.215,
            "lng": -78.5001,
            "country": "Ecuador",
            "iso2": "EC",
            "iso3": "ECU",
            "admin_name": "Pichincha",
            "capital": "primary",
            "population": 1701000,
            "id": 1218441993
        },
        {
            "city": "Antananarivo",
            "city_ascii": "Antananarivo",
            "lat": -18.9166,
            "lng": 47.5166,
            "country": "Madagascar",
            "iso2": "MG",
            "iso3": "MDG",
            "admin_name": "Antananarivo",
            "capital": "primary",
            "population": 1697000,
            "id": 1450978461
        },
        {
            "city": "Budapest",
            "city_ascii": "Budapest",
            "lat": 47.5,
            "lng": 19.0833,
            "country": "Hungary",
            "iso2": "HU",
            "iso3": "HUN",
            "admin_name": "Budapest",
            "capital": "primary",
            "population": 1679000,
            "id": 1348611435
        },
        {
            "city": "Yaound\u00e9",
            "city_ascii": "Yaounde",
            "lat": 3.8667,
            "lng": 11.5167,
            "country": "Cameroon",
            "iso2": "CM",
            "iso3": "CMR",
            "admin_name": "Centre",
            "capital": "primary",
            "population": 1611000,
            "id": 1120298240
        },
        {
            "city": "La Paz",
            "city_ascii": "La Paz",
            "lat": -16.498,
            "lng": -68.15,
            "country": "Bolivia",
            "iso2": "BO",
            "iso3": "BOL",
            "admin_name": "La Paz",
            "capital": "primary",
            "population": 1590000,
            "id": 1068000064
        },
        {
            "city": "Abuja",
            "city_ascii": "Abuja",
            "lat": 9.0833,
            "lng": 7.5333,
            "country": "Nigeria",
            "iso2": "NG",
            "iso3": "NGA",
            "admin_name": "Federal Capital Territory",
            "capital": "primary",
            "population": 1576000,
            "id": 1566342270
        },
        {
            "city": "Harare",
            "city_ascii": "Harare",
            "lat": -17.8178,
            "lng": 31.0447,
            "country": "Zimbabwe",
            "iso2": "ZW",
            "iso3": "ZWE",
            "admin_name": "Harare",
            "capital": "primary",
            "population": 1572000,
            "id": 1716196799
        },
        {
            "city": "Montevideo",
            "city_ascii": "Montevideo",
            "lat": -34.858,
            "lng": -56.1711,
            "country": "Uruguay",
            "iso2": "UY",
            "iso3": "URY",
            "admin_name": "Montevideo",
            "capital": "primary",
            "population": 1513000,
            "id": 1858107000
        },
        {
            "city": "Bamako",
            "city_ascii": "Bamako",
            "lat": 12.65,
            "lng": -8,
            "country": "Mali",
            "iso2": "ML",
            "iso3": "MLI",
            "admin_name": "Bamako",
            "capital": "primary",
            "population": 1494000,
            "id": 1466965925
        },
        {
            "city": "Conakry",
            "city_ascii": "Conakry",
            "lat": 9.5315,
            "lng": -13.6802,
            "country": "Guinea",
            "iso2": "GN",
            "iso3": "GIN",
            "admin_name": "Conakry",
            "capital": "primary",
            "population": 1494000,
            "id": 1324568159
        },
        {
            "city": "Phnom Penh",
            "city_ascii": "Phnom Penh",
            "lat": 11.55,
            "lng": 104.9166,
            "country": "Cambodia",
            "iso2": "KH",
            "iso3": "KHM",
            "admin_name": "Phnom Penh",
            "capital": "primary",
            "population": 1466000,
            "id": 1116260534
        },
        {
            "city": "Lom\u00e9",
            "city_ascii": "Lome",
            "lat": 6.1319,
            "lng": 1.2228,
            "country": "Togo",
            "iso2": "TG",
            "iso3": "TGO",
            "admin_name": "Maritime",
            "capital": "primary",
            "population": 1452000,
            "id": 1768409132
        },
        {
            "city": "Doha",
            "city_ascii": "Doha",
            "lat": 25.2866,
            "lng": 51.533,
            "country": "Qatar",
            "iso2": "QA",
            "iso3": "QAT",
            "admin_name": "Ad Daw\u1e29ah",
            "capital": "primary",
            "population": 1450000,
            "id": 1634459660
        },
        {
            "city": "Kuala Lumpur",
            "city_ascii": "Kuala Lumpur",
            "lat": 3.1667,
            "lng": 101.7,
            "country": "Malaysia",
            "iso2": "MY",
            "iso3": "MYS",
            "admin_name": "Kuala Lumpur",
            "capital": "primary",
            "population": 1448000,
            "id": 1458988644
        },
        {
            "city": "Maputo",
            "city_ascii": "Maputo",
            "lat": -25.9553,
            "lng": 32.5892,
            "country": "Mozambique",
            "iso2": "MZ",
            "iso3": "MOZ",
            "admin_name": "Maputo",
            "capital": "primary",
            "population": 1446000,
            "id": 1508074843
        },
        {
            "city": "San Salvador",
            "city_ascii": "San Salvador",
            "lat": 13.71,
            "lng": -89.203,
            "country": "El Salvador",
            "iso2": "SV",
            "iso3": "SLV",
            "admin_name": "San Salvador",
            "capital": "primary",
            "population": 1433000,
            "id": 1222647454
        },
        {
            "city": "Kampala",
            "city_ascii": "Kampala",
            "lat": 0.3167,
            "lng": 32.5833,
            "country": "Uganda",
            "iso2": "UG",
            "iso3": "UGA",
            "admin_name": "Kampala",
            "capital": "primary",
            "population": 1420000,
            "id": 1800406299
        },
        {
            "city": "Brazzaville",
            "city_ascii": "Brazzaville",
            "lat": -4.2592,
            "lng": 15.2847,
            "country": "Congo (Brazzaville)",
            "iso2": "CG",
            "iso3": "COG",
            "admin_name": "Brazzaville",
            "capital": "primary",
            "population": 1355000,
            "id": 1178340306
        },
        {
            "city": "Pretoria",
            "city_ascii": "Pretoria",
            "lat": -25.7069,
            "lng": 28.2294,
            "country": "South Africa",
            "iso2": "ZA",
            "iso3": "ZAF",
            "admin_name": "Gauteng",
            "capital": "primary",
            "population": 1338000,
            "id": 1710176249
        },
        {
            "city": "Lusaka",
            "city_ascii": "Lusaka",
            "lat": -15.4166,
            "lng": 28.2833,
            "country": "Zambia",
            "iso2": "ZM",
            "iso3": "ZMB",
            "admin_name": "Lusaka",
            "capital": "primary",
            "population": 1328000,
            "id": 1894157390
        },
        {
            "city": "San Jos\u00e9",
            "city_ascii": "San Jose",
            "lat": 9.935,
            "lng": -84.0841,
            "country": "Costa Rica",
            "iso2": "CR",
            "iso3": "CRI",
            "admin_name": "San Jos\u00e9",
            "capital": "primary",
            "population": 1284000,
            "id": 1188749877
        },
        {
            "city": "Panama City",
            "city_ascii": "Panama City",
            "lat": 8.968,
            "lng": -79.533,
            "country": "Panama",
            "iso2": "PA",
            "iso3": "PAN",
            "admin_name": "Panam\u00e1",
            "capital": "primary",
            "population": 1281000,
            "id": 1591672475
        },
        {
            "city": "Stockholm",
            "city_ascii": "Stockholm",
            "lat": 59.3508,
            "lng": 18.0973,
            "country": "Sweden",
            "iso2": "SE",
            "iso3": "SWE",
            "admin_name": "Stockholm",
            "capital": "primary",
            "population": 1264000,
            "id": 1752425602
        },
        {
            "city": "Sofia",
            "city_ascii": "Sofia",
            "lat": 42.6833,
            "lng": 23.3167,
            "country": "Bulgaria",
            "iso2": "BG",
            "iso3": "BGR",
            "admin_name": "Sofia-Grad",
            "capital": "primary",
            "population": 1185000,
            "id": 1100762037
        },
        {
            "city": "Prague",
            "city_ascii": "Prague",
            "lat": 50.0833,
            "lng": 14.466,
            "country": "Czechia",
            "iso2": "CZ",
            "iso3": "CZE",
            "admin_name": "Praha, Hlavn\u00ed M\u011bsto",
            "capital": "primary",
            "population": 1162000,
            "id": 1203744823
        },
        {
            "city": "Ouagadougou",
            "city_ascii": "Ouagadougou",
            "lat": 12.3703,
            "lng": -1.5247,
            "country": "Burkina Faso",
            "iso2": "BF",
            "iso3": "BFA",
            "admin_name": "Centre",
            "capital": "primary",
            "population": 1149000,
            "id": 1854029208
        },
        {
            "city": "Ottawa",
            "city_ascii": "Ottawa",
            "lat": 45.4167,
            "lng": -75.7,
            "country": "Canada",
            "iso2": "CA",
            "iso3": "CAN",
            "admin_name": "Ontario",
            "capital": "primary",
            "population": 1145000,
            "id": 1124399363
        },
        {
            "city": "Helsinki",
            "city_ascii": "Helsinki",
            "lat": 60.1756,
            "lng": 24.9341,
            "country": "Finland",
            "iso2": "FI",
            "iso3": "FIN",
            "admin_name": "Uusimaa",
            "capital": "primary",
            "population": 1115000,
            "id": 1246177997
        },
        {
            "city": "Yerevan",
            "city_ascii": "Yerevan",
            "lat": 40.1812,
            "lng": 44.5136,
            "country": "Armenia",
            "iso2": "AM",
            "iso3": "ARM",
            "admin_name": "Yerevan",
            "capital": "primary",
            "population": 1102000,
            "id": 1051074169
        },
        {
            "city": "Mogadishu",
            "city_ascii": "Mogadishu",
            "lat": 2.0667,
            "lng": 45.3667,
            "country": "Somalia",
            "iso2": "SO",
            "iso3": "SOM",
            "admin_name": "Banaadir",
            "capital": "primary",
            "population": 1100000,
            "id": 1706893395
        },
        {
            "city": "Tbilisi",
            "city_ascii": "Tbilisi",
            "lat": 41.725,
            "lng": 44.7908,
            "country": "Georgia",
            "iso2": "GE",
            "iso3": "GEO",
            "admin_name": "Tbilisi",
            "capital": "primary",
            "population": 1100000,
            "id": 1268203191
        },
        {
            "city": "Belgrade",
            "city_ascii": "Belgrade",
            "lat": 44.8186,
            "lng": 20.468,
            "country": "Serbia",
            "iso2": "RS",
            "iso3": "SRB",
            "admin_name": "Beograd",
            "capital": "primary",
            "population": 1099000,
            "id": 1688374696
        },
        {
            "city": "Dushanbe",
            "city_ascii": "Dushanbe",
            "lat": 38.56,
            "lng": 68.7739,
            "country": "Tajikistan",
            "iso2": "TJ",
            "iso3": "TJK",
            "admin_name": "Dushanbe",
            "capital": "primary",
            "population": 1086244,
            "id": 1762930616
        },
        {
            "city": "Copenhagen",
            "city_ascii": "Copenhagen",
            "lat": 55.6786,
            "lng": 12.5635,
            "country": "Denmark",
            "iso2": "DK",
            "iso3": "DNK",
            "admin_name": "Hovedstaden",
            "capital": "primary",
            "population": 1085000,
            "id": 1208763942
        },
        {
            "city": "Amman",
            "city_ascii": "Amman",
            "lat": 31.95,
            "lng": 35.9333,
            "country": "Jordan",
            "iso2": "JO",
            "iso3": "JOR",
            "admin_name": "Al \u2018\u0100\u015fimah",
            "capital": "primary",
            "population": 1060000,
            "id": 1400522593
        },
        {
            "city": "Dublin",
            "city_ascii": "Dublin",
            "lat": 53.3331,
            "lng": -6.2489,
            "country": "Ireland",
            "iso2": "IE",
            "iso3": "IRL",
            "admin_name": "Dublin",
            "capital": "primary",
            "population": 1059000,
            "id": 1372595407
        },
        {
            "city": "Monrovia",
            "city_ascii": "Monrovia",
            "lat": 6.3106,
            "lng": -10.8048,
            "country": "Liberia",
            "iso2": "LR",
            "iso3": "LBR",
            "admin_name": "Montserrado",
            "capital": "primary",
            "population": 1041000,
            "id": 1430477826
        },
        {
            "city": "Amsterdam",
            "city_ascii": "Amsterdam",
            "lat": 52.35,
            "lng": 4.9166,
            "country": "Netherlands",
            "iso2": "NL",
            "iso3": "NLD",
            "admin_name": "Noord-Holland",
            "capital": "primary",
            "population": 1031000,
            "id": 1528355309
        },
        {
            "city": "Jerusalem",
            "city_ascii": "Jerusalem",
            "lat": 31.7784,
            "lng": 35.2066,
            "country": "Israel",
            "iso2": "IL",
            "iso3": "ISR",
            "admin_name": "",
            "capital": "primary",
            "population": 1029300,
            "id": 1376261644
        },
        {
            "city": "Guatemala City",
            "city_ascii": "Guatemala City",
            "lat": 14.6211,
            "lng": -90.527,
            "country": "Guatemala",
            "iso2": "GT",
            "iso3": "GTM",
            "admin_name": "Guatemala",
            "capital": "primary",
            "population": 1024000,
            "id": 1320197916
        },
        {
            "city": "N\u2019Djamena",
            "city_ascii": "N'Djamena",
            "lat": 12.1131,
            "lng": 15.0491,
            "country": "Chad",
            "iso2": "TD",
            "iso3": "TCD",
            "admin_name": "Ville de N\u2019Djam\u00e9na",
            "capital": "primary",
            "population": 989000,
            "id": 1148708596
        },
        {
            "city": "Tegucigalpa",
            "city_ascii": "Tegucigalpa",
            "lat": 14.102,
            "lng": -87.2175,
            "country": "Honduras",
            "iso2": "HN",
            "iso3": "HND",
            "admin_name": "Francisco Moraz\u00e1n",
            "capital": "primary",
            "population": 946000,
            "id": 1340344059
        },
        {
            "city": "Kingston",
            "city_ascii": "Kingston",
            "lat": 17.9771,
            "lng": -76.7674,
            "country": "Jamaica",
            "iso2": "JM",
            "iso3": "JAM",
            "admin_name": "Kingston",
            "capital": "primary",
            "population": 937700,
            "id": 1388709177
        },
        {
            "city": "Nay Pyi Taw",
            "city_ascii": "Nay Pyi Taw",
            "lat": 19.7666,
            "lng": 96.1186,
            "country": "Myanmar",
            "iso2": "MM",
            "iso3": "MMR",
            "admin_name": "Nay Pyi Taw",
            "capital": "primary",
            "population": 930000,
            "id": 1104838105
        },
        {
            "city": "Djibouti",
            "city_ascii": "Djibouti",
            "lat": 11.595,
            "lng": 43.148,
            "country": "Djibouti",
            "iso2": "DJ",
            "iso3": "DJI",
            "admin_name": "Djibouti",
            "capital": "primary",
            "population": 923000,
            "id": 1262028958
        },
        {
            "city": "Managua",
            "city_ascii": "Managua",
            "lat": 12.153,
            "lng": -86.2685,
            "country": "Nicaragua",
            "iso2": "NI",
            "iso3": "NIC",
            "admin_name": "Managua",
            "capital": "primary",
            "population": 920000,
            "id": 1558296252
        },
        {
            "city": "Niamey",
            "city_ascii": "Niamey",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Niamey_harobanda.jpg",
            "lat": 13.5167,
            "lng": 2.1167,
            "country": "Niger",
            "iso2": "NE",
            "iso3": "NER",
            "admin_name": "Niamey",
            "capital": "primary",
            "population": 915000,
            "id": 1562932886
        },
        {
            "city": "Tirana",
            "city_ascii": "Tirana",
            "lat": 41.3275,
            "lng": 19.8189,
            "country": "Albania",
            "iso2": "AL",
            "iso3": "ALB",
            "admin_name": "Tiran\u00eb",
            "capital": "primary",
            "population": 895350,
            "id": 1008162156
        },
        {
            "city": "Kathmandu",
            "city_ascii": "Kathmandu",
            "lat": 27.7167,
            "lng": 85.3166,
            "country": "Nepal",
            "iso2": "NP",
            "iso3": "NPL",
            "admin_name": "B\u0101gmat\u012b",
            "capital": "primary",
            "population": 895000,
            "id": 1524589448
        },
        {
            "city": "Ulaanbaatar",
            "city_ascii": "Ulaanbaatar",
            "lat": 47.9167,
            "lng": 106.9166,
            "country": "Mongolia",
            "iso2": "MN",
            "iso3": "MNG",
            "admin_name": "Ulaanbaatar",
            "capital": "primary",
            "population": 885000,
            "id": 1496024767
        },
        {
            "city": "Kigali",
            "city_ascii": "Kigali",
            "lat": -1.9536,
            "lng": 30.0605,
            "country": "Rwanda",
            "iso2": "RW",
            "iso3": "RWA",
            "admin_name": "Kigali",
            "capital": "primary",
            "population": 860000,
            "id": 1646923541
        },
        {
            "city": "Bishkek",
            "city_ascii": "Bishkek",
            "lat": 42.8731,
            "lng": 74.5852,
            "country": "Kyrgyzstan",
            "iso2": "KG",
            "iso3": "KGZ",
            "admin_name": "Bishkek",
            "capital": "primary",
            "population": 837000,
            "id": 1417191971
        },
        {
            "city": "Oslo",
            "city_ascii": "Oslo",
            "lat": 59.9167,
            "lng": 10.75,
            "country": "Norway",
            "iso2": "NO",
            "iso3": "NOR",
            "admin_name": "Oslo",
            "capital": "primary",
            "population": 835000,
            "id": 1578324706
        },
        {
            "city": "Bangui",
            "city_ascii": "Bangui",
            "lat": 4.3666,
            "lng": 18.5583,
            "country": "Central African Republic",
            "iso2": "CF",
            "iso3": "CAF",
            "admin_name": "Bangui",
            "capital": "primary",
            "population": 831925,
            "id": 1140080881
        },
        {
            "city": "Freetown",
            "city_ascii": "Freetown",
            "lat": 8.47,
            "lng": -13.2342,
            "country": "Sierra Leone",
            "iso2": "SL",
            "iso3": "SLE",
            "admin_name": "Western Area",
            "capital": "primary",
            "population": 827000,
            "id": 1694085071
        },
        {
            "city": "Islamabad",
            "city_ascii": "Islamabad",
            "lat": 33.7,
            "lng": 73.1666,
            "country": "Pakistan",
            "iso2": "PK",
            "iso3": "PAK",
            "admin_name": "Isl\u0101m\u0101b\u0101d",
            "capital": "primary",
            "population": 780000,
            "id": 1586306717
        },
        {
            "city": "Vientiane",
            "city_ascii": "Vientiane",
            "lat": 17.9667,
            "lng": 102.6,
            "country": "Laos",
            "iso2": "LA",
            "iso3": "LAO",
            "admin_name": "Viangchan",
            "capital": "primary",
            "population": 754000,
            "id": 1418732714
        },
        {
            "city": "Riga",
            "city_ascii": "Riga",
            "lat": 56.95,
            "lng": 24.1,
            "country": "Latvia",
            "iso2": "LV",
            "iso3": "LVA",
            "admin_name": "R\u012bga",
            "capital": "primary",
            "population": 742572,
            "id": 1428586192
        },
        {
            "city": "Nouakchott",
            "city_ascii": "Nouakchott",
            "lat": 18.0864,
            "lng": -15.9753,
            "country": "Mauritania",
            "iso2": "MR",
            "iso3": "MRT",
            "admin_name": "",
            "capital": "primary",
            "population": 742144,
            "id": 1478414984
        },
        {
            "city": "Muscat",
            "city_ascii": "Muscat",
            "lat": 23.6133,
            "lng": 58.5933,
            "country": "Oman",
            "iso2": "OM",
            "iso3": "OMN",
            "admin_name": "Masqa\u0163",
            "capital": "primary",
            "population": 734697,
            "id": 1512035506
        },
        {
            "city": "Ashgabat",
            "city_ascii": "Ashgabat",
            "lat": 37.95,
            "lng": 58.3833,
            "country": "Turkmenistan",
            "iso2": "TM",
            "iso3": "TKM",
            "admin_name": "",
            "capital": "primary",
            "population": 727700,
            "id": 1795049992
        },
        {
            "city": "Zagreb",
            "city_ascii": "Zagreb",
            "lat": 45.8,
            "lng": 16,
            "country": "Croatia",
            "iso2": "HR",
            "iso3": "HRV",
            "admin_name": "Zagreb, Grad",
            "capital": "primary",
            "population": 722526,
            "id": 1191233290
        },
        {
            "city": "Sarajevo",
            "city_ascii": "Sarajevo",
            "lat": 43.85,
            "lng": 18.383,
            "country": "Bosnia And Herzegovina",
            "iso2": "BA",
            "iso3": "BIH",
            "admin_name": "Bosnia and Herzegovina, Federation of",
            "capital": "primary",
            "population": 696731,
            "id": 1070966777
        },
        {
            "city": "Chisinau",
            "city_ascii": "Chisinau",
            "lat": 47.005,
            "lng": 28.8577,
            "country": "Moldova",
            "iso2": "MD",
            "iso3": "MDA",
            "admin_name": "Chi\u015fin\u0103u",
            "capital": "primary",
            "population": 688134,
            "id": 1498011437
        },
        {
            "city": "Lilongwe",
            "city_ascii": "Lilongwe",
            "lat": -13.9833,
            "lng": 33.7833,
            "country": "Malawi",
            "iso2": "MW",
            "iso3": "MWI",
            "admin_name": "Lilongwe",
            "capital": "primary",
            "population": 646750,
            "id": 1454688499
        },
        {
            "city": "Asmara",
            "city_ascii": "Asmara",
            "lat": 15.3333,
            "lng": 38.9333,
            "country": "Eritrea",
            "iso2": "ER",
            "iso3": "ERI",
            "admin_name": "Ma\u2019\u0101kel",
            "capital": "primary",
            "population": 620802,
            "id": 1232791236
        },
        {
            "city": "Abu Dhabi",
            "city_ascii": "Abu Dhabi",
            "lat": 24.4667,
            "lng": 54.3666,
            "country": "United Arab Emirates",
            "iso2": "AE",
            "iso3": "ARE",
            "admin_name": "Ab\u016b Z\u0327aby",
            "capital": "primary",
            "population": 603492,
            "id": 1784176710
        },
        {
            "city": "Port Louis",
            "city_ascii": "Port Louis",
            "lat": -20.1666,
            "lng": 57.5,
            "country": "Mauritius",
            "iso2": "MU",
            "iso3": "MUS",
            "admin_name": "Port Louis",
            "capital": "primary",
            "population": 595491,
            "id": 1480131261
        },
        {
            "city": "Libreville",
            "city_ascii": "Libreville",
            "lat": 0.3854,
            "lng": 9.458,
            "country": "Gabon",
            "iso2": "GA",
            "iso3": "GAB",
            "admin_name": "Estuaire",
            "capital": "primary",
            "population": 578156,
            "id": 1266952885
        },
        {
            "city": "Manama",
            "city_ascii": "Manama",
            "lat": 26.2361,
            "lng": 50.5831,
            "country": "Bahrain",
            "iso2": "BH",
            "iso3": "BHR",
            "admin_name": "Al \u2018\u0100\u015fimah",
            "capital": "primary",
            "population": 563920,
            "id": 1048989486
        },
        {
            "city": "Vilnius",
            "city_ascii": "Vilnius",
            "lat": 54.6834,
            "lng": 25.3166,
            "country": "Lithuania",
            "iso2": "LT",
            "iso3": "LTU",
            "admin_name": "Vilniaus Miestas",
            "capital": "primary",
            "population": 542366,
            "id": 1440887149
        },
        {
            "city": "Skopje",
            "city_ascii": "Skopje",
            "lat": 42,
            "lng": 21.4335,
            "country": "Macedonia",
            "iso2": "MK",
            "iso3": "MKD",
            "admin_name": "Skopje",
            "capital": "primary",
            "population": 494087,
            "id": 1807600615
        },
        {
            "city": "Bloemfontein",
            "city_ascii": "Bloemfontein",
            "lat": -29.12,
            "lng": 26.2299,
            "country": "South Africa",
            "iso2": "ZA",
            "iso3": "ZAF",
            "admin_name": "Free State",
            "capital": "primary",
            "population": 463064,
            "id": 1710495933
        },
        {
            "city": "Bratislava",
            "city_ascii": "Bratislava",
            "lat": 48.15,
            "lng": 17.117,
            "country": "Slovakia",
            "iso2": "SK",
            "iso3": "SVK",
            "admin_name": "Bratislavsk\u00fd",
            "capital": "primary",
            "population": 423737,
            "id": 1703195001
        },
        {
            "city": "Bissau",
            "city_ascii": "Bissau",
            "lat": 11.865,
            "lng": -15.5984,
            "country": "Guinea-Bissau",
            "iso2": "GW",
            "iso3": "GNB",
            "admin_name": "Bissau",
            "capital": "primary",
            "population": 403339,
            "id": 1624168850
        },
        {
            "city": "Tallinn",
            "city_ascii": "Tallinn",
            "lat": 59.4339,
            "lng": 24.728,
            "country": "Estonia",
            "iso2": "EE",
            "iso3": "EST",
            "admin_name": "Harjumaa",
            "capital": "primary",
            "population": 394024,
            "id": 1233260021
        },
        {
            "city": "Wellington",
            "city_ascii": "Wellington",
            "lat": -41.3,
            "lng": 174.7833,
            "country": "New Zealand",
            "iso2": "NZ",
            "iso3": "NZL",
            "admin_name": "Wellington",
            "capital": "primary",
            "population": 393400,
            "id": 1554772152
        },
        {
            "city": "Valletta",
            "city_ascii": "Valletta",
            "lat": 35.8997,
            "lng": 14.5147,
            "country": "Malta",
            "iso2": "MT",
            "iso3": "MLT",
            "admin_name": "Valletta",
            "capital": "primary",
            "population": 368250,
            "id": 1470574399
        },
        {
            "city": "Maseru",
            "city_ascii": "Maseru",
            "lat": -29.3167,
            "lng": 27.4833,
            "country": "Lesotho",
            "iso2": "LS",
            "iso3": "LSO",
            "admin_name": "Maseru",
            "capital": "primary",
            "population": 361324,
            "id": 1426977668
        },
        {
            "city": "Nur-Sultan",
            "city_ascii": "Nur-Sultan",
            "lat": 51.1811,
            "lng": 71.4278,
            "country": "Kazakhstan",
            "iso2": "KZ",
            "iso3": "KAZ",
            "admin_name": "Astana",
            "capital": "primary",
            "population": 345604,
            "id": 1398516045
        },
        {
            "city": "Canberra",
            "city_ascii": "Canberra",
            "lat": -35.283,
            "lng": 149.129,
            "country": "Australia",
            "iso2": "AU",
            "iso3": "AUS",
            "admin_name": "Australian Capital Territory",
            "capital": "primary",
            "population": 327700,
            "id": 1036142029
        },
        {
            "city": "New Delhi",
            "city_ascii": "New Delhi",
            "lat": 28.6,
            "lng": 77.2,
            "country": "India",
            "iso2": "IN",
            "iso3": "IND",
            "admin_name": "Delhi",
            "capital": "primary",
            "population": 317797,
            "id": 1356215164
        },
        {
            "city": "Ljubljana",
            "city_ascii": "Ljubljana",
            "lat": 46.0553,
            "lng": 14.515,
            "country": "Slovenia",
            "iso2": "SI",
            "iso3": "SVN",
            "admin_name": "Ljubljana",
            "capital": "primary",
            "population": 314807,
            "id": 1705917455
        },
        {
            "city": "Porto-Novo",
            "city_ascii": "Porto-Novo",
            "lat": 6.4833,
            "lng": 2.6166,
            "country": "Benin",
            "iso2": "BJ",
            "iso3": "BEN",
            "admin_name": "Ou\u00e9m\u00e9",
            "capital": "primary",
            "population": 300000,
            "id": 1204172060
        },
        {
            "city": "Bandar Seri Begawan",
            "city_ascii": "Bandar Seri Begawan",
            "lat": 4.8833,
            "lng": 114.9333,
            "country": "Brunei",
            "iso2": "BN",
            "iso3": "BRN",
            "admin_name": "Brunei and Muara",
            "capital": "primary",
            "population": 296500,
            "id": 1096465895
        },
        {
            "city": "Port of Spain",
            "city_ascii": "Port of Spain",
            "lat": 10.652,
            "lng": -61.517,
            "country": "Trinidad And Tobago",
            "iso2": "TT",
            "iso3": "TTO",
            "admin_name": "Port of Spain",
            "capital": "primary",
            "population": 294934,
            "id": 1780670676
        },
        {
            "city": "Port Moresby",
            "city_ascii": "Port Moresby",
            "lat": -9.4647,
            "lng": 147.1925,
            "country": "Papua New Guinea",
            "iso2": "PG",
            "iso3": "PNG",
            "admin_name": "National Capital",
            "capital": "primary",
            "population": 283733,
            "id": 1598685395
        },
        {
            "city": "Bern",
            "city_ascii": "Bern",
            "lat": 46.9167,
            "lng": 7.467,
            "country": "Switzerland",
            "iso2": "CH",
            "iso3": "CHE",
            "admin_name": "Bern",
            "capital": "primary",
            "population": 275329,
            "id": 1756374318
        },
        {
            "city": "Windhoek",
            "city_ascii": "Windhoek",
            "lat": -22.57,
            "lng": 17.0835,
            "country": "Namibia",
            "iso2": "NA",
            "iso3": "NAM",
            "admin_name": "Khomas",
            "capital": "primary",
            "population": 268132,
            "id": 1516802003
        },
        {
            "city": "Georgetown",
            "city_ascii": "Georgetown",
            "lat": 6.802,
            "lng": -58.167,
            "country": "Guyana",
            "iso2": "GY",
            "iso3": "GUY",
            "admin_name": "Demerara-Mahaica",
            "capital": "primary",
            "population": 264350,
            "id": 1328160906
        },
        {
            "city": "Paramaribo",
            "city_ascii": "Paramaribo",
            "lat": 5.835,
            "lng": -55.167,
            "country": "Suriname",
            "iso2": "SR",
            "iso3": "SUR",
            "admin_name": "Paramaribo",
            "capital": "primary",
            "population": 254169,
            "id": 1740518660
        },
        {
            "city": "Dili",
            "city_ascii": "Dili",
            "lat": -8.5594,
            "lng": 125.5795,
            "country": "Timor-Leste",
            "iso2": "TL",
            "iso3": "TLS",
            "admin_name": "D\u00edli",
            "capital": "primary",
            "population": 234331,
            "id": 1626308942
        },
        {
            "city": "Nassau",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Nassau%2C_Bahamas_welcome_gateway.JPG/1280px-Nassau%2C_Bahamas_welcome_gateway.JPG",
            "city_ascii": "Nassau",
            "lat": 25.0834,
            "lng": -77.35,
            "country": "Bahamas, The",
            "iso2": "BS",
            "iso3": "BHS",
            "admin_name": "",
            "capital": "primary",
            "population": 227940,
            "id": 1044318561
        },
        {
            "city": "Sucre",
            "city_ascii": "Sucre",
            "lat": -19.041,
            "lng": -65.2595,
            "country": "Bolivia",
            "iso2": "BO",
            "iso3": "BOL",
            "admin_name": "Chuquisaca",
            "capital": "primary",
            "population": 224838,
            "id": 1068823873
        },
        {
            "city": "Nicosia",
            "city_ascii": "Nicosia",
            "lat": 35.1667,
            "lng": 33.3666,
            "country": "Cyprus",
            "iso2": "CY",
            "iso3": "CYP",
            "admin_name": "Lefkos\u00eda",
            "capital": "primary",
            "population": 224300,
            "id": 1196944155
        },
        {
            "city": "Dodoma",
            "city_ascii": "Dodoma",
            "lat": -6.1833,
            "lng": 35.75,
            "country": "Tanzania",
            "iso2": "TZ",
            "iso3": "TZA",
            "admin_name": "Dodoma",
            "capital": "primary",
            "population": 218269,
            "id": 1834288497
        },
        {
            "city": "Colombo",
            "city_ascii": "Colombo",
            "lat": 6.932,
            "lng": 79.8578,
            "country": "Sri Lanka",
            "iso2": "LK",
            "iso3": "LKA",
            "admin_name": "Western",
            "capital": "primary",
            "population": 217000,
            "id": 1144251314
        },
        {
            "city": "Gaborone",
            "city_ascii": "Gaborone",
            "lat": -24.6463,
            "lng": 25.9119,
            "country": "Botswana",
            "iso2": "BW",
            "iso3": "BWA",
            "admin_name": "Gaborone",
            "capital": "primary",
            "population": 208411,
            "id": 1072756768
        },
        {
            "city": "Yamoussoukro",
            "city_ascii": "Yamoussoukro",
            "lat": 6.8184,
            "lng": -5.2755,
            "country": "C\u00f4te D\u2019Ivoire",
            "iso2": "CI",
            "iso3": "CIV",
            "admin_name": "Yamoussoukro",
            "capital": "primary",
            "population": 206499,
            "id": 1384683557
        },
        {
            "city": "Bridgetown",
            "city_ascii": "Bridgetown",
            "lat": 13.102,
            "lng": -59.6165,
            "country": "Barbados",
            "iso2": "BB",
            "iso3": "BRB",
            "admin_name": "Saint Michael",
            "capital": "primary",
            "population": 191152,
            "id": 1052274244
        },
        {
            "city": "Suva",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Suva%2C_Fiji_52.jpg/1920px-Suva%2C_Fiji_52.jpg",
            "city_ascii": "Suva",
            "lat": -18.133,
            "lng": 178.4417,
            "country": "Fiji",
            "iso2": "FJ",
            "iso3": "FJI",
            "admin_name": "Rewa",
            "capital": "primary",
            "population": 175399,
            "id": 1242615095
        },
        {
            "city": "Reykjav\u00edk",
            "city_ascii": "Reykjavik",
            "lat": 64.15,
            "lng": -21.95,
            "country": "Iceland",
            "iso2": "IS",
            "iso3": "ISL",
            "admin_name": "H\u00f6fu\u00f0borgarsv\u00e6\u00f0i",
            "capital": "primary",
            "population": 166212,
            "id": 1352327190
        },
        {
            "city": "Malabo",
            "city_ascii": "Malabo",
            "lat": 3.75,
            "lng": 8.7833,
            "country": "Equatorial Guinea",
            "iso2": "GQ",
            "iso3": "GNQ",
            "admin_name": "Bioko Norte",
            "capital": "primary",
            "population": 155963,
            "id": 1226861333
        },
        {
            "city": "Willemstad",
            "city_ascii": "Willemstad",
            "lat": 12.2004,
            "lng": -69.02,
            "country": "Cura\u00e7ao",
            "iso2": "CW",
            "iso3": "CUW",
            "admin_name": "",
            "capital": "primary",
            "population": 146813,
            "id": 1531000000
        },
        {
            "city": "Podgorica",
            "city_ascii": "Podgorica",
            "lat": 42.466,
            "lng": 19.2663,
            "country": "Montenegro",
            "iso2": "ME",
            "iso3": "MNE",
            "admin_name": "Podgorica",
            "capital": "primary",
            "population": 145850,
            "id": 1499454516
        },
        {
            "city": "Moroni",
            "city_ascii": "Moroni",
            "lat": -11.7042,
            "lng": 43.2402,
            "country": "Comoros",
            "iso2": "KM",
            "iso3": "COM",
            "admin_name": "Grande Comore",
            "capital": "primary",
            "population": 128698,
            "id": 1174793581
        },
        {
            "city": "Sri Jayewardenepura Kotte",
            "city_ascii": "Sri Jayewardenepura Kotte",
            "lat": 6.9,
            "lng": 79.95,
            "country": "Sri Lanka",
            "iso2": "LK",
            "iso3": "LKA",
            "admin_name": "Western",
            "capital": "primary",
            "population": 115826,
            "id": 1144239330
        },
        {
            "city": "Praia",
            "city_ascii": "Praia",
            "lat": 14.9167,
            "lng": -23.5167,
            "country": "Cabo Verde",
            "iso2": "CV",
            "iso3": "CPV",
            "admin_name": "Praia",
            "capital": "primary",
            "population": 113364,
            "id": 1132398770
        },
        {
            "city": "Male",
            "city_ascii": "Male",
            "lat": 4.1667,
            "lng": 73.4999,
            "country": "Maldives",
            "iso2": "MV",
            "iso3": "MDV",
            "admin_name": "Maale",
            "capital": "primary",
            "population": 112927,
            "id": 1462441685
        },
        {
            "city": "Juba",
            "city_ascii": "Juba",
            "lat": 4.83,
            "lng": 31.58,
            "country": "South Sudan",
            "iso2": "SS",
            "iso3": "SSD",
            "admin_name": "Central Equatoria",
            "capital": "primary",
            "population": 111975,
            "id": 1728444337
        },
        {
            "city": "Luxembourg",
            "city_ascii": "Luxembourg",
            "lat": 49.6117,
            "lng": 6.13,
            "country": "Luxembourg",
            "iso2": "LU",
            "iso3": "LUX",
            "admin_name": "Luxembourg",
            "capital": "primary",
            "population": 107260,
            "id": 1442262731
        },
        {
            "city": "Thimphu",
            "city_ascii": "Thimphu",
            "lat": 27.473,
            "lng": 89.639,
            "country": "Bhutan",
            "iso2": "BT",
            "iso3": "BTN",
            "admin_name": "Thimphu",
            "capital": "primary",
            "population": 98676,
            "id": 1064010361
        },
        {
            "city": "Mbabane",
            "city_ascii": "Mbabane",
            "lat": -26.3167,
            "lng": 31.1333,
            "country": "eSwatini",
            "iso2": "SZ",
            "iso3": "SWZ",
            "admin_name": "Hhohho",
            "capital": "primary",
            "population": 90138,
            "id": 1748811945
        },
        {
            "city": "S\u00e3o Tom\u00e9",
            "city_ascii": "Sao Tome",
            "lat": 0.3334,
            "lng": 6.7333,
            "country": "Sao Tome And Principe",
            "iso2": "ST",
            "iso3": "STP",
            "admin_name": "S\u00e3o Tom\u00e9",
            "capital": "primary",
            "population": 88219,
            "id": 1678301324
        },
        {
            "city": "Honiara",
            "city_ascii": "Honiara",
            "lat": -9.438,
            "lng": 159.9498,
            "country": "Solomon Islands",
            "iso2": "SB",
            "iso3": "SLB",
            "admin_name": "Honiara",
            "capital": "primary",
            "population": 76328,
            "id": 1090737486
        },
        {
            "city": "Oranjestad",
            "city_ascii": "Oranjestad",
            "lat": 12.5304,
            "lng": -70.029,
            "country": "Aruba",
            "iso2": "AW",
            "iso3": "ABW",
            "admin_name": "",
            "capital": "primary",
            "population": 68775,
            "id": 1533513057
        },
        {
            "city": "Apia",
            "city_ascii": "Apia",
            "lat": -13.8415,
            "lng": -171.7386,
            "country": "Samoa",
            "iso2": "WS",
            "iso3": "WSM",
            "admin_name": "Tuamasaga",
            "capital": "primary",
            "population": 61916,
            "id": 1882489296
        },
        {
            "city": "Andorra la Vella",
            "city_ascii": "Andorra la Vella",
            "lat": 42.5,
            "lng": 1.5165,
            "country": "Andorra",
            "iso2": "AD",
            "iso3": "AND",
            "admin_name": "Andorra la Vella",
            "capital": "primary",
            "population": 53998,
            "id": 1020828846
        },
        {
            "city": "Kingstown",
            "city_ascii": "Kingstown",
            "lat": 13.1483,
            "lng": -61.2121,
            "country": "Saint Vincent And The Grenadines",
            "iso2": "VC",
            "iso3": "VCT",
            "admin_name": "Saint George",
            "capital": "primary",
            "population": 49485,
            "id": 1670376659
        },
        {
            "city": "Port-Vila",
            "city_ascii": "Port-Vila",
            "lat": -17.7334,
            "lng": 168.3166,
            "country": "Vanuatu",
            "iso2": "VU",
            "iso3": "VUT",
            "admin_name": "Shefa",
            "capital": "primary",
            "population": 44040,
            "id": 1548805075
        },
        {
            "city": "Banjul",
            "city_ascii": "Banjul",
            "lat": 13.4539,
            "lng": -16.5917,
            "country": "Gambia, The",
            "iso2": "GM",
            "iso3": "GMB",
            "admin_name": "Banjul",
            "capital": "primary",
            "population": 43094,
            "id": 1270723713
        },
        {
            "city": "Nuku\u2018alofa",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Nukualofa_Tonga_2.jpg/250px-Nukualofa_Tonga_2.jpg",
            "city_ascii": "Nuku`alofa",
            "lat": -21.1385,
            "lng": -175.2206,
            "country": "Tonga",
            "iso2": "TO",
            "iso3": "TON",
            "admin_name": "Tongatapu",
            "capital": "primary",
            "population": 42620,
            "id": 1776737461
        },
        {
            "city": "Castries",
            "city_ascii": "Castries",
            "lat": 14.002,
            "lng": -61,
            "country": "Saint Lucia",
            "iso2": "LC",
            "iso3": "LCA",
            "admin_name": "Castries",
            "capital": "primary",
            "population": 37963,
            "id": 1662922505
        },
        {
            "city": "Monaco",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Panorama_von_Monaco-La_Turbie.jpg/1920px-Panorama_von_Monaco-La_Turbie.jpg",
            "city_ascii": "Monaco",
            "lat": 43.7396,
            "lng": 7.4069,
            "country": "Monaco",
            "iso2": "MC",
            "iso3": "MCO",
            "admin_name": "",
            "capital": "primary",
            "population": 36371,
            "id": 1492854256
        },
        {
            "city": "Vaduz",
            "city_ascii": "Vaduz",
            "lat": 47.1337,
            "lng": 9.5167,
            "country": "Liechtenstein",
            "iso2": "LI",
            "iso3": "LIE",
            "admin_name": "Vaduz",
            "capital": "primary",
            "population": 36281,
            "id": 1438317747
        },
        {
            "city": "Saint John\u2019s",
            "city_ascii": "Saint John's",
            "lat": 17.118,
            "lng": -61.85,
            "country": "Antigua And Barbuda",
            "iso2": "AG",
            "iso3": "ATG",
            "admin_name": "Saint John",
            "capital": "primary",
            "population": 35499,
            "id": 1028912067
        },
        {
            "city": "Saint George\u2019s",
            "city_ascii": "Saint George's",
            "lat": 12.0526,
            "lng": -61.7416,
            "country": "Grenada",
            "iso2": "GD",
            "iso3": "GRD",
            "admin_name": "Saint George",
            "capital": "primary",
            "population": 33734,
            "id": 1308891766
        },
        {
            "city": "Victoria",
            "city_ascii": "Victoria",
            "lat": -4.6166,
            "lng": 55.45,
            "country": "Seychelles",
            "iso2": "SC",
            "iso3": "SYC",
            "admin_name": "",
            "capital": "primary",
            "population": 33576,
            "id": 1690193579
        },
        {
            "city": "San Marino",
            "city_ascii": "San Marino",
            "lat": 43.9172,
            "lng": 12.4667,
            "country": "San Marino",
            "iso2": "SM",
            "iso3": "SMR",
            "admin_name": "San Marino Citt\u00e0",
            "capital": "primary",
            "population": 29579,
            "id": 1674741947
        },
        {
            "city": "Tarawa",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Line5304_-_Flickr_-_NOAA_Photo_Library.jpg/1280px-Line5304_-_Flickr_-_NOAA_Photo_Library.jpg",
            "city_ascii": "Tarawa",
            "lat": 1.3382,
            "lng": 173.0176,
            "country": "Kiribati",
            "iso2": "KI",
            "iso3": "KIR",
            "admin_name": "",
            "capital": "primary",
            "population": 28802,
            "id": 1296152641
        },
        {
            "city": "Majuro",
            "city_ascii": "Majuro",
            "lat": 7.103,
            "lng": 171.38,
            "country": "Marshall Islands",
            "iso2": "MH",
            "iso3": "MHL",
            "admin_name": "Majuro",
            "capital": "primary",
            "population": 25400,
            "id": 1584000000
        },
        {
            "city": "Roseau",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/RoseauWide..jpg/300px-RoseauWide..jpg",
            "city_ascii": "Roseau",
            "lat": 15.301,
            "lng": -61.387,
            "country": "Dominica",
            "iso2": "DM",
            "iso3": "DMA",
            "admin_name": "Saint George",
            "capital": "primary",
            "population": 23336,
            "id": 1212060440
        },
        {
            "city": "Basseterre",
            "city_ascii": "Basseterre",
            "lat": 17.302,
            "lng": -62.717,
            "country": "Saint Kitts And Nevis",
            "iso2": "KN",
            "iso3": "KNA",
            "admin_name": "Saint George Basseterre",
            "capital": "primary",
            "population": 21887,
            "id": 1659198919
        },
        {
            "city": "Belmopan",
            "city_ascii": "Belmopan",
            "lat": 17.252,
            "lng": -88.7671,
            "country": "Belize",
            "iso2": "BZ",
            "iso3": "BLZ",
            "admin_name": "Cayo",
            "capital": "primary",
            "population": 15220,
            "id": 1084586375
        },
        {
            "city": "Pago Pago",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/f/f5/Pagopago_amerika_s\u0101moa.jpg",
            "city_ascii": "Pago Pago",
            "lat": -14.274,
            "lng": -170.7046,
            "country": "American Samoa",
            "iso2": "AS",
            "iso3": "ASM",
            "admin_name": "",
            "capital": "primary",
            "population": 12576,
            "id": 1016976740
        },
        {
            "city": "Lobamba",
            "city_ascii": "Lobamba",
            "lat": -26.4667,
            "lng": 31.2,
            "country": "eSwatini",
            "iso2": "SZ",
            "iso3": "SWZ",
            "admin_name": "Hhohho",
            "capital": "primary",
            "population": 9782,
            "id": 1748963140
        },
        {
            "city": "Funafuti",
            "city_ascii": "Funafuti",
            "lat": -8.5167,
            "lng": 179.2166,
            "country": "Tuvalu",
            "iso2": "TV",
            "iso3": "TUV",
            "admin_name": "Funafuti",
            "capital": "primary",
            "population": 4749,
            "id": 1798251391
        },
        {
            "city": "Palikir",
            "city_ascii": "Palikir",
            "lat": 6.9166,
            "lng": 158.15,
            "country": "Micronesia, Federated States Of",
            "iso2": "FM",
            "iso3": "FSM",
            "admin_name": "Pohnpei",
            "capital": "primary",
            "population": 4645,
            "id": 1583008885
        },
        {
            "city": "Capitol Hill",
            "city_ascii": "Capitol Hill",
            "lat": 15.2137,
            "lng": 145.7546,
            "country": "Northern Mariana Islands",
            "iso2": "MP",
            "iso3": "MNP",
            "admin_name": "",
            "capital": "primary",
            "population": 2500,
            "id": 1580556972
        },
        {
            "city": "Hag\u00e5t\u00f1a",
            "city_ascii": "Hagta",
            "lat": 13.4745,
            "lng": 144.7504,
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Hagatna_from_Fort_Santa_Agueda.JPG/250px-Hagatna_from_Fort_Santa_Agueda.JPG",
            "country": "Guam",
            "iso2": "GU",
            "iso3": "GUM",
            "admin_name": "",
            "capital": "primary",
            "population": 1051,
            "id": 1316937540
        },
        {
            "city": "Al Quds",
            "city_ascii": "Al Quds",
            "lat": 31.7764,
            "lng": 35.2269,
            "country": "West Bank",
            "iso2": "XW",
            "iso3": "XWB",
            "admin_name": "",
            "capital": "primary",
            "population": "",
            "id": 1934000006
        },
        {
            "city": "Philipsburg",
            "city_ascii": "Philipsburg",
            "lat": 18.0255,
            "lng": -63.045,
            "country": "Sint Maarten",
            "iso2": "SX",
            "iso3": "SXM",
            "admin_name": "",
            "capital": "primary",
            "population": "",
            "id": 1534859858
        },
        {
            "city": "Gitega",
            "city_ascii": "Gitega",
            "lat": -3.4271,
            "lng": 29.9246,
            "country": "Burundi",
            "iso2": "BI",
            "iso3": "BDI",
            "admin_name": "Gitega",
            "capital": "primary",
            "population": "",
            "id": 1108778000
        },
        {
            "city": "Pristina",
            "city_ascii": "Pristina",
            "lat": 42.6666,
            "lng": 21.1724,
            "country": "Kosovo",
            "iso2": "XK",
            "iso3": "XKS",
            "admin_name": "Prishtin\u00eb",
            "capital": "primary",
            "population": "",
            "id": 1901760068
        },
        {
            "city": "Ngerulmud",
            "city_ascii": "Ngerulmud",
            "lat": 7.5,
            "lng": 134.6242,
            "country": "Palau",
            "iso2": "PW",
            "iso3": "PLW",
            "admin_name": "Melekeok",
            "capital": "primary",
            "population": "",
            "id": 1585525081
        },
        {
            "city": "Macau",
            "city_ascii": "Macau",
            "lat": 22.203,
            "lng": 113.545,
            "country": "Macau",
            "iso2": "MO",
            "iso3": "MAC",
            "admin_name": "",
            "capital": "",
            "population": 568700,
            "id": 1446227359
        },
        {
            "city": "Gibraltar",
            "city_ascii": "Gibraltar",
            "lat": 36.1324,
            "lng": -5.3781,
            "country": "Gibraltar",
            "iso2": "GI",
            "iso3": "GIB",
            "admin_name": "",
            "capital": "",
            "population": 187083,
            "id": 1292385245
        },
        {
            "city": "Papeete",
            "city_ascii": "Papeete",
            "lat": -17.5334,
            "lng": -149.5667,
            "country": "French Polynesia",
            "iso2": "PF",
            "iso3": "PYF",
            "admin_name": "\u00celes du Vent",
            "capital": "",
            "population": 131695,
            "id": 1258907380
        },
        {
            "city": "Noum\u00e9a",
            "city_ascii": "Noumea",
            "lat": -22.2625,
            "lng": 166.4443,
            "country": "New Caledonia",
            "iso2": "NC",
            "iso3": "NCL",
            "admin_name": "Province Sud",
            "capital": "primary",
            "population": 93060,
            "id": 1540958092
        },
        {
            "city": "Hamilton",
            "city_ascii": "Hamilton",
            "lat": 32.2942,
            "lng": -64.7839,
            "country": "Bermuda",
            "iso2": "BM",
            "iso3": "BMU",
            "admin_name": "Hamilton",
            "capital": "",
            "population": 52320,
            "id": 1060000000
        },
        {
            "city": "Nuuk",
            "city_ascii": "Nuuk",
            "lat": 64.1983,
            "lng": -51.7327,
            "country": "Greenland",
            "iso2": "GL",
            "iso3": "GRL",
            "admin_name": "Sermersooq",
            "capital": "primary",
            "population": 14798,
            "id": 1304028354
        },
        {
            "city": "Grand Turk",
            "city_ascii": "Grand Turk",
            "lat": 21.4664,
            "lng": -71.136,
            "country": "Turks And Caicos Islands",
            "iso2": "TC",
            "iso3": "TCA",
            "admin_name": "",
            "capital": "",
            "population": 5801,
            "id": 1796965313
        },
        {
            "city": "George Town",
            "city_ascii": "George Town",
            "lat": 19.2804,
            "lng": -81.33,
            "country": "Cayman Islands",
            "iso2": "KY",
            "iso3": "CYM",
            "admin_name": "",
            "capital": "primary",
            "population": 4268,
            "id": 1136159124
        },
        {
            "city": "Avarua",
            "city_ascii": "Avarua",
            "lat": -21.25,
            "lng": -159.75,
            "country": "Cook Islands",
            "iso2": "CK",
            "iso3": "COK",
            "admin_name": "",
            "capital": "",
            "population": 5445,
            "id": 1184217570
        },
        {
            "city": "Stanley",
            "city_ascii": "Stanley",
            "lat": -51.7,
            "lng": -57.85,
            "country": "Falkland Islands (Islas Malvinas)",
            "iso2": "FK",
            "iso3": "FLK",
            "admin_name": "",
            "capital": "",
            "population": 2213,
            "id": 1238780509
        },
        {
            "city": "Adamstown",
            "city_ascii": "Adamstown",
            "lat": -25.066667,
            "lng": -130.1,
            "country": "Pitcairn Islands",
            "iso2": "PN",
            "admin_name": "",
            "capital": "primary",
            "population": 50,
            "id": 9999999998
        },
        {
            "city": "Alofi",
            "city_ascii": "Alofi",
            "lat": -19.054,
            "lng": -169.92,
            "country": "Niue",
            "iso2": "NU",
            "admin_name": "",
            "capital": "primary",
            "population": 50,
            "id": 9999999997
        },
        {
            "city": "Flying Fish Cove",
            "img_link": "https://upload.wikimedia.org/wikipedia/commons/7/7e/Flying_Fish_Cove.jpg",
            "city_ascii": "Flying Fish Cove",
            "lat": -10.421667,
            "lng": 105.678056,
            "country": "Christmas Island",
            "iso2": "CX",
            "admin_name": "",
            "capital": "primary",
            "population": 1600,
            "id": 9999999996
        },
        {
            "city": "Kingston",
            "city_ascii": "Kingston",
            "lat": -29.05,
            "lng": 167.966667,
            "country": "Norfolk Island",
            "iso2": "NF",
            "admin_name": "",
            "capital": "primary",
            "population": 1748,
            "id": 9999999990
        },
        {
            "city": "West Island",
            "city_ascii": "West Island",
            "lat": -12.186944,
            "lng": 96.828333,
            "country": "Cocos (Keeling) Islands",
            "iso2": "CC",
            "admin_name": "",
            "capital": "primary",
            "population": 120,
            "id": 9999999991
        },
        {
            "city": "Saint Peter Port",
            "city_ascii": "Saint Peter Port",
            "lat": 49.4555,
            "lng": -2.5368,
            "country": "Guernsey",
            "iso2": "GG",
            "admin_name": "",
            "capital": "primary",
            "population": 18958,
            "id": 9999999993
        },
        {
            "city": "Saint Helier",
            "city_ascii": "Saint Helier",
            "lat": 49.19,
            "lng": -2.11,
            "country": "Jersey",
            "iso2": "JE",
            "admin_name": "",
            "capital": "primary",
            "population": 33500,
            "id": 9999999994
        }
    ]
}